### ISSUE TITLE
Automatic takeoff in "position" mode when armed.

### ISSUE THREAD

**Issue by tuloski** [PX4/PX4-Autopilot#10817]
I think it's a bug, or unwanted behavior, but maybe it's a feature :).

I'm using pixracer on quadcopter.
Flight mode: position.
As soon as I arm the motors with yaw stick and the throttle is at zero, the copter automatically takes off, and it spins on yaw since I have no time to release the stick which is arming.

Shouldn't it takeoff when the throttle stick is around middle position? I didn't find any info on the docs.

**Comment by tuloski** [comment]
It seems strange it's the landing detector, because I plug the battery, put in position and arm, so it never flew before. I can share the log. How and where?

**Comment by mhkabir** [comment]
https://docs.px4.io/en/getting_started/flight_reporting.html

**Comment by tuloski** [comment]
https://logs.px4.io/plot_app?log=0c027a87-0095-4108-8265-34250e9f8e0e

I have many more if needed. Also with lidar enabled. But this seems very clear to me.

**Comment by tuloski** [comment]
To me it looks a baro problem. The pressure caused by the motors when it arms make the quad think it's lower that it should so it pushes up. Is the position control enabled as soon as it's armed or as soon as the takeoff is performed with throttle stick?
