### ISSUE TITLE
Setting failsafe mode for AUX PWM channels errors out

### ISSUE THREAD

**Issue by ghost** [PX4/PX4-Autopilot#11077]
**Describe the bug**
I am trying to force failsafe mode for AUX channels in Pixhawk 4 but it is erroring out

**To Reproduce**
1. Connect Pixhawk 4 to QGC
2. On MAVLINK Console , run the command `pwm forcefail on -d /dev/pwm_output1`
3. The above command errors out
4. Setting terminatefail also errors out : `pwm terminatefail on -d /dev/pwm_output1`
4. The same command works for MAIN channels : `pwm forcefail on`

**Expected behavior**
The forcefail command should set the failsafe PWM values on AUX channel

**Log Files and Screenshots**

![image](https://user-images.githubusercontent.com/23453289/50266012-edc7e380-0447-11e9-9ede-f67ca4691ac1.png)

**Drone (please complete the following information):**
Pixhawk 4 but the same behavior is observed in Pixhawk 1 also

**Comment by julianoes** [comment]
Thanks for the issue. We should check that. FYI @davids5
