### ISSUE TITLE
Tighter range check may be necessary for Thrust parameters in auto thrust control

### ISSUE THREAD

**Issue by ktskt** [PX4/PX4-Autopilot#11471]
**Describe the bug**
Dear, developers, 

I think it would be great if there is a range check for MPC_THR_MAX, MPC_THR_MIN.
For example, if MPC_THR_MIN is larger than a certain value (e.g., 0.6 or larger), it cannot lower the altitude in some cases.
Also, if MPC_THR_MAX is smaller than some value (e.g., 0.6), it causes oscillating flight. 
Additionally, putting lower value into MPC_THR_MAX during the flight causes an immediate crash.

I think it is necessary to put some minimal checks... 
Also, if MPC_THR_MAX < MPC_THR_MIN, a drone shows unexpected operations (when I did this, a thrust value did not change correctly)
If you plan to patch this, I think it must be patched with MPC_THR_MAX  > MPC_THR_MIN + some constant.

**To Reproduce**
param set MPC_THR_MAX or MPC_THR_MIN value (e.g., 0.6)

**Expected behavior**
Oscillating flight or crash on the ground

**Log Files and Screenshots**
I will prepare some logs if you need. But, it is really easy to reproduce.

**Drone (please complete the following information):**
SITL with IRIS+ quadcopter model

**Comment by julianoes** [comment]
Connected to #12439
