### ISSUE TITLE
EKF2 wind estimate wrong in high wind (again)

### ISSUE THREAD

**Issue by ryanjAA** [PX4/PX4-Autopilot#11747]
Wind estimate is wrong when in high wind (TAS Test Ratio >1). Only occurs in high wind.
Same as https://github.com/PX4/Firmware/issues/9726 (maybe just reopen that but this is occurring in master).

Log: https://review.px4.io/plot_app?log=32669e1d-56d7-4f94-a517-cb9623c0c0e8
(disregard mode changes, that's another issue i'll file)

![Airspeed](https://user-images.githubusercontent.com/31726584/55284457-e6fd1680-533c-11e9-9ad3-4583e3e2b67d.png)

**Comment by julianoes** [comment]
@RomanBapst something for you

**Comment by moreba1** [comment]
what is method of calculating wind speed in px4 ? 
i think there is a simple way for calculating by subtract true airspeed and groundspeed vectors .

**Comment by sfuhrer** [comment]
> what is method of calculating wind speed in px4 ?
> i think there is a simple way for calculating by subtract true airspeed and groundspeed vectors .
> 
> @sfuhrer
> @dagar

Yes groundspeed - groundspeed is used, as well as sideslip fusing (you know there is wind from the side if the vehicle is moving lateral to it's heading). 

See https://github.com/PX4/ecl/blob/master/airdata/WindEstimator.cpp#L1 for the code. It's a standalone, small EKF only for wind estimation.

**Comment by bresch** [comment]
The airspeed scale factor was probably wrong. `main` does now estimate it as well

![high_wind](https://user-images.githubusercontent.com/14822839/184618052-a5232c46-7e53-43b6-9b44-fdad2c83be57.png)

**Comment by ryanjAA** [comment]
From the above you would just increase the scale by  0.1 as a starting point?

**Comment by bresch** [comment]
@ryanjAA set `ASPD_SCALE_1` to 0.9. In recent version of the code (probably already from 1.12), the scale is estimated by a separate estimator (not EKF2) and then used to re-scale the airspeed data that is used by other modules (EKF2, TECS, ...) so it should already be better even without setting the `ASPD_SCALE_1` parameter (but it's better if it's set to the correct value).
You can also look at a recent log to see to which value the estimator converged (see https://github.com/PX4/PX4-Autopilot/blob/d7a962b4269d3ca3d2dcae44da7a37177af1d8cd/msg/airspeed_wind.msg#L13)
