### ISSUE TITLE
How disable preflight check? 

### ISSUE THREAD

**Issue by archee8** [PX4/PX4-Autopilot#11876]
Hello. When I launch drone from the ground, everything is fine(fig.1). But When I launch drone from the mobile robot, I get a preflight error. How disable preflight Check(fig.2)?
Fig.1.
![Screenshot from 2019-04-19 20-04-39](https://user-images.githubusercontent.com/26280435/56434899-351f8d00-62df-11e9-868d-e21995cc9c2a.png)
Fig.2
![Screenshot from 2019-04-19 20-05-20](https://user-images.githubusercontent.com/26280435/56434986-8039a000-62df-11e9-88dc-4aa58679c57d.png)

![Screenshot from 2019-04-19 20-12-29](https://user-images.githubusercontent.com/26280435/56434977-79ab2880-62df-11e9-9bc8-fc33e3810af3.png)

**Comment by AlexisTM** [comment]
The check that fails here is the following.

https://github.com/PX4/Firmware/blob/20adce50778f835b1787f17a168e0b1061bbb593/src/modules/ekf2/ekf2_main.cpp#L1776

You could change it to `_preflt_fail = false;` which will disable that specific Preflight check.

**Comment by hamishwillee** [comment]
This is actually kind of interesting. This fails innovation checks, which are supposed to tell us if measurements vs IMU are mismatched with other sensors.

So it may be doing the right thing, but I wonder if this means it isn't possible to use PX4 from a moving target? @priseborough ?
