### ISSUE TITLE
EKF2 replay doesnt reproduce in-flight results with default parameters

### ISSUE THREAD

**Issue by abishu** [PX4/PX4-Autopilot#12504]
I am trying to use the ekf2 replay as in: https://dev.px4.io/v1.8.2/en/debug/system_wide_replay.html
**PX4 verison:** v1.8.2

My **orb_publisher.rules**:
restrict_topics: sensor_combined, vehicle_gps_position, vehicle_land_detected
module: replay
ignore_others: false

**replay_params.txt**: untouched with flight log.

**Log file type**: ulog.

**command run:** make posix none

The replay estimate and real flight values don’t match. On plotting estimator ->state 1 for instance:
![inflight_state1](https://user-images.githubusercontent.com/53010296/61385235-49f5c780-a8b2-11e9-8204-80f91f2f5778.jpg)
![replayed_state1](https://user-images.githubusercontent.com/53010296/61385261-567a2000-a8b2-11e9-82a8-b385bd92ee2d.jpg)

**Comment by abishu** [comment]
I also posted in: https://discuss.px4.io/t/ekf-replay-doesnt-reproduce-in-flight-results-with-default-parameters/11983

Not sure which is mostly used. Sorry about that.

**Comment by abishu** [comment]
Also I had a huge timeslip approx 8-10s after starting the replay!!
![timeslip](https://user-images.githubusercontent.com/53010296/61386589-d6a18500-a8b4-11e9-9b78-195457434df1.png)

**Comment by julianoes** [comment]
@CarlOlsson maybe you could help here?

**Comment by CarlOlsson** [comment]
I'm on vacation for two weeks can take a look when I am back. Please upload the logfile which you are trying to replay

**Comment by bresch** [comment]
Replayed evolved quite a bit now, not worth investigating an old issue. Please re-open a new issue if needed.
