### ISSUE TITLE
Could not calibrate magnetometer on BeagleBone Blue

### ISSUE THREAD

**Issue by silentjet** [PX4/PX4-Autopilot#12516]
**Describe the bug**
Could not calibrate sensors (mag, accel, gyro) on BeagleBone Blue board.
Every calibration ends up with several timeout error messages.
When installing the board to the actual frame of the drone, it is almost impossible to fly due to the huge instability and constant jerking.

**To Reproduce**
1. Board powered up
2. px4 service is started manually by using the following command:
```bash
sudo build/beaglebone_blue_native/bin/px4 -s posix-configs/bbblue/px4.config
```
3. By using WiFi QGC connects to the px4
4. Starting calibration of the compass or gyro from Sensors menu
5. Calibration failed with a timeouts

**Expected behavior**
Calibration succeed. Drone behaves stable when in the air.

**Log Files and Screenshots**
[calibration_console_log.txt](https://github.com/PX4/Firmware/files/3408674/calibration_console_log.txt)
![calibration_qgc_view](https://user-images.githubusercontent.com/556278/61497345-69c6e180-a9bf-11e9-9b8c-03cf1b0ef782.png)

**Drone (please complete the following information):**
- standard quad 450

**Additional context**
OS: Debian for BeagleBone family
Kernel: 4.14.71-ti-rt-r80

**Comment by julianoes** [comment]
Just FYI, I'm not aware of anyone currently using PX4 on the BeagleBone Blue, so you'll probably have to fix these things yourself.

**Comment by julianoes** [comment]
Also, the plan is to deprecate the DriverFramework at some point which would mean some changes for the BBB coming up. On the flipside this would then make thinks like calibration consistent again and prevent these sorts of issues.
