### ISSUE TITLE
Pixhawk Cube_calibration issue on Master

### ISSUE THREAD

**Issue by Tony3dr** [PX4/PX4-Autopilot#12692]
**Describe the bug**
When setting up the vehicle for a flight, on arming the vehicle I get a "Compass not found" message, see image below:
![image](https://user-images.githubusercontent.com/39415493/62976692-0a979980-bdd2-11e9-9e1e-65a1f90f1168.png)
This issue is on Master e25db016 & PR Pull[12650](https://github.com/PX4/Firmware/pull/12650#event-2540347567), tried on Stable version and was able to fly. v1.9.2 (10690587).
**To Reproduce**
1. Power on the Drone
2. Uploaded mission 
3. Arm vehicle and Takeoff
4. Error, "Preflight Fail: COmpass #2 uncalibrated"
5. Calibrate vehicle 
6. Error message Gyro 1 no matching uORB devid
7. Unable to calibrate the vehicle on Master
![image](https://user-images.githubusercontent.com/39415493/62978246-ad054c00-bdd5-11e9-8470-26f7e1acde02.png)

**Log Files**
Compass not found and Calibration issue log on Master:
https://review.px4.io/plot_app?log=13cc9db5-4a03-41ff-a9e2-b80013d3e104

Stable  v1.9.2 (10690587) log:
https://logs.px4.io/plot_app?log=71a782cc-7979-4ff1-a6e8-f3d8f4757f55

PR 12650 log issue:
https://review.px4.io/plot_app?log=18094d44-f808-4b67-b7d6-8ef0df7f4f05
 
**Drone **
Frame- DJI F450
Flight Controller: Pixhawk 2(The Cube)

@dagar we tried calibrating the vehicle and get an Error message Gyro 1 no matching uORB devid. On Stable version, we were able to arm, calibrate and fly the vehicle with no issues.

**Comment by dagar** [comment]
I believe this is a bug with the icm20948 driver, which up until recently was using an incorrect device id. I'll try to reproduce.

**Comment by proficnc** [comment]
So was this introduced bug fixed?

**Comment by darshanz** [comment]
Is it fixed yet?? facing same problem.

**Comment by FlavioTonelli** [comment]
I'm facing a similar issue with Here2 compass on a pixhawk 4 board.
That seems to confirm the bug is related to ICM20948 driver.

**Comment by JacobCrabill** [comment]
Is this pull request relevant?
https://github.com/PX4/Firmware/pull/11189

**Comment by feemi** [comment]
This issue still exists on pixhawk cube 2.1 fmu-v3 autopilot.

**Comment by FlavioTonelli** [comment]
I can't reproduce anymore this issue on current stable version.
Tested on both Pixhawk v3 and v5 autopilot, equipped with an Here 2 antenna.
Is that been fixed?

**Comment by JacobCrabill** [comment]
It's possible that this has been fixed by #14345, if the issue was in regards to external UAVCAN compasses.

**Comment by mrpollo** [comment]
@Tony3dr Can you please verify @JacobCrabill comment? it would be great to resolve/close this issue asap.

**Comment by LorenzMeier** [comment]
Solved a long time ago.
