### ISSUE TITLE
Throttle goes up to 100 % and over FW_THR_MAX

### ISSUE THREAD

**Issue by moreba1** [PX4/PX4-Autopilot#12716]
Hi

In climb there is a wrong happening. Throttle goes up to 100 % and over FW_THR_MAX that will cause overheating and damage motor . 

![image](https://user-images.githubusercontent.com/14200369/63153274-247beb00-c023-11e9-9db9-7d7312bd75c2.png)

**Comment by julianoes** [comment]
Could you share a link to the log please?

**Comment by moreba1** [comment]
yes ,

https://review.px4.io/plot_app?log=b6146ff1-7a47-4259-a6ed-be9f05e1d172

**Comment by dsaffo** [comment]
Could this be a problem with your altitude set points? Looks like its still trying to be at a 1,000 meters when its trying to land. 

![HighThrust](https://user-images.githubusercontent.com/13991410/63214565-9e75a800-c0e7-11e9-93ca-72a7b608f180.PNG)

Thrust is encoded on the flight path (black low -> red high) and the charts on the right are filtered to only show data after the auto-return command (red square around 31 seconds on the timeline). Charts on the left showing thrust, alt set point, estimated and recorded  in that order.

**Comment by RomanBapst** [comment]
@moreba1 This is why it happens:
https://github.com/PX4/ecl/blob/62fa464e4dd6cb5e585d23bd353aa50a469879f7/tecs/tecs.cpp#L319

TECS was in an underspeed conditions for all the time when the throttle values was at 100%.

**Comment by RomanBapst** [comment]
![image](https://user-images.githubusercontent.com/7610489/63222510-528b3780-c1a9-11e9-8cdb-7e712984e491.png)

**Comment by moreba1** [comment]
@RomanBapst 
The motor had a problem with this test .  But the thrust should not exceed the FW_THR_MAX under any conditions.

**Comment by sfuhrer** [comment]
> @RomanBapst
> The motor had a problem with this test . But the thrust should not exceed the FW_THR_MAX under any conditions.

Let's close this one and try to bring https://github.com/PX4/PX4-Autopilot/pull/15321 to a resolution.
