### ISSUE TITLE
GF_ACTION "Hold" fails to prevent geofence violation while in Hold-reposition

### ISSUE THREAD

**Issue by superware** [PX4/PX4-Autopilot#12761]
**Describe the bug**
When GF_ACTION is "Hold" and there's a geofence violation while the drone is in Hold-reposition (QGroundControl click on map and "Go to location"), the drone continues to the commanded location which is outside the geofence.

**To Reproduce**
1. Set GF_ACTION to Hold (Loiter).
2. Upload a geofence to the drone.
3. Takeoff, click somewhere outside the geofence (or inside if it's a keep-out fence) and select "Go to location".
4. Observe the drone violating the geofence and continuing to the destination position.

**Expected behavior**
The drone must reposition to the closest location on the geofence border, even if it's already in Hold/Loiter mode! Simply switching to Hold/Loiter isn't enough.

**Comment by bozkurthan** [comment]
Hello @superware ,
Actually there was no problem with GF_ACTION when I tested with real flight. 

Can you check GF_COUNT parameter to sure about problem is related to PX4 stack.

> GF_COUNT
> 
>  Geofence counter limitComment: Set how many subsequent position measurements outside of the fence are needed before geofence violation is triggered
>

**Comment by superware** [comment]
Hello @bozkurthan ,

> Actually there was no problem with GF_ACTION when I tested with real flight.

Did you try to violate the geofence while already in Hold (repositioning to another location)? This is easily reproducible with SITL.

> Can you check GF_COUNT parameter to sure about problem is related to PX4 stack.

GF_COUNT: -1, I am using PX4.

**Comment by julianoes** [comment]
Thanks for the issue. This sounds like the implementation is broken for this case.

**Comment by bozkurthan** [comment]
@superware 
Nope, you are right I just tried with manual mode.
I reproduced this behavior.

GF_ACTION
![vio3](https://user-images.githubusercontent.com/44507545/63433563-13204d80-c42c-11e9-9b7c-7c2ed5c9a12d.png)

Fence limit
![violation](https://user-images.githubusercontent.com/44507545/63433399-cd638500-c42b-11e9-9194-e057d63e249e.png)

Violation by using "Go to Location"
![violation2](https://user-images.githubusercontent.com/44507545/63433407-cfc5df00-c42b-11e9-9ae8-6aa5edf2e52d.png)

**Comment by BazookaJoe1900** [comment]
its still relevant

**Comment by hamishwillee** [comment]
This needs to be fixed :-(

**Comment by BazookaJoe1900** [comment]
related to: 'MC Geofence violation not easy to resolve #12320'

**Comment by sfuhrer** [comment]
This has been fixed in the meantime (double actually: there is a check that doesn't allow you to set a goto outside of the fence, and upon hitting the fence the vehicle would now stop there).
