### ISSUE TITLE
Abnormal hover in RTL mode

### ISSUE THREAD

**Issue by jiejiezhang** [PX4/PX4-Autopilot#12789]
Description of the problem: Frequent switching mode (RTL<------->POSITION), there is a probability that an abnormal hover will occur in rtl mode. The position_setpoint_triplet.lat and position_setpoint_triplet.lon are not published is at this time.

So I am a bit confused about here(https://github.com/PX4/Firmware/blob/master/src/modules/navigator/navigator_main.cpp#L723-L736): Why do we publish only once when updated the position setpoint ?

**Comment by julianoes** [comment]
Thanks for the issue @jiejiezhang. Do you have a log to show what happens?

**Comment by jiejiezhang** [comment]
![rtl](https://user-images.githubusercontent.com/23076781/63630731-b2258f00-c650-11e9-8277-251edc3d1572.png)

So I guess it is because the position setpoint here((https://github.com/PX4/Firmware/blob/master/src/modules/navigator/navigator_main.cpp#L723-L736) is only sent once after each updated.

**Comment by julianoes** [comment]
@MaEtUgR @bresch FYI

**Comment by bresch** [comment]
I've not see this recently, please re-open if it still occurs
