### ISSUE TITLE
Parameter tuning MPC_ALT_MODE

### ISSUE THREAD

**Issue by Seeelefant** [PX4/PX4-Autopilot#12833]
**Describe the bug**
A clear and concise description of the bug.
I was trying to bind the parameter to (using parameter tuning in QGroundcontrol) to my low-medium-high settings of a 3-way switch, but only got
![image](https://user-images.githubusercontent.com/30323691/63894397-d8e71b00-c9ec-11e9-978b-f9c6442df40f.png)
low:
![image](https://user-images.githubusercontent.com/30323691/63894404-de446580-c9ec-11e9-8d8b-0d61111617ab.png)
medium:
![image](https://user-images.githubusercontent.com/30323691/63894416-e1d7ec80-c9ec-11e9-9b02-b86878c058f6.png)
high:
![image](https://user-images.githubusercontent.com/30323691/63894432-e8666400-c9ec-11e9-9abc-e86b5f19fe65.png)
Please advice.
Best 
--Seeelefant

**To Reproduce**
1. Drone switched on '...'
2. Uploaded mission '....' (attach QGC mission file)
3. Took off '....'

**Expected behavior**
Low-0: Altitude following
Medium-1: Terrain following
High-2: Terrain hold
**Log Files and Screenshots**
*Always* provide a link to the flight log file:
- Download the flight log file from the vehicle ([tutorial](https://docs.px4.io/en/getting_started/flight_reporting.html)).
- Share the link to a log showing the problem on [PX4 Flight Review](http://logs.px4.io/).

Add screenshots to help explain your problem.

**Drone (please complete the following information):**
- Describe the type of drone.
- Photo of the IMU / autopilot setup if possible.

**Additional context**

**Comment by julianoes** [comment]
Thanks for the issue. I have the feeling the parameter tuning using a know was never tested/used for params with int type (not float). Feel free to debug it in code, maybe in HITL simulation. I'm not sure when someone else would look into this.

It's an interesting idea though to use the tuning knob functionality in this way.

**Comment by Seeelefant** [comment]
Hi Julian,
thanks for your response...I suspected something like that. However, thinking the other way around: Within ArduCopter there is a continuous paramter called RNGFND_GAIN, which essentially interpolates between the height measured by the baro sensor and the rangefinder. Wouldn´t such a paramter make sense in the PX4 environment?

**Comment by julianoes** [comment]
I don't know where a parameter like that would fit into the control and ekf2 set-up.

I would say we should fix the actual bug that you found here.
