### ISSUE TITLE
Can we use PID controller instead of PI controller in the inner loop of FW flight control?

### ISSUE THREAD

**Issue by bluecat1997** [PX4/PX4-Autopilot#12886]
I have noticed that when I tuning my fixedwing aircrafts. for rate controller ,which know as the inner loop , I can only tune the proportional gain and integrator gain and no derivative gain to tune just like MC_PITCHRATE_D param in Multicopter Attitude Control.

I think we don't use derivative controller here in FW aircrafts maybe because that most of fixedwing plane have enough derivative force from their own aerodynamic shape ,especially for normal fixedwing with tails.

BUT, I have tested some special planes, whitch have little derivative force from their own in pitch axis , and there is no derivative controller in my flight controller to use. So They need to take several cycles to attenuate the wobble on the pitch axis.

This is a problem that many people around me have had with some strange airplanes. The most typical is the tailless flywings which have small backsweep , especially in some rectangular flywings. They nearly have no derivative force from their aerodynamic shape.
So It is very important for them to have derivative controller in flight control system.

**Comment by Antiheavy** [comment]
+1 for this feature request!

**Comment by bresch** [comment]
To me, it still makes sense to add an optional D term for the pitch axis

**Comment by bresch** [comment]
Anyone interested of implementing it?

**Comment by RomanBapst** [comment]
@bresch @jlecoeur @sfuhrer I think what we should do is implemented this in the context of a unified rate controller for fixed wings and mulirotors.
We already have a separate work item for rate control, we just need to add feedforward and airspeed scaling. That is also very much aligned with future plans for control allocation.

**Comment by jlecoeur** [comment]
@RomanBapst I agree

**Comment by bresch** [comment]
@RomanBapst Awesome, I'm totally in favor of an unified controller.
