### ISSUE TITLE
Align PX4 rotation enum with MAVLink rotation enum

### ISSUE THREAD

**Issue by jlecoeur** [PX4/PX4-Autopilot#12906]
**Describe the bug**
PX4's rotation enum has diverged from MAVLink's rotation enum.

See:
https://github.com/PX4/Firmware/blob/c75954fef8ec6a7c7e4f7a68b2e536c1b5b633ab/src/lib/conversion/rotation.h#L51

and:
https://github.com/mavlink/mavlink/blob/24e853a937dfcf494370b1a4c0ecdc6f3521e018/message_definitions/v1.0/common.xml#L2636

**Comment by jlecoeur** [comment]
Still an issue

**Comment by junwoo091400** [comment]
Solved via https://github.com/PX4/PX4-Autopilot/pull/15784
