### ISSUE TITLE
Px4 Flow Sensor - Unable to properly work

### ISSUE THREAD

**Issue by Ken-Thorburn** [PX4/PX4-Autopilot#12911]
I am trying to use a px4 flow sensor for position hold mode on a drone. Currently, I have tried using Ekf2 and LPE.

For Ekf2, the optical flow sensor is enabled and range is set as the height sensor, however, the flight controller will not allow me to enter into position hold mode. The drone is only receiving height information and not x and y (Seen in /mavros/local_position/pose). 

Additionally, I have tried using LPE, but the flight controller will only enter position hold mode with the parameters seen in the image one. This issue was also found in https://github.com/PX4/Firmware/issues/7600 in that the flight controller uses the camera for position, but does not use the sonar for height. 

Essentially, I have only been able to use the sonar for height with Ekf2 and the camera for position when using LPE.   

If anyone knows how to get this working, please let me know.

***Image One***
![image](https://user-images.githubusercontent.com/53093134/64367124-94a7dc00-cfe5-11e9-8c2f-6f4c8810c047.png)

**Drone:**
- DJI F450
- Px4 Flow Sensor is connected via i2C bus shared with compass
- Photo of the IMU / autopilot setup
![image](https://user-images.githubusercontent.com/53093134/64367622-827a6d80-cfe6-11e9-9de4-a1c0937f41c9.png)

**Comment by julianoes** [comment]
It would probably also help if you could share some logs for the cases that you see.

**Comment by gouyiyong** [comment]
I have the same problem, /mavros/local_position/pose is not updating except z, but the optical flow data is published. I am using 1.9.0 version.

**Comment by Ken-Thorburn** [comment]
@gouyiyong Have you tried flying and then switching into position hold mode?

**Comment by gouyiyong** [comment]
> @gouyiyong Have you tried flying and then switching into position hold mode?

NO, just test no fly, x and y no any update, i dont know how to handle it, ekf2 issue?

**Comment by gouyiyong** [comment]
NO, just test no fly, x and y no any update, i dont know how to handle it, ekf2 issue?

**Comment by Ken-Thorburn** [comment]
I've tried bench testing it as well and have been unsuccessful. I will probably try flying it tomorrow, but my guess is that it prevents the x and y values of the px4 flow sensor from publishing to the pose until it has taken off and reached the minimum height and quality (default 1.5m and >150).

**Comment by Ken-Thorburn** [comment]
@gouyiyong Are you using the sonar for height estimation or the barometer?

**Comment by gouyiyong** [comment]
> @gouyiyong Are you using the sonar for height estimation or the barometer?

yes, i use lidar for height and px4flow for x and y

**Comment by Ken-Thorburn** [comment]
What pixhawk fmu version are you using? @gouyiyong

**Comment by gouyiyong** [comment]
> What pixhawk fmu version are you using? @gouyiyong
it is clone version

**Comment by bresch** [comment]
This works on `main`
