### ISSUE TITLE
[Feature] Method to prevent VTOL arming while in Fixed Wing Mode

### ISSUE THREAD

**Issue by dlwalter** [PX4/PX4-Autopilot#12931]
**Describe problem solved by the proposed feature**
Many vtol aircraft do not have ground clearance to allow spinning props while landed in fixed wing mode.  This would prevent VTOL aircraft from arming when on the ground in fixed wing mode if needed.

**Describe your preferred solution**
An addition parameter COM_ARM_FW_VTOL that would allow vtol arming in FW mode (1) or prevent arming in FW mode (0).  There would be an addition PreflightCheck that would run if the aircraft is a vtol, and send a preflight failure if the aircraft is NOT in rotary wing mode and the parameter does NOT allow arming in FW mode.

**Comment by junwoo091400** [comment]
@sfuhrer any ideas? Or whether this is necessary / feasible?

**Comment by sfuhrer** [comment]
As far as I understand this was solved with https://github.com/PX4/PX4-Autopilot/pull/13987
