### ISSUE TITLE
Airspeed setpoint is affected by sensor temperture

### ISSUE THREAD

**Issue by moreba1** [PX4/PX4-Autopilot#13090]
Hi

Airspeed setpoint (max ,trim and min) for plane not depends to weather and temperature , also true airspeed measured depends to temperature (or density of air) . i think tecs code must be changed.

in tecs.cpp :
157  _TAS_setpoint  = _EAS_setpoint * EAS2TAS;
538  _TAS_setpoint_last = _EAS * EAS2TAS;

562 _TAS_setpoint_last      = _EAS * EAS2TAS;
563 _TAS_setpoint_adj       = _EAS * EAS2TAS;

**Comment by julianoes** [comment]
If you have a suggestion, please create a pull requests. It's easier to review than this issue.

**Comment by moreba1** [comment]
https://github.com/PX4/ecl/pull/654
