### ISSUE TITLE
Bad Loiter to alt function

### ISSUE THREAD

**Issue by moreba1** [PX4/PX4-Autopilot#13220]
**Describe the bug**
loiter to alt : Do not give elevation change before reaching the loiter point.

**Expected behavior**

changing altitude during going to loiter point .

![image](https://user-images.githubusercontent.com/14200369/67008532-8970c180-f0f6-11e9-8d2f-fe7a8fcca3e2.png)

![image](https://user-images.githubusercontent.com/14200369/67008658-d81e5b80-f0f6-11e9-8ff1-51cce7fdf061.png)

**Comment by julianoes** [comment]
Does this param have an effect?
https://dev.px4.io/v1.9.0/en/advanced/parameter_reference.html#MIS_ALTMODE

**Comment by dagar** [comment]
Where are you expecting it to intersect?

**Comment by moreba1** [comment]
@julianoes  I dont know .

**Comment by julianoes** [comment]
I'm not sure what the behaviour should be. What do you think @dagar?

**Comment by dagar** [comment]
This is the intended behavior (using loiter to attain an altitude), but variations are certainly possible if @moreba1 can elaborate.

**Comment by moreba1** [comment]
@dagar 
In my proposed behavior there is improvement in power saving and time saving in both descent and climb. At the end of flight in descent no need to motor power for going to loiter waypoint . also In starting flight after takeoff or transition to fw it is better and safer that planes gain height.

**Comment by dagar** [comment]
That makes sense, I'm not sure that should be the behaviour within LOITER_TO_ALT (https://mavlink.io/en/messages/common.html#MAV_CMD_NAV_LOITER_TO_ALT).

We should already be able to make this the norm within a regular waypoint or loiter.

**Comment by moreba1** [comment]
The relevant code is in navigator/mission_block.cpp . In ardupilot code loiter_to_alt mode works like the proposed method. 

![image](https://user-images.githubusercontent.com/14200369/67149180-06e23080-f2b5-11e9-9a1b-876857c672f7.png)

**Comment by dagar** [comment]
LOITER_TO_ALT was specifically added for a landing sequence consisting of loitering down from the current altitude, then breaking out of the loiter on a tangent to begin your landing approach. Only descending via loiter is the point. 

Questions
1. How will your suggestion to change LOITER_TO_ALT impact that?
2. Why do you need LOITER_TO_ALT to behave this way if it can already be achieved with a regular loiter or waypoint?

**Comment by moreba1** [comment]
``

> Why do you need LOITER_TO_ALT to behave this way if it can already be achieved with a regular loiter or waypoint?
regular waypoint can not be used because it has not "heading wait" .
can we define a waypoint in mission before LOITER_TO_ALT in same position ?

**Comment by moreba1** [comment]
we can define initial altitude for loiter_to_alt points .
