### ISSUE TITLE
Max altitude parameter does weird things

### ISSUE THREAD

**Issue by RomanBapst** [PX4/PX4-Autopilot#13345]
I think the parameter LNDMC_ALT_MAX is implemented very poorly and can lead to very unexpected behavior from the users perspective:

- mission altitudes are just cropped based on the max altitude reported by the land detector -> no user feedback at all. I would suggest to include it into the mission feasibility checker so that you cannot plan a mission with an invalid altitude.
https://github.com/PX4/Firmware/blob/master/src/modules/navigator/mission_block.cpp#L718

- to make matters even worse the max altitude reported by the land detector is a function of the battery level of the vehicle -> the max altitude can change during a flight and can lead to very unexpected mission behavior, potentially just running into a tree.
https://github.com/PX4/Firmware/blob/master/src/modules/land_detector/MulticopterLandDetector.cpp#L242
I don't  quite understand why we need this logic. We have battery failsafe in place which, if activated, triggers a RTL or makes the vehicle land. Limiting the altitude based on the battery states is just weird. You could fly a 2 hour mission at low altitude, you are still going to run out of battery.

- why does the land detector publish the maximum altitude in the first place?

Suggestions:
- remove dependency on battery level and include check for max altitude in mission feasibility, but DON'T just crop altitude
- remove from land detector. Should flighttask and navigator handle this entirely?

**Comment by LorenzMeier** [comment]
I don't want to comment on the current design, but I can provide the rationale behind it: If you fly up 200 meters and have a descend rate of 4 m/s (which is quite fast for a quad), then you need 50 seconds to descend. At a lower descend speed it is even worse and gets into the minutes, which for some systems is 5-10% of the total flight time.

If you go out of range horizontally the system goes into an emergency descend and nobody gets hurt, if you get it wrong on the altitude, then you turn the drone into a falling brick.

So this is all needed, but it probably could be done more elegantly and more transparently for the full system. I also think that it needs to factor in if its a VTOL that can (and is configured) to loiter down as fixed wing.
