### ISSUE TITLE
Rover: GPS loss leads to "fixed bank loiter" instead of just stopping

### ISSUE THREAD

**Issue by jbeyerstedt** [PX4/PX4-Autopilot#13467]
When the GPS position is lost during a mission, the rover switches to a "fixed bank loiter", which is nice for a fixed wing aircraft, but not necessary for a ground vehicle.
(I just tested in SITL and not with a real rover.)

**To Reproduce**
1. Start rover and QCG
2. create and upload a mission and start the mission
3. turn off GPS in nxh with `gpssim stop` at any point in the mission
4. obverse two warning messages in QGC
```
WARN  [commander] Failsafe enabled: no global position
WARN  [navigator] Global position failure: fixed bank loiter
```

**Current behavior**
The vehicle outputs cruising? throttle (PWM 1665) and a zero degree steering angle (PWM 1492). The roll set point is set to 15 degrees, which has no effect on a rover.

**Expected behavior**
Just stop driving

**Log Files and Screenshots**
- Flight log: https://logs.px4.io/plot_app?log=b8a6959a-7e85-4ebb-8473-d9d930775e3e

**Comment by chfriedrich98** [comment]
Cleaning up rover related issues:
Behaviour has changed since this issue was opened: The rover goes into land/descend mode on gps loss, which stops the rover as requested here.
