### ISSUE TITLE
Unexpected Freefall druing Loiter Mode

### ISSUE THREAD

**Issue by pifordi** [PX4/PX4-Autopilot#13479]
I have flight three times with my vtol plane two days ago. In the last flight,  during loiter mode at 280meters, the plane start to descent its altitude. I commanded RTL at 25meters and it return back to home but It still losing altitude during rtl mode. RTL altitude set to 40m but the plane did not climbout to 40m during rtl mode. I switch to manual at about 10 meters and landed the plane. Loiter mode does not appear in flight log records. I think that fw control module stops to work in air. The plane did not try to reach cruise airspeed during this period. Actually, it did not try to correct anything. 

After landing, I was able to run lifter motors, servos and pusher motor. The plane was able to take off and landing normally after landing. There was no hardware problem. You can see easily, there is long dropout on flightlog at all plots. You can watch the flight from "Open 3D View", the plane was flying backwards bcause of dropouts on log file.

Flight log: https://review.px4.io/plot_app?log=ecc40545-1384-4185-828e-c14322655122

**Comment by julianoes** [comment]
What I can see is that you had RC loss for a while right in the beginning. Did you notice that?

**Comment by pifordi** [comment]
The plane always fly in mission mode. Do not matter manual-control lost warnings for me.

**Comment by julianoes** [comment]
> The plane always fly in mission mode. Do not matter manual-control lost warnings for me.

You're right. `NAV_RCL_ACT` is set to `0`.

@Antiheavy maybe you have some insights here?

**Comment by sfuhrer** [comment]
There was really something very weird going on, never seen something similar. Looks like the whole controller stops.
![image](https://user-images.githubusercontent.com/26798987/104962747-5c861b00-59d9-11eb-8064-16cc3656686e.png)
Please re-open/comment if you have seen that again and thus want to keep it open - if it was a software issue, the chance is high though it has been fixed since.
