### ISSUE TITLE
NXP K66: System console drops parameters

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/PX4-Autopilot#14325]
@igalloway @davidaroyer The K66 console drops characters, as demonstrated by this failed test:
http://ci.px4.io:8080/blue/organizations/jenkins/PX4_misc%2FFirmware-hardware/detail/pr-mavlink-ftp-filenotfound/17/pipeline

<img width="703" alt="Screen Shot 2020-03-08 at 21 11 10" src="https://user-images.githubusercontent.com/1208119/76170480-8ef0a600-6182-11ea-8422-26da930af70a.png">

The code calls "tests parameters" but what arrives at the system is "test parameters" (which is an invalid command, the "s" got dropped). @dagar We should consider to disable the K66 until this is resolved, because it will lead to a flaky QA experience.

We did need to enable RX DMA in the past to ensure that no characters from a serial buffer could be dropped.

**Comment by dagar** [comment]
I need to piece together where we could be dropping things with the current architecture.

From `perf latency` (same nxp k66 on test rack) we can get a reasonable idea of the worst case interrupt latency.

![Screenshot from 2020-03-09 11-12-00](https://user-images.githubusercontent.com/84712/76228244-d9ac0580-61f6-11ea-8020-5493954c6dcf.png)

**Comment by jarivanewijk** [comment]
Thank you for reporting and thanks @dagar for the fix.

Our team in Eindhoven has to work at home because of the corona virus. I currently don't have an FMUK66 at home, but I can go get one later today. Let us know if there is anything we might be able to help with.

**Comment by jarivanewijk** [comment]
@dagar @LorenzMeier Did I misunderstand that there was already a fix for this issue? #14351 was closed without merging.

**Comment by davids5** [comment]
@jarivanewijk - i believe this was a misunderstanding that the Nuttx driver for the K66 supported DMA on the lpuart. It does not.  I will need to look at what is involved in adding it.

**Comment by davids5** [comment]
LPUART Serial DMA added. Console https://github.com/PX4/PX4-Autopilot/pull/17956
