### ISSUE TITLE
Battery emergency RTL initiate climb command, even if drone already landing

### ISSUE THREAD

**Issue by BazookaJoe1900** [PX4/PX4-Autopilot#14479]
**Describe the bug**
I found on a flight that I have came to nearly empty battery that there is something that look to me like bug in the emergency and critical battery logic.
I started to land in nearly empty battery, but then the emergency battery logic intiated, and instead of continue landing, it started to RTL (climbing), I took control to RC and landed.
it seems that COM_LOW_BAT_ACT doesn't respect the current flight mode, and if the drone has already started to land, it can re-initiate action, that might be climbing.

**To Reproduce**
 * in order to reproduce easily in simulator I have changed the next parameters:
BAT_LOW_THR = 30%
BAT_EMERGEN_THR  = 20%
BAT_CRIT_THR = 10%
COM_LOW_BAT_ACT = 3 (Return mode at critically low level, Land mode at current position if reaching dangerously low levels)
RTL_RETURN_ALT = 100m
SIM_BAT_MIN_PCT = 0%

 * take-off
 * fly to another location
 * climb to 20m
 * wait that the battery will get to ~30% and start land
 * the RTL will be initiated, starting with climbing (and here the bug)

**Expected behavior**
in case of already started landing, don't initiate RTL. and don't re-initiate landing

**Log Files and Screenshots**
https://review.px4.io/plot_app?log=c50117f1-3f81-4141-af5f-5e905ea239e5
![image](https://user-images.githubusercontent.com/29940676/77550563-ecdaf880-6eb9-11ea-8598-910b5f52d097.png)

**Drone (please complete the following information):**
- simulation (master 25/3/2020)

**Comment by BazookaJoe1900** [comment]
@julianoes Is there someone I can refer this issue?
I am not that familiar with this sections of code, and its critical code, so I don't want want to mess things there.

**Comment by julianoes** [comment]
@RomanBapst might have a better idea.

**Comment by BazookaJoe1900** [comment]
still relevant
