### ISSUE TITLE
px4_fmu-v3 (and probably others) bogus differential_pressure and airspeed publication

### ISSUE THREAD

**Issue by dagar** [PX4/PX4-Autopilot#14503]
Likely a bug in the analog airspeed handling.

**Comment by mhkabir** [comment]
I wonder if this is why we've seen "Airspeed check bit" errors from EKF2 on a multirotor recently...

**Comment by dagar** [comment]
> I wonder if this is why we've seen "Airspeed check bit" errors from EKF2 on a multirotor recently...

Which board?

**Comment by mhkabir** [comment]
fmu-v5

**Comment by LorenzMeier** [comment]
Closing as this code section has been reworked.
