### ISSUE TITLE
Magless operation improvements

### ISSUE THREAD

**Issue by bresch** [PX4/PX4-Autopilot#14559]
Magnetometer-less GPS fusion is now possible thanks to the INS/GNSS yaw estimation provided by the yaw EKF-GSF filter introduced in https://github.com/PX4/ecl/pull/770 (Firmware PR: https://github.com/PX4/Firmware/pull/14162).

The general functionality is there and works properly but a few points are still to be improved (https://github.com/PX4/Firmware/pull/14162#issuecomment-607149388):
- [x] Set home position even if GPS is not fused in the EKF solution (because the orientation is unknown)
- [x] Improve local position validity probation logic: we shouldn't need to wait for more than a few seconds if the EKF reports valid local position (@MaEtUgR **EDIT:** https://github.com/PX4/Firmware/pull/14224)

**Comment by MaEtUgR** [comment]
The second point would require to find a good solution for https://github.com/PX4/Firmware/pull/14224

**Comment by ryanjAA** [comment]
Is there anything specific or special that should be considered if wanting to test this in fixedwing?

**Comment by bresch** [comment]
@ryanjAA Please try it first in SITL (I never tried it for a FW). If everything goes well, I'm quite confident that this would also work properly on a real vehicle. Just be ready to do the whole flight in stabilized/altitude mode if something goes wrong.
