### ISSUE TITLE
NuttX mkfatfs doesn't seem to work

### ISSUE THREAD

**Issue by dagar** [PX4/PX4-Autopilot#14655]
I'm seeing this on all boards.

![Screenshot from 2020-04-13 12-33-17](https://user-images.githubusercontent.com/84712/79138707-f9e55c00-7d82-11ea-984a-45f75cb3adde.png)

In many cases `umount /fs/microsd` fails, but regardless of a successful umount mkfatfs still fails with the same error.

**Comment by mirkix** [comment]
@dagar @davids5  When using `mkfatfs -F 32 /dev/mmcsd0` it is working on a CubeBlack (STM32F4), only use the `-F 32`parameter. On o CubeOrange (STM32H7) it fails even with `mkfatfs -F 32 /dev/mmcsd0` but when I add `# CONFIG_STM32H7_SDMMC_IDMA is not set` to the NuttX defconfig, I can use it successful with a CubeOrange as well.

**Comment by davids5** [comment]
fixed with https://github.com/PX4/NuttX-apps/pull/14
