### ISSUE TITLE
EKF2 altitude jump when GPS checks first pass in flight

### ISSUE THREAD

**Issue by dagar** [PX4/PX4-Autopilot#14926]
https://logs.px4.io/plot_app?log=677d9349-3e6e-4242-b253-44d1ef488568

![Screenshot from 2020-05-18 18-03-08](https://user-images.githubusercontent.com/84712/82263884-dab58d80-9931-11ea-9b66-8071ae09fb27.png)

![Screenshot from 2020-05-18 18-04-28](https://user-images.githubusercontent.com/84712/82263972-0b95c280-9932-11ea-8d78-1a44a11bef6a.png)

The z reset counter is 0 the entire flight.

**Comment by xdwgood** [comment]
I am interested in this question so I say a few observations:
From the log: 
1: The altitude source used by ekf has not changed during the flight (keep `control_mode_flags.CS_RNG_HGT`)
2:  Several key parameters:   `MPC_ALT_MODE ==1`   Terrain following
`EKF2_RNG_AID==1`
3:`local.ref_alt` change when reset position to gps
Looking forward to see the answers of experts :smiley:

**Comment by bresch** [comment]
The vz reset counter increases properly. I think the issue could be in the handler; I'll check that.

![2020-05-20_10-03-04_01_plot](https://user-images.githubusercontent.com/14822839/82421196-f9766a00-9a80-11ea-9295-fd5d677d4765.png)

**Comment by priseborough** [comment]
This is a result of resetting the covariances for the velocity and horizontal position states and the velocity state vector (which is reset to the GPS velocity) when GPS passes checks.
