### ISSUE TITLE
Typhoon h480 in SITL has a lot of vibrations in flight

### ISSUE THREAD

**Issue by Jaeyoung-Lim** [PX4/PX4-Autopilot#14953]
**Describe the bug**
The typhoon h480 model in SITL has been showing a lot of vibrations in flight lately. I tried detuning the attitude rate command, but doesn't seem to solve any vibration problems.

**To Reproduce**
```
make px4_sitl gazebo_typhoon_h480
```

**Log Files and Screenshots**
![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/5248102/82564862-c95ec200-9b79-11ea-9c57-3e13289faf44.gif)
Log: https://review.px4.io/plot_app?log=12f06674-3498-4a09-81f6-29b946a0b708

**Comment by dagar** [comment]
What's it like with the gazebo rate increased?

When did this last work?

**Comment by Jaeyoung-Lim** [comment]
@dagar I think it was like this for quite some time...

My initial suspicion is that the landing gear joint position control has something to do with the oscillations. Disabling the gimbal joint controllers certainly improve the situation, but doesn't solve it completely

**Comment by Jaeyoung-Lim** [comment]
This is still the case

**Comment by canberkdurmus** [comment]
We can close this issue since it is been resolved in #16519
