### ISSUE TITLE
SITL CI VTOL tailsitter intermittent failures

### ISSUE THREAD

**Issue by dagar** [PX4/PX4-Autopilot#15054]
- http://ci.px4.io:8080/blue/organizations/jenkins/PX4_misc%2FFirmware-SITL_tests_ASan/detail/master/1851/pipeline

![Screenshot from 2020-06-08 10-54-51](https://user-images.githubusercontent.com/84712/84045185-80c74700-a976-11ea-84bf-c7e487e3b4de.png)

Is this a VTOL problem or an issue with the simulation?

**Comment by dagar** [comment]
http://ci.px4.io:8080/blue/organizations/jenkins/PX4_misc%2FFirmware-SITL_tests_coverage/detail/pr-sens_ext_i2c_probe/1/pipeline

**Comment by Jaeyoung-Lim** [comment]
@dagar Those resets of thrust looks strnage. Is there something publishing zero thrust?

**Comment by dagar** [comment]
http://ci.px4.io:8080/blue/organizations/jenkins/PX4_misc%2FFirmware-SITL_tests_coverage/detail/pr-boards_cleanup/4/pipeline

**Comment by sfuhrer** [comment]
I don't think this is still valid, is it?

**Comment by Jaeyoung-Lim** [comment]
I believe this is not valid anymore, closing
