### ISSUE TITLE
FMUv4 pro - incorrect voltage measurement on battery port2

### ISSUE THREAD

**Issue by steffensol** [PX4/PX4-Autopilot#15069]
**Describe the bug**
Running PX4 1.10:

Battery 1 shows correct voltage, and battery 2 shows incorrect voltage in QGC (and in mavlink-messages).
Battery 2's lower-than-expected voltage is leading to low battery-percentage situations.

![Screenshot from 2020-06-09 14-33-12](https://user-images.githubusercontent.com/10667120/84191362-af3d4300-aa98-11ea-8847-7bd04822856a.png)

When connecting up a Drotek p3 pro with the drotek power management unit (Dual battery monitors) - we are getting two battery (Analog ADC voltage and current) measurements in PX4 1.10 - which is as expected with the dual input of the p3 pro and dual measurements of the PMU.

![image](https://user-images.githubusercontent.com/10667120/84183652-8616b580-aa8c-11ea-865b-b1e67825e611.png)

![drotek-powerunit](https://user-images.githubusercontent.com/10667120/84183955-daba3080-aa8c-11ea-8f7a-5eeef41365dd.png)

After setting up the offsets/scaling factors correctly (and measuring the power-monitor outputs to be equal with voltmeter)
The first battery's measurements are correct - However, the second battery's measurements are always measuring a much lower voltage. The difference can typically be 49V for battery1, on a fresh 12S lipo - versus 41V for battery2. Switching power monitor inputs 1/2 does not alter the results - measurements stay at same values.

**To Reproduce**
Drotek p3 pro FC
Drotek power management pro connected to power port 1 and 2 on Drotek p3 pro FC.
Set scaling factors according to manufacturer. 
Apply voltage to drone 
Apply voltmeter to Power-manager individual outputs and verify same input voltage for autopilot ADCs.
Turn on drone and QGC should show two batteries.

Battery 1 will show voltage equal to actual battery voltage(Vref & Vbat1).
Battery 2 will show a lower-than-battery-voltage (Vbat2).

Through adjusting voltages (Vref), we've found that there is always a multiplication factor of 1.20 between the measured voltages (Vbat1/Vbat2).

**Expected behavior**
Battery 1 should show correct voltage (~50v for a full 12s)
Battery 2 should show correct voltage (~50v for a full 12s)

Battery percentage estimate should be stable, and ideally there should be a description of how the system handles the two batteries. Especially considering the 1.10 release doesn't have parameters to set up a second battery measurement, with its capacity, resistance etc.

**Log Files and Screenshots**
No flight logs done, all ground testing. Can provide ground testing values if strictly needed.

**Additional context**

Between multiple vehicle's there also seems to be a difference in which battery is chosen as the "main" battery, or how weighting is applied between the two batteries - because the battery % estimate in QGC drops much faster for one vehicle versus another, with exact same HW setup and batteries. (Yes, also when switching the physical batteries between the two vehicles)

Either fixing measurement on Bat2 so that it is correct, or removing the measurement completely would solve the issue.

@dagar - Here's the issue discussed on slack. Thanks alot for looking into it.

**Comment by LorenzMeier** [comment]
Is the issue still present in QGC? If yes, please file an issue in its issue tracker, ping me there and reference this one. Thanks!
