### ISSUE TITLE
SPI_SETBITS of transferhword reads and writes data of more than 8 bits will cause an abnormal signal on the sck .

### ISSUE THREAD

**Issue by cuhome** [PX4/PX4-Autopilot#15073]
I want to add adis16470, but I found that when using SPI_SETBITS to read the data of ADis16470, the sck of it is abnormal. The following figure shows the specific problem.
![图片](https://user-images.githubusercontent.com/31507501/84225542-f4518b80-ab11-11ea-99f5-a8f8efe6179b.png)

**Comment by dagar** [comment]
I believe this is fixed with the NuttX upgrade. https://github.com/PX4/Firmware/pull/15139

**Comment by saengphet** [comment]
Related topic? #15909

**Comment by davids5** [comment]
Closed by https://github.com/PX4/PX4-Autopilot/pull/17213 and https://github.com/apache/incubator-nuttx/pull/3167
