### ISSUE TITLE
After the X7 flight control board is configured with 14 PWM channels, an error (this statement may fall through) will be prompted when compiling the firmware

### ISSUE THREAD

**Issue by CUAVcaijie** [PX4/PX4-Autopilot#15090]
**Describe the bug**
After the X7 flight control board is configured with 14 PWM channels, an error (this statement may fall through) will be prompted when compiling the firmware
![image](https://user-images.githubusercontent.com/30532769/84477470-391c2480-acc2-11ea-9168-b96e9fccdcae.png)

**To Reproduce**
Test 14 PWM source addresses ：
https://github.com/cuav/Firmware/tree/pr-pwm14

I commented some code and compiled it. The compilation was successful. I want to know what caused this error.
![image](https://user-images.githubusercontent.com/30532769/84479118-fb6ccb00-acc4-11ea-8b89-3ed4cb1171dc.png)

URL after commenting code：
https://github.com/cuav/Firmware/tree/pr-pwm14_1

**Comment by dagar** [comment]
As you noticed I left this for later in the initial x7pro board support. Let's open a PR and take a closer look. 

This also reminds me we didn't get Nora support merged. https://github.com/PX4/Firmware/pull/14475
We should bring over the recent x7pro changes/fixes and get it in.

**Comment by dagar** [comment]
Continued in https://github.com/PX4/Firmware/pull/15110.

**Comment by cuhome** [comment]
@dagar I tested the pr-pwm14_1 branch firmware, Generic Quadplane VTOL frame aux1~aux5 have no signal output.

**Comment by jinger26** [comment]
@dagar  any update on this?
