### ISSUE TITLE
unable to start the simulator either on gmavsim as well as gazebo with different errors

### ISSUE THREAD

**Issue by KumarSaurav366** [PX4/PX4-Autopilot#15102]
Saurav@Kumars-MacBook-Air-94 ~ % cd Firmware          
Saurav@Kumars-MacBook-Air-94 Firmware % make px4_sitl jmavsim
sed: 1: "s/.*2575.*/Applications ...": bad flag in substitute command: 'X'
[  1%] Built target lockstep_scheduler
[  2%] Built target logs_symlink
[  2%] Built target drivers_board
[  2%] Built target uorb_headers
[  2%] Built target git_ecl
[  2%] Built target ver_gen
[  2%] Built target git_mavlink_v2
[  2%] Built target mixer_gen_6dof
[  3%] Built target mixer_gen
[  3%] Built target git_gps_devices
[  4%] Built target rc
[  4%] Built target git_jmavsim
[  4%] Built target tinybson
[  5%] Built target perf
[  7%] Built target work_queue
[  7%] Built target ecl_airdata
[  8%] Built target ecl_geo_lookup
[  8%] Built target ecl_geo
[  8%] Built target ecl_tecs
[  9%] Built target ecl_validation
[  9%] Built target version
[  9%] Built target Mixer
[ 10%] Built target parameters
[ 29%] Built target uorb_msgs
[ 29%] Built target ecl_l1
[ 31%] Built target ecl_EKF
[ 31%] Built target SimpleMixer
[ 31%] Built target HelicopterMixer
[ 32%] Built target MultirotorMixer
[ 32%] Built target NullMixer
[ 33%] Built target generate_topic_listener
[ 34%] Built target modules__uORB
[ 34%] Built target mixer
[ 35%] Built target px4_work_queue
[ 36%] Built target px4_platform
[ 37%] Built target px4_daemon
[ 38%] Built target px4_layer
[ 39%] Built target systemlib
[ 40%] Built target cdev
[ 40%] Built target bezier
[ 40%] Built target battery
[ 40%] Built target lib__cdev__test__cdev_test
[ 40%] Built target circuit_breaker
[ 40%] Built target airspeed
[ 40%] Built target AirspeedValidator
[ 41%] Built target hysteresis
[ 43%] Built target CollisionPrevention
[ 44%] Built target conversion
[ 44%] Built target FlightTask
[ 44%] Built target lib__controllib__controllib_test
[ 45%] Built target controllib
[ 45%] Built target drivers__device
[ 45%] Built target drivers_magnetometer
[ 45%] Built target drivers_barometer
[ 46%] Built target Takeoff
[ 47%] Built target systemcmds__perf
[ 47%] Built target systemcmds__pwm
[ 47%] Built target systemcmds__sd_bench
[ 48%] Built target examples__hello
[ 49%] Built target FlightTaskOffboard
[ 50%] Built target FlightTaskFailsafe
[ 50%] Built target FlightTaskDescend
[ 50%] Built target FlightTaskTransition
[ 51%] Built target modules__landing_target_estimator
[ 52%] Built target modules__logger
[ 53%] Built target modules__local_position_estimator
[ 53%] Built target pid
[ 53%] Built target landing_slope
[ 54%] Built target modules__mavlink__mavlink_tests
[ 55%] Built target mathlib
[ 55%] Built target mixer_module
[ 55%] Built target output_limit
[ 55%] Built target launchdetection
[ 55%] Built target runway_takeoff
[ 56%] Built target lib__rc__rc_tests
[ 56%] Built target tunes
[ 58%] Built target modules__land_detector
[ 58%] Built target WeatherVane
[ 58%] Built target mag_compensation
[ 58%] Built target arch_tone_alarm
[ 58%] Built target lib__work_queue__test__wqueue_test
[ 58%] Built target modules__uORB__uORB_tests
[ 58%] Built target drivers__camera_capture
[ 59%] Built target drivers__camera_trigger
[ 60%] Built target drivers__gps
[ 60%] Built target drivers__pwm_out_sim
[ 61%] Built target examples__rpm_simulator
[ 61%] Built target drivers__tone_alarm
[ 61%] Built target modules__airspeed_selector
[ 62%] Built target modules__attitude_estimator_q
[ 62%] Built target modules__camera_feedback
[ 62%] Built target failure_detector
[ 62%] Built target HealthFlags
[ 62%] Built target ArmAuthorization
[ 63%] Built target modules__commander__commander_tests
[ 63%] Built target modules__dataman
[ 63%] Built target Ekf2Utility
[ 64%] Built target modules__events
[ 64%] Built target AttitudeControl
[ 65%] Built target modules__fw_att_control
[ 66%] Built target zero_order_hover_thrust_ekf
[ 67%] Built target PositionControl
[ 67%] Built target RateControl
[ 68%] Built target systemcmds__tests__hrt_test
[ 68%] Built target systemcmds__topic_listener
[ 68%] Built target systemcmds__tune_control
[ 68%] Built target modules__mc_att_control
[ 68%] Built target modules__rc_update
[ 69%] Built target modules__replay
[ 70%] Built target sensor_corrections
[ 73%] Built target modules__navigator
[ 73%] Built target vehicle_air_data
[ 73%] Built target modules__rover_pos_control
[ 73%] Built target systemcmds__led_control
[ 74%] Built target systemcmds__mixer
[ 74%] Built target systemcmds__motor_ramp
[ 75%] Built target modules__temperature_compensation
[ 77%] Built target drivers__vmount
[ 78%] Built target modules__vtol_att_control
[ 78%] Built target modules__uuv_att_control
[ 78%] Built target systemcmds__dyn
[ 78%] Built target systemcmds__esc_calib
[ 78%] Built target systemcmds__shutdown
[ 78%] Built target examples__rover_steering_control
[ 78%] Built target systemcmds__motor_test
[ 78%] Built target systemcmds__param
[ 84%] Built target systemcmds__tests
[ 86%] Built target systemcmds__ver
[ 86%] Built target systemcmds__work_queue
[ 86%] Built target examples__fixedwing_control
[ 86%] Built target examples__px4_mavlink_debug
[ 86%] Built target examples__px4_simple_app
[ 86%] Built target examples__uuv_example_app
[ 86%] Built target examples__work_item
[ 87%] Built target avoidance
[ 88%] Built target FlightTaskUtility
[ 88%] Built target FlightTaskManual
[ 88%] Built target drivers_accelerometer
[ 88%] Built target drivers_gyroscope
[ 88%] Built target modules__fw_pos_control_l1
[ 88%] Built target modules__ekf2
[ 90%] Built target PreFlightCheck
[ 90%] Built target modules__mc_hover_thrust_estimator
[ 90%] Built target modules__mc_rate_control
[ 90%] Built target vehicle_acceleration
[ 91%] Built target vehicle_angular_velocity
[ 91%] Built target vehicle_imu
[ 91%] Built target FlightTaskManualAltitude
[ 92%] Built target modules__simulator
[ 92%] Built target FlightTaskAuto
[ 92%] Built target modules__sensors
[ 92%] Built target FlightTaskManualAltitudeSmooth
[ 93%] Built target modules__commander
[ 94%] Built target FlightTaskManualAltitudeSmoothVel
[ 94%] Built target FlightTaskAutoMapper
[ 94%] Built target FlightTaskManualPosition
[ 95%] Built target FlightTaskAutoFollowMe
[ 95%] Built target FlightTaskOrbit
[ 95%] Built target FlightTaskManualPositionSmooth
[ 97%] Built target modules__mavlink
[ 97%] Built target FlightTaskManualPositionSmoothVel
[ 97%] Built target FlightTaskAutoLineSmoothVel
[ 98%] Built target FlightTasks
[100%] Built target modules__mc_pos_control
[100%] Built target px4
SITL ARGS
sitl_bin: /Users/Saurav/Firmware/build/px4_sitl_default/bin/px4
debugger: none
program: jmavsim
model: none
world: none
src_path: /Users/Saurav/Firmware
build_path: /Users/Saurav/Firmware/build/px4_sitl_default
empty model, setting iris as default
SITL COMMAND: "/Users/Saurav/Firmware/build/px4_sitl_default/bin/px4" "/Users/Saurav/Firmware"/ROMFS/px4fmu_common -s etc/init.d-posix/rcS -t "/Users/Saurav/Firmware"/test_data
INFO  [px4] Creating symlink /Users/Saurav/Firmware/ROMFS/px4fmu_common -> /Users/Saurav/Firmware/build/px4_sitl_default/tmp/rootfs/etc

______  __   __    ___ 
| ___ \ \ \ / /   /   |
| |_/ /  \ V /   / /| |
|  __/   /   \  / /_| |
| |     / /^\ \ \___  |
\_|     \/   \/     |_/

px4 starting.

INFO  [px4] Calling startup script: /bin/sh etc/init.d-posix/rcS 0
INFO  [param] selected parameter default file eeprom/parameters_10016
[param] parameter file not found, creating eeprom/parameters_10016
  SYS_AUTOCONFIG: curr: 0 -> new: 1
/Users/Saurav/Firmware/Tools/jmavsim_run.sh: line 77: ant: command not found
* SYS_AUTOSTART: curr: 0 -> new: 10016
  BAT_N_CELLS: curr: 0 -> new: 3
  CAL_ACC0_ID: curr: 0 -> new: 1311244
  CAL_ACC_PRIME: curr: 0 -> new: 1311244
  CAL_GYRO0_ID: curr: 0 -> new: 1311244
  CAL_GYRO_PRIME: curr: 0 -> new: 1311244
  CAL_MAG0_ID: curr: 0 -> new: 197388
  CAL_MAG_PRIME: curr: 0 -> new: 197388
  CBRK_SUPPLY_CHK: curr: 0 -> new: 894281
  COM_DISARM_LAND: curr: 2.0000 -> new: 0.5000
  COM_OBL_ACT: curr: 0 -> new: 2
  COM_RC_IN_MODE: curr: 0 -> new: 1
  EKF2_ANGERR_INIT: curr: 0.1000 -> new: 0.0100
  EKF2_GBIAS_INIT: curr: 0.1000 -> new: 0.0100
  COM_ARM_EKF_AB: curr: 0.0022 -> new: 0.0050
  EKF2_REQ_GPS_H: curr: 10.0000 -> new: 0.5000
  MC_PITCH_P: curr: 6.5000 -> new: 6.0000
  MC_PITCHRATE_P: curr: 0.1500 -> new: 0.2000
  MC_ROLL_P: curr: 6.5000 -> new: 6.0000
  MC_ROLLRATE_P: curr: 0.1500 -> new: 0.2000
  MPC_HOLD_MAX_Z: curr: 0.6000 -> new: 2.0000
  MPC_Z_VEL_P_ACC: curr: 4.0000 -> new: 12.0000
  MPC_Z_VEL_I_ACC: curr: 2.0000 -> new: 3.0000
  MPC_XY_P: curr: 0.9500 -> new: 0.8000
  MPC_XY_VEL_P_ACC: curr: 1.8000 -> new: 4.0000
  MPC_XY_VEL_D_ACC: curr: 0.2000 -> new: 0.3200
  MPC_SPOOLUP_TIME: curr: 1.0000 -> new: 0.5000
  MPC_TKO_RAMP_T: curr: 3.0000 -> new: 1.0000
  NAV_ACC_RAD: curr: 10.0000 -> new: 2.0000
  NAV_DLL_ACT: curr: 0 -> new: 2
  RTL_DESCEND_ALT: curr: 30.0000 -> new: 5.0000
  RTL_LAND_DELAY: curr: -1.0000 -> new: 5.0000
  RTL_RETURN_ALT: curr: 60.0000 -> new: 30.0000
  SDLOG_MODE: curr: 0 -> new: 1
  SDLOG_PROFILE: curr: 3 -> new: 131
  SDLOG_DIRS_MAX: curr: 0 -> new: 7
  SENS_BOARD_X_OFF: curr: 0.0000 -> new: 0.0000
  SENS_DPRES_OFF: curr: 0.0000 -> new: 0.0010
  TRIG_INTERFACE: curr: 4 -> new: 3
  COM_CPU_MAX: curr: 90.0000 -> new: -1.0000
  IMU_INTEG_RATE: curr: 200 -> new: 250
* RTL_DESCEND_ALT: curr: 5.0000 -> new: 10.0000
* RTL_LAND_DELAY: curr: 5.0000 -> new: 0.0000
  PWM_MAX: curr: 2000 -> new: 1950
  PWM_MIN: curr: 1000 -> new: 1075
  GPS_UBX_DYNMODEL: curr: 7 -> new: 6
* SYS_AUTOCONFIG: curr: 1 -> new: 0
INFO  [dataman] Unknown restart, data manager file './dataman' size is 11798680 bytes
INFO  [simulator] Waiting for simulator to accept connection on TCP port 4560

and this keeps on running with no simulator opening. 

**For the gazebo simulator:** the error as follow: 

Saurav@Kumars-MacBook-Air-94 Firmware % make px4_sitl gazebo  
sed: 1: "s/.*3550.*/Applications ...": bad flag in substitute command: 'X'
[  1%] Built target lockstep_scheduler
[  2%] Built target drivers_board
[  2%] Built target logs_symlink
[  2%] Built target uorb_headers
[  2%] Built target git_ecl
[  2%] Built target ver_gen
[  2%] Built target git_mavlink_v2
[  2%] Built target mixer_gen_6dof
[  3%] Built target mixer_gen
[  4%] Built target rc
[  4%] Built target git_gps_devices
[  4%] Built target git_gazebo
[  5%] Built target perf
[  5%] Built target tinybson
[  7%] Built target work_queue
[  7%] Built target ecl_airdata
[  8%] Built target ecl_geo_lookup
[  8%] Built target ecl_geo
[  8%] Built target ecl_tecs
[  9%] Built target ecl_validation
[  9%] Built target version
[  9%] Built target Mixer
[ 10%] Performing configure step for 'sitl_gazebo'
-- install-prefix: /usr/local
[ 28%] Built target uorb_msgs
[ 29%] Built target parameters
[ 31%] Built target ecl_EKF
-- Using C++17 compiler
[ 31%] Built target ecl_l1
[ 31%] Built target SimpleMixer
[ 31%] Built target HelicopterMixer
[ 32%] Built target MultirotorMixer
[ 34%] Built target generate_topic_listener
[ 34%] Built target NullMixer
[ 35%] Built target modules__uORB
[ 35%] Built target mixer
[ 36%] Built target px4_work_queue
[ 37%] Built target px4_platform
[ 38%] Built target px4_daemon
[ 39%] Built target px4_layer
[ 40%] Built target systemlib
[ 41%] Built target cdev
CMake Error at /usr/local/Cellar/cmake/3.14.3/share/cmake/Modules/FindBoost.cmake:2147 (message):
  Unable to find the requested Boost libraries.

  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.
Call Stack (most recent call first):
  CMakeLists.txt:31 (find_package)

[ 41%] Built target lib__cdev__test__cdev_test
[ 41%] Built target bezier
[ 41%] Built target battery
CMake Error at CMakeLists.txt:32 (find_package):
  By not providing "Findgazebo.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "gazebo", but
  CMake did not find one.

  Could not find a package configuration file provided by "gazebo" with any
  of the following names:

    gazeboConfig.cmake
    gazebo-config.cmake

  Add the installation prefix of "gazebo" to CMAKE_PREFIX_PATH or set
  "gazebo_DIR" to a directory containing one of the above files.  If "gazebo"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!
[ 41%] Built target circuit_breaker
See also "/Users/Saurav/Firmware/build/px4_sitl_default/build_gazebo/CMakeFiles/CMakeOutput.log".
[ 41%] Built target airspeed
make[4]: *** [external/Stamp/sitl_gazebo/sitl_gazebo-configure] Error 1
make[3]: *** [platforms/posix/CMakeFiles/sitl_gazebo.dir/all] Error 2
make[3]: *** Waiting for unfinished jobs....
[ 42%] Built target CollisionPrevention
[ 42%] Built target AirspeedValidator
[ 43%] Built target hysteresis
make[2]: *** [platforms/posix/CMakeFiles/gazebo.dir/rule] Error 2
make[1]: *** [gazebo] Error 2
make: *** [px4_sitl] Error 2

**Comment by KumarSaurav366** [comment]
Please help, I tried installation process following :
https://dev.px4.io/v1.9.0/en/setup/dev_env_mac.html

**Comment by Jaeyoung-Lim** [comment]
@KumarSaurav366 You don't have gazebo installed on your system, as written in the error log.

**Comment by KumarSaurav366** [comment]
Thank you for letting me know, 
what is the significance of Xcode in the installation process? 
I have followed the gazebo installation from: 
http://gazebosim.org/tutorials?cat=install&tut=install_on_mac&ver=8.0
and after downloading this Error comes out:

Error: Your Xcode (10.3) is too outdated.
Please update to Xcode 11.4.1 (or delete it).
Xcode can be updated from the App Store.

So, is this installation problem is caused by the Xcode version? I am using homebrew for the installations

**Comment by Jaeyoung-Lim** [comment]
@KumarSaurav366 The error log seems to state that is the case. Have you tried updating the Xcode version?

**Comment by MaEtUgR** [comment]
Closing this as stale, please reopen if the issue persists.
