### ISSUE TITLE
Differential rover goes into a spin when GPS position is lost

### ISSUE THREAD

**Issue by Jaeyoung-Lim** [PX4/PX4-Autopilot#15211]
**Describe the bug**
When GPS is lost, differential rover goes into a fixed bank loiter - which results in the vehicle spinning around while being stationary. 

**To Reproduce**
1. `make px4_sitl gazebo_r1_rover`
2. Start a mission
3. Trigger a gps failure

**Expected behavior**
Not sure, but maybe keeping stationary would be a more sensible behavior

**Log Files and Screenshots**
![diff_rover_spin](https://user-images.githubusercontent.com/5248102/85537785-9003f100-b614-11ea-8c39-fcf38243f423.gif)

**Comment by dagar** [comment]
Quick fixes that come to mind.
1. Hack navigator/gpsfailure for rover     
     - https://github.com/PX4/Firmware/blob/1761ef39520a271982a7a01ef6cd2b934d359a1b/src/modules/navigator/gpsfailure.cpp#L86-L90
2. Handle it in the state machine.
    - https://github.com/PX4/Firmware/blob/1761ef39520a271982a7a01ef6cd2b934d359a1b/src/modules/commander/state_machine_helper.cpp#L701-L759
    - A special case here for rover would be tolerable. https://github.com/PX4/Firmware/blob/1761ef39520a271982a7a01ef6cd2b934d359a1b/src/modules/commander/state_machine_helper.cpp#L730-L745

**Comment by Jaeyoung-Lim** [comment]
Realized this was a duplicate of https://github.com/PX4/Firmware/issues/13467

**Comment by aaryanmurgunde** [comment]
@Jaeyoung-Lim Was a solution found for this ?

**Comment by Jaeyoung-Lim** [comment]
@aaryanmurgunde No, as you can see in the thread https://github.com/PX4/PX4-Autopilot/issues/13467 is still open

**Comment by aaryanmurgunde** [comment]
I was trying to do a quick simulation on any differential drive robot with either Rover by Ardupilot or PX4 Autopilot 
Do you have any alternative that I could use for SITL and Gazebo ROS?

@Jaeyoung-Lim

**Comment by Jaeyoung-Lim** [comment]
@aaryanmurgunde This issue is not related to the model being usable or not but related to the behavior of what happens when GPS is lost. You can use the model as is

**Comment by aaryanmurgunde** [comment]
@Jaeyoung-Lim So if I get this right I'm using SITL and gazebo so technically the GPS should be mimicked by the SITL right ?

**Comment by aaryanmurgunde** [comment]
@Jaeyoung-Lim In my case I don't see a gps failure still face the same issue 
![image](https://user-images.githubusercontent.com/44398228/171620540-73fafb3b-4693-4bf3-b4a8-5d6d642a50bc.png)

**Comment by aaryanmurgunde** [comment]
You can see all three screens here 
https://user-images.githubusercontent.com/44398228/171621239-ff323636-a778-4751-937e-596f29484458.mp4

**Comment by sajisaka** [comment]
Any update on this issue?
I'm in the same situation, but it doesn't seem to be a GPS problem.
When the rover starts to spin, the GPS is still capturing the position.

**Comment by Jaeyoung-Lim** [comment]
@sajisaka If that is the case, it is not the same problem
