### ISSUE TITLE
MacOS intermittent segmentation fault during unit tests

### ISSUE THREAD

**Issue by dagar** [PX4/PX4-Autopilot#15225]
https://github.com/PX4/Firmware/pull/15222/checks?check_run_id=810620037

![Screenshot from 2020-06-26 09-49-22](https://user-images.githubusercontent.com/84712/85864290-5658f480-b792-11ea-8ceb-d9c82dea5dfe.png)

Only seems to be happening on the Github Actions MacOS machines, and not the older Jenkins MacOS build slaves.

**Comment by dagar** [comment]
@julianoes we should think about replicating the core dump, backtrace, and upload functionality from the Linux SITL tests.

**Comment by dagar** [comment]
Github Actions MacOS (currently 10.15) environment details. https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md

**Comment by dagar** [comment]
Running the tests on Github Actions (MacOS) has been disabled for now, but this will still need to be addressed.

**Comment by Jaeyoung-Lim** [comment]
@dagar Should we bring this back? macOS builds properly with gazebo now

**Comment by dagar** [comment]
> @dagar Should we bring this back? macOS builds properly with gazebo now

Yes let's give it a try.
