### ISSUE TITLE
HITL disarm after takeoff FMU V3

### ISSUE THREAD

**Issue by bravepaulo** [PX4/PX4-Autopilot#15417]
**Describe the bug**
HITL with FMU_V3 disarm few seconds after taking off.

**To Reproduce**
1. Arm the Drone in QGC, Manual or Position mode engaged
2. Full throtle up
3. Wait some seconds
4. The drone will disarm and will descend uncontrolled

**Expected behavior**
It was expected that the drone would keep armed and disarmed on command or when landed

**Comment by julianoes** [comment]
Might be fixed by #17481.

**Comment by bravepaulo** [comment]
Hi @julianoes.
I believe that you are right.  #17481 fixed it.
This can be closed.
