### ISSUE TITLE
RTL: descending before having reached mission land point

### ISSUE THREAD

**Issue by ThomasRigi** [PX4/PX4-Autopilot#15410]
**Describe the bug**
Upon RTL the drone starts to descend immediately and does not even reach the Land waypoint of the mission.
You can see how the horizontal velocity stops suddenly but the controller wants to continue:
![image](https://user-images.githubusercontent.com/48206725/88314240-e730da80-cd14-11ea-9911-0527860f7e8c.png)

**To Reproduce**
1. Checkout current master (aa7735c)
2. `make px4_sitl gazebo_standard_vtol`
3. Load a mission, e.g. [square vtol.zip](https://github.com/PX4/Firmware/files/4967729/square.vtol.zip)
4. Start the mission and observe. (this uses bug #15409 to trigger RTL with the provided .plan file)
5. Alternatively switch to RTL over QGC once the drone has taken off.

**Expected behavior**
The drone should follow what is outlined in https://docs.px4.io/master/en/flight_modes/return.html . In particular, it should stay at or above RTL_RETURN_ALT until it has reached the landing spot. (or according the cone settings, but the default settings were on no cone)

**Log Files and Screenshots**
https://logs.px4.io/plot_app?log=44529271-2e29-4827-a09a-64d78b725c6d
https://logs.px4.io/plot_app?log=32d68ad0-a322-451d-b3ca-4640bda64670

**Drone (please complete the following information):**
Tested with Gazebo standard_vtol

**Comment by sfuhrer** [comment]
Fixed by https://github.com/PX4/PX4-Autopilot/pull/16377
