### ISSUE TITLE
How to create simulator server not on localhost

### ISSUE THREAD

**Issue by eyalalon** [PX4/PX4-Autopilot#15428]
Hello,

We want to create a simulator server (accepting clients on tcp port 4560, refer to image below) not on localhost.

![image](https://user-images.githubusercontent.com/59776414/88556559-d2648780-d031-11ea-9599-8ccbf8a99b15.png)

In simulator_mavlink.cpp we see that the client connects to _myaddr, which is initialized to:
`_myaddr.sin_addr.s_addr = htonl(INADDR_ANY);
`
As we understand, INADDR_ANY is normally routed to loopback address. Hence, our question is, how do we define our own ip?

Thanks,
Eyal

**Comment by MuesliReep** [comment]
Hi Eyal, 

We ran into exactly the same problem. I have sent a pull request with our solution here: https://github.com/PX4/Firmware/pull/15443

Afterwards you can set the desired host in your rcS startup script (Firmware/ROMFS/px4fmu_common/init.d-posix/rcS), by changing `simulator start -c $simulator_tcp_port` into `simulator start -t "192.168.178.122" $simulator_tcp_port`.

Hope this helps!

Regards,
Peter
