### ISSUE TITLE
pwm command does not work for UGV (50002)

### ISSUE THREAD

**Issue by stmoon** [PX4/PX4-Autopilot#15435]
Hi, 

I bought Traxxas Stampede VXL to apply to PX4 (px4-fmu-v3-default for pixhawk 2.1)
and I changed air frame  (50002, traxxas_stampede_2wd)

I followed https://docs.px4.io/master/en/frames_rover/traxxas_stampede.html

Before the operation test, I just try to test pwm using "pwm test -c 24 -p 1700"
However, when pwm command is entered, there is no reaction.

It only works once after booting by PWM_MIN.  

Why is the pwm command not working?

**Comment by stmoon** [comment]
Does anyone have any idea?

**Comment by Jaeyoung-Lim** [comment]
@stmoon There has been quite some fixes recently, and rover should be in a working state now.

**Comment by stmoon** [comment]
Thanks! I will try it again !.

**Comment by chfriedrich98** [comment]
Cleanup rover related issues:
The rover support in PX4 has been completely revamped since this issue has been opened.
