### ISSUE TITLE
Turned off motors of the tiltrotor in fw mode don't go down to full disarm

### ISSUE THREAD

**Issue by notoriou5** [PX4/PX4-Autopilot#15501]
**Describe the bug**
PX4 Version: v1.11.0-rc1
Simulation modell: tiltrotor
After the front transition, when entering into the FW config, the motors which are not used (turned off with the param VT_FW_MOT_OFFID) are set to a PWM value of 900 [with this code](https://github.com/PX4/Firmware/blob/v1.11.0-rc1/src/modules/vtol_att_control/vtol_type.cpp#L366). Why do they go back up to a value of 1000 right after? Is there a specific reason for this? It does not behave like this with the standard_vtol model, which turns off all hover motors in fw mode.

![image](https://user-images.githubusercontent.com/17237189/89499378-34ef1d80-d7c0-11ea-823d-bda4f3d1674d.png)

**To Reproduce**
1. start simulation with the tiltrotor model
2. Uploaded mission with a Vtol Takeoff Mission item
3. Start mission
4. Observe the motor PWM outputs

**Expected behavior**
The turned off motors stay at a PWM value of 900 during the whole fw mode.

**Comment by sfuhrer** [comment]
I'm not able to reproduce on current master and SITL - in my case the MC motors go to 900 PWM after transition.
![image](https://user-images.githubusercontent.com/26798987/103519995-bf72a080-4e76-11eb-99bb-19b541f48f60.png)
