### ISSUE TITLE
MAVLink over USB not working on CUAV Nora

### ISSUE THREAD

**Issue by coderkalyan** [PX4/PX4-Autopilot#15585]
**Describe the bug**
On Nora autopilot, unable to connect to MAVLink (via QGC) over the USB-C connection.

**To Reproduce**
1. Build the cuav_nora_default target and flash it to a nora autopilot
2. Connect the USB-C cable to your computer and open up QGC

**Expected behavior**
Ability to connect via QGC and configure the autopilot.

**Additional context**
Otherwise the autopilot runs fine, I can connect over telemetry radio and use it properly.

**Comment by taileron** [comment]
maybe QGC just doesn't know the board yet. You could try the newest daily build. Meanwhile you can simply create a new com link serial port in QGC with what is recognized by the computer (br 57600) and then it connects to what you like.
