### ISSUE TITLE
Support for GPS NMEA message

### ISSUE THREAD

**Issue by moreba1** [PX4/PX4-Autopilot#15588]
Hi

I tested emlid reach GPS with NMEA output message and I adjusted baud rate to 38400 , but I could not connect GPS to autopilot.

related to 
https://github.com/PX4/GpsDrivers/pull/58
https://github.com/PX4/GpsDrivers/pull/38

**Comment by dagar** [comment]
Is there a reason to prefer NMEA over the binary format? We should follow up in https://github.com/PX4/GpsDrivers/pull/58.

**Comment by moreba1** [comment]
> 
> 
> Is there a reason to prefer NMEA over the binary format? We should follow up in [PX4/GpsDrivers#58](https://github.com/PX4/GpsDrivers/pull/58).

Emlid reach m+ GPS export NMEA format only.
https://docs.px4.io/master/en/gps_compass/
