### ISSUE TITLE
MRO X2.1-777 DSM(X) voltage switches off and no GPS in

### ISSUE THREAD

**Issue by taileron** [PX4/PX4-Autopilot#15595]
**Describe the bug**
when the fc is booted no 3.3V goes to Spektrum Sat
GPS doesn´t work
could be a relation to #15527

**To Reproduce**
Steps to reproduce the behaviour:
while the fc boots there is Spektrum 3.3V then it disappears finally no rc-in is detected
the receiver is not recognized even if 3.3V is supplied externally
GPS uart  tx (202) or Tel 1 (101) sends initialization to GPS module (measured) but the fc doesn´t detect a GPS module on uart rx (baud=0 and others tested) while it´s external I2C mag gets detected and works perfect. 

**Expected behavior**
rc receiver works and shows channels
GPS works on one of the fc´s uarts

**Comment by dagar** [comment]
https://github.com/PX4/Firmware/blob/0b0d23e8fa636da1a06ad24fee1bb73eb5c737aa/boards/mro/x21-777/src/board_config.h#L81-L83

These need to be reviewed.

https://github.com/PX4/Firmware/blob/0b0d23e8fa636da1a06ad24fee1bb73eb5c737aa/boards/mro/x21-777/src/init.c#L179-L184

**Comment by dagar** [comment]
> rc receiver works and shows channels

This is handled by the px4_io-v2.

**Comment by taileron** [comment]
Firmware of px4_io-v2 still gets rejected by:
[PX4IO] using firmware from /etc/extras/px4_io-v2_default.bin
[PX4IO] bad sync 0x7f,0x7f
[PX4IO] found unsupported bootloader revision 269619218, exiting

**Comment by taileron** [comment]
Could the IO possibly be flashed from outside despite the wrong bootloader via SWD ... what would be necessary for this?

**Comment by taileron** [comment]
With the meanwhile successfully flashed IO almost all of the above mentioned issues are fixed.
Only GPS can not be used on any UART (I2C works). Telemetry can be used on all this UARTs without problems. Even with 9600 baud the GPS module gets not initialized correctly. The whole systems work on PixRacer that has the same connectors and pinouts for UARTs

**Comment by taileron** [comment]
It´s definitely only the rx part of the uart and only when the interface concerned is used for gps. For telemetry all uarts work perfect. The gps module receives the commands to negotiate bitrate etc. but nothing comes back to PX4.
The signal from the GPS module is perfectly measurable at the RX pin.
nsh> gps status
INFO  [gps] Main GPS
INFO  [gps] protocol: UBX
INFO  [gps] status: NOT OK, port: /dev/ttyS3, baudrate: 0
INFO  [gps] sat info: disabled
#15907 probably the similar issue?

**Comment by taileron** [comment]
@dagar what else could I test to get GPS working, the interfaces are basically working, only to all GPS modules there is no connection via the RX side of the UART. Either something is wrong with BAUD, timings, RX DMA or frequencies, that do not interfere when ESP 8266 telemetry connected to this GPS uart connector.
All parameters are correct in any case but behave incorrectly for GPS use. 
UART4 and USART2 has the same behaviour.
(to test GPS on (101 / USART2) Tel1 baud=0 or 9600 and Tel1 on (201 / UART4) GPS UART baud=921200)
No matter on which serial port it is always only GPS which is not detected.
If negotiating the baud rate was the reason, it should work with 9600

What would make sense to change for tests in the code ? e.g. Boards/NuttX

**Comment by taileron** [comment]
U(S)ART ports also used as telemetry generate more transmission errors than controllers, e.g. Pixracer on which GPS is detected.
Can the clock frequency of the F777's U(S)ARTs be increased extremely fine for testing? 
IMU_GYRO_RATEMAX=800 results in Sensors Status a loop rate of only approx 792 Hz
Pixracer results above 799 Hz which seems to be much more accurate

**Comment by taileron** [comment]
@dagar Disabling RXDMA for UART4 boards/nsh/defconfig enables GPS. 
But this does not reduce the transmission errors for USART2, telemetry does not seem to work at all without RXDMA

**Comment by dagar** [comment]
> @dagar Disabling RXDMA for UART4 boards/nsh/defconfig enables GPS.
> But this does not reduce the transmission errors for USART2, telemetry does not seem to work at all without RXDMA

Where/how are you measuring transmission errors?

**Comment by taileron** [comment]
So far only from the feedback like lost packets and interruptions and time outs during log download from QGC

**Comment by taileron** [comment]
@dagar To make it more objective, I have now taken the master from September 5th (currently my most stable) and switched off RXDMA for UART4 and USART2.
Now also the lost packets in the telemetry and aborts or timeouts in the log download disappear along with all working GPS.  
For further testing I switched off the RXDMA for the cross connection UART8 to the IO but even after I undid it, I can't get the IO to start from now on anyhow the FW doesn't accept the checksum of the IO after the external Flash via SWD

**Comment by taileron** [comment]
@dagar later IO firmwares are a few bytes bigger, if you flash an older one via SWD, the area above the smaller FW will remain with the previous code.
If you delete F000-FC00 manually before, the IO works again, but I can't determine if the connection to the IO is better with or without UART8 RXDMA. If RXDMA would work correctly, it should be more tolerant of wrong timings etc.

**Comment by LorenzMeier** [comment]
Could you re-try current master? A bunch of safety checks got into the way of upgrading IO firmware which might have affected you.

**Comment by taileron** [comment]
The IO is still not automatically updated (with and without pressing SB at start).
Which IO bootloader is expected by this procedure? So far I have tested the PX4 BL Master and one I got from MRO/APM  https://firmware.ardupilot.org/Tools/Bootloaders/px4io_bl.bin.

**Comment by taileron** [comment]
most aspects of the board are already full functional: sensors, rc in, mavlink, io, uavcan all works quite stable.

a few issues are left:
- uarts are not working smooth (compared to e.g. PixRacer) especially with active RX or TX dma
- gps is only recognised with rx dma = off
- CONFIG_ARMV7M_LAZYFPU=y      causes hardfault  #16548 
- io fw update can only be carried out via swd, not from fmu
- mtd driver doesn´t start
ERROR [PX4_MTD] failed to initialize mtd driver
ERROR [PX4_MTD] mtd failure: -5 bus 2 address 0 class 1

**Comment by taileron** [comment]
can be closed only #17558 is left for this board

**Comment by taileron** [comment]
the dsm input always worked perfect with the board because rx dma was never set to that correponding port
