### ISSUE TITLE
hovergames disarm in air

### ISSUE THREAD

**Issue by dagar** [PX4/PX4-Autopilot#15810]
https://review.px4.io/plot_app?log=37ee74be-7c86-41b9-b172-115dcd91cd5b
https://www.youtube.com/watch?v=6e8kV0kW_Gk

![Screenshot from 2020-09-24 11-12-02](https://user-images.githubusercontent.com/84712/94164261-d0168200-fe56-11ea-9e45-b9f9e6f2eb65.png)

https://github.com/PX4/Firmware/pull/13992#issuecomment-698317062

@igalloway

**Comment by dagar** [comment]
Disarmed by safety button while still in the air.

I would propose that we remove the ability for the safety button to disarm (at least by default).

**Comment by landonh12** [comment]
Here is the flight log: https://review.px4.io/plot_app?log=37ee74be-7c86-41b9-b172-115dcd91cd5b

**Comment by dagar** [comment]
Going by the details in your log the change in https://github.com/PX4/Firmware/pull/15811 should have prevented the disarm in air.

I'd still like to more explicitly have the safety disarm behavior entirely disabled by default, including px4io side.

**Comment by dagar** [comment]
Fixed by https://github.com/PX4/PX4-Autopilot/pull/15811.
