### ISSUE TITLE
Gazebo simulation of Typhoon causes flip/crash on takeoff

### ISSUE THREAD

**Issue by mjforan** [PX4/PX4-Autopilot#15879]
I am simulating in Gazebo using Ubuntu 18.04 running on VMWare ESXi. There are a few different models of drones pre-made for use with the simulator. I have been using the 3DR Iris, which works fine, but I want to use the camera plugin so I tried switching to the Yuneec Typhoon. I launch the simulator with the command `make px4_sitl gazebo_typhoon_h480`, as per the simulation tutorial page. When I try to take off (either through my autopilot script or QGroundControl) the drone promptly does a flip and crashes upside-down on the ground

Here are log files for the [successful Iris takeoff](https://logs.px4.io/plot_app?log=f7c7ee5d-fa5a-47cf-b572-ee711f3e1893) and the [Typhoon failure](https://logs.px4.io/plot_app?log=003e3314-1c9f-4860-8e16-a01245fb6003).

Potentially related to #14997 , where another user experiences flips during flight of a simulated drone.

**Comment by Jaeyoung-Lim** [comment]
This was fixed in https://github.com/PX4/PX4-Autopilot/pull/16519
