### ISSUE TITLE
SITL test failures to investigate

### ISSUE THREAD

**Issue by dagar** [PX4/PX4-Autopilot#15894]
- https://github.com/PX4/Firmware/pull/15892/checks?check_run_id=1215051101

**Comment by dagar** [comment]
![Screenshot from 2020-10-06 09-58-14](https://user-images.githubusercontent.com/84712/95211374-7ac56380-07ba-11eb-8ca7-19fca355a2dd.png)

**Comment by Jaeyoung-Lim** [comment]
The failure seems intermittent: re-running the tests can make the tests fail / pass on different tests

**Comment by dagar** [comment]
> The failure seems intermittent: re-running the tests can make the tests fail / pass on different tests

"Have you trying turning it off and on again?"

**Comment by dagar** [comment]
We should fix the ulg upload in these.
![Screenshot from 2020-10-06 09-59-05](https://user-images.githubusercontent.com/84712/95211543-b7915a80-07ba-11eb-8583-bd637f9589f3.png)

**Comment by Jaeyoung-Lim** [comment]
@dagar What do you mean by off/on? - I run the same tests in sitl_gazebo, and running it 3-4 times make it pass.

- We need to investigate this, but not sure where to start

**Comment by dagar** [comment]
@julianoes what do you think about extending the mavsdk test runner (python) to also upload logs to flight review (with all metadata)? I think it would help debug failures if we could trivially compare flight review runs side-by-side (failure and last success).
