### ISSUE TITLE
v1.11.1, dsm channel shift: misleading comment in lib/rc/dsm.cpp

### ISSUE THREAD

**Issue by Roman-** [PX4/PX4-Autopilot#15915]
After the `dsm_channel_shift` variable definition here https://github.com/PX4/Firmware/blob/v1.11.1/src/lib/rc/dsm.cpp#L78 the comment says it can have values 0, 1 and 2.
Later in the code it is being assigned to values 10, 11: https://github.com/PX4/Firmware/blob/v1.11.1/src/lib/rc/dsm.cpp#L247.

**Comment by LorenzMeier** [comment]
Thanks, fixed! https://github.com/PX4/PX4-Autopilot/commit/0bdae5745aec4efb2a32e0967ae43ba0563852b3
