### ISSUE TITLE
Durandal can't connect to companion computer

### ISSUE THREAD

**Issue by bys1123** [PX4/PX4-Autopilot#15944]
**Describe the bug**
Durandal can't connect to companion computer, tested on Telem2.
Same setting on Pixhawk4 works fine

**Log Files and Screenshots**
![image](https://user-images.githubusercontent.com/4748411/95704925-004a8700-0c85-11eb-92ee-be5f14e2aab6.png)
![image](https://user-images.githubusercontent.com/4748411/95704986-30922580-0c85-11eb-9926-0d6f82f3ed0f.png)

**Comment by dagar** [comment]
Do you get any particular error? What does `mavlink status` on the console say?

**Comment by bys1123** [comment]
![image](https://user-images.githubusercontent.com/4748411/96371367-0617ff00-1194-11eb-9e98-2acccf70d15d.png)

**Comment by dagar** [comment]
On the Durandal side what does `mavlink status` show?

**Comment by bys1123** [comment]
I don't have a Durandal on hand recently, this output are from my client, hope it will help, let me know if you need further information
![image](https://user-images.githubusercontent.com/4748411/99353946-7c696780-28e0-11eb-8d7a-b1042fc375a2.png)

**Comment by bys1123** [comment]
Other users tested fine on latest firmware, closed.
