### ISSUE TITLE
How to disable airspeed blend in VTOL transition ?

### ISSUE THREAD

**Issue by moreba1** [PX4/PX4-Autopilot#15969]
Hi

I set VT_ARSP_BLEND =0  but blending started in transition. How I can disable servo actuators during the transition?

Parameter: VT_ARSP_BLEND

"By default, as the airspeed gets close to the transition speed, multirotor attitude control will be reduced and fixed-wing control will start increasing continuously until the transition occurs.
Disable blending by setting this parameter to 0 which will keep full multirotor control and zero fixed wing control until the transition occurs."

**Comment by moreba1** [comment]
@dagar 
@RomanBapst

**Comment by ThomasRigi** [comment]
As a quick fix you can set VT_ARSP_BLEND to your transition airspeed

**Comment by moreba1** [comment]
> 
> 
> As a quick fix you can set VT_ARSP_BLEND to your transition airspeed

I setted VT_ARSP_BLEND to transition airspeed but it did not stop.

**Comment by moreba1** [comment]
@RomanBapst

**Comment by sfuhrer** [comment]
@moreba1 Disabling fixed-wing actuation during transition is currently not possible. It will be active from the start of the transition. The blending only refers to the MC actuaion (it will "blend it out"). --> We need to fix the parameter description  ~"fixed-wing control will start increasing continuously until the transition occurs."~ In some way, the FW actuators are also "blended in" automatically, as they gain effectiveness with increased airspeed.

May I know why you want it to be disabled during transition?

**Comment by moreba1** [comment]
> May I know why you want it to be disabled during transition?

For prevention from Intermingling of the controllers.

**Comment by sfuhrer** [comment]
> For prevention from Intermingling of the controllers.

With the current VTOL architecture where we have separate controllers running for MC and FW flight, we always need some sort of blending from one to the other.
