### ISSUE TITLE
Boot Loop on when hardfault corrupts the TCB stack size

### ISSUE THREAD

**Issue by davids5** [PX4/PX4-Autopilot#16027]
If the TCB is overwritten in such a way that 

adj_stack_ptr and/or adj_stack_size when combined create an invalid bus reference while checking the stack penetration.

We need to present the uses with the coice to clean the bad fault data or a boot loop ensues. 

Enter B - Continue booting
Enter C - Clear the fault log
Enter D - Dump fault log

The solution is a persistent critical section marker. (as one more char dev in bbsram or as a RTC REG)

**Comment by LorenzMeier** [comment]
Fixed.
