### ISSUE TITLE
sbus out using pixhawk 2 with orange cube

### ISSUE THREAD

**Issue by rakeshsahay1** [PX4/PX4-Autopilot#16054]
How can i use tarot peeper 10x gimble with pixhawk cube . using sbus out only .

**Comment by rakeshsahay1** [comment]
req help. iam new in pixhawk  users

**Comment by LorenzMeier** [comment]
Use the output labeles S.BUS out

**Comment by Ashok-killis** [comment]
How to use tarot peeper 10x gimble with pixhawk cube orange ?
