### ISSUE TITLE
Compass calibration resets

### ISSUE THREAD

**Issue by LaurensKools** [PX4/PX4-Autopilot#16070]
Hi everyone!

I’m using a Cube Orange with PX4 1.11.0, Here 2 GPS and Qgroundcontrol V4.0. Every time the system reboots (either via software or unplug the power), the compass calibration resets and the heading is inconsistent (pre-flight fail: Compasses inconsistent by x degrees). When recalibrating all sensors (gyro, accel, level horizon and compass) and not click “reboot” it does work fine. However, doing this every time after a reboot shouldn’t be necessary so is there a solution to this problem?

**Comment by dagar** [comment]
Are you losing other parameters on reboot?

**Comment by LaurensKools** [comment]
No that's not the case. I also tried different orange cube's but same issue appears

**Comment by LaurensKools** [comment]
@dagar do you have an idea how to solve this?

**Comment by dagar** [comment]
> @dagar do you have an idea how to solve this?

Could you verify exactly what's on your system?

From the command line (serial console or through QGC mavlink console).

`work_queue status`
`listener sensor_mag`
`param show CAL_MAG*`

**Comment by LaurensKools** [comment]
@dagar yes sure, captured the results below:
![px4_bug](https://user-images.githubusercontent.com/43440815/98011815-a3ac3900-1df8-11eb-9f97-9315cad1452c.png)

**Comment by dagar** [comment]
Ok, so it looks like the Here2 isn't being detected at all.

**Comment by julianoes** [comment]
Closing this, follow up in https://github.com/PX4/PX4-Autopilot/issues/15591
