### ISSUE TITLE
Rename NXP RDDRONE-UAVCAN146 to UCANS32K146

### ISSUE THREAD

**Issue by jarivanewijk** [PX4/PX4-Autopilot#16085]
@davids5, would it be possible to rename the RDDRONE-UAVCAN146 board to UCANS32K146? This has also been discussed with @igalloway.

I think this name was copied from the NuttX boardconfig that we created, which we actually plan to change soon as well. UCANS32K146 is the official product code/name and it's also more in line with our other boards supported by PX4 (FMUK66 and FMURT1062).

**Comment by davids5** [comment]
Can do. I will put it on my list

**Comment by jarivanewijk** [comment]
Already renamed. Thanks again, David.
