### ISSUE TITLE
HITL based on gazebo, File and command errors

### ISSUE THREAD

**Issue by mengchaoheng** [PX4/PX4-Autopilot#16134]
developer documentation in https://dev.px4.io/master/en/simulation/hitl.html used a wrong command：gazebo Tools/sitl_gazebo/worlds/iris.world。In the current master branch, it should be：gazebo Tools/sitl_gazebo/worlds/hitl_iris.world
, but There seems to be a problem with the Tools/sitl_gazebo/models/iris_hitl/iris_hitl.sdf file. After I overwrite its content with the content of the Tools/sitl_gazebo/models/iris/iris.sdf file, it works perfectly.

**Comment by Jaeyoung-Lim** [comment]
@mengchaoheng Thanks, would you be able to make a PR for this fix?

**Comment by julianoes** [comment]
Thank you, I've fixed it in https://github.com/PX4/PX4-user_guide/pull/1238
