### ISSUE TITLE
can’t load aux file

### ISSUE THREAD

**Issue by Zywu1996** [PX4/PX4-Autopilot#16144]
I’m tring to load my own aux mixer file but always fail.
The reason I found was that in the startup file rcS, the program set SYS_USE_IO to 0, which caused the subsequent aux file loading process to be skipped.

I guess the problem is caused by hardware. The board I use is [cuav_v5_nano](https://docs.px4.io/master/en/flight_controller/cuav_v5_nano.html).

How can I solve this problem?

**Comment by bkueng** [comment]
Mixer files got removed in https://github.com/PX4/PX4-Autopilot/pull/19990.
