### ISSUE TITLE
[Regression] PX4 takes more time to build

### ISSUE THREAD

**Issue by lukegluke** [PX4/PX4-Autopilot#16162]
I notice that after moving to latest PX4 with upgraded NuttX 10.0.0 it takes more time to build, even if there is nothing to build. Previously there was such output: "nothing to build", now it always "hanging" longer and then prints `[1/4] Generating apps/libapps.a, apps/platform/.built` and elf linking output.

I'm using Windows toolchain, but @MaEtUgR think it can be general build system issue.

**Comment by dagar** [comment]
Can you give https://github.com/PX4/PX4-Autopilot/pull/16163 a try?

**Comment by lukegluke** [comment]
> Can you give #16163 a try?

Yes it helps, minimize "hanging" and `ninja: no work to do` as it was before, thanks!
