### ISSUE TITLE
Help using the Bezier Trajectory Interface in Offboard mode

### ISSUE THREAD

**Issue by Kavin-Kailash** [PX4/PX4-Autopilot#16184]
Hello devs,

I recently found that PX4 supports the [bezier trajectory representation](https://docs.px4.io/master/en/computer_vision/path_planning_interface.html#companion-bezier-trajectory-interface) in Auto Modes by using the [TRAJECTORY_REPRESENTATION_BEZIER](https://mavlink.io/en/messages/common.html#TRAJECTORY_REPRESENTATION_BEZIER) mavlink message. I wanted to explore the possibility of using a similar interface for Trajectory tracking in Offboard mode, to follow arbitrary reference paths. 

That is, the result from a high-level planner (ROS-based) will be parameterised to a bezier trajectory and passed to PX4 for execution.

Any directions on how to achieve this (make PX4 execute the trajectory) would be highly appreciated.

Thanks in Advance!

**Comment by dagar** [comment]
The avoidance library is what consumes the bezier trajectory (https://github.com/PX4/PX4-Autopilot/blob/master/src/lib/avoidance/ObstacleAvoidance.cpp) as `ORB_ID(vehicle_trajectory_bezier)` within PX4.

In the context of OFFBOARD you could consume and use it within the Offboard flight task (https://github.com/PX4/PX4-Autopilot/tree/master/src/lib/flight_tasks/tasks/Offboard).
