### ISSUE TITLE
gazebo_sitl_multiple_run.sh appears to always give unsupported airframe error in script mode (-s)

### ISSUE THREAD

**Issue by bbworld1** [PX4/PX4-Autopilot#16182]
**Describe the bug**
When running the `Tools/gazebo_sitl_multiple_run.sh` multi sim script in -s mode (`-s iris:2,plane:1` as specified by examples), the script errors out saying that the airframe is unsupported, even though iris and plane are fully supported.

**To Reproduce**
0. Setup gazebo simulation with PX4 sitl
1. Compile the sim (`make px4_sitl gazebo`)
2. Run (`Tools/gazebo_sitl_multiple_run.sh -s iris:2,plane:1`)
3. Look on in disbelief as it says iris is unsupported, then proceeds to tell you that iris is one of the supported models

I am running the simulation using the `px4io/px4-dev-simulation-bionic:latest` Docker image, but other environments with similar bash versions likely will run into the same error.

**Expected behavior**
`gazebo_sitl_multiple_run.sh` runs without error.

Relevant code causing the issue appears to be here:

```bash
	if [[ " ${SUPPORTED_MODELS[*]} " != *"$MODEL "* ]];
	then
		echo "ERROR: Currently only vehicle model $MODEL is not supported!"
		echo "       Supported Models: [${SUPPORTED_MODELS[@]}]"
		trap "cleanup" SIGINT SIGTERM EXIT
		exit 1
	fi
```
Removing the quotes and space (`*$MODEL*`) appears to fix the problem. I have a fix on my fork, but would like to hold off on submitting a PR until this is reproduced.

**Comment by Jaeyoung-Lim** [comment]
@bbworld1 I could reproduce your results and made a fix in #16340

Would you be able to test if this fixes your problems?
