### ISSUE TITLE
Wrong order of else if statements for setpoint type allocation

### ISSUE THREAD

**Issue by Jonny-air** [PX4/PX4-Autopilot#16218]
https://github.com/PX4/PX4-Autopilot/blob/387659d61589928fbba2d4cf5454eb8f08c89b95/src/modules/mavlink/mavlink_receiver.cpp#L860-L880

Hello, for a project I added a setpoint type and stumbled across this. It seems that the order of "else if" statements achieves the opposite of what it is intended to do according to the comment ("Takeoff can override loiter"). It seems that the logic still makes sense, since a loiter setpoint is always also a takeoff and land setpoint due to the bitmask. Is the comment just wrong here?

Cheers,
Jonathan

**Comment by Jaeyoung-Lim** [comment]
@Jonny-air I think the comment itself is correct, but might not be clear enough. It simply means that since takeoff can override loiter, with the bit masks the conditions are ordered in a specific order. Changing the behavior will lead to change of behavior
