### ISSUE TITLE
Regression: pixhawk 4 out of service on master

### ISSUE THREAD

**Issue by MaEtUgR** [PX4/PX4-Autopilot#16230]
**Describe the bug**
Regression: Flashing the IO chip fails on a pixhawk 4 flashed with latest master.

**Found by @priseborough** 🙏 
FYI @dagar / @davids5 

**To Reproduce**
1. Fetch latest master f18e70029ab873fca52c950eb860009c05e3c03e
2. Flash a pixhawk 4 `make fmu-v5 upload`
3. When it boots hear fast beeping all the time, IO pins don't come up
4. MAVLink shell
![image](https://user-images.githubusercontent.com/4668506/99644217-f1a67b00-2a4d-11eb-90c2-79060c3e8dbe.png)

**Expected behavior**
Flashes IO chip, stopps beeping and IO pins come up.

**Log Files and Screenshots**
https://photos.app.goo.gl/YB4pTSUkK7eiz3FN7

**Drone (please complete the following information):**
- Reproducable with bare board hooked up over USB

**Additional context**
Flashing back stable 1.11.2 recovers it all. **EDIT:** Only after wiping the parameters and loading a new airframe?

**Comment by priseborough** [comment]
For reference, when I also encountered this behaviour, the relevant airframe parameters in use at the time were:
 
<img width="306" alt="Screen Shot 2020-11-19 at 8 31 51 pm" src="https://user-images.githubusercontent.com/3596952/99647755-5097de80-2aa6-11eb-9367-171d9d132146.png">

**Comment by MaEtUgR** [comment]
I have another clue: dmesg repeatedly shows "px4io bad sync" 💡 
<details><summary>dmesg output</summary>
<p>

#### yes, even hidden code blocks!

![image](https://user-images.githubusercontent.com/4668506/99650257-7c3ea880-2a55-11eb-8a1b-98d62a607beb.png)

</p>
</details>

**Comment by davids5** [comment]
I see the issue......

**Comment by davids5** [comment]
I suspected the timing had changed...but it was not that simple.

**Comment by MaEtUgR** [comment]
Thanks @davids5 !
