### ISSUE TITLE
Make px4_sitl gazebo crashes whole system.

### ISSUE THREAD

**Issue by LightningPORTO** [PX4/PX4-Autopilot#16232]
After a clean installation, with all the dependencies and submodules, the PX4 SITL Gazebo make is crashing the hole system.

**To Reproduce**
1. Clean installation;
2. Download current branch & dependencies
3. run "make px4_sitl gazebo"

**Expected behavior**
Successful make of SITL gazebo

**Comment by Jaeyoung-Lim** [comment]
@LightningPORTO Have you looked at your memory? Probably you don't have enough RAM?

**Comment by julianoes** [comment]
Try `make px4_sitl gazebo -j2`

**Comment by LightningPORTO** [comment]
> @LightningPORTO Have you looked at your memory? Probably you don't have enough RAM?

I have 16 Gb, it goes wild when compiling. Im using htop to check it

**Comment by LightningPORTO** [comment]
> make px4_sitl gazebo -j2

Same problem

**Comment by Jaeyoung-Lim** [comment]
> 4. See error

Can you share the error?

**Comment by LightningPORTO** [comment]
There is no error, it just freezes the PC

**Comment by dagar** [comment]
@LightningPORTO try adding `-- -j1` here. https://github.com/PX4/PX4-Autopilot/blob/aa80167b476957f546a33b4626752958e9d30518/platforms/posix/cmake/sitl_target.cmake#L48

**Comment by LightningPORTO** [comment]
Still doesnt fix it. Im closing this issue, but the error is still there. Something to to with the gazebo Sitl submodules
