### ISSUE TITLE
Some questions about the paper"Attitude and Thrust Strategies for Fully-Actuated Multirotors: The Fast-Track to Real-World Applications"

### ISSUE THREAD

**Issue by daydayupcg137** [PX4/PX4-Autopilot#16249]
Hi, in the paper "Attitude and Thrust Strategies for Fully-Actuated Multirotors:
In "The Fast-Track to Real-World Applications", what do you think of The experimental data of your last tilted UAV?It feels like the experimental data is not good compared to the zero tilt drone

**Comment by keipour** [comment]
> Hi, in the paper "Attitude and Thrust Strategies for Fully-Actuated Multirotors:
> In "The Fast-Track to Real-World Applications", what do you think of The experimental data of your last tilted UAV?It feels like the experimental data is not good compared to the zero tilt drone

Hi daydayupcg137. You have submitted the issue in the main PX4 forum, which is not monitored by the authors (I saw this post completely by chance). Please feel free to email me directly about the paper.
