### ISSUE TITLE
ninja: build stopped: subcommand failed. Makefile:200: recipe for target 'px4_sitl' failed

### ISSUE THREAD

**Issue by daydayupcg137** [PX4/PX4-Autopilot#16259]
Today I had a few problems during the compilation of your firmware, I clone your code in the ubuntu18.04 "git clone https://github.com/PX4/PX4-Autopilot.git --recursive", but I "make px4_fmu_v3_default" or use other compiler command, an error is as follows:
![image](https://user-images.githubusercontent.com/66363845/99955363-32402480-2dbf-11eb-9e06-aa07804c40ae.png)

**Comment by Jaeyoung-Lim** [comment]
@daydayupcg137 Something is not right. You mention that you are trying to build for fmuv3, which the make target you have written is not correct. It should be
```
make px4_fmu-v3_default
```

But on top of that, the error says that you are trying to build SITL(Software-In-The-Loop) simulation.
