### ISSUE TITLE
px4 support for pixracer pro

### ISSUE THREAD

**Issue by berndpfrommer** [PX4/PX4-Autopilot#16289]
The newest "pro" version of the pixracer is only supported on ArduPilot. 
https://store.mrobotics.io/mRo-PixRacer-Pro-p/m10064c.htm

Are there any plans of getting the px4 stack to work on this hardware?
Thanks!

**Comment by mhkabir** [comment]
Adding support is in-progress here: https://github.com/PX4/PX4-Autopilot/pull/15939
