### ISSUE TITLE
ssh: connect to host 10.0.0.1 port 22: Connection refused fatal: 无法读取远程仓库。

### ISSUE THREAD

**Issue by daydayupcg137** [PX4/PX4-Autopilot#16303]
when   I  use "git pull --tags", the error is as follows:

**ssh: connect to host 10.0.0.1 port 22: Connection refused**
fatal: 无法读取远程仓库。
请确认您有正确的访问权限并且仓库存在。

Can someone help me?Thank you very much

**Comment by dagar** [comment]
I'd start by checking your local git config ($HOME/.gitconfig) and your git remotes `git remote -v` to see if anything is misconfigured.

I don't see how anything in PX4 would be causing this.
