### ISSUE TITLE
PX4 v1.11.1 NSH problem

### ISSUE THREAD

**Issue by aet2230** [PX4/PX4-Autopilot#16302]
Hi!
After upgrading to 1.11.0, 1.11.1 I have the following problem with NSH:
I can connect NSH via QGC
When I run "top" - I can see the modules running.
All other commands to communicate with PX4 modules, such as: `listener`, `"module" start` (for example `mavlink stop`) atc..., I get
`unknown command`.
In 1.10 everything works

**Comment by dayjaby** [comment]
Did you cancel the top command by typing c and then enter in the MAVLink console?

**Comment by aet2230** [comment]
Please ignore. Everything works
