### ISSUE TITLE
Problem mavlink communication between FMU and a companion computer

### ISSUE THREAD

**Issue by dmdobrea** [PX4/PX4-Autopilot#16308]
Based on the MAVLink Messaging tutorial (https://dev.px4.io/v1.10/en/middleware/mavlink.html), I followed all the step, but when I compile the code I get the error:

error: ‘MavlinkOrbSubscription’ does not name a type 

in mavlin_messages.c.

Searching I found that the MavlinkOrbSubscription class is included in "the mavlink_orb_subscription.h" file. But, I do not have a such file in the PX4 master release.

The file can be founded in 1.10.2 version. 

So, plese can you update the 1.11.2 version with all the components? 

Thank you very much!!!

Dobrea Dan

**Comment by antonio-sc66** [comment]
Looks like the documentation hasn't been updated. Use uORB::Subscription instead of MavlinkOrbSubscription

**Comment by dmdobrea** [comment]
Thank you, very much! I am working now.

**Comment by igalloway** [comment]
@Hamish Willee <hamishwillee@gmail.com>

**Comment by hamishwillee** [comment]
Thanks @igalloway - this is being tracked in https://github.com/PX4/PX4-user_guide/pull/932

**Comment by antonio-sc66** [comment]
@dmdobrea The tutorial should be working now, check https://docs.px4.io/master/en/middleware/mavlink.html

**Comment by dmdobrea** [comment]
Thank you!!!
