### ISSUE TITLE
EKF2 large attitude estimate jumps

### ISSUE THREAD

**Issue by JMshare** [PX4/PX4-Autopilot#16300]
We are experiencing some large attitude estimate jumps during our fixed-wing flights, see bellow.
![image](https://user-images.githubusercontent.com/22155994/100553445-d9243500-3285-11eb-939b-f313fc00e234.png)

I found out that they match the `quat_reset_counter` changes in the `vehicle_attitude` topic, but I can't say what triggers them.

Now, I can live with the small jumps in pitch and roll, but 50 degree yaw jump if you are using differential thrust for yaw control is not  great. The next few seconds after each jump is the reaction of the plane trying to get back to stable.

Nothing extraordinary seen in the `vehicle_magnetometer` data that should be triggering this I think.
Log [https://review.px4.io/plot_app?log=6a0e6bec-c709-4d34-9ba2-031072c61098](url)

I am using the Pixhawk4 with the default UBLOX NEO M8N GPS module. Firmware v1.9.0.
The EKF2 estimator is used, `EKF2_MAG_TYPE` set to default 0. Seems like it is running in the 3-axis fusion mode once it is in the air.

Do you know why this is happening and how to prevent it?

**Comment by JMshare** [comment]
Hello,

is this really not considered an issue here? I have at least one of these jumps in every single flight log from May 2019
![image](https://user-images.githubusercontent.com/22155994/101379532-49494100-38ac-11eb-904a-d90dc6bd21ae.png)

**Comment by dagar** [comment]
There are quite a few faults in that log.

<img width="1337" alt="Screen Shot 2020-12-07 at 2 11 42 PM" src="https://user-images.githubusercontent.com/84712/101394223-30359580-3896-11eb-8405-1b8e4747fd18.png">

The magnetic heading innovations also look questionable.

<img width="1178" alt="Screen Shot 2020-12-07 at 2 12 42 PM" src="https://user-images.githubusercontent.com/84712/101394308-4fccbe00-3896-11eb-82c7-49c2bb0b5d68.png">


You said your based on PX4 v1.9.0? As a start I'd highly recommend updating to v1.11.2 or even current master (soon to be v1.12). The main estimator (ekf2) has improved considerably in the past couple years.

**Comment by JMshare** [comment]
Thanks Daniel, I will try that.

**Comment by mrpollo** [comment]
Let us know how it goes @JMshare feel free to re-open the issue once you check with the latest PX4
