### ISSUE TITLE
BMX055 Driver

### ISSUE THREAD

**Issue by Pskoog3** [PX4/PX4-Autopilot#16319]
Please add driver support for BMX055 IMU.

**Comment by dagar** [comment]
I'm not aware of any boards that use this sensor. Any reason to prefer it over existing options?

For support you could start with BMI055 and see if it's similar. https://github.com/PX4/PX4-Autopilot/tree/master/src/drivers/imu/bosch

**Comment by mrpollo** [comment]
@Pskoog3 let us know if you have a board that is using this sensor, we can help you add support for your board
