### ISSUE TITLE
Wrong Ignition Math library installed via Ubuntu toolchain script

### ISSUE THREAD

**Issue by ryanjAA** [PX4/PX4-Autopilot#16349]
Tested on a Fresh Ubuntu 20.04.1 install

When running the Ubunto.sh toolchain script from Master (https://github.com/PX4/PX4-Autopilot/commit/3276916df94cc2376a5fe500539860d56fd2ca71), the ignition math 6 library is installed. Flightgear requires  Math 4 and doesn't work with 6.

A sudo apt-get install -y libignition-math4-dev fixes this.

**Comment by Jaeyoung-Lim** [comment]
@ryanjAA That is actually a problem of the flightgear bridge. the default toolchain script is not installing any of the flightgear bridge dependencies.

Also, having a ignition dependency from flightgear doesn't make any sense. Related: https://github.com/ThunderFly-aerospace/PX4-FlightGear-Bridge/issues/15
