### ISSUE TITLE
Metadata: add support for tagged versions

### ISSUE THREAD

**Issue by bkueng** [PX4/PX4-Autopilot#16351]
From https://github.com/PX4/PX4-Autopilot/pull/16039, for boards that will use external metadata:
- Push metadata for a released version to S3 to a directory with the tag name
- Use that URL in `component_info.metadata_uri`

**Comment by dagar** [comment]
At the moment it's going to be something like

 - master/main
    - vendor (eg px4)
      - board (eg fmu-v5)
         - compressed metadata (airframe, parameters, etc)
 - vX.Y.Z (includes anything tagged alpha, beta, RC, etc)
    - vendor
      - board
         - compressed metadata (airframe, parameters, etc)


One edge case this is glossing over is if we want to handle board variants (specialized builds). 

I'm also still potentially interested in making these metadata packages available by hash for the sake of development builds.

**Comment by bkueng** [comment]
>  One edge case this is glossing over is if we want to handle board variants (specialized builds).

I think we have to, otherwise we don't have all metadata for e.g. all v2 build variants.

Also important: the max url length is 70 chars for the mavlink message. I was thinking we can use the board ID instead of the full name.

**Comment by bkueng** [comment]
Done in https://github.com/PX4/PX4-Autopilot/pull/17191
