### ISSUE TITLE
Add a gimbal to iris

### ISSUE THREAD

**Issue by AliaChe** [PX4/PX4-Autopilot#16378]
Hello, 

I'm trying to add a gimbal to the iris model and I'm facing these two main problems : 
 
- The drone control performance is degrading, especially when the drone is trying to stop.
- The gimbal control performance is deteriorated in some configurations. 

So, I'm using these commits :
 PX4-Autopilot :  378b41af6a91cb5dfcabb24421f0a0c9e21a98e5
 px4_msgs : 227223c5aeb1873c1b2e3629592d8739a0af652d
 px4_ros_com : 958ccdb3323ca0655a57ed0d9f998de565e573b6
 
Here is how I proceed :
Based on the typhoon_h480's model, where a gimbal is modeled and controlled, I build the iris model with gimbal (see iris_gimbal.sdf file). 
Then I add the files 1999_iris_gimbal and 1999_iris_gimbal.post  to PX4-Autopilot/ROMFS/px4fmu_common/init.d-posix/airframes.
Finally, I use the iris_gimbal.launch.py file to launch the simulation, where I set the environment variable 'PX4_SIM_MODEL' to 'iris_gimbal'. 

Here are my files:
https://gist.github.com/AliaChe/a2467ba3a95bc3d89e023c65a8ce5a9a

With this configuration, the drone control is deteriorated, it has a large response time. So, we can see the drone falling down and then retrying to gain its altitude in nearly 0.5 to 1 second. 

The second problem is related to the gimbal controller. Once I remove the sonar model from my configuration, the gimbal starts to move in all directions when the drone is spawn into gazebo and when the drone starts moving, the control performance is not satisfactory.  

Thanks in advance.

**Comment by mrpollo** [comment]
@Jaeyoung-Lim do you have any hints for @AliaChe ?

**Comment by Jaeyoung-Lim** [comment]
@AliaChe 

> With this configuration, the drone control is deteriorated, it has a large response time. So, we can see the drone falling down and then retrying to gain its altitude in nearly 0.5 to 1 second.

I think this is expected and representitive on what will happen in the real world if you add additional payload to the drone - you need to retune the vehicle. 

> The second problem is related to the gimbal controller. Once I remove the sonar model from my configuration, the gimbal starts to move in all directions when the drone is spawn into gazebo and when the drone starts moving, the control performance is not satisfactory.

Are you sure you have all the gimbal control channels configured in the mixer and also the sdf configured correctly?

**Comment by AliaChe** [comment]
@Jaeyoung-Lim  

Thanks for your reply.

I agree, I will try retuning the vehicle. However, I have succeeded to add a gimbal to iris without retuning the drone controllers, using ros-eloquent and an older version of PX4-Autopilot (9fcbf18d).

Concerning the gimbal controller, the control channels are configured correctly in the sdf. I'll check the mixer to verify.

**Comment by AliaChe** [comment]
@Jaeyoung-Lim 

In fact, the problem of the vehicle control is solved once I reset the motors constant value to 8.54e-06 as in sitl_gazebo 0da08f0 instead of 5.84e-06 as in sitl_gazebo cd8ba25.

**Comment by LorenzMeier** [comment]
The gimbal is too heavy for a "realistic" IRIS model. You would need to completely re-design also the trust curves.
