### ISSUE TITLE
ekf2 airspeed check bit on a multicopter

### ISSUE THREAD

**Issue by dagar** [PX4/PX4-Autopilot#16372]
This is from a quadcopter that as far as I know doesn't have an airspeed sensor.

<img width="801" alt="Screen Shot 2020-12-10 at 9 23 17 PM" src="https://user-images.githubusercontent.com/84712/101853721-1615e480-3b2e-11eb-8f1f-f4f9464e2e27.png">

https://logs.px4.io/plot_app?log=0ad8c6f0-a7d5-47a1-be91-0da064561eea

**Comment by bresch** [comment]
There's a mismatch between the ecl and firmware bitmasks.

The innovation that fails is the yaw observation
![2020-12-11_09-45-29_01_plot](https://user-images.githubusercontent.com/14822839/101882153-c4a14000-3b95-11eb-9677-0d89791aea77.png)

**Comment by dagar** [comment]
> should we log 13 booleans instead of a bitmask?

Yes please! It'll burn a bit of flash storing the string for each field (need for listener and logger), but I think it's worth it.

**Comment by dagar** [comment]
Started in https://github.com/PX4/PX4-Autopilot/pull/16383.

**Comment by mrpollo** [comment]
@dagar where should we track this issue? (which project board?)

**Comment by dagar** [comment]
We can consider this fixed by https://github.com/PX4/PX4-Autopilot/pull/16383.
