### ISSUE TITLE
HMC6343 Driver Support

### ISSUE THREAD

**Issue by Pskoog3** [PX4/PX4-Autopilot#16374]
Please include driver support for three-axis compass HMC6343 for PX4.

**Comment by mrpollo** [comment]
@Pskoog3 thanks for your comment, we can help guide you implement the driver, do you have the hardware available?

I'm closing this issue, please open a forum post, or join us on Slack if you want help writing the driver

https://discuss.px4.io
http://slack.px4.io

**Comment by ryanjAA** [comment]
Given the high cost of this module what is its benefit? Is there something that stands out about it?

**Comment by ryanjAA** [comment]
Ahh - it is tilt compensated. Isn't that a problem for EKF2?
