### ISSUE TITLE
Logging of actuator_ouputs -> PWM limited to 80Hz

### ISSUE THREAD

**Issue by Lilienthal-GF** [PX4/PX4-Autopilot#16391]
**Describe the bug**
The actuator_output topic can only be logged with 80Hz.

**To Reproduce**
1. Flash PX4-Autopilot v1.11.2
2. Configure IMU_RATE and PWM_RATE to 400Hz
![image](https://user-images.githubusercontent.com/59968353/102193487-6be6e580-3ebc-11eb-9660-71c2cf87ce30.png)
3. Configure SD-Logging Profile to High Rate
![image](https://user-images.githubusercontent.com/59968353/102194204-51f9d280-3ebd-11eb-9583-47d5e823ed34.png)
4. Log flight and extract measurements from ulog file

**Expected behavior**
Measurement should contain the signal actuator_outputs_0 with a rate of 400 Hz -> dt = 0.0025s.

**Log Files and Screenshots**
Plotting the time differences between consecutive ulog messages and the corresponding histogramm shows actutator_outputs to be logged at 80Hz -> 0.0125

![image](https://user-images.githubusercontent.com/59968353/102195013-4fe44380-3ebe-11eb-8d4d-3c37c7950f0e.png)

**Drone (please complete the following information):**
- Holybro S500 with Holybro pixhawk4

**Comment by dagar** [comment]
Did you reboot after updating `SDLOG_PROFILE`?

**Comment by Lilienthal-GF** [comment]
Thank you for the quick response.

I did reboot the vehicle. In fact tested recalibrating the sensors and ESCs and complete air frame resets followed by the described calibration and a reboot. What i didn't do so far is test on a number of pixhawks.

**Comment by dagar** [comment]
Can you share the full log? https://logs.px4.io/

**Comment by dagar** [comment]
In addition to sharing the full log you could check a few things through the mavlink shell to see how fast things are actually running.

``` Console

nsh> uorb top

nsh> work_queue status

nsh> logger status
```

**Comment by Lilienthal-GF** [comment]
I uploaded a measurement 

https://logs.px4.io/plot_app?log=7fdae510-e504-4021-b603-1621ce6ff967

For the measurement the quadcopter was armed without rotors and moved by hand. So the attitude does not respond to the actuator_outputs.

Here is the response to nsh> uorb top
![screenshot1](https://user-images.githubusercontent.com/59968353/102231549-61454400-3eee-11eb-9c6d-3ae531923991.PNG)
![screenshot2](https://user-images.githubusercontent.com/59968353/102231562-63a79e00-3eee-11eb-980d-ae2ad79b2f0f.PNG)

and to nsh> work_queue status
![screenshot3](https://user-images.githubusercontent.com/59968353/102231580-66a28e80-3eee-11eb-8470-c13d59277eb4.PNG)

**Comment by Lilienthal-GF** [comment]
I'm sorry I forgot to do the nsh> logger status, but even so it looks like the rate_ctrl loop are running at the correct rate.

**Comment by dagar** [comment]
@Lilienthal-GF actuator_outputs is only being published at ~ 50 Hz.

![Screenshot from 2020-12-15 10-49-47](https://user-images.githubusercontent.com/84712/102238044-54f7c180-3ec3-11eb-81c1-f8f7d1c330e6.png)

This is because on the Pixhawk 4 the MAIN outputs are actually going out to the px4io over serial, a separate stm32f1 processor.

Reading back the output is throttled to about 50 Hz here. https://github.com/PX4/PX4-Autopilot/blob/aa244a098c39a2b21b82fd9cd5950ed566293fdc/src/drivers/px4io/px4io.cpp#L923-L934

You can lift that limit in the code, but be careful to check the corresponding change in cpu usage.

Alternatively if you really care about getting the full data you might be better off putting the outputs on AUX where the main processor simply directly writes PWM and publishes `actuator_outputs` at corresponding to each actual update. You can even use things like oneshot or dshot if you want to remove additional latency (and your ESCs support it).

**Comment by mrpollo** [comment]
@Lilienthal-GF looks like @dagar answered your question, feel free to re-open if you don't agree or open a new issue if you find something else. Thank you!

**Comment by Lilienthal-GF** [comment]
Thanks for answering my question. I think the issue can stay closed, although i do have a small follow up question.

I was not aware of this distribution of the functionality on the two controllers. The reason for trying to get the PWMs is that we would like to know the outputs of the quadcopter including the limiting and scaling in the mixer for system identification purposes.

So far, i was working under the assumption that the actuator_outputs get published from the mixer_module, i.e.

https://github.com/PX4/PX4-Autopilot/blob/97ab8277ed16a548ee2c933c3c56b6360b2d145b/src/lib/mixer_module/mixer_module.cpp#L385-L391

https://github.com/PX4/PX4-Autopilot/blob/97ab8277ed16a548ee2c933c3c56b6360b2d145b/src/lib/mixer_module/mixer_module.cpp#L414-L421

https://github.com/PX4/PX4-Autopilot/blob/97ab8277ed16a548ee2c933c3c56b6360b2d145b/src/lib/mixer_module/mixer_module.cpp#L428-L439

Can you point me to some documentation, where the interaction of the rate controller, the mixer, and the driver is explained in more details?
