### ISSUE TITLE
actuator_outputs.02 empty or not being logged when using UAVCAN + aux mixer

### ISSUE THREAD

**Issue by RicardoM17** [PX4/PX4-Autopilot#16414]
**Describe the bug**
UAVCAN implementation seems to have some issues on current master or I'm missing a step here. It works well when only 1 mixer is loaded (for example a quadcopter). `actuator_outputs.0` becomes empty and the UAVCAN commands go on `actuator_outputs.1`.

![image](https://user-images.githubusercontent.com/11491719/102488887-0128dc00-406d-11eb-89ed-ea48a0e36460.png)

What happens is that `actuator_outputs.2` just becomes completely empty. Example log: https://logs.px4.io/plot_app?log=c78cffc9-d73e-42b1-a4e5-b752b06e7922

Example picture:

![image](https://user-images.githubusercontent.com/11491719/102489508-d8edad00-406d-11eb-8556-13aafd724044.png)

UAVCAN status reports that the outputs are correct and that mixer is indeed loaded so perhaps it's simply just not logged. I'm running this on a benchtest so I can't confirm for sure that no outputs are coming out.

![image](https://user-images.githubusercontent.com/11491719/102490021-98426380-406e-11eb-8279-411257b43b04.png)

**To Reproduce**
1. Flash current master or any recent version
2. set `UAVCAN_ENABLE` to `3`. Possibly disable `COM_ARM_CHK_ESCS` if in a bench test.
3. Arm
4. Check that `actuator_outputs.2` doesn't show up in the log.

This was tested on a Pixhawk 4 (FMUV5). That's also the same pixhawk running in our drones.

**Expected behavior**

Once an aux mixer is added the behaviour should be as follows with the main mixer as UAVCAN (or at least that's how it was ~April 2020).

`actuator_outputs.0`  = empty

`actuator_outputs.1` = aux mixer output

`actuator_outputs.2` = main mixer output with UAVCAN

![image](https://user-images.githubusercontent.com/11491719/102489851-56b1b880-406e-11eb-8022-dc1719dc74e8.png)

**Other notes**

Since it only happens when there's a main + aux mixer it works fine for example with `4001` quad_x frame. The issue occurs with multiple VTOLs, and also I tried adding an aux_mixer to the `4001` quad_x frame and the issue happened again. So it doesn't seem to be frame specific.

Please let me know if this is a real issue or if I'm simply missing a step that wasn't needed before.

**Comment by GigaFlopsis** [comment]
I have the same problem with VTOL frame on CUAV x7 pro. However CUAV v5 work fine with the same parameters.
