### ISSUE TITLE
Airspeed is not constant in SITL with gazebo with wind

### ISSUE THREAD

**Issue by moreba1** [PX4/PX4-Autopilot#16441]
Airspeed is not constant in SITL with gazebo with wind

log:

https://review.px4.io/plot_app?log=5057cec3-fb7c-4a26-866f-20d3ec035747

**Comment by Jaeyoung-Lim** [comment]
@moreba1 Airspeed is the air relative velocity of the vehicle, therefore it should not be constant if the vehicle is moving.

**Comment by moreba1** [comment]
In real flight motor control airspeed and maintain it constant at trim airspeed with some low oscilations. and ground speed change beacuse of wind.
