### ISSUE TITLE
px4 sitl: etc/init.d-posix/rcS: 6: .: px4-alias.sh: not found

### ISSUE THREAD

**Issue by dgeorge83616** [PX4/PX4-Autopilot#16445]
**Describe the bug**
`PX4_CMAKE_BUILD_TYPE=Debug make px4_sitl gazebo_tailsitter_gdb` results in:
```
me@mine:~/projects/community-px4$ make clean
me@mine:~/projects/community-px4$ PX4_CMAKE_BUILD_TYPE=Debug make px4_sitl gazebo_tailsitter_gdb
-- PX4 version: v1.11.0-rc3-914-g7861377e20
... snip ...
INFO  [px4] Calling startup script: /bin/sh etc/init.d-posix/rcS 0
[Detaching after vfork from child process 452457]
etc/init.d-posix/rcS: 6: .: px4-alias.sh: not found
ERROR [px4] Startup script returned with return value: 512
```
**To Reproduce**
See above

**Expected behavior**
px4 runs without error and has `-O0` optimization for effective stepping.

**Log Files and Screenshots**
*Always* provide a link to the flight log file:
NA

**Drone (please complete the following information):**
px4_sitl

**Comment by dagar** [comment]
Fixed by https://github.com/PX4/PX4-Autopilot/pull/16446.
