### ISSUE TITLE
Issue with MavlinkFTP of pixhawk1

### ISSUE THREAD

**Issue by 1AwesomeDeveloper** [PX4/PX4-Autopilot#16459]
hello all, I am trying using PX4 Pro Stable Release v1.11.2 on PX4 FMU v2, and I am trying to download a file via Mavlink FTP.
But when I try to request a file via Mavlink FTP the board doesnot repond to this operation, and I get a timeout error. Can anyone please tell me that why this is happening, and is Mavlink FTP available for this old version of Pixhawk ?

**Comment by LorenzMeier** [comment]
No, it is not available, since the board is flash constrained. You might be lucky though and your manufacturer might have mis-classified its FMUv3 as a v2 and you can convert it using the bootloader update:
https://docs.px4.io/master/en/config/firmware.html#bootloader

**Comment by 1AwesomeDeveloper** [comment]
![image](https://user-images.githubusercontent.com/43859232/103279481-e3a42c80-49f3-11eb-9ac3-1450dd7ef28f.png)
Tried bootloader update FMUv3 was installed but didn't worked for my FTP Problem...still the board is not responding

**Comment by LorenzMeier** [comment]
Could you share a screenshot of the firmware upgrade?

**Comment by 1AwesomeDeveloper** [comment]
![image](https://user-images.githubusercontent.com/43859232/103279717-71801780-49f4-11eb-96ef-1e62d8b767ff.png)
here it is

**Comment by LorenzMeier** [comment]
Thanks! Let me quickly cross-check!

**Comment by LorenzMeier** [comment]
Which QGroundcontrol version are you using?

**Comment by LorenzMeier** [comment]
I checked and on my setup MAVLink FTP is enabled: 
<img width="497" alt="Screen Shot 2020-12-29 at 12 30 03" src="https://user-images.githubusercontent.com/1208119/103280878-bfcfef00-49d1-11eb-836e-8a0bcba7e56f.png">

**Comment by 1AwesomeDeveloper** [comment]
I updated the firmware from stable version of QGroundControl v4.0.10. 
I forked the main repo to my github (https://github.com/1AwesomeDeveloper/qgroundcontrol/tree/Spacejam_NPNT) and here I am doing changes. Applogies I don't know how to check the version of QGC I am working on

**Comment by 1AwesomeDeveloper** [comment]
when I try to check, from debug build I get this 
![image](https://user-images.githubusercontent.com/43859232/103281161-26680380-49f8-11eb-9dde-c1debc65f73a.png)

**Comment by 1AwesomeDeveloper** [comment]
here is how you can get an idea what I am trying to do.
https://github.com/mavlink/qgroundcontrol/issues/9275

**Comment by LorenzMeier** [comment]
The URL of the file is incorrect - any file on the SD card is on `/fs/microsd/key.txt`, NOT `/key.txt`

**Comment by LorenzMeier** [comment]
Make sure you can see the file in the MAVLink shell - `ls /fs/microsd/key.txt` should list it.

**Comment by 1AwesomeDeveloper** [comment]
I tried to run on Mavlink Console but it shows 
![image](https://user-images.githubusercontent.com/43859232/103281952-4dbfd000-49fa-11eb-803b-682650f9a1c2.png)

**Comment by LorenzMeier** [comment]
Use a QGC daily build please so we're sure you have the latest and something proven (it works for me).

**Comment by 1AwesomeDeveloper** [comment]
I have key.txt in my sd card 
![image](https://user-images.githubusercontent.com/43859232/103282412-b0659b80-49fb-11eb-8087-f72b3e890638.png)
But when I look through mavlink console it doesn't show me 
![image](https://user-images.githubusercontent.com/43859232/103282439-c96e4c80-49fb-11eb-881b-9c6ff55f6138.png)

**Comment by 1AwesomeDeveloper** [comment]
Sir, Now I am using the stable build.

**Comment by 1AwesomeDeveloper** [comment]
Sir by default my SD card has LOGS directory (note the caps), but in the Mavlink Console I have log(in small letters), I guess this is the issue but don't know how to fix it
Any Idea ?

**Comment by LorenzMeier** [comment]
The screenshot from your SD card shows that you don't have the file `key.txt` in the root of the SD card. You put it into a folder and so it can't be found on the path that you're attempting. Please make sure to check the file path and your steps very carefully. The issue tracker for an open source project is not intended for 1:1 debugging support.

I'm more than happy to resolve any real issues.

**Comment by 1AwesomeDeveloper** [comment]
> Make sure you can see the file in the MAVLink shell - `ls /fs/microsd/key.txt` should list it.

Earlier it was not showing but I it showed after mounting the SD card on the PX4 filesystem using mount -t vfat /dev/mmcsd0 /fs/microsd

**Comment by 1AwesomeDeveloper** [comment]
> The screenshot from your SD card shows that you don't have the file `key.txt` in the root of the SD card. You put it into a folder and so it can't be found on the path that you're attempting. Please make sure to check the file path and your steps very carefully. The issue tracker for an open source project is not intended for 1:1 debugging support.
> 
> I'm more than happy to resolve any real issues.

thanks a lot. I will ask on forums for 1:1 debugging support.

**Comment by 1AwesomeDeveloper** [comment]
> o it can't be found on the path that you're attempting

in root path also it didn't worked

**Comment by LorenzMeier** [comment]
I will be using this for mixer configurations myself in the next days and will post my working branch here. You might just need a working example to work from.
