### ISSUE TITLE
CAMERA_IMAGE_CAPTURED reporting capture_result = 0 

### ISSUE THREAD

**Issue by DonLakeFlyer** [PX4/PX4-Autopilot#16467]
* This causes QGC to not display image icons on the map when flying a pattern
* This reproduces using v1.11.2 SITL with the typhoon. If this repros with real vehicles as well then this is a fairly significant loss of functionality.
* Strangely the telemetry from the camera itself has a success for result
![Screen Shot 2020-12-30 at 12 16 20 PM](https://user-images.githubusercontent.com/5876851/103379131-72b75000-4a99-11eb-995e-30b82c5b032c.png)
* But the one from the vehicle itself which QGC uses has it as failed
![Screen Shot 2020-12-30 at 12 16 27 PM](https://user-images.githubusercontent.com/5876851/103379152-82cf2f80-4a99-11eb-9717-40fa00dc5e7b.png)

You should be able to test with any random survey. This is what I was using:
[CameraImageCaptured.plan.zip](https://github.com/PX4/PX4-Autopilot/files/5755590/CameraImageCaptured.plan.zip)

**Comment by LorenzMeier** [comment]
Fix is here: https://github.com/PX4/PX4-Autopilot/pull/16468
