### ISSUE TITLE
px4_fmu-v5 periodic hardfaults in debug or stackcheck builds

### ISSUE THREAD

**Issue by dagar** [PX4/PX4-Autopilot#16511]
http://ci.px4.io:8080/blue/organizations/jenkins/PX4_misc%2FFirmware-hardware/detail/pr-update_src%2Flib%2Fecl/2/pipeline/741

![Screenshot from 2021-01-07 12-02-34](https://user-images.githubusercontent.com/84712/103921238-41193700-50e0-11eb-823e-1eed0d86aa80.png)

Hopefully just stack sizing, but a few casual attempts to silence it have failed (eg bumping CONFIG_USERMAIN_STACKSIZE, etc). Needs to be debugged directly.
This should be relatively easy to reproduce by flashing `px4_fmu-v5_debug` and rebooting.

**Comment by davids5** [comment]
@dagar - Still relevant?

**Comment by dagar** [comment]
I haven't seen this recently.
