### ISSUE TITLE
how to hold height while controling attitude in offboard mode?

### ISSUE THREAD

**Issue by shupx** [PX4/PX4-Autopilot#16532]
I use "mavros" to control px4, and I wonder if there is a way that I can control drone's attitude(roll,pitch) while holding height?
I know there are ROS topics named "mavros/setpoint_attitude" and "mavros/setpoint_raw/local" that allow me to control drone's attitude, but they require "thrust" input as well, which means i need to write a height controller on companion computer by myself.
In "Altitude" mode, I can control drone's roll and pitch angle while holding height, so I guess it may also work in "offboard" mode. But I just don't find the proper ROS topic to do it.
Is anyone who faces the same question with me?
thx!

**Comment by Jaeyoung-Lim** [comment]
> In "Altitude" mode, I can control drone's roll and pitch angle while holding height, so I guess it may also work in "offboard" mode.

This is not true, the control logic is written in the altitude flight mode, which is a different flight mode as offboard mode. Therefore, you need to write your own height controller. If you need reference, https://github.com/Jaeyoung-Lim/mavros_controllers can be useful for you
