### ISSUE TITLE
X2.1-777 doesn´t boot anymore with current master

### ISSUE THREAD

**Issue by taileron** [PX4/PX4-Autopilot#16548]
probably same as #16545

the cause is line 38 in defconfig:
CONFIG_ARMV7M_LAZYFPU=y

removing this line, delete build folder and rebuild then it boots again. 

I only came across this by chance because I thought this flag could have an influence on the instability of UART DMA on F777.

**Comment by matthewoots** [comment]
Hi @taileron, thank you so much, I'll try your fix and get back to you on whether it works for the mRo Control Zero F7.

**Comment by taileron** [comment]
LAZYFPU seems to interact with the not yet functioning MTD (FRAM) driver.
[fault_2042_08_16_17_46_12.log](https://github.com/PX4/PX4-Autopilot/files/5809021/fault_2042_08_16_17_46_12.log)

**Comment by taileron** [comment]
The real cause was a wrong pin definition on the FRAM spi connection: #17794
now Lazy FPU doesn't interact anymore with the FRAM driver as soon as it´s SPI pins are correct defined.
All that boards will boot even with enabled Lazy FPU.
I can do the PRs for all corresponding boards

**Comment by taileron** [comment]
was not such a good idea when I re-enabled the DMA to search for the UART DMA problem, the board no longer boots.
This error probably occurs as soon as an interrupt is not processed correctly somewhere.
-> not such a good function for troubleshooting

**Comment by taileron** [comment]
would close this particular issue (solved)... only the uart dma problem ist left
