### ISSUE TITLE
ninja: error: '/usr/lib/x86_64-linux-gnu/libignition-common1.so.1.0.1', needed by 'libmav_msgs.so', missing and no known rule to make it

### ISSUE THREAD

**Issue by li-fa-bo** [PX4/PX4-Autopilot#16567]
ninja: error: '/usr/lib/x86_64-linux-gnu/libignition-common1.so.1.0.1', needed by 'libmav_msgs.so', missing and no known rule to make it

**Comment by kadhirumasankar** [comment]
I deleted the `PX4-Autopilot` folder and recloned it, reran `ubuntu.sh`, and reran `make px4_sitl gazebo`, and that fixed the issue for me

**Comment by cggos** [comment]
in the `PX4-Autopilot` folder
```sh
make clean
make px4_sitl_default gazebo
```
