### ISSUE TITLE
Can't enable Hardware in the loop  

### ISSUE THREAD

**Issue by AbdallahReda** [PX4/PX4-Autopilot#16584]
**Describe the bug**
I use pixhawk v2.4.8 and upload the px4_fmu-v2_fixedwing firmware using QGroundControl v3.5.6, then connecting to MissionPlanner v1.3.39 as a GCS.
I set the two parameters SYS_HITL and MAV_USEHILGPS to 1 (to use Hardware in the loop mode with Xplane simulator)

I have an issue when setting these parameters to 1, MissionPlanner writes "No GPS" so the hardware in the loop is not activated.
I expect to enter HIL mode but it didn't happen.

Did I miss anything? And I also want how to check if the hardware in the loop mode is enabled or not?

![issue 1](https://user-images.githubusercontent.com/30808065/105020119-94c84080-5a4f-11eb-908b-8f01b69e621f.PNG)

![issue 6](https://user-images.githubusercontent.com/30808065/105020019-719d9100-5a4f-11eb-9018-a82bc285b27f.PNG)

**Comment by eldewany** [comment]
You should use QGC to select the aircraft configuration to be the HIL Quadrotor or whatever is suitable for you. I'm not sure if this is the same in mission planner.

**Comment by AbdallahReda** [comment]
Thanks for your reply, I have entered the HIL mode using QGC. However, I want to enter HIL mode in mission planner using the same firmware.

**Comment by eldewany** [comment]
@AbdallahReda After you set up the board on QGC you start the simulator using the normal method on the docuentation page for HITL, and then start mission planner and connect through udp through port 14570 (the same for QGC as far as i remember) and it should work.

**Comment by julianoes** [comment]
Has this been resolved?

**Comment by julianoes** [comment]
@AbdallahReda you can't mix PX4 and MissionPlanner. You either need to use ArduPilot with MissionPlanner or PX4 with QGC. I'm closing this for now. Please comment if you find out more.
