### ISSUE TITLE
CUAV NORA power+telem issues

### ISSUE THREAD

**Issue by sanderux** [PX4/PX4-Autopilot#16602]
The NORA board does not boot in the following setup:

POWERA power supply
TELEM1 (or 2) RX/TX attached on CUAV P9
(5V/GND to the P9 is supplied by the BEC on the servo rail)
NEOV3 gps attached

disconnecting the RX/TX makes everything work
Waiting for the board to boot and attaching RX/TX then works
powering on POWERC also works

Joining servo-rail GND to telem GND does not solve it

@CUAVcaijie @dagar

**Comment by sanderux** [comment]
Additional information

- Unable to reproduce on the CUAV X7
- It requires both the telem AND the GPS to be attached for this issue to present

**Comment by cuhome** [comment]
@sanderux Please provide your firmware version number

**Comment by sanderux** [comment]
Reproduced on yesterdays master and stable 1.11.3

**Comment by sanderux** [comment]
Problem related to type of BEC used.
Tested with 3 other BEC types and problem goes away.
