### ISSUE TITLE
System log?

### ISSUE THREAD

**Issue by HHHHHCS** [PX4/PX4-Autopilot#16629]
Does PX4 have system log now?If not，may it be?

**Comment by HHHHHCS** [comment]
It could record that such as PX4_INFO,PX4_WARN,printf......

**Comment by LorenzMeier** [comment]
The PX4_INFO and PX4_WARN messages get added to a system log that is stored on the SD card and can be exported as part of the ULOG file. There is also a ```dmesg``` console command to see boot log messages.
