### ISSUE TITLE
EKF2Selector.cpp VZ reset may have a typo

### ISSUE THREAD

**Issue by chungchung21** [PX4/PX4-Autopilot#16621]
Hello

In src/modules/ekf2/EKF2Selector.cpp, L377
I think that "_delta_z_reset = local_position.delta_vz;"  should be  "_delta_vz_reset = local_position.delta_vz;"
Is that right?

Thanks.

**Comment by Jaeyoung-Lim** [comment]
@chungchung21 Would you be able to create a pull request? Thanks!

**Comment by dagar** [comment]
Thanks @chungchung21, nice catch!
