### ISSUE TITLE
[Question] RPi: All Wireless Communication via Ethernet?

### ISSUE THREAD

**Issue by Pskoog3** [PX4/PX4-Autopilot#16628]
Is it possible to put remote control, telemetry and video stream all on the Ethernet of raspberry pi with PX4 build?
I mean instead of connecting individual RC receiver and telemetry module to raspberry pi, all communication is routed via a Wifi modem connected to Ethernet port while the RC input is connected to QGroundControl or some other ground station. Is it already implemented?

**Comment by Phillweston** [comment]
I think it is possible, but you need a companion computer running a specified embedded system, such as APSync or so.
Unfortunately, APSync does not support PX4 firmware at this time, and it is recommended to consider using Ardupilot firmware if you do have such a need.
You can refer to this instruction below:
https://ardupilot.org/dev/docs/apsync-intro.html

**Comment by Phillweston** [comment]
You don't need to compile PX4-related source code on an on-board computer, which only transmits data to flight control through the mavlink protocol.

**Comment by LorenzMeier** [comment]
Here is the documentation on how to set up the communication between the flight controller and the computer for forwarding via Wifi (or any other IP baed link): https://docs.px4.io/master/en/companion_computer/pixhawk_companion.html
