### ISSUE TITLE
Undefined reference to PX4Rangefinder for distance_sensor/lightware_laser_i2c

### ISSUE THREAD

**Issue by lirc572** [PX4/PX4-Autopilot#16715]
**Describe the bug**

Undefined reference to PX4Rangefinder during compilation after adding `distance_sensor/lightware_laser_i2c` driver. `lightware_laser_i2c` seems to be missing a dependency on `drivers_rangefinder`.

**To Reproduce**
1. Add `distance_sensor/lightware_laser_i2c` to `default.cmake`
2. Build

Refer to #13616

**Comment by dagar** [comment]
@lirc572 I'll make the dependency explicit so reduced builds work.

**Comment by dagar** [comment]
Can you try https://github.com/PX4/PX4-Autopilot/pull/16721?
