### ISSUE TITLE
FMUv5 hardware uORB test fails

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/PX4-Autopilot#16730]
http://ci.px4.io:8080/blue/organizations/jenkins/PX4_misc%2FFirmware-hardware/detail/pr-v5x-fix/1/pipeline/1802

Not quite clear yet if this is test infrastructure or a hint at a real issue.

**Comment by jkflying** [comment]
It wasn't reproduced in the next run on master... looks like some flakiness in the timing of uorb subscriptions. @bkueng any ideas?

**Comment by bkueng** [comment]
> @bkueng any ideas?

This check depends on the CPU load of CI, and therefore will be flaky. We increased the threshold in the past, but to really resolve it we need to do it differently, e.g. use CPU runtime or a cycle counter.
