### ISSUE TITLE
Issues with: make px4_sitl jmavsim

### ISSUE THREAD

**Issue by YasinAl** [PX4/PX4-Autopilot#16767]
Hi,
When following the User guide, I keep having issues with the following command: make px4_sitl jmavsim or even DONT_RUN=1 make px4_sitl_default gazebo.
I understand that it says failed to import some stuff like toml or empy. These are installed by the script that was used to install everything. I even double checked and installed them again and the error persists.

Any ideas?

Quick notes:
Ubuntu 18.04
px4 package gets built successfully when building the workspace (catkin build).

The error is as follows:

`yasin@vs ~/catkin_ws/src/PX4-Autopilot $ make clean
yasin@vs ~/catkin_ws/src/PX4-Autopilot $ make px4_sitl jmavsim
-- PX4 version: v1.11.0-rc3-1408-ga399bb9894
-- PX4 config file: /home/yasin/catkin_ws/src/PX4-Autopilot/boards/px4/sitl/default.cmake
-- PX4 config: px4_sitl_default
-- PX4 platform: posix
-- PX4 lockstep: enabled
-- cmake build type: RelWithDebInfo
-- The CXX compiler identification is GNU 7.5.0
-- The C compiler identification is GNU 7.5.0
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Building for code coverage
-- ccache enabled (export CCACHE_DISABLE=1 to disable)
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.6.9", minimum required is "3") 
-- build type is RelWithDebInfo
-- PX4 ECL: Very lightweight Estimation & Control Library v1.9.0-rc1-509-gb919f3d
-- ROMFS: px4fmu_common
-- Configuring done
-- Generating done
-- Build files have been written to: /home/yasin/catkin_ws/src/PX4-Autopilot/build/px4_sitl_default
[0/779] git submodule src/drivers/gps/devices
[7/779] Generating mixer_multirotor_6dof.generated.h
FAILED: src/lib/mixer/MultirotorMixer/mixer_multirotor_6dof.generated.h 
cd /home/yasin/catkin_ws/src/PX4-Autopilot/build/px4_sitl_default/src/lib/mixer/MultirotorMixer && /usr/bin/python3 /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/tools/px_generate_mixers.py --sixdof -f /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/dodeca_bottom_cox.toml /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/dodeca_top_cox.toml /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/hex_cox.toml /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/hex_plus.toml /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/hex_t.toml /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/hex_x.toml /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/octa_cox.toml /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/octa_cox_wide.toml /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/octa_plus.toml /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/octa_x.toml /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/quad_deadcat.toml /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/quad_h.toml /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/quad_plus.toml /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/quad_s250aq.toml /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/quad_vtail.toml /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/quad_wide.toml /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/quad_x_cw.toml /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/quad_x.toml /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/quad_x_pusher.toml /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/quad_y.toml /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/tri_y.toml /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/twin_engine.toml -o mixer_multirotor_6dof.generated.h
Failed to import toml: No module named 'toml'

You may need to install it using:
    pip3 install --user toml

[9/779] Generating mixer_multirotor.generated.h
FAILED: src/lib/mixer/MultirotorMixer/mixer_multirotor.generated.h 
cd /home/yasin/catkin_ws/src/PX4-Autopilot/build/px4_sitl_default/src/lib/mixer/MultirotorMixer && /usr/bin/python3 /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/tools/px_generate_mixers.py -f /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/dodeca_bottom_cox.toml /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/dodeca_top_cox.toml /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/hex_cox.toml /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/hex_plus.toml /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/hex_t.toml /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/hex_x.toml /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/octa_cox.toml /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/octa_cox_wide.toml /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/octa_plus.toml /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/octa_x.toml /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/quad_deadcat.toml /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/quad_h.toml /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/quad_plus.toml /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/quad_s250aq.toml /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/quad_vtail.toml /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/quad_wide.toml /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/quad_x_cw.toml /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/quad_x.toml /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/quad_x_pusher.toml /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/quad_y.toml /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/tri_y.toml /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/twin_engine.toml -o mixer_multirotor.generated.h
Failed to import toml: No module named 'toml'

You may need to install it using:
    pip3 install --user toml

[10/779] Generating mixer_multirotor_normalized.generated.h
FAILED: src/lib/mixer/MultirotorMixer/mixer_multirotor_normalized.generated.h 
cd /home/yasin/catkin_ws/src/PX4-Autopilot/build/px4_sitl_default/src/lib/mixer/MultirotorMixer && /usr/bin/python3 /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/tools/px_generate_mixers.py --normalize -f /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/dodeca_bottom_cox.toml /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/dodeca_top_cox.toml /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/hex_cox.toml /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/hex_plus.toml /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/hex_t.toml /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/hex_x.toml /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/octa_cox.toml /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/octa_cox_wide.toml /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/octa_plus.toml /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/octa_x.toml /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/quad_deadcat.toml /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/quad_h.toml /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/quad_plus.toml /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/quad_s250aq.toml /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/quad_vtail.toml /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/quad_wide.toml /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/quad_x_cw.toml /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/quad_x.toml /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/quad_x_pusher.toml /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/quad_y.toml /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/tri_y.toml /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/twin_engine.toml -o mixer_multirotor_normalized.generated.h
Failed to import toml: No module named 'toml'

You may need to install it using:
    pip3 install --user toml

[12/779] Generating uORB topic headers
FAILED: uORB/topics/uORBTopics.hpp uORB/topics/actuator_armed.h uORB/topics/actuator_controls.h uORB/topics/actuator_outputs.h uORB/topics/adc_report.h uORB/topics/airspeed.h uORB/topics/airspeed_validated.h uORB/topics/battery_status.h uORB/topics/camera_capture.h uORB/topics/camera_trigger.h uORB/topics/cellular_status.h uORB/topics/collision_constraints.h uORB/topics/collision_report.h uORB/topics/commander_state.h uORB/topics/control_allocator_status.h uORB/topics/cpuload.h uORB/topics/debug_array.h uORB/topics/debug_key_value.h uORB/topics/debug_value.h uORB/topics/debug_vect.h uORB/topics/differential_pressure.h uORB/topics/distance_sensor.h uORB/topics/ekf2_timestamps.h uORB/topics/ekf_gps_drift.h uORB/topics/esc_report.h uORB/topics/esc_status.h uORB/topics/estimator_innovations.h uORB/topics/estimator_optical_flow_vel.h uORB/topics/estimator_selector_status.h uORB/topics/estimator_sensor_bias.h uORB/topics/estimator_states.h uORB/topics/estimator_status.h uORB/topics/estimator_status_flags.h uORB/topics/follow_target.h uORB/topics/generator_status.h uORB/topics/geofence_result.h uORB/topics/gps_dump.h uORB/topics/gps_inject_data.h uORB/topics/home_position.h uORB/topics/hover_thrust_estimate.h uORB/topics/input_rc.h uORB/topics/iridiumsbd_status.h uORB/topics/irlock_report.h uORB/topics/landing_gear.h uORB/topics/landing_target_innovations.h uORB/topics/landing_target_pose.h uORB/topics/led_control.h uORB/topics/log_message.h uORB/topics/logger_status.h uORB/topics/mag_worker_data.h uORB/topics/manual_control_setpoint.h uORB/topics/manual_control_switches.h uORB/topics/mavlink_log.h uORB/topics/mission.h uORB/topics/mission_result.h uORB/topics/mount_orientation.h uORB/topics/multirotor_motor_limits.h uORB/topics/navigator_mission_item.h uORB/topics/obstacle_distance.h uORB/topics/offboard_control_mode.h uORB/topics/onboard_computer_status.h uORB/topics/optical_flow.h uORB/topics/orb_test.h uORB/topics/orb_test_large.h uORB/topics/orb_test_medium.h uORB/topics/orbit_status.h uORB/topics/parameter_update.h uORB/topics/ping.h uORB/topics/position_controller_landing_status.h uORB/topics/position_controller_status.h uORB/topics/position_setpoint.h uORB/topics/position_setpoint_triplet.h uORB/topics/power_button_state.h uORB/topics/power_monitor.h uORB/topics/pwm_input.h uORB/topics/px4io_status.h uORB/topics/qshell_req.h uORB/topics/qshell_retval.h uORB/topics/radio_status.h uORB/topics/rate_ctrl_status.h uORB/topics/rc_channels.h uORB/topics/rc_parameter_map.h uORB/topics/rpm.h uORB/topics/rtl_flight_time.h uORB/topics/safety.h uORB/topics/satellite_info.h uORB/topics/sensor_accel.h uORB/topics/sensor_accel_fifo.h uORB/topics/sensor_baro.h uORB/topics/sensor_combined.h uORB/topics/sensor_correction.h uORB/topics/sensor_gps.h uORB/topics/sensor_gyro.h uORB/topics/sensor_gyro_fft.h uORB/topics/sensor_gyro_fifo.h uORB/topics/sensor_mag.h uORB/topics/sensor_preflight_mag.h uORB/topics/sensor_selection.h uORB/topics/sensors_status_imu.h uORB/topics/system_power.h uORB/topics/takeoff_status.h uORB/topics/task_stack_info.h uORB/topics/tecs_status.h uORB/topics/telemetry_status.h uORB/topics/test_motor.h uORB/topics/timesync.h uORB/topics/timesync_status.h uORB/topics/trajectory_bezier.h uORB/topics/trajectory_waypoint.h uORB/topics/transponder_report.h uORB/topics/tune_control.h uORB/topics/uavcan_parameter_request.h uORB/topics/uavcan_parameter_value.h uORB/topics/ulog_stream.h uORB/topics/ulog_stream_ack.h uORB/topics/vehicle_acceleration.h uORB/topics/vehicle_actuator_setpoint.h uORB/topics/vehicle_air_data.h uORB/topics/vehicle_angular_acceleration.h uORB/topics/vehicle_angular_acceleration_setpoint.h uORB/topics/vehicle_angular_velocity.h uORB/topics/vehicle_attitude.h uORB/topics/vehicle_attitude_setpoint.h uORB/topics/vehicle_command.h uORB/topics/vehicle_command_ack.h uORB/topics/vehicle_constraints.h uORB/topics/vehicle_control_mode.h uORB/topics/vehicle_global_position.h uORB/topics/vehicle_gps_position.h uORB/topics/vehicle_imu.h uORB/topics/vehicle_imu_status.h uORB/topics/vehicle_land_detected.h uORB/topics/vehicle_local_position.h uORB/topics/vehicle_local_position_setpoint.h uORB/topics/vehicle_magnetometer.h uORB/topics/vehicle_odometry.h uORB/topics/vehicle_rates_setpoint.h uORB/topics/vehicle_roi.h uORB/topics/vehicle_status.h uORB/topics/vehicle_status_flags.h uORB/topics/vehicle_thrust_setpoint.h uORB/topics/vehicle_torque_setpoint.h uORB/topics/vehicle_trajectory_bezier.h uORB/topics/vehicle_trajectory_waypoint.h uORB/topics/vtol_vehicle_status.h uORB/topics/wheel_encoders.h uORB/topics/wind_estimate.h uORB/topics/yaw_estimator_status.h 
cd /home/yasin/catkin_ws/src/PX4-Autopilot/msg && /usr/bin/python3 tools/px_generate_uorb_topic_files.py --headers -f actuator_armed.msg actuator_controls.msg actuator_outputs.msg adc_report.msg airspeed.msg airspeed_validated.msg battery_status.msg camera_capture.msg camera_trigger.msg cellular_status.msg collision_constraints.msg collision_report.msg commander_state.msg control_allocator_status.msg cpuload.msg debug_array.msg debug_key_value.msg debug_value.msg debug_vect.msg differential_pressure.msg distance_sensor.msg ekf2_timestamps.msg ekf_gps_drift.msg esc_report.msg esc_status.msg estimator_innovations.msg estimator_optical_flow_vel.msg estimator_selector_status.msg estimator_sensor_bias.msg estimator_states.msg estimator_status.msg estimator_status_flags.msg follow_target.msg generator_status.msg geofence_result.msg gps_dump.msg gps_inject_data.msg home_position.msg hover_thrust_estimate.msg input_rc.msg iridiumsbd_status.msg irlock_report.msg landing_gear.msg landing_target_innovations.msg landing_target_pose.msg led_control.msg log_message.msg logger_status.msg mag_worker_data.msg manual_control_setpoint.msg manual_control_switches.msg mavlink_log.msg mission.msg mission_result.msg mount_orientation.msg multirotor_motor_limits.msg navigator_mission_item.msg obstacle_distance.msg offboard_control_mode.msg onboard_computer_status.msg optical_flow.msg orb_test.msg orb_test_large.msg orb_test_medium.msg orbit_status.msg parameter_update.msg ping.msg position_controller_landing_status.msg position_controller_status.msg position_setpoint.msg position_setpoint_triplet.msg power_button_state.msg power_monitor.msg pwm_input.msg px4io_status.msg qshell_req.msg qshell_retval.msg radio_status.msg rate_ctrl_status.msg rc_channels.msg rc_parameter_map.msg rpm.msg rtl_flight_time.msg safety.msg satellite_info.msg sensor_accel.msg sensor_accel_fifo.msg sensor_baro.msg sensor_combined.msg sensor_correction.msg sensor_gps.msg sensor_gyro.msg sensor_gyro_fft.msg sensor_gyro_fifo.msg sensor_mag.msg sensor_preflight_mag.msg sensor_selection.msg sensors_status_imu.msg system_power.msg takeoff_status.msg task_stack_info.msg tecs_status.msg telemetry_status.msg test_motor.msg timesync.msg timesync_status.msg trajectory_bezier.msg trajectory_waypoint.msg transponder_report.msg tune_control.msg uavcan_parameter_request.msg uavcan_parameter_value.msg ulog_stream.msg ulog_stream_ack.msg vehicle_acceleration.msg vehicle_actuator_setpoint.msg vehicle_air_data.msg vehicle_angular_acceleration.msg vehicle_angular_acceleration_setpoint.msg vehicle_angular_velocity.msg vehicle_attitude.msg vehicle_attitude_setpoint.msg vehicle_command.msg vehicle_command_ack.msg vehicle_constraints.msg vehicle_control_mode.msg vehicle_global_position.msg vehicle_gps_position.msg vehicle_imu.msg vehicle_imu_status.msg vehicle_land_detected.msg vehicle_local_position.msg vehicle_local_position_setpoint.msg vehicle_magnetometer.msg vehicle_odometry.msg vehicle_rates_setpoint.msg vehicle_roi.msg vehicle_status.msg vehicle_status_flags.msg vehicle_thrust_setpoint.msg vehicle_torque_setpoint.msg vehicle_trajectory_bezier.msg vehicle_trajectory_waypoint.msg vtol_vehicle_status.msg wheel_encoders.msg wind_estimate.msg yaw_estimator_status.msg -i /home/yasin/catkin_ws/src/PX4-Autopilot/msg -o /home/yasin/catkin_ws/src/PX4-Autopilot/build/px4_sitl_default/uORB/topics -e templates/uorb -t /home/yasin/catkin_ws/src/PX4-Autopilot/build/px4_sitl_default/msg/tmp/headers -q
Failed to import em: No module named 'em'

You may need to install it using:
    pip3 install --user empy

[13/779] Generating serial_params.c
FAILED: generated_params/serial_params.c 
cd /home/yasin/catkin_ws/src/PX4-Autopilot/build/px4_sitl_default/src/lib/parameters && /usr/bin/cmake -E make_directory /home/yasin/catkin_ws/src/PX4-Autopilot/build/px4_sitl_default/generated_params && /usr/bin/python3 /home/yasin/catkin_ws/src/PX4-Autopilot/Tools/serial/generate_config.py --params-file /home/yasin/catkin_ws/src/PX4-Autopilot/build/px4_sitl_default/generated_params/serial_params.c --serial-ports --config-files /home/yasin/catkin_ws/src/PX4-Autopilot/src/lib/battery/module.yaml /home/yasin/catkin_ws/src/PX4-Autopilot/src/drivers/gps/module.yaml /home/yasin/catkin_ws/src/PX4-Autopilot/src/modules/mavlink/module.yaml
Failed to import jinja2: No module named 'jinja2'

You may need to install it using:
    pip3 install --user jinja2

[15/779] Generating git version header
ninja: build stopped: subcommand failed.
Makefile:224: recipe for target 'px4_sitl' failed
make: *** [px4_sitl] Error 1
`

**Comment by Jaeyoung-Lim** [comment]
@YasinAl As you can see in the logs, you are missing a few python packages.

Please install them as instructed in the toolchain installation: http://docs.px4.io/master/en/dev_setup/dev_env_linux_ubuntu.html#development-environment-on-ubuntu-lts-debian-linux

**Comment by YasinAl** [comment]
> @YasinAl As you can see in the logs, you are missing a few python packages.
> 
> Please install them as instructed in the toolchain installation: http://docs.px4.io/master/en/dev_setup/dev_env_linux_ubuntu.html#development-environment-on-ubuntu-lts-debian-linux

@Jaeyoung-Lim They have been installed like I said in the original issue "I understand that it says failed to import some stuff like toml or empy. These are installed by the script that was used to install everything. I even double checked and installed them again and the error persists."

Any idea what the issue could be except for installing them? I have reinstalled pip and reinstalled the packages to see if it was the issue but that did not fix anything.

**Comment by antonio-sc66** [comment]
@YasinAl Since you're using Ubuntu 18.04 are you sure you installed the packages in Python3? Can you test if you can import them in a Python3 interpreter?

**Comment by Jaeyoung-Lim** [comment]
@YasinAl If your installations don't fix the issue, it means you have an issue with your python path and the issue is not related to this repository.

I see that you have put px4 inside your catkin workspace. Is there any chance that you have sourced the catkin workspace? If you are on ROS melodic, it will try to use python2 and break all the python paths that px4 is using.

On a side note, it is not a good practice to put px4 inside your workspace, since px4 doesn't follow the catkin directory structure

**Comment by YasinAl** [comment]
> @YasinAl Since you're using Ubuntu 18.04 are you sure you installed the packages in Python3? Can you test if you can import them in a Python3 interpreter?

Actually spot on. For some reason they are not imported even though my other Python3 libraries are working. I had to reinstall them all manually (this is like the fourth time) and then they were successfully imported into a Python3 interpreter and only then did the make command work. Really weird.

**Comment by YasinAl** [comment]
> @YasinAl If your installations don't fix the issue, it means you have an issue with your python path and the issue is not related to this repository.
> 
> I see that you have put px4 inside your catkin workspace. Is there any chance that you have sourced the catkin workspace? If you are on ROS melodic, it will try to use python2 and break all the python paths that px4 is using.
> 
> On a side note, it is not a good practice to put px4 inside your workspace, since px4 doesn't follow the catkin directory structure

Maybe that was that was the issue but after reinstalling the packages and importing them somewhere else, I could run the command successfully.

Ah thanks for the side note. I will move it now!
