### ISSUE TITLE
RPi3: LSM9DS1 Accel/Gyro and Mag Calibration Failed!

### ISSUE THREAD

**Issue by Pskoog3** [PX4/PX4-Autopilot#16772]
Unable to calibrate accelerometer, gyro and magnetometer for LSM9DS1 connected to Raspberry Pi 3 SPI interface. The horizon level calibration also fails.

The log is available at the following link... was unable to upload to logs.px4.io
https://drive.google.com/file/d/1UAWU1LU9kpD4hHc-K8WDeF2FWpS83VWN/view?usp=sharing
Either the sensor itself is faulty or the driver needs to be updated!

**Comment by dagar** [comment]
Can you show the actual error messages? I don't see any in the log.

The z axis of the accel has a large offset, so the estimator probably isn't going to initialize until after the accel has a good calibration. The level horizon calibration depends on the attitude (vehicle_attitude publication), so it's not going to work until the estimator has initialized. 

![Screenshot from 2021-02-06 12-24-58](https://user-images.githubusercontent.com/84712/107125199-6384a880-6876-11eb-8d1a-d3cd4c51cf49.png)

**Comment by dagar** [comment]
Your log file also shows what appears to be valid calibration data. Why do you think it failed? Can you share a screenshot of the errors?

```
CAL_ACC0_ID | 4456450
CAL_ACC0_PRIO | 50
CAL_ACC0_ROT | -1
CAL_ACC0_XOFF | 0.05530215
CAL_ACC0_XSCALE | 1.0017482
CAL_ACC0_YOFF | 0.16195849
CAL_ACC0_YSCALE | 1.0015078
CAL_ACC0_ZOFF | -1.2258157
CAL_ACC0_ZSCALE | 1.0112919
```

**Comment by Pskoog3** [comment]
Daniel, here is the latest log that might show the problem...
https://drive.google.com/file/d/1zMf2fN2T35MSr7TIE3HU_hAw-lOjRNlB/view?usp=sharing
