### ISSUE TITLE
CUAV Nora mag calibration crash

### ISSUE THREAD

**Issue by coderkalyan** [PX4/PX4-Autopilot#16813]
**Describe the bug**
On master, I am unable to calibrate the mag on CUAV Nora. Either during the calibration, or after it is done but before the values are saved, the autopilot reboots itself and I lose the calibration.

**To Reproduce**
1. CUAV Nora on master
2. Calibrate mag with QGC

**Expected behavior**
The magnetometer should be calibrated correctly.

**Log Files and Screenshots**
No flight log since I wasn't flying :smile: Unfortunately I am not sure how to get more debug information. I tried taking a look at the debug UART shell output but didn't get anything useful. I can try using a debugger or bisecting to find the commit culprit.

Add screenshots to help explain your problem.

**Drone (please complete the following information):**
- Just a CUAV Nora connected over USB to QGC. Have observed the same thing over telemetry radio as well.

**Additional context**
Please let me know what I can do to help you reproduce this.

**Comment by LorenzMeier** [comment]
When you say master, which specific commit was that? There was a recent fix for mag cal on master.

**Comment by coderkalyan** [comment]
@LorenzMeier d03d46b8a302152dafabfed9a8073aae13abbcee

**Comment by coderkalyan** [comment]
Oh, I see that ef444da68994ca33f338b2d60a49147eb4afaf25 was commited afterwards. Let me try this now.

**Comment by coderkalyan** [comment]
@LorenzMeier Still able to reproduce this on master ef444da68994ca33f338b2d60a49147eb4afaf25.

**Comment by MaEtUgR** [comment]
From dev call: Could you please run the calibration with full-rate logging running at the same time and share the log.
