### ISSUE TITLE
Unable to start adis16448

### ISSUE THREAD

**Issue by Jaeyoung-Lim** [PX4/PX4-Autopilot#16839]
**Describe the bug**
The `aid16448` IMU driver is unable to start on a pixhawk4

**To Reproduce**
1. `Tools/mavlink_shell.py`
2. Start the driver

```
nsh> adis16448 -S start
WARN  [SPI_I2C] adis16448: no instance started (no device on bus?)
```

**Expected behavior**
IMU driver is started successfully.

**Log Files and Screenshots**
Starting the driver manually fails. 
- I also tried starting the driver in `rc.board_sensors` and disabled all the other sensors but had resulted in the same.
- I have tried different SPI modes / chip selects. The Blue LED lights up on the interface board, which I suspect that it is trying to start the driver

```
nsh> adis16448 -S start
WARN  [SPI_I2C] adis16448: no instance started (no device on bus?)
```

- Digging into the code where exactly it fails is when comparing the checksum in https://github.com/PX4/PX4-Autopilot/blob/a002a07ed52897dfd1082100b0af24f9b247916e/src/drivers/imu/adis16448/ADIS16448.cpp#L470-L476

**Drone (please complete the following information):**
- Pixhawk4 with a ADIS16448AMLZ IMU

![PXL_20210212_102341840](https://user-images.githubusercontent.com/5248102/107756945-37a96d00-6d25-11eb-92af-c0436808d4e6.jpg)

**Additional context**
- @tstastny @acfloria FYI

**Comment by Jaeyoung-Lim** [comment]
Update: I tried on one of the old PX4 releases that were used in the lab (something close to 1.9.0-beta), and seems to work without any problems, so not a hardware issue

**Comment by Jaeyoung-Lim** [comment]
Disabling the CRC check seems to bypass the issue. Looking into what could have gone wrong with the CRC checks

**Comment by saengphet** [comment]
Hi @Jaeyoung-Lim , I now use the adis16470 with firmware 1.9.XX (not sure) and it works well. I plan to upgrade firmware to the current stable version. Do you think the same problem will occur or not with adis16470?

**Comment by Jaeyoung-Lim** [comment]
@saengphet I don't think the two IMUs are related, so hard to tell. Moreover, this issue has been fixed by https://github.com/PX4/PX4-Autopilot/pull/16855

**Comment by LorenzMeier** [comment]
Fixed.
