### ISSUE TITLE
Hardware Security of PX4

### ISSUE THREAD

**Issue by korkeep** [PX4/PX4-Autopilot#16850]
Hi 😀  

I am working on my project of ensuring the **hardware security** of the Flight Controller.  
I am planning to use Infinion make **[Trusted Platform Modules (TPM)](https://www.infineon.com/cms/en/product/security-smart-card-solutions/optiga-embedded-security-solutions/optiga-tpm/)** to ensure hardware integrity of Pixhawk Cube.  

TPM modules are used in an IOT environment for hardware security, they are used as **Root of Trust**.  

It is necessary to change the PX4 firmware through this project.  
Considering SPI/I2C interface of TPM module, how can I start building this system?  

Although, I can implement the TPM + Raspberry Pi system,  
I have no idea how to begin with interfacing a TPM module to Pixhawk 😭  

Is there any other way by which I can ensure hardware integrity of the Pixhawk Cube?  
How do I make sure nobody messes up with my Pixhawk Cube when my drone gets into the wrong hands? 🤔

Thank you for your hard work 🙏

**Comment by mrpollo** [comment]
@korkeep I might be misunderstanding what you are trying to achieve here, but it looks like you are trying to work with the Cube pilots, you need to talk to the manufacturer of the Cube to get support, please try their forums https://discuss.cubepilot.org

**Comment by LorenzMeier** [comment]
The FMUv5X and FMUv6X autopilot standards have a secure element by NXP - happy to look into that if you are interested. You can reach me on lorenz@px4.io

**Comment by korkeep** [comment]
@mrpollo @LorenzMeier  

Thank you for checking :)
As this is my first opensource project, I will do my best👍

**Comment by LorenzMeier** [comment]
@korkeep Could you drop me an email on lorenz@px4.io? I'd like to send you further material.

**Comment by mrpollo** [comment]
Thanks for reaching out @korkeep you are welcome on this community, let's follow up via email, let's figure out if we can help you.

**Comment by korkeep** [comment]
@LorenzMeier @mrpollo
I really appreciate for your guidance.

If I can contribute for this fascinating project,
It will be a great honor for me. 

Are there any things I need to prepare to participate on this project?

Here is my small resume :)
+ PX4-MalSW: https://github.com/korkeep/PX4-MalSW
+ Github: https://github.com/korkeep 

Please take care of your health. 
Thank you sincerely 😀

**Comment by Aman738** [comment]
Hello,
I am also working on similar project where hardware security of the Flight Controller is needed.
It will be a great help if someone guide me with it.

Thank you.
