### ISSUE TITLE
sorry, unimplemented: non-trivial designated initializers not supported

### ISSUE THREAD

**Issue by gitfishup** [PX4/PX4-Autopilot#16899]
**Describe the bug**
After git pull newest source code , I use "make cuav_can-gps-v1" to compile and there was an error in UavcanNode.cpp .
![image](https://user-images.githubusercontent.com/69180601/108583030-f0009200-7371-11eb-83f3-67a3cae71bd3.png)

![image](https://user-images.githubusercontent.com/69180601/108583106-5f768180-7372-11eb-9f24-bbc2b24a2bc3.png)

![image](https://user-images.githubusercontent.com/69180601/108583254-2ab6fa00-7373-11eb-86a6-2a3f6ff125aa.png)

**Comment by AlexKlimaj** [comment]
See https://github.com/PX4/PX4-Autopilot/pull/16900

**Comment by gitfishup** [comment]
> See #16900

Thanks a lot!

**Comment by davids5** [comment]
Thanks Alex!
