### ISSUE TITLE
Unstable flight - Shaking from side to side

### ISSUE THREAD

**Issue by gizmond1982** [PX4/PX4-Autopilot#16930]
Hi all,

I have just completed my first S500 drone build. I am using 40A ESC, T-motor 2216, Pixhawk 2.4.8, m8n gps, and 5200mah / 60C lipo.

My drone can takeoff and land but during the flight the drone is very jumpy and unstable shaking from side to side (left, right, front, back) even almost no winds.

I was wondering what could be the reason...

Here are the logs - 
https://logs.px4.io/plot_app?log=8dfa4940-16f4-4934-b91b-281926d05ce9

**Comment by notoriou5** [comment]
@gizmond1982 
On the first look it seems like a PID tuning issue. Especially the roll attitude can not be followed at all:
![image](https://user-images.githubusercontent.com/17237189/109415125-244e0100-79b7-11eb-874d-7d42d35394b6.png)
Ideally, the red line should exactly follow the green like. I guess the MC_PITCH_P param is set to high. Did you do a PID tuning or did you just fly with some preset parameters. If you are new to the hobby, maybe read up on how to PID tune (e.g. on the [PX4 docs homepage](https://docs.px4.io/master/en/config_mc/pid_tuning_guide_multicopter.html)).

Hope this helps a bit :)

**Comment by gizmond1982** [comment]
Thank you @notoriou5 .
I was able to improve it with in-flight PID tuning. Not perfect but flyable.
https://review.px4.io/plot_app?log=8bc698c9-a17c-4952-b3cc-64195cbbf725

**Comment by bresch** [comment]
That's already much better @gizmond1982 !
![bokeh_plot(19)](https://user-images.githubusercontent.com/14822839/109976354-f68cf300-7cfb-11eb-804b-a41bda8517cd.png)

As this isn't a problem with the firmware I'll close this issue, but feel free to ask for more help on the forum (http://discuss.px4.io) and/or slack if needed.
