### ISSUE TITLE
Potential division-by-zero in FixedwingAttitudeControl.cpp

### ISSUE THREAD

**Issue by wuruoyu** [PX4/PX4-Autopilot#16979]
**Describe the bug**
There is a potential division-by-zero exception in the following code

https://github.com/PX4/PX4-Autopilot/blob/c2151cb4fafc8fdbbf136d6da4989185b0763217/src/modules/fw_att_control/FixedwingAttitudeControl.cpp#L244-L270

From the [Parameter Reference](http://docs.px4.io/master/en/advanced_config/parameter_reference.html), `FW_AIRSPD_MIN` can be zero. So if `airspeed_valid` is false, `airspeed` can be zero before and after the `constrain` at line 268. Therefore, a divide-bg-zero exception can happen at line 270. 

**Expected behavior**
A guarding check before the division would be preferred here, or the range of related parameters should be further constrained.

**Comment by RomanBapst** [comment]
@wuruoyu Yes, I think think your observation is correct. We should make sure to constrain the final airspeed.
