### ISSUE TITLE
Unable to compile forked version

### ISSUE THREAD

**Issue by ibrahimqazi** [PX4/PX4-Autopilot#17076]
Hello all,
I am unable to the compile the forked version of PX4. I have followed these steps:
`git clone https://github.com/<your git name>/PX4-Autopilot.git`
```
cd PX4-Autopilot
git submodule update --init --recursive
git remote add upstream https://github.com/PX4/PX4-Autopilot.git
```
But when I compile for PixHawk 1 board using `make px4_fmu-v2_default`
I get the following error:
`-- PX4 version: v1.11.0-rc3-1759-g9d0c966b15
-- PX4 config file: /home/ibrrahim/PX4-Autopilot/boards/px4/fmu-v2/default.cmake
-- PX4 config: px4_fmu-v2_default
-- PX4 platform: nuttx
make[2]: *** No rule to make target 'dirlinks'.  Stop.
make[1]: *** [dirlinks] Error 2
-- cmake build type: MinSizeRel
-- The CXX compiler identification is GNU 7.2.1
-- The C compiler identification is GNU 7.2.1
-- The ASM compiler identification is GNU
-- Found assembler: /home/ibrrahim/gcc-arm-none-eabi-7-2017-q4-major/bin/arm-none-eabi-gcc
-- Check for working CXX compiler: /home/ibrrahim/gcc-arm-none-eabi-7-2017-q4-major/bin/arm-none-eabi-g++
-- Check for working CXX compiler: /home/ibrrahim/gcc-arm-none-eabi-7-2017-q4-major/bin/arm-none-eabi-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /home/ibrrahim/gcc-arm-none-eabi-7-2017-q4-major/bin/arm-none-eabi-gcc
-- Check for working C compiler: /home/ibrrahim/gcc-arm-none-eabi-7-2017-q4-major/bin/arm-none-eabi-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- ccache enabled (export CCACHE_DISABLE=1 to disable)
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.6.9", minimum required is "3") 
CMake Error at platforms/nuttx/cmake/px4_impl_os.cmake:128 (message):
  Could not determine chip architecture from NuttX config.  You may have to
  add it.
Call Stack (most recent call first):
  CMakeLists.txt:304 (px4_os_determine_build_chip)

-- Configuring incomplete, errors occurred!
See also "/home/ibrrahim/PX4-Autopilot/build/px4_fmu-v2_default/CMakeFiles/CMakeOutput.log".
See also "/home/ibrrahim/PX4-Autopilot/build/px4_fmu-v2_default/CMakeFiles/CMakeError.log".
Error: /home/ibrrahim/PX4-Autopilot/build/px4_fmu-v2_default is not a directory
Makefile:217: recipe for target 'px4_fmu-v2_default' failed
make: *** [px4_fmu-v2_default] Error 1`

I run the bash file mentioned in issue 14962 [https://github.com/PX4/PX4-Autopilot/issues/14962](url) but still the same problem. If someone can help me you that would be great.

**Comment by Jaeyoung-Lim** [comment]
@ibrahimqazi 

```
make submodulesupdate
```

**Comment by ibrahimqazi** [comment]
@Jaeyoung-Lim why we need to use this command ?

**Comment by Jaeyoung-Lim** [comment]
@ibrahimqazi Because this repo has submodules and you didn't update them when cloning

**Comment by ibrahimqazi** [comment]
@Jaeyoung-Lim Thanks I followed exactly the same commands mentioned on this website, and didn't miss any step:
[https://docs.px4.io/master/en/contribute/git_examples.html](url)
The command you mentioned was not there. I have a little confusion so my cloned forked repository will need `make submodulesupdate` to compile it because the command `make px4_fmu-v2_default` still does not work. Appreciate your support.
