### ISSUE TITLE
FMUK66 revE log files format issue

### ISSUE THREAD

**Issue by dk7xe** [PX4/PX4-Autopilot#17087]
**Describe the bug**
log files of FMUK66 revE seems to have an format issue and can not be loaded on to logs.px4.io for analysis.

**To Reproduce**
1. Enable logging on FMUK66 revE (nxp_fmuk66-e_default target)
2. Power drone, fly, .. land, power off.
3. Download log file via USB
4. Try to upload log file to https://logs.px4.io

**Expected behavior**
Log files accepted by https://logs.px4.io

**Log Files and Screenshots**
Log file examples
[ID10_TestDrone3.zip](https://github.com/PX4/PX4-Autopilot/files/6120873/ID10_TestDrone3.zip)

Screenshot
![grafik](https://user-images.githubusercontent.com/3907200/110745906-49a30080-823c-11eb-8979-00b9c0b6250e.png)

**Comment by dk7xe** [comment]
@davids5 may you please look into that

**Comment by davids5** [comment]
I can not get to it at the moment, A quick fix may be enabling CONFIG_MMCSD_MULTIBLOCK_DISABLE
