### ISSUE TITLE
Px4 log unknown date in QGC

### ISSUE THREAD

**Issue by aet2230** [PX4/PX4-Autopilot#17097]
Recently I started to use Cube Orange and I get logs with unknown date in QGC.
When I look at SD card, logs do have correct date (foldername) and time (filename).
Usually such issue happens when I erase logs and perform flights til firs connection with QGC.
Once QGC is connected once, further logs are displayed.
Attached is the screenshot that describes the issue: I entered nsh an you may see that in logdata.txt, the logname is ok, but its timestamp represents Saturday, January 1, 2000

![Screenshot from 2021-03-11 15-03-17](https://user-images.githubusercontent.com/43025389/110829274-991b1800-82a0-11eb-8f04-28c237db796e.png)

**Comment by julianoes** [comment]
I tried to reproduce this but failed. For me it seems correct. Do you have any more hints what to try? Does it still happen?

**Comment by aet2230** [comment]
Too old, may be closed

**Comment by vacoff** [comment]
I have come across the same issue today, new cube orange had the exact same issue. it's the second flight of the platform
