### ISSUE TITLE
Jitter in mode of Altitude at MC(VTOL) 

### ISSUE THREAD

**Issue by Kim-zhi-jiang** [PX4/PX4-Autopilot#17119]
Hello there

I have a problem in version 1.11.3, I will test again in version 1.12 tomorrow.
MC(VTOL) in the mode of Altitude, only the forward direction jitters, and strangely it is no problem to fly backwards to the left and to the right.

![2021-03-15 12-23-04 的屏幕截图](https://user-images.githubusercontent.com/80669694/111114459-3c6c7580-859e-11eb-8cc8-a74b22910233.png)

**Comment by jinger26** [comment]
@sfuhrer @RomanBapst are you able to take a look here?

**Comment by Jaeyoung-Lim** [comment]
@Kim-zhi-jiang Can you share the full log?

**Comment by Kim-zhi-jiang** [comment]
> @Kim-zhi-jiang Can you share the full log?

https://review.px4.io/plot_app?log=3d4a955f-41ed-4f71-93b9-1aa45727bcab

Just uploaded.

**Comment by Kim-zhi-jiang** [comment]
I tried to find the source of the problem, but unfortunately.
Forward  direction have airspeed...

**Comment by sfuhrer** [comment]
Looks to me like it struggles a lot when flying (hovering) with high roll/pitch angles.
@Kim-zhi-jiang can you share a flight done in Stabilized and Position mode? That would help finding out if the issue is indeed coming from the altitude controller, and/or if related to high attitude angles.

**Comment by Kim-zhi-jiang** [comment]
@sfuhrer 

MC_ROLLRATE_MAX 120-150
MC_PITCHRATE_MAX 120-150

Forward,Backward,Left,Right it's OK in Stabilized and Position mode
Jitters only forward in Altitude mode

I think the plane will crashed with this problem in windy weather.

Stabilized Position and Altitude log:
https://review.px4.io/plot_app?log=3cacd01b-213f-4092-9f12-8330b416296f

**Comment by Kim-zhi-jiang** [comment]
@all
The controller was wrong if Position change to Stabilized mode.
Also move the plane  in Stabilized mode.

crying

**Comment by Kim-zhi-jiang** [comment]
> Looks to me like it struggles a lot when flying (hovering) with high roll/pitch angles.
> @Kim-zhi-jiang can you share a flight done in Stabilized and Position mode? That would help finding out if the issue is indeed coming from the altitude controller, and/or if related to high attitude angles.
> Does the vehicle have a large wing area?

If forward direction speed more than 11m/s then also jitters in Position mode.
