### ISSUE TITLE
CUAV nano compile and upload v1.12.0-beta1 program error

### ISSUE THREAD

**Issue by mengchaoheng** [PX4/PX4-Autopilot#17188]
**Describe the bug**
The initial bell（STARTUP_TUNE） is incomplete, the output of the servo is wrong after startup, and the safety switch does not work.

**To Reproduce**
1. make px4_fmu-v5_default
2. make px4_fmu-v5_default upload
3. See error

**Expected behavior**
The tune_control play -t $STARTUP_TUNE command will work. After starting, press the safety switch and the servo output will appear.

**Log Files and Screenshots**
![Ubuntu-2021-03-22-11-47-36](https://user-images.githubusercontent.com/43166007/111938349-b3f15600-8b04-11eb-9691-7a574b2f7c1e.png)
![Ubuntu-2021-03-22-11-50-08](https://user-images.githubusercontent.com/43166007/111938387-cc617080-8b04-11eb-964e-976d04ffa57f.png)

**Additional context**
But when I download the beta firmware in QGC, it can run normally. I don’t know why the firmware compiled locally has problems.

**Comment by mengchaoheng** [comment]
https://user-images.githubusercontent.com/43166007/111938902-f23b4500-8b05-11eb-9367-f6a2cfaec961.mp4

----------------------------------------------------------
This is the wrong initial ringtone

**Comment by mengchaoheng** [comment]
@LorenzMeier

**Comment by mengchaoheng** [comment]
https://github.com/PX4/PX4-Autopilot/issues/16883, see also

**Comment by mengchaoheng** [comment]
Additional context
But when I download the beta firmware in QGC, The safety switch is also wrong. It is open sourced but cannot be closed.

**Comment by LorenzMeier** [comment]
Safety now defaults to off - just added that to the release notes: https://github.com/PX4/PX4-Autopilot/releases/tag/v1.12.0-beta1

**Comment by mrpollo** [comment]
@mengchaoheng did @LorenzMeier comment help you? are you still experiencing this issue?

**Comment by mengchaoheng** [comment]
yes, it work now.


| |
蒙超恒
|
|
***@***.***
|

签名由 网易邮箱大师 定制

On 04/29/2021 00:13, Ramon Roche wrote:

@mengchaoheng did @LorenzMeier comment help you? are you still experiencing this issue?

**Comment by mrpollo** [comment]
Thanks @mengchaoheng 👍
