### ISSUE TITLE
Hardfault on pixracer r15 with current master

### ISSUE THREAD

**Issue by helo9** [PX4/PX4-Autopilot#17207]
**Describe the bug**
With the current master (something like 1d8808183, not completely sure which version QGC took), I get hardfaults on my pixracer R15. `git bisect` seems to identify e7722b11eb as first commit with that issue.

**To Reproduce**
1. Pixracer R15 connected via USB
2. Update Firmware with QGC to development/master
4. Observe pixracer constantly rebooting

**Expected behavior**
.. should not cause hardfault

**Log Files and Screenshots**
[fault_2000_01_01_00_00_04.log](https://github.com/PX4/PX4-Autopilot/files/6188910/fault_2000_01_01_00_00_04.log)

**Drone (please complete the following information):**
- pixracer r15, px4_fmu-v4

~**Additional context**~

**Comment by dagar** [comment]
Thanks for sharing the bisect, this should now be fixed in master. https://github.com/PX4/PX4-Autopilot/pull/17202
