### ISSUE TITLE
Flashing nxp_fmuk66-v_rtps or nxp_fmuk66-v_default causes continuous self-rebooting

### ISSUE THREAD

**Issue by KatrinMoritz** [PX4/PX4-Autopilot#17212]
**Describe the bug**
Flashing the nxp_fmuk66-v3_rtps.px4 or nxp_fmuk66-v3_default.px4 via QGC causes that the FMU is always rebooting and not starting correctly. It reboots before the communication with QGC is started. Therefore the FMU is with this version not usable. This behavior can be observed from the commit e7722b11eb. In the commit before (c1c0a62be5) the firmware works as expected.

**To Reproduce**
1. Build the firmware on the status of commit e7722b11eb
2. Uploaded firmware (.px4) via QGC
3. See error: directly rebooting after every reboot

**Expected behavior**
Blue light is blinking slow. FMU connects to QGC after flashing.

**Log Files and Screenshots**
I want to upload a video but the file is too big.

**Drone (please complete the following information):**
- Rover Setup with NXP Cup Rover
- RDDRONE-FMUK66

**Comment by KatrinMoritz** [comment]
@96moustafa @dk7xe

**Comment by dk7xe** [comment]
@dagar @davids5 fyi

**Comment by davids5** [comment]
@dk7xe can you get a console on the debug connector? Is it a hardfault in the PWM module?

**Comment by dagar** [comment]
This should be fixed in master as of https://github.com/PX4/PX4-Autopilot/commit/9b1cf98474b271ef402dd3d7dd47acd581acc1d7.

**Comment by KatrinMoritz** [comment]
I tested the new master with both versions (default and rtps). The rebooting issue is fixed with 9b1cf98, @dagar.
