### ISSUE TITLE
Some old params in v1.12.beat1 and A short time pause at before transfer(MC to WING) in VTOL plane

### ISSUE THREAD

**Issue by Kim-zhi-jiang** [PX4/PX4-Autopilot#17216]
Hello there

I can't find some old params in v1.12.beat1 and A short time pause at before transfer(MC to WING) in VTOL plane.

https://github.com/PX4/PX4-Autopilot/tree/v1.12.0-beta1/src/modules/sensors/

PWM_MIN ---I don't know
PX4-Autopilot/src/modules/sensors/pwm_params_main.c Not file

PWM_MAX ---I don't know
PX4-Autopilot/src/modules/sensors/pwm_params_main.c Not file

PWM_DISARMED ---I don't know
PX4-Autopilot/src/modules/sensors/pwm_params_main.c Not file

PWM_AUX_DISARMED ---I don't know
/PX4-Autopilot/src/modules/sensors/pwm_params_aux.c Not file

PWM_RATE ---OK Default 400 
PX4-Autopilot/src/modules/sensors/pwm_params_main.c Not file

FW_RSP_OFF ---OK Deletied
PX4-Autopilot/src/modules/fw_att_control/fw_att_control_params.c

MPC_JERK_MIN ---OK Deletied
/PX4-Autopilot/src/modules/mc_pos_control/mc_pos_control_params.c

![2021-03-24 08-48-37 的屏幕截图](https://user-images.githubusercontent.com/80669694/112238761-394d4580-8c80-11eb-9d0f-538f38fce5b0.png)

**Comment by jinger26** [comment]
@sfuhrer @RomanBapst  can you take a look at the transition issue here?

**Comment by jinger26** [comment]
@dagar reminder to respond with regards to parameters translation per dev-call, thank you!
