### ISSUE TITLE
Cuavx7 top 8 PWM channels have no output

### ISSUE THREAD

**Issue by CUAVcaijie** [PX4/PX4-Autopilot#17237]
**Describe the bug**
CUAVx7 MAIN channel has no output 

**To Reproduce**
1.Firmware version: a12442654138c88c796f9a655907f78fc258d04d
2. Set the model to 4001 
![image](https://user-images.githubusercontent.com/30532769/112571858-deecea00-8e23-11eb-9ccc-15fb7dbaa477.png)

3. Calibrate all sensors 
4. Setting parameters: 
5. Restart 
6. Connect to the remote control

Test Results:
CAUVx7:
    PWM output before unlocking: 
![image](https://user-images.githubusercontent.com/30532769/112572219-aef21680-8e24-11eb-8d08-14e0f426dfbc.png)

    Unlock PWM output:
![image](https://user-images.githubusercontent.com/30532769/112572227-b2859d80-8e24-11eb-9764-62ff274e79dc.png)

Analysis: No output from MAIN interface, normal output from AUX interface 

Use CUAVv5 for comparison: 
    PWM output before unlocking: 
![image](https://user-images.githubusercontent.com/30532769/112572232-b5808e00-8e24-11eb-97a5-5c4ff15fb3b9.png)

    Unlock PWM output:
![image](https://user-images.githubusercontent.com/30532769/112572234-b7e2e800-8e24-11eb-8349-d0c943991673.png)

**Comment by CUAVcaijie** [comment]
parameter settings:
CBRK_USB_CHK = 197848
CBRK_SUPPLY_CHK = 894281
RC_MAP_AUX1 = Channel 6
RC_MAP_AUX2 = Channel 7

**Comment by dagar** [comment]
Thanks for reporting, I think we have a regression.
