### ISSUE TITLE
UAVCAN command bridge: Spamming message

### ISSUE THREAD

**Issue by ecmnet** [PX4/PX4-Autopilot#17305]
In 1.12-beta2, dmesg (and log) still is spammed with UAVCAN messages after arming:

<img width="912" alt="Bildschirmfoto 2021-04-02 um 13 10 40" src="https://user-images.githubusercontent.com/7580193/113410997-00fee300-93b5-11eb-8deb-cfc73faf085f.png">

**Comment by dagar** [comment]
Thanks for reporting, I think we can get rid of this now.

**Comment by dagar** [comment]
Things should be a bit quieter with https://github.com/PX4/PX4-Autopilot/pull/17307.

**Comment by ecmnet** [comment]
Perfect, with https://github.com/PX4/PX4-Autopilot/pull/17307 those messages do not appear any more.
