### ISSUE TITLE
3D Velodyne Lidar Support for Iris

### ISSUE THREAD

**Issue by cserko** [PX4/PX4-Autopilot#17345]
Hi, 

**Describe problem solved by the proposed feature**
It'd be very nice if there was 3D Velodyne lidar extension for the Iris drone.

**Describe your preferred solution**
I will add a new model velodyne lidar (like rplidar) into Tools/sitl_gazebo then test it on Gazebo & ROS.

**Describe possible alternatives**
I don't know any.

**Additional context**
nothing yet

**Comment by Jaeyoung-Lim** [comment]
@cserko If this is of concern of gazebo in SITL, lets move the discussion to https://github.com/PX4/PX4-SITL_gazebo, since it is not related to this repository.
