### ISSUE TITLE
Found that many parameters are not activated in v1.12.beat2

### ISSUE THREAD

**Issue by Kim-zhi-jiang** [PX4/PX4-Autopilot#17344]
Hello there

Found that many parameters are not activated,  worried about affecting the flight. 

Don't know it's discarded?

![2021-04-06 10-30-10 的屏幕截图](https://user-images.githubusercontent.com/80669694/113651471-9c010100-96c4-11eb-97c7-effbad539433.png)

**Comment by LorenzMeier** [comment]
The -a option is only for system development - because PX4 supports multicopters, planes, rovers, boats it will never use all parameters at once. Use ```param show``` to see the current active ones.
