### ISSUE TITLE
Cube Orange USB Serial not working on WIndows

### ISSUE THREAD

**Issue by dlech** [PX4/PX4-Autopilot#17352]
**Describe the bug**

Cube Orange flashed with PX4 firmware does not connect on Windows due to the serial port driver not loading for the mavlink connection.

**To Reproduce**

1. Flash PX4 firmware using QGroundControl (using developer/master)
  ![image](https://user-images.githubusercontent.com/963645/113749928-ce642b80-96cf-11eb-833e-d9ab661a142c.png)
2. After the autopilot reboots, it does not connect
3. Go to *Device Manager* and notice an error
  ![image](https://user-images.githubusercontent.com/963645/113750238-2864f100-96d0-11eb-843b-45696e6160f9.png)
4. Double-click it to see the details
  ![image](https://user-images.githubusercontent.com/963645/113750379-56e2cc00-96d0-11eb-959a-6301a7cc04ec.png)

**Expected behavior**

Cube Orange should be able to connect the same as other autopilots. 

**Additional context**

The reason I think this is a firmware issue rather than an issue with my computer is that other autopilots work (Cube Black and original Pixhawk) and if I flash the ArduPilot firmware instead of the PX4 firmware to the Cube Orange, I don't get this error.

![image](https://user-images.githubusercontent.com/963645/113751136-35361480-96d1-11eb-94ac-b1525c3930b4.png)

![image](https://user-images.githubusercontent.com/963645/113751269-63b3ef80-96d1-11eb-89c9-49b6d4279c64.png)

**Comment by saengphet** [comment]
I am not sure this can solve your problem or not but it works for me. I installed the latest version of mission planner, then try to connect cube orange again in QGC. In my opinion it is about cube orange usb driver in windows, in Linux works fine without above installation.

**Comment by dlech** [comment]
Thanks for the tip! I can confirm that installing the latest mission planner fixed the issue for me as well.

**Comment by saengphet** [comment]
> Thanks for the tip! I can confirm that installing the latest mission planner (v1.3.74) fixed the issue for me as well.

Wonderful !! However, we still need the right solution for other users. @dagar

**Comment by mrpollo** [comment]
@davids5 Can you please give this a quick test? it should just work with our bootloader on windows.

**Comment by MaEtUgR** [comment]
@davids5 was just able to reproduce this. We're not sure what the bootloader does to get into this situation.

**Comment by dlech** [comment]
>           ===>Device Descriptor<===
> bLength:                           0x12
> bDescriptorType:                   0x01
> bcdUSB:                          0x0200
> bDeviceClass:                      0x02  -> This is a Communication Device
> bDeviceSubClass:                   0x00
> bDeviceProtocol:                   0x00
> bMaxPacketSize0:                   0x40 = (64) Bytes
> idVendor:                        0x2DAE = Vendor ID not listed with USB.org as of 02-15-2012
> idProduct:                       0x1016
> bcdDevice:                       0x0101
> iManufacturer:                     0x01
>      English (United States)  "CubePilot"
> iProduct:                          0x02
>      English (United States)  "PX4 BL CubePilot CubeOrange"
> iSerialNumber:                     0x03
>      English (United States)  "0"
> bNumConfigurations:                0x01

Should `bDeviceSubClass` be 0x02 to match the built-in Windows USB serial driver? https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/usb-driver-installation-based-on-compatible-ids#windows10

**Comment by n-snyder** [comment]
I am having the same issue from Windows 10 using either Mission Planner 1.3.75 or today's daily build of QGC. I can install ArduPilot fine, and communicate with it afterward. However, when installing PX4 v4.1.3 from either MP or QGC, I can install PX4 fine, but the USB comm port for Mavlink is invalid.

**Comment by davids5** [comment]
My Windows 10 machine is down at the moment. But I would guess that the driver install in QGC is not up to date with the mission planers copy. We should see if a virgin install of QGC has the inf files with 
a VID/PID
idVendor:                        0x2DAE 
idProduct:                       0x1016

If not that is the root cause.

@mrpollo - remember the test we did on you Win10 machine. It is the same that is needed here.

**Comment by trddo** [comment]
Was there a final conclusion, (fix) for this issue?
I am also experiencing this same phenomenon.
I was temporarily able to connect after uninstalling all drivers, then reinstalling latest drivers.msi PX4, however this only worked for a one time connection.

**Comment by mnumanuyar** [comment]
>  But I would guess that the driver install in QGC is not up to date with the mission planers copy. 

I had this problem, with device manager and all. installing mission planner solved it for me

**Comment by julianoes** [comment]
I can reproduce some of the problems. I'm having a look.

**Comment by julianoes** [comment]
As @davids5 pointed out above. The likely culprit is that [QGC's driver.msi is from 2020](https://github.com/mavlink/qgroundcontrol/commit/513ab1ed252f8b0bb7e3d99fc9ffca9b7ee035ae) and needs to be updated.

I'm trying to update it: https://github.com/mavlink/qgroundcontrol/pull/10679

**Comment by dlech** [comment]
It would be even better if the firmware was modified to included the required USB descriptors so that drivers are not required at all on Windows.

See https://learn.microsoft.com/en-us/windows-hardware/drivers/usbcon/supported-usb-classes

**Comment by julianoes** [comment]
@dlech ok, how/what would we have to change?

**Comment by dlech** [comment]
Since this is a serial port, I think just changing the device subclass to 0x02 should do it.

https://learn.microsoft.com/en-us/windows-hardware/drivers/usbcon/usb-driver-installation-based-on-compatible-ids#windows10-and-later

**Comment by julianoes** [comment]
Where? Sorry I'm not sure how this all works.

**Comment by dlech** [comment]
I did some digging. It looks like USB is handled in NuttX.

Based on the descriptor listings in previous comments, it looks like this device descriptor is being used which has subclass of `CDC_SUBCLASS_NONE` which is 0x00. See https://github.com/PX4/NuttX/blob/eb43c582eacff396c49a878b6e067ef66b8841d3/drivers/usbdev/cdcacm_desc.c#L49-L68

There are also interface association descriptors that have subclass of `CDC_SUBCLASS_ACM` which is the 0x02 that Windows uses for driver matching. See https://github.com/PX4/NuttX/blob/eb43c582eacff396c49a878b6e067ef66b8841d3/drivers/usbdev/cdcacm_desc.c#L412-L447

So, I think it is probably a matter of changing the NuttX config to make the USB device appear as a composite device instead of strictly as a communication device then Windows will use the interface associate descriptors to figure out which driver to use.

**Comment by dlech** [comment]
Or perhaps more simply, change this line to `CDC_SUBCLASS_ACM`.

https://github.com/PX4/NuttX/blob/eb43c582eacff396c49a878b6e067ef66b8841d3/drivers/usbdev/cdcacm_desc.c#L66

**Comment by julianoes** [comment]
Interesting. @davids5 would that make sense?

**Comment by MaEtUgR** [comment]
But is it a cube thing then? I currently don't have any cube board at hand but e.g. pixhawk 4 (+ mini), pixracer just connect to the ground station and can be flashed under Windows 10/11 without installing any driver. QGC at installation always prompts you to install additional drivers, I just press abort and it all works for years now already.

**Comment by davids5** [comment]
> Interesting. @davids5 would that make sense?

I am not sure. The notes say you need a inf file for 8.1 So we have always had one. If windows 10+ qualifies the driver on the sub-class it may work. I am having troubles finding the use of "sub-class" So I would try the suggested change and test it.
