### ISSUE TITLE
Vehicle Setup>Power Setup

### ISSUE THREAD

**Issue by mommotti** [PX4/PX4-Autopilot#17366]
I'm trying to set up my Pixhawk 2.1 using PX4.
I don't have a battery, the Pixhawk is connected to my companion computer ( Raspberry Pi 3b ) via USB.
I have already disabled the USB checks with " CBRK_USB_CHK 197848 "
Is there a way to bypass the Power Setup and just use the USB connection provided by the Raspberry to power the Pixhawk?
Power Setup:
![image](https://user-images.githubusercontent.com/49097348/114188814-cca59c80-9949-11eb-8bef-2bd0f3ccb2df.png)
Parameters (Battery Calibration): 
![image](https://user-images.githubusercontent.com/49097348/114190057-2a86b400-994b-11eb-97bf-a4a64958b23a.png)
The build:
![image](https://user-images.githubusercontent.com/49097348/114191075-50608880-994c-11eb-84b7-eb97c41329d4.png)
Thank you in advance!

**Comment by benjinne** [comment]
Try setting CBRK_SUPPLY_CHK to arm with no power input

**Comment by mommotti** [comment]
> 
> 
> Try setting CBRK_SUPPLY_CHK to arm with no power input

![image](https://user-images.githubusercontent.com/49097348/114310630-a61f6700-9aeb-11eb-94a7-b120344ad3d4.png)
Thanks for the quick reply! Still nothing tho... The problem persists

**Comment by LorenzMeier** [comment]
What is the error message you are getting?

**Comment by mommotti** [comment]
> 
> 
> What is the error message you are getting?

I was getting something similar to "Unable to arm, please complete the setup."
But now that warning message doesn't pop up anymore on QGC... Thank you all, let's call it close for now
