### ISSUE TITLE
Choosing the Local Position Estimator (LPE) causes PX4 not to boot properly on hardware with v1.12.0-beta2

### ISSUE THREAD

**Issue by FernandezR** [PX4/PX4-Autopilot#17380]
**Describe the bug**
The flight controller will not allow mavlink connections on hardware after setting the parameter SYS_MC_EST_GROUP to LPE and rebooting the flight controller. 

**To Reproduce**
1. Flash pixracer with v1.12.0-beta2 with default params
2. Set the airframe to Generic Quadrotor X
3. Set the SYS_MC_EST_GROUP parameter to LPE
4. Reboot flight controller
5. Attempt to create mavlink connection to board using qgroundcontrol
6. See error where re-connection does not occur

**Expected behavior**
It was expected that the flight controller would boot like normal after setting the parameter and rebooting.

**Additional context**
I first noticed this issue on a Modal AI Flight Deck board and then tested on the pixracer to confirm the board was not the issue.

Additionally, I tested this bug in the gazebo simulation and the simulation was able to start and the drone was able to takeoff like normal.

**Comment by dagar** [comment]
I'll see if this can be resolved in time for v1.12, however I'd still strongly recommend switching to EKF2 as LPE isn't really supported anymore.
