### ISSUE TITLE
About the setpoints in offboard mode

### ISSUE THREAD

**Issue by shupx** [PX4/PX4-Autopilot#17412]
https://github.com/PX4/PX4-Autopilot/pull/16739#issue-566432599
In this PR, the FlightTaskOffboard.cpp was deleted. I don't understand why. How does PX4 process the setpoints in offboard mode as this mode was deleted?

Thanks!

**Comment by shupx** [comment]
Oh! I have figured out why. The setpoints are published by mavlink_receiver.cpp directly rather than by FlightTaskOffboard.cpp as it used to be.

**Comment by MaEtUgR** [comment]
I was late https://github.com/PX4/PX4-Autopilot/pull/16739#issuecomment-822297169 😃

**Comment by shupx** [comment]
@MaEtUgR Thank you though
