### ISSUE TITLE
Unable to flying more than 20 minutes

### ISSUE THREAD

**Issue by Kim-zhi-jiang** [PX4/PX4-Autopilot#17455]
Hello everybody

Unable to flying more than 20 minutes at v-master version in simulation environment.

1 MC iris
![mc](https://user-images.githubusercontent.com/80669694/115987078-24006980-a5e6-11eb-8e48-db804342aa34.png)

2 standard vtol
![vtol](https://user-images.githubusercontent.com/80669694/115987094-32e71c00-a5e6-11eb-9107-1864b254af3b.png)

**Comment by julianoes** [comment]
Interesting, this is probably something hanging due to lockstep.

Is this in VirtualBox? And how many CPU cores have you enabled? I'm just asking so I can try to reproduce this.

**Comment by Kim-zhi-jiang** [comment]
Only one Ubuntu system in laptop, But V-1.11.x no this problem.
Test PX4 master version every day, still this problems (Don't know why the latency is high )

**Comment by Kim-zhi-jiang** [comment]
@julianoes 

Thank you！  

Have been used before "PX4_SIM_SPEED_FACTOR=3 make -j4 px4_sitl gazebo"
If "PX4_SIM_SPEED_FACTOR=1" like this
![Uploading 2021-05-08 07-20-40 的屏幕截图.png…]()

**Comment by Kim-zhi-jiang** [comment]
![2021-05-08 07-20-40 的屏幕截图](https://user-images.githubusercontent.com/80669694/117517523-d107b880-afce-11eb-8a3f-fb8b284c46d8.png)

**Comment by SalimTerryLi** [comment]
Confirmed with latest master f15eefcc9503d2abe0713defe7f017519e337b0b .

`make px4-sitl gazebo` and crashed after 30min. Ubuntu 20.04 host without any virtualization.

Seems that something went wrong within gzserver.

**Comment by Jaeyoung-Lim** [comment]
@Kim-zhi-jiang Can you check your memory usage?

**Comment by julianoes** [comment]
I can reproduce it. It doesn't seam to happen with jmavsim.

**Comment by Jaeyoung-Lim** [comment]
@julianoes Thanks, I will have a look

**Comment by Kim-zhi-jiang** [comment]
@Jaeyoung-Lim  Sometime RTL or TIMEOUT used today "541697d19" version.

![2021-05-09 07-36-46 的屏幕截图](https://user-images.githubusercontent.com/80669694/117556483-13e39200-b09c-11eb-8246-15136f761e48.png)
![2021-05-09 07-37-37 的屏幕截图](https://user-images.githubusercontent.com/80669694/117556485-1514bf00-b09c-11eb-81e6-2c7138643d80.png)
![2021-05-09 07-48-24 的屏幕截图](https://user-images.githubusercontent.com/80669694/117556486-1645ec00-b09c-11eb-92e0-8e169e17362c.png)

**Comment by julianoes** [comment]
Fix coming in https://github.com/PX4/PX4-SITL_gazebo/pull/747.

**Comment by Kim-zhi-jiang** [comment]
@julianoes  @Jaeyoung-Lim 
Perfect！

**Comment by heleidsn** [comment]
Hi @julianoes and @Kim-zhi-jiang, 

Is this problem solved after the **PX4/PX4-SITL_gazebo#747**? 

I find the same problem and now I cannot simulate over 35min with `export PX4_SIM_SPEED_FACTOR=20`. It can be reproduced on my PC.

![Screenshot from 2021-05-15 10-48-09](https://user-images.githubusercontent.com/9855921/118346058-67a61d80-b56b-11eb-9973-1071983ea2f8.png)

OS: Ubuntu 18.04
PX4: 5f14ee2a9705d746de7a87034f347db1c624fab2
px4_sitl: 2496b85dd22d2f9c1c1281d5ef77dfb86ef604a3

**Comment by julianoes** [comment]
@heleidsn does this happen consistently?

**Comment by Kim-zhi-jiang** [comment]
"PX4_SIM_SPEED_FACTOR=20"  so fast！I use 3
Some code needs to be optimized.

for(i=0 i++ i=1000000000){
double xyz=11111.0f;
.....
}
VS
double xyz;
for(i=0 i++ i=1000000000){
xyz=11111.0f;
.....
}

**Comment by Kim-zhi-jiang** [comment]
"PX4_SIM_SPEED_FACTOR=20"  so fast！I use 3
Some code needs to be optimized.

for(i=0 i++ i=1000000000){
double xyz=11111.0f;
.....
}
VS
double xyz;
for(i=0 i++ i=1000000000){
xyz=11111.0f;
.....
}

**Comment by julianoes** [comment]
@Kim-zhi-jiang like where?

**Comment by Kim-zhi-jiang** [comment]
I just touch drones,but find some, later will find EKF POS ATT.
![2021-05-17 19-38-31 的屏幕截图](https://user-images.githubusercontent.com/80669694/118482725-b5777d00-b747-11eb-8f62-d4d34e671de1.png)
![2021-05-17 19-39-52 的屏幕截图](https://user-images.githubusercontent.com/80669694/118482734-b7d9d700-b747-11eb-8c81-75aa6dcfec52.png)

**Comment by heleidsn** [comment]
> @heleidsn does this happen consistently?

Hi @julianoes, this happens every time on my PC. 

Hi @Kim-zhi-jiang, as for `PX4_SIM_SPEED_FACTOR=20`, I think it's not too fast because it will reach the hardware limitation if we set `PX4_SIM_SPEED_FACTOR` a big number. On my PC, it can reach 20 times of real-time speed.

**Comment by julianoes** [comment]
@heleidsn sorry, what happens?

**Comment by heleidsn** [comment]
> @heleidsn sorry, what happens?

@julianoes Hi, I mean the same crash problem happens. As I said here: https://github.com/PX4/PX4-Autopilot/issues/17455#issuecomment-841588584

**Comment by Kim-zhi-jiang** [comment]
@heleidsn 

More than this?

param set-default IMU_GYRO_RATEMAX 400 # Default 400 100 250 400 800 1000 2000Hz
param set-default IMU_INTEG_RATE 200 #Default 200 100 200 250 400Hz

Annoying lazy data transfer!

**Comment by Kim-zhi-jiang** [comment]
@heleidsn 

More than this?

param set-default IMU_GYRO_RATEMAX 400 # Default 400 100 250 400 800 1000 2000Hz
param set-default IMU_INTEG_RATE 200 #Default 200 100 200 250 400Hz

Annoying lazy data transfer!

**Comment by Kim-zhi-jiang** [comment]
@heleidsn 

More than this?

param set-default IMU_GYRO_RATEMAX 400 # Default 400 100 250 400 800 1000 2000Hz
param set-default IMU_INTEG_RATE 200 #Default 200 100 200 250 400Hz

Annoying lazy data transfer!
