### ISSUE TITLE
There is packet loss when UAVCAN sends large data

### ISSUE THREAD

**Issue by CUAVcaijie** [PX4/PX4-Autopilot#17486]
**Describe the bug**
RTK base is connected to QGC and forwarded to the CAN RTK mobile terminal using the CAN port. The mobile terminal detects a packet loss error in UAVCAN data (flip error...)

**To Reproduce**
Use f6a34e1e80ff259838dd15b17b7eb97fd347ee01 version firmware

> equipment:
CUAVv5Nano
F9P base, CAN RTK Mobile
QGC

> parameter settings：
UAVCAN_ENABLE = Sensors Manual Config

**Expected behavior**
You can check the packet loss on the CAN of the mobile terminal

 **The following is the code connection I tested and modified**
https://github.com/cuav/libuavcan/tree/cuav_test
https://github.com/cuav/Firmware/tree/cuav_uavcan_test

**Problem finding process**
Print the UAVACAN package at the send function entry of the src/drivers/uavcan/libuavcan/libuavcan/src/transport/uc_can_io.cpp file. No data was lost.
Print the UAVACAN packet in the sendToIface function and find that it is the same as the data received by CAN RTK Mobile. There is already a packet loss. So I guess the problem is in the queue

**Comment by CUAVcaijie** [comment]
This picture shows only the first frame of data
![image](https://user-images.githubusercontent.com/30532769/116659504-46b6c780-a9c4-11eb-9a12-7c15557ef51c.png)
This is the queue is full
![image](https://user-images.githubusercontent.com/30532769/116659517-49b1b800-a9c4-11eb-906c-e6bb25b99989.png)

**Comment by davids5** [comment]
@pavel-kirienko ideas?

**Comment by pavel-kirienko** [comment]
Try increasing the memory allocation arena here and see if it fixes the problem:

https://github.com/PX4/PX4-Autopilot/blob/4f52c0b6daa93f01b3c02e9457265be107af74be/src/drivers/uavcan/allocator.hpp#L54-L55

**Comment by CUAVcaijie** [comment]
Okay, test it when I go back during the holidays

**Comment by CUAVcaijie** [comment]
Hello, increase these two values by 200, but the packet loss error still occurs.
![image](https://user-images.githubusercontent.com/30532769/117258631-c1c62500-ae7f-11eb-8a08-351de42e2a5c.png)

**Comment by CUAVcaijie** [comment]
@pavel-kirienko 
Hello, I added a number of enqueue and dequeue data volume statistics, and found that when the queue does not overflow, the queue dequeue data has been lost.

![image](https://user-images.githubusercontent.com/30532769/117261793-233bc300-ae83-11eb-984a-817e6dc2a852.png)
1 is to print directly using the queue length. 2 is the difference between entering and leaving the team. What is more obvious here is that suddenly there is no data in the queue.

A few minutes later, the difference between entering and leaving the team reached tens of thousands
![image](https://user-images.githubusercontent.com/30532769/117262373-c096f700-ae83-11eb-811a-8bd0e56a3de4.png)


This is the code I added to print：
https://github.com/cuav/libuavcan/tree/cuav_test

**Comment by CUAVcaijie** [comment]
I blocked my print information, and then increased the allocated memory. There is no packet loss.
More than 160 memory blocks were used, but only 126 were originally allocated.
![image](https://user-images.githubusercontent.com/30532I will repeat the test tomorrow769/117273603-df4ebb00-ae8e-11eb-9975-6848f4243998.png)

**Comment by CUAVcaijie** [comment]
CUAV X7

Here is to allocate memory to print
![image](https://user-images.githubusercontent.com/30532769/117384782-54b19e80-af16-11eb-8935-2db0693aef4d.png)

Here, there is packet loss when the queue is not full, and the difference between the incoming and outgoing queues is getting bigger and bigger.
![image](https://user-images.githubusercontent.com/30532769/117384848-73b03080-af16-11eb-96b4-a37e3fd6521d.png)

**Comment by CUAVcaijie** [comment]
CUAV V5nano

Here is to allocate memory to print
![image](https://user-images.githubusercontent.com/30532769/117385445-b7f00080-af17-11eb-942b-2ed602d0c2b9.png)

The number of enqueues and the number of exits remain the same
![image](https://user-images.githubusercontent.com/30532769/117385470-c5a58600-af17-11eb-8797-6b6ef263651e.png)

**Comment by CUAVcaijie** [comment]
@pavel-kirienko 
After the CUAV v5Nano flight controller increases the allocated memory, the packet loss problem can be solved.

In addition to insufficient memory allocation, the CUAV X7 flight controller has other problems that cause packet loss. Not found yet

**Comment by CUAVcaijie** [comment]
Any good suggestions?

**Comment by CUAVcaijie** [comment]
Hello, I found that the entrance sent by CUAV X7 is different from the entrance sent by CUAV v5Nano. Will it affect the subsequent data loss?

CUAV V5 sending entrance:
src/drivers/uavcan/libuavcan/libuavcan/include/uavcan/node/publisher.hpp
int broadcast(const DataType& message)

CUAV X7 send entrance:
src/drivers/uavcan/uavcan_main.cpp
void UavcanNode::node_spin_once()

**Comment by CUAVcaijie** [comment]
@pavel-kirienko 
Sorry, it turns out that there is a problem with the baud rate setting of my CAN device. Configured to 87.5, it can be used normally. No packet loss

**Comment by CUAVcaijie** [comment]
@davids5 @pavel-kirienko 
Thank you

**Comment by davids5** [comment]
@CUAVcaijie - Would you please make a PR with any relevant changes needed.
