### ISSUE TITLE
CUAV 1.12beta4 test report

### ISSUE THREAD

**Issue by jinger26** [PX4/PX4-Autopilot#17491]
CUAV tested 1.12beta4 for PWM controls, and here's the result (April 30)

Hardware: X7

Airframe selection:
![Screen Shot 2021-04-30 at 11 42 16 PM](https://user-images.githubusercontent.com/4444989/116719606-d6349880-aa0d-11eb-9382-151172b95c75.png)

Note: **rc7 is mapped to aux6

Output:
![Screen Shot 2021-04-30 at 11 42 50 PM](https://user-images.githubusercontent.com/4444989/116719869-227fd880-aa0e-11eb-911d-4dc21f674116.png)

总结：该机型所有的电机和舵机解锁后都有输出，并且可以通过遥控器控制，但是设置RC7映射到aux6,M14没有pwm输出。
Summary: All motors and servos of this model have pwm outputs after ARM, and can be controlled by remote control, but set RC7 to map to aux6, M14 has no pwm output.

**Comment by dagar** [comment]
Thanks for the info.
