### ISSUE TITLE
Real drone can not take-off during mission

### ISSUE THREAD

**Issue by Cristian-wp** [PX4/PX4-Autopilot#17609]
Hello, I am working with PX4-Avoidance for a project using missions.
At the moment the avoidance ROS node (for what I can see by logs) it working correctly (even in simulation).
Now I am trying to test it on a real drone but I am unable to take off in mission mode, my steps are:

1. Turn on the drone waiting for GSP signal
2. Turn on avoidance ros node
3. Planning a mission with QGC
4. Start the mission

When I arm and the mission starts, the motor start to spin at minimum PWM  (PWM_MIN value) and do not change.
I have tried already manual and altitude mode and I can take off manually, so is not a problem of payload.

What can I check to resolve this problem? 
In QGC I do not have any error or warning , I have also check the return to home in mission mode and the result is the same, the motor spin always at PWM_MIN value (that is different from PWM_MAX)

**Comment by mrpollo** [comment]
@Cristian-wp per slack, it seems that you already figure out your problem was a configuration issue, and this can be closed.

Let me know if we should re-open.
