### ISSUE TITLE
RTK GPS over CAN

### ISSUE THREAD

**Issue by FreshGresh** [PX4/PX4-Autopilot#17613]
RTK GPS over CAN (from Here3) is not currently compatible with PX4 (but is with Ardupilot).

Is this in the works or can I request it be added as a feature?

For reference, I am using a Pixhawk Cube Orange with Here3 connected via the CAN. I have demonstrated RTK GPS (fixed) using the Here+ over I2C.

**Comment by FreshGresh** [comment]
Worked with v1.12-beta5, thanks! 
3D RTK GPS lock (fixed) just fine with Quadrotor X airframe. I'll try in flight with a fixed wing normal airplane soon. Looking forward to the v1.12 stable release!

**Comment by Franzi13** [comment]
Hi everyone,
I think there is still a problem using RTK GPS over CAN with the Pixhawk 4 and also with the new Pixhawk 6c board.
Is there a way to make it work there too?
Thank you in advance!
