### ISSUE TITLE
Vectored Thrust Model

### ISSUE THREAD

**Issue by bazfp** [PX4/PX4-Autopilot#17662]
It would be useful for vehicles to have a model for vectored thrust. For example boats often use jet propulsion, which is a vectored thrust control scheme. It's very simple, just a single big motor and a servo for controlling direction of the thrust. Considerations must be taken, such as requiring power to turn and a variable turning effectiveness based on speed. Ardupilot has an implementation of this. https://ardupilot.org/rover/docs/rover-vectored-thrust.html

**Describe your preferred solution**
A model for controlling vectored thrust systems. A vehicle frame for a boat that has vectored thrust would also be nice :)

**Comment by mrpollo** [comment]
Thanks for the suggestion @bazfp whoever our Github is only for raising issues with the codebase, if you would like to pitch a feature, you are free to do it on our [forums](https://discuss.px4.io) or [slack](http://slack.px4.io), we can also help you develop this feature on your own if you want to try that route which I would recommend.
