### ISSUE TITLE
Yaw setpoint spike, when landing triggered via Mavlink command MAV_CMD_NAV_LAND

### ISSUE THREAD

**Issue by ecmnet** [PX4/PX4-Autopilot#17685]
In 1.12.beta, triggering landing via MAV_CMD_NAV_LAND leads to a spike in Yaw at the beginning of the landing phase, which should not occur. This issue is independent from parameter 4 of MAV_CMD_NAV_LAND (setting it to NaN or current yaw):

<img width="793" alt="Bildschirmfoto 2021-06-01 um 16 21 37" src="https://user-images.githubusercontent.com/7580193/120339553-7fb0c780-c2f5-11eb-9306-82bfc93f0a56.png">

<img width="793" alt="Bildschirmfoto 2021-06-01 um 16 25 22" src="https://user-images.githubusercontent.com/7580193/120340119-036ab400-c2f6-11eb-90b9-c7826195471c.png">

ULog: [https://logs.px4.io/plot_app?log=07daba2b-95db-4f4b-b5e9-423ebb3f5fa0](https://logs.px4.io/plot_app?log=07daba2b-95db-4f4b-b5e9-423ebb3f5fa0)

**Comment by dagar** [comment]
Looks like its jumping to your current heading.

![image](https://user-images.githubusercontent.com/84712/120348102-dbb22680-c2ca-11eb-8fa0-9bedaca5f84e.png)

**Comment by ecmnet** [comment]
Possible reason might be that the yaw Setpoint is set to the current yaw measured:

![chart_1](https://user-images.githubusercontent.com/7580193/120427422-2d61bc00-c372-11eb-8359-034b0461ba37.png)

**Comment by LorenzMeier** [comment]
@MaEtUgR Do you have an idea what change set might have introduced this?

**Comment by MaEtUgR** [comment]
I'm not aware of any particular change that would cause this. Navigator indeed just sets the setpoint to the current yaw estimate but there is(/was?) a slewrate applied on top that always results in feasible turn speeds configured by the maximum yawrate.

**Comment by MaEtUgR** [comment]
I would first check if the slewrate is configured and initialized the correct way...

**Comment by ecmnet** [comment]
I do not believe anymore that this is due to stepping changes. I saw that kind of spikes now during takeoff also.

**Comment by Kim-zhi-jiang** [comment]
VTOL  v_master 
![2021-06-16 10-22-44 的屏幕截图](https://user-images.githubusercontent.com/80669694/122149072-10f37280-ce8e-11eb-90ab-76abb14eeecd.png)

**Comment by ecmnet** [comment]
UPDATE: Might be related to HIGH_RES SD logging. First checks show, that after setting the logging mode from 17 to 1, the spikes do not occur anymore.

**Comment by ecmnet** [comment]
I can confirm now, that this issue is related to the switch of the yaw Setpoint to the current yaw. Might be solved by better tuning of the yaw controller.

**Comment by MaEtUgR** [comment]
I haven't had time to look into details yet. My suspicion is that the yaw rate limit for waypoint
https://github.com/PX4/PX4-Autopilot/blob/155d3c7d367fced2830ff57031e346c2faa037c8/src/modules/flight_mode_manager/tasks/Auto/FlightTaskAuto.cpp#L93-L124
is not initialized the right way and that's why you might run into the issue.

**Comment by ecmnet** [comment]
I do not understand why the setpoint is updated even if yaw is aligned

`if (!PX4_ISFINITE(_yawspeed_setpoint) && (_deltatime > FLT_EPSILON)) { 
 			// Create a feedforward 
 			_yawspeed_setpoint = dyaw / _deltatime; 
 		} `

It is hard to reproduce the issue in SITL but if the aligned condition is added, no setpoint change happens:

`if (!PX4_ISFINITE(_yawspeed_setpoint) && (_deltatime > FLT_EPSILON) && !_yaw_sp_aligned) {
			// Create a feedforward
			_yawspeed_setpoint = dyaw / _deltatime;
		}`

**Comment by ecmnet** [comment]
Closing this as the spike does not occur anymore with v1.12-stable.
