### ISSUE TITLE
CUAV x7 Pro The master firmware enables camera triggering, causing no other PWM output

### ISSUE THREAD

**Issue by CUAVcaijie** [PX4/PX4-Autopilot#17726]
**Describe the bug**
There is no output from the PWM channel after the camera trigger is enabled

**test environment**
Test hardware: 
CUAV X7 Pro

Test firmware version:
FW git-hash: 66dbc1e25f6fc173cb0ca54f73723b7bbc460cf8

Test model: eight-axis
SYS_AUTOSTART = 8001
![image](https://user-images.githubusercontent.com/30532769/121012751-9e69ff00-c7ca-11eb-9914-96d4371288e8.png)

parameter settings:
CBRK_USB_CHK = 197848（(It can be unlocked normally when connected to the USB)）
CBRK_SUPPLY_CHK = 894281（It can be unlocked normally without connecting the ammeter）
RC_MAP_AUX1 = Channel5
RC_MAP_AUX2 = Channel6
RC_MAP_AUX3 = Channel7
RC_MAP_AUX4 = Channel8

**Test comparison**

1. PWM output when camera trigger is not enabled
Before unlocking, only the first eight channels have output (normal)
![八轴-没有开启相机触发-解锁](https://user-images.githubusercontent.com/30532769/121018604-336ff680-c7d1-11eb-9858-08ac0862675d.png)

After unlocking: the first eight channels plus 4 RC channels (normal)
![八轴-没有开启相机触发-未解锁](https://user-images.githubusercontent.com/30532769/121018623-38cd4100-c7d1-11eb-8ca6-88344c79f747.png)

2. Enable PWM output when camera is triggered
Camera trigger settings:
![相机触发设置](https://user-images.githubusercontent.com/30532769/121018816-6f0ac080-c7d1-11eb-9e40-630c36c05f44.png)

DEBUG error message after enabling camera trigger:
![设置相机触发后DEBUG输出](https://user-images.githubusercontent.com/30532769/121018842-75993800-c7d1-11eb-9a9e-764d0a2ef1aa.png)

Enable camera trigger-not unlocked: The 6th channel becomes the camera trigger channel. The first eight channels of PWM control have no output
![开启相机触发-解锁前](https://user-images.githubusercontent.com/30532769/121018861-7b8f1900-c7d1-11eb-83b7-918a9be27e29.png)

Enable camera trigger-unlock: Same as unlocked, PWM has no output.
![开启相机触发-解锁](https://user-images.githubusercontent.com/30532769/121018883-7fbb3680-c7d1-11eb-8818-71dee5807528.png)

**The cause of this phenomenon**

1. Camera trigger channels should be the last few
2. In line 393 of file ROMFS/px4fmu_common/init.d/rcS. It is caused by setting the output mode to none. 

**modified code test**
https://github.com/cuav/Firmware/tree/camera_trigger_test
Set the camera to 2000 after trigger
Test Results：PWM OUT OK, camera trigger OK
![相机触发-成功](https://user-images.githubusercontent.com/30532769/121018404-fad01d00-c7d0-11eb-9df4-891183785ca2.png)

**Comment by CUAVcaijie** [comment]
Because the modification involves various motherboards, I hope to get help on the modification.

**Comment by davids5** [comment]
@CUAVcaijie please test https://github.com/PX4/PX4-Autopilot/pull/17748
