### ISSUE TITLE
gyro_calibration potentially leaking

### ISSUE THREAD

**Issue by PetervdPerk-NXP** [PX4/PX4-Autopilot#17753]
**Describe the bug**
I'm running low on RAM on my board so I'm looking at potential optimizations. During startup I've noticed that gyro_calibration runs nicely and calibrates the gyro and then just exits when done. However it seems that when not running gyro_calibration it yields more free memory. My guess is that calibration values of gyro always exist even without running the gyro_calibration thus I would expect that running gyro_calibration shouldn't increase the memory usage.

With `IMU_GYRO_CAL_EN=1`

```
             total       used       free    largest
Umem:       221184     195760      25424      25136
```

With `IMU_GYRO_CAL_EN=0`

```
             total       used       free    largest
Umem:       221184     194656      26528      26224
```

**To Reproduce**
Toggle `IMU_GYRO_CAL_EN` and check memory usage.

**Comment by dagar** [comment]
The `gyro_calibration` module doesn't exit, it's always running to catch gradual bias changes. Once armed it sits idle, then resumes cycling once disarmed again.

It sounds like for memory constrained boards we should either disable it entirely, or have it exit after the first successful cal (majority of the value).
