### ISSUE TITLE
variations in sensor_combined/accelerometer_integral_dt

### ISSUE THREAD

**Issue by NicolasM0** [PX4/PX4-Autopilot#17804]
**Describe the bug**
During some of my tests, I have done very long logs (I work on a tether drone that is able to fly several days continuously).

I noticed a strange patern in the accelrometer vibration metric while my autopilot did not move as it was on my desk during the weekend:
![acc_vibe](https://user-images.githubusercontent.com/59083163/123425598-9c71af80-d5c2-11eb-85e4-515770d608db.png)

Digging a big, I have found that it comes from a non-constant accelerometer integration duration causing difference between accumalated acceleration:
![acc_int_dt](https://user-images.githubusercontent.com/59083163/123425987-1a35bb00-d5c3-11eb-9dc3-9610b19c7083.png)

I have repeated 3 long logs on the same autopilot (CUAV V5+) with px4 v1.11.3 : the integration duration variation appear at exactly 8590sec after boot on the three logs.
I have tested v1.12 in the same condition on another autopilot (still CUAV v5+) : the same variations appear at about 8590sec after boot but I also have some variation before that : 
![acc_int_dt_v1 12](https://user-images.githubusercontent.com/59083163/123429246-068c5380-d5c7-11eb-8ae2-a435c5c7de2f.png)

It seems that the average integration duration is constant. I suppose that in averge, the correct amount of accelerometers sample is used.

I have nerver noticed that on v1.10 (not checked in a lot of logs).

Is it safe to fly more than 8590sec in v1.11 and v1.12 ?
I suppose yes as the integration is correct but what could happen if the variation continue to increase ?

**Comment by dagar** [comment]
Are you able to share the full log (v1.12 ideally)?

In v1.12 we can check this across different IMUs (`vehicle_imu`) and I'd also like to know which sensor was your primary in the plots above.

**Comment by NicolasM0** [comment]
> Are you able to share the full log (v1.12 ideally)?
> 
> In v1.12 we can check this across different IMUs (`vehicle_imu`) and I'd also like to know which sensor was your primary in the plots above.

The log is downloading but I'm not sure will be able to share it today (very bad connexion...) 
It appears on the three estimators:
![vibs](https://user-images.githubusercontent.com/59083163/123433516-d72c1580-d5cb-11eb-8bb0-4dfda9dcdee1.png)

**Comment by NicolasM0** [comment]
estimator_selector_status_0.accel_device_id = 3932170

**Comment by dagar** [comment]
> 3932170

3932170 = 0x3C000A

0x3C is the device type for the icm20689.
https://github.com/PX4/PX4-Autopilot/blob/9d3e18dbe10700a13f3048f2807dc4b1a62eee62/src/drivers/drv_sensor.h#L93

**Comment by NicolasM0** [comment]
I will share the log monday.

here is the vehicle_imu_X.delta_velocity_dt:
![vehicle_imu_a](https://user-images.githubusercontent.com/59083163/123436019-7c47ed80-d5ce-11eb-8abd-ad4c4990c489.png)

zoom:
![vehicle_imu](https://user-images.githubusercontent.com/59083163/123435436-dd22f600-d5cd-11eb-95c4-cccaf5373f6d.png)

imu 2 is has some varition from the begining but is seems worst after 8590sec
imu 0 and 1 are have both the issue

**Comment by dagar** [comment]
Ok, we'll dig into it more with the full log. One thing to note with the CUAV v5+ is that all 3 IMUs are on the same bus (SPI1), so it's possible they're interacting somewhat.

**Comment by NicolasM0** [comment]
> > 3932170
> 
> 3932170 = 0x3C000A
> 
> 0x3C is the device type for the icm20689.
> 
> https://github.com/PX4/PX4-Autopilot/blob/9d3e18dbe10700a13f3048f2807dc4b1a62eee62/src/drivers/drv_sensor.h#L93

Thank you for this !

**Comment by dagar** [comment]
The perf counters (`perf`) might be another clue before looking at the full log.

If the problem originates in the sensor itself the thing to start thinking about is if/how we can catch it at that level and trigger a reset.

https://github.com/PX4/PX4-Autopilot/blob/9d3e18dbe10700a13f3048f2807dc4b1a62eee62/src/drivers/imu/invensense/icm20689/ICM20689.cpp#L242-L264

**Comment by dagar** [comment]
I haven't been able to reproduce this yet on my CUAV v5+.

**Comment by dagar** [comment]
Still no failure on my v5+ after about 2 days. Did you reproduce this on multiple units?

**Comment by NicolasM0** [comment]
Reproduced 100% but only over 2 units. I can try on another one.

I will try the patch monday. And share the logs.

**Comment by NicolasM0** [comment]
here is the 1.12-beta5 log: https://drive.google.com/file/d/1SzOaOcWYg99Y-BOUoyc_pKfHt1Gutokz/view?usp=sharing

**Comment by NicolasM0** [comment]
and one 1.11 log (with higher variation as it is longer): https://drive.google.com/file/d/1rn7GjICs4cpv_uJbhwRm-VdSup6YEipG/view?usp=sharing
