### ISSUE TITLE
Support for NCP5623B - Holybro

### ISSUE THREAD

**Issue by vincentpoont2** [PX4/PX4-Autopilot#17852]
The current i2c LED driver we using is NCP5623C, but there is a shortage and we are facing sourcing issue. 

NCP5623**B** is available but doesn't look like it's supported, can PX4 add support for NCP5623**B**? 

[NCP5623B Datasheet](https://github.com/PX4/PX4-Autopilot/files/6771546/NCP5623B.pdf)
[NCP5623C Datasheet](https://github.com/PX4/PX4-Autopilot/files/6771545/NCP5623C.pdf)

**Comment by davids5** [comment]
I expect it to work. Please test it as follows:
Start the driver with -a 56 (0x38) for the B part and -a 57 (the default 0x39)for the C part.

rgbled_ncp5623c start -X -a 56

```
rgbled_ncp5623c start -X -a 0x38
Usage: rgbled <command> [arguments...]
 Commands:

   start
     [-I]        Internal I2C bus(es)
     [-X]        External I2C bus(es)
     [-b <val>]  board-specific bus (default=all) (external SPI: n-th bus (default=1))
     [-f <val>]  bus frequency in kHz
     [-q]        quiet startup (no message if no device found)
     [-a <val>]  I2C address
                 default: 57
```

**Comment by vincentpoont2** [comment]
Hi @davids5 
After adding the line of rgbled_ncp5623c start -X -a 56 to the rc.board_defaults file, compile the firmware, and after flashing into the flight control, the NCP5623B can be recognized.

Can this support be added directly in master and next release?
