### ISSUE TITLE
px4_sitl_default vs px4_sitl 

### ISSUE THREAD

**Issue by adbidwai** [PX4/PX4-Autopilot#17876]
When we try to build the PX4 Autopilot firmware, we usually run ```make px4_sitl_default gazebo```. The official PX4 dev guide suggests ```make px4_sitl gazebo```. How are ```make px4_sitl_default gazebo``` different and which one should I use?

**Comment by Jaeyoung-Lim** [comment]
@adbidwai I believe they are the same

**Comment by adbidwai** [comment]
@Jaeyoung-Lim Alright, Thanks!
