### ISSUE TITLE
Mag declination Angle is Incorrect, when auto GPS based declination compensation is enable with LPE.

### ISSUE THREAD

**Issue by kcx064** [PX4/PX4-Autopilot#17885]
**Describe the bug**
In my position, that is China, Beijing, when I switch estimator to LPE, the PX4 will set a error mag declination

This Bug appeared only when the PX4 version is 1.11.3 with LPE estimator.   However, anything is normal when the version is 1.10 and before. 

So I think the Bug  appears begin at v1.11. 

**Then is my gps status screenshort**
![gps status](https://user-images.githubusercontent.com/41360413/125181986-b656f780-e23c-11eb-9a12-3900c4b29497.PNG)

**When I disable the Param ATT_MAG_DECL_A the head is** 
![head2](https://user-images.githubusercontent.com/41360413/125182016-f1592b00-e23c-11eb-8f6f-5c45c766144f.PNG)
**But when the ATT_MAG_DECL_A is enable, the head is** 
![head1](https://user-images.githubusercontent.com/41360413/125182033-059d2800-e23d-11eb-8195-567d1f9f53bd.PNG)

**Comment by LorenzMeier** [comment]
LPE is not any more actively maintained / supported. @bkueng @dagar we might want to remove it entirely, in particular since the EKF has seen significant performance improvements for racers and seen indoor / VIO feature integration.
