### ISSUE TITLE
Thrust curve parameter cannot be changed

### ISSUE THREAD

**Issue by serday** [PX4/PX4-Autopilot#17951]
When configuring PIDs, you need to change thrust curve or THR_MDL_FAC  parameter from 0 to 1. firmware 1.12 does not allow you to do this. Firmware 1.11 allows you to do this.

**Comment by dagar** [comment]
`THR_MDL_FAC` is definitely still present in v1.12. 

What are you seeing?

**Comment by ebtrac** [comment]
Actually, it can be changed. The real issue is that you can only set `THR_MDL_FAC` to be 0 or 1. If you try to give it a value of say, 0.25, it will not change.

**Comment by serday** [comment]
Ok, thanks. But how its must working? 
I see that "The mapping from motor control signals (e.g. PWM) to expected thrust is linear by default — setting THR_MDL_FAC to 1 makes it quadratic. Values in between use a linear interpolation of the two. Typical values are between 0.3 and 0.5."
from here - https://docs.px4.io/master/en/config_mc/pid_tuning_guide_multicopter.html
May be it is not important parameter

**Comment by ebtrac** [comment]
I have figured out why this is happening. My version of QGroundControl was outdated. If your QGroundControl version doesn't say v4.1.3, you should uninstall it and download the latest release from github.

Here is what it should look like if you have the right version:
![image](https://user-images.githubusercontent.com/22060606/126700181-408a6121-2e13-4cf8-9ac7-b6546f5af001.png)

Download the latest version from here:

**Comment by serday** [comment]
Thanks, you really helped. I will follow the new versions
