### ISSUE TITLE
STM32H7's PA0 Can not read ADC 

### ISSUE THREAD

**Issue by Abner0907** [PX4/PX4-Autopilot#17953]
@davids5 ,  Now I have a issue about the PA0, I can not read the adc value or read a random value, it will show a random value in PA0/CHANNEL 16 channel when I type `listener adc_report`. I can read the PA1 and PA3's adc value.
The datasheet said it has a PA0_C. I can not confirm whether this is the reason I can not read the adc. Maybe I have config the PA0 wrong? I am very appreciated that you can give me some notes. many thanks.
![Screenshot from 2021-07-20 22-27-21](https://user-images.githubusercontent.com/64906552/126341705-a792cb59-3bf8-415f-980b-b99b87888f27.png)

**BTW:** I have check the hardware. it is ok. And I modify the hardware to PA1. The adc is also ok.

**Comment by davids5** [comment]
Also the schematic would help

**Comment by Abner0907** [comment]
@davids5 Hello, the configure is here: https://github.com/Abner0907/Firmware/tree/taloon1000/H7-v1.12.0-rc1/boards/codev/dp1000-v2

The schematic's link is here: https://github.com/CodevDynamics/Opensource_Hardware/blob/main/DP_FC_SCH.pdf

FYI: In the schematic, I have use the STM32H743VIT6 for the chip is stm32f765vi, I have seen the pin definition is the same.

**Comment by Abner0907** [comment]
@davids5  I can read channel 17 but can not read channel 16. So for hot fix, I jump a line to Channel 17(PA1) The configuration in my code.

**Comment by davids5** [comment]
Stop in the debugger and and look at the GPIOA register set (GPIOA_MODER etal). See if it is still in analog mode? I would bet that something in the config is overwriting it. 

Also you have a CONFIG_ARCH_CHIP_STM32H743II (176 pin) set in the defconfig You would need to check the pinmap and see if it is it the same at the 100 pin part.

**Comment by davids5** [comment]
Also, are the _C pins even bonded out on the V package? 

See my notes about the SYSCFG_PMCR default state.

https://github.com/PX4/PX4-Autopilot/blob/master/boards/px4/fmu-v6x/src/board_config.h#L154-L158

But I do not think it applies in the V package.

**Comment by Abner0907** [comment]
@davids5 
**1:** 
>Also you have a CONFIG_ARCH_CHIP_STM32H743II (176 pin) set in the defconfig You would need to check the pinmap and see if it is it the same at the 100 pin part.

I have seen the definition in the datasheet. I think the pinmap is ok.

![Screenshot from 2021-07-21 21-20-17](https://user-images.githubusercontent.com/64906552/126495472-ebddc986-1219-462f-b397-4e44547b9dac.png)

2: 
> Also, are the _C pins even bonded out on the V package?

Yes, I also think the _C pins is not on the V package.

3: 
> See my notes about the SYSCFG_PMCR default state.

I have read this register's value. The value is 0x3000000.

**Comment by davids5** [comment]
@Abner0907 What do the GPIO regs show?

**Comment by Abner0907** [comment]
@davids5 
I add a 6s battery and I measured it, the voltage is 25.3v.
The PA0 gpio's pin will show a random value between 6500-8500, the value will change all the time.

![Screenshot from 2021-07-21 21-45-39](https://user-images.githubusercontent.com/64906552/126499136-25ea06d7-5632-4451-bc17-8e0664cd9916.png)

**Comment by Abner0907** [comment]
My real voltage now is 22.03v. What is battery show is:
![Screenshot from 2021-07-21 21-51-31](https://user-images.githubusercontent.com/64906552/126500081-b664d85b-4344-4dcb-ba32-a0b3f911044b.png)

**Comment by davids5** [comment]
dump the value in GPIOA MODER. Is is set to default? Check the GPIOA AFRL

![image](https://user-images.githubusercontent.com/1945821/126500309-e8964941-9cf4-4c34-b7c8-e9fd45120514.png)

**Comment by Abner0907** [comment]
@davids5 
J-Link>mem32 0x58020020 1    (GPIOA AFRL)
58020020 = 55500000 

J-Link>mem32 0x58020000 1 (GPIOA MODER)
58020000 = 6A83A9FC

**Comment by Abner0907** [comment]
@davids5 
Just now I have modify the GPIOA MODER's value to 6A83A9FF. The value can be detected correctly.
So the PA0's mode is be modified or changed by somewhere?

**Comment by davids5** [comment]
Set a HW breakpoint on writes to MODER, then look up the stack.

PA maps to 00 and so does Pin 0 So it  anything that is broken passing a 0 to GPIO config can overwrite.  PA0...fun....fun...fun :)

**Comment by Abner0907** [comment]
@davids5 
Interesting, Each time when I run this line, the `GPIOA->MODER->MODER0[1:0]` will change from '0b11' to `ob00`
![Screenshot from 2021-07-22 12-14-30](https://user-images.githubusercontent.com/64906552/126589210-f7c36329-aeed-4351-a327-dba0326c873f.png)

When I comment out this line, the register's value will not change. 

It seems that `(GPIO_OTGFS_VBUS & GPIO_PUPD_MASK) | GPIO_PULLDOWN)` remap a wrong pin/input ?

**Comment by Abner0907** [comment]
@davids5 
Hi, I found the reason, I have wrong configure the usb. define the vbus as below:
```
#define GPIO_OTGFS_VBUS         /* PA9 */ (GPIO_INPUT|GPIO_PULLDOWN|GPIO_SPEED_100MHz|GPIO_PORTA|GPIO_PIN9)
```
I configured it as
```
	// stm32_configgpio((GPIO_OTGFS_VBUS & GPIO_PUPD_MASK) | GPIO_PULLDOWN);
```
It should be configured as:
```
stm32_configgpio(GPIO_OTGFS_VBUS);

```

**Comment by Abner0907** [comment]
@davids5 many thanks you for your help. It is very usefully.
