### ISSUE TITLE
vehicle_local_position.z return 0 in HITL as global_local_alt0 is reinited

### ISSUE THREAD

**Issue by Ankur1014** [PX4/PX4-Autopilot#17977]
z in vehicle_local_position return 0 in HITL mode global_local_alt0 is reinited everytime while decoding HIL_STATE_QUATERNION.

PX4 Firmware: v1.12.0

I was running HITL simulation after upgrading my firmware when I discovered that z is always return 0 in vehicle_local_position. I debugged this issue and found that in mavlink_receiver.cpp while parsing HIL_STATE_QUATERNION in handle_message_hil_state_quaternion, the reference altitude global_local_alt0 is reinited everytime. (line no 2571 in [mavlink_receiver.cpp ](https://github.com/PX4/PX4-Autopilot/blob/v1.12.0/src/modules/mavlink/mavlink_receiver.cpp#L2571))

This bug seems to have to have crept in [this ](https://github.com/PX4/PX4-Autopilot/commit/263b00b65fc89c7fd9383f0364760fceb15ea12a#diff-22f2d2347fbee4247ef71142274d558334f8991fb89dca50f7505ba05bf9873f)commit

**Comment by dagar** [comment]
Please try https://github.com/PX4/PX4-Autopilot/pull/18010
