### ISSUE TITLE
Hardfault on FMUK66 with tarket nxp_fmuk66-v3_socketcan

### ISSUE THREAD

**Issue by dk7xe** [PX4/PX4-Autopilot#18014]
**Describe the bug**
I'm periodically getting a hardfault on FMUK66

**To Reproduce**
1. compile current master for target nxp_fmuk66-v3_socketcan
2. update FMUK66_v3 with fmuk66-v3_socketcan build
3. Power cycle FMU

**Expected behavior**
Normal operation

**Log Files and Screenshots**
![grafik](https://user-images.githubusercontent.com/3907200/127842829-1f08ac1a-ed2e-464b-a76e-b274e54c68cf.png)
full hardfaul message:
[FMUK66_hardfault.txt](https://github.com/PX4/PX4-Autopilot/files/6916049/FMUK66_hardfault.txt)

```
nsh> ver all
HW arch: NXP_FMUK66_V3
FW git-hash: 607be59fd5b47160326052dea8eea7edc7619d66
FW version: 1.12.0 0 (17563648)
FW git-branch: master
OS: NuttX
OS version: Release 10.0.0 (167772415)
OS git-hash: eeaa803749e44e1b233cf35964f588f57777833c
Build datetime: Aug  2 2021 10:06:00
Build uri: localhost
Toolchain: GNU GCC, 9.3.1 20200408 (release)
PX4GUID: 0003000dffffffffffff4e4555526005002c
MCU: Kinetis K66, rev. 8
nsh>
```

**Comment by dk7xe** [comment]
@dagar @davids5

**Comment by davids5** [comment]
@dk7xe  would you please test https://github.com/PX4/PX4-Autopilot/pull/18017

It fixes a bad stop but there is still massive leaking.

Also, please list what HW is connected and command you have issued

**Comment by davids5** [comment]
@dk7xe 

 hmmm.

do you have code on your branch?

I can not check out that hash:
```
` git checkout 607be59fd5b47160326052dea8eea7edc7619d66
fatal: reference is not a tree: 607be59fd5b47160326052dea8eea7edc7619d66`
```

**Comment by dk7xe** [comment]
Hi @davids5 
since #18017 was merged to master i tested a fresh master built.
Now the hardfault comes when i arm the rover during that try.
[FMUK66_hardfault_202108091055.txt](https://github.com/PX4/PX4-Autopilot/files/6953136/FMUK66_hardfault_202108091055.txt)

Afterwards the hardfault came at the moment of home position set.

**Comment by davids5** [comment]
Hi @Gerald I am going to need some preproduces help on the HF.
```
HW arch: NXP_FMUK66_V3
FW git-hash: e9a21ee9110d3d25b1d330c3967c79d409da51a3
FW version: 1.13.0 40 (17629248)
FW git-branch: master
```
Is not PX4 master. Can you check your remote

This is PX4
```
FW git-hash: 11480cdbc7cee0ee0c05098555a912d1dfa5d357
FW version: 1.12.0 0 (17563648)
FW git-branch: master
OS: NuttX
OS version: 0.0.0 0 (0)
OS git-hash: eeaa803749e44e1b233cf35964f588f57777833c
Build datetime: Aug  9 2021 13:20:59
```
Maybe we can work thought it on a call. I am going to need the params set and commands that are causing the fault.
