### ISSUE TITLE
FMUv5X incorrect rotation when calibrating

### ISSUE THREAD

**Issue by mrpollo** [PX4/PX4-Autopilot#18029]
When calibrating Holybro FMUv5X with a Holybro GPS using v1.12, the GPS reports incorrect mag #17765, this issue was initially reported by Farhang.

<img width="1921" alt="Screen Shot 2021-08-05 at 10 09 25 AM" src="https://user-images.githubusercontent.com/317648/128392841-c62f7e17-9c9a-4b8d-b389-840148581900.png">
<img width="1923" alt="Screen Shot 2021-08-05 at 10 08 43 AM" src="https://user-images.githubusercontent.com/317648/128392852-92209ecf-c987-4b57-b745-5178c815766d.png">

https://user-images.githubusercontent.com/317648/128392759-f6c12f62-91cf-4d9b-acc6-e57cdc125ecf.mp4

**Comment by mrpollo** [comment]
cc @davids5

**Comment by dagar** [comment]
https://github.com/PX4/PX4-Autopilot/blob/a6d88cad18a52c39c9baf46e7a4ebf953e0293a3/boards/px4/fmu-v5/init/rc.board_sensors#L24-L25

**Comment by davids5** [comment]
fixed on master by https://github.com/PX4/PX4-Autopilot/pull/18069
