### ISSUE TITLE
QGC when Virtual Joystick enabled FMU goes to Fail Safe connect on USB

### ISSUE THREAD

**Issue by davids5** [PX4/PX4-Autopilot#18054]
QGC when Virtual Joystick enabled FMU goes to Fail Safe on connect USB.

Set the check box.

Plug in the FMU - 10-30 seconds it will failsafe

![image](https://user-images.githubusercontent.com/1945821/129064162-0c75ca07-cfd0-4500-bc0f-cdea9cbb9c56.png)

**Comment by davids5** [comment]
https://review.px4.io/plot_app?log=3e5178ea-bba4-4666-a499-3b64bb037419

**Comment by taileron** [comment]
I believe that since CBRK_USB_CHK = 197848 was introduced, it is the only way to bypass that.
