### ISSUE TITLE
Gazebo Gimbal: Not working

### ISSUE THREAD

**Issue by tawfiq1200** [PX4/PX4-Autopilot#18063]
Gazebo gimbal is not responding to vmount commands or to the QGround Controller. [This](https://docs.px4.io/master/en/advanced/gimbal_control.html) is the documentation for the gimbal control using commands. The gimbal does not rotate when the commands are executed in the terminal and it also does not rotate when I set pitch and yaw to a certain degree from the QGC.
![Screenshot from 2021-08-11 22-49-40](https://user-images.githubusercontent.com/14095396/129222093-aa59dc87-05aa-4059-94d9-04797a3b53c3.png) The attached screenshot shows that when I run a mission from QGround control, the roll, pitch and yaw stays 0. 

I built PX4 from [this](https://docs.px4.io/master/en/dev_setup/building_px4.html) 

From this [issue](https://github.com/PX4/PX4-Autopilot/issues/8599), it seems that it could be a plugin issue, but not sure what could go wrong.

**Comment by tawfiq1200** [comment]
It seems like the gimbal controller topic is not publishing:

[Err] [JointControlWidget.cc:393] Error advertising topic [/data://world/default/model/typhoon_h480/plugin/gimbal_controller/joint_cmd]

**Comment by Jaeyoung-Lim** [comment]
I have just tested the gimbal on the typhoon h480, and setting ROI through QGC is fully functional.

@tawfiq1200 Could you provide the exact commands you were trying to run, and the expected behavior of the commands?

**Comment by tawfiq1200** [comment]
Yes, 
commander takeoff
vmount test yaw (30, 120, etc.)

You can see from the screenshot that the gimbal is not moving.
![120 degree yaw](https://user-images.githubusercontent.com/14095396/129369535-0b38a8fc-a2b3-4ef2-8736-74338c7ad727.png)

**Comment by tawfiq1200** [comment]
@Jaeyoung-Lim The drone is armed as seen in the screenshot while the gimbal is not moving.

**Comment by tawfiq1200** [comment]
ROI is indeed working with QGC but not the vmount commands.

**Comment by Jaeyoung-Lim** [comment]
@tawfiq1200 Which vmount command are you running?

**Comment by tawfiq1200** [comment]
@Jaeyoung-Lim 
vmount stop
vmount test yaw 30

**Comment by tawfiq1200** [comment]
Since QGC is working, it is not a plugin issue so I am closing the issue though updating the PX4 doc for vmount commands will be good.
