### ISSUE TITLE
Plane: lastest master code,:cuav v5(i2c2) nora(i2c3) can't read i2c airspeed sensors

### ISSUE THREAD

**Issue by gitfishup** [PX4/PX4-Autopilot#18090]
**Describe the bug**
I use the lastest master code (29616ec387b97be3a384e1b35d5306de1b6c6c2a) ，but the flight controller 's i2c interface can't read airspeed sensor. The following is the output ：
 [airspeed_selector] No airspeed sensor detected. Switch to non-airspeed mode.

However, if i use the firmware of stable release v1.12.1, it works.

**Comment by dagar** [comment]
Currently in master you have to manually enable these sensors now. For example set `SENS_EN_MS4525 1`. https://github.com/PX4/PX4-Autopilot/pull/17810

This was done to prevent false positives at startup with sensors that have overlapping I2C addresses and no other identifier internally (eg ms5611 and ms4525, etc).

**Comment by gitfishup** [comment]
Thanks!
