### ISSUE TITLE
QGC:Parameters: abnormal display

### ISSUE THREAD

**Issue by gitfishup** [PX4/PX4-Autopilot#18095]
**Describe the bug**
![image](https://user-images.githubusercontent.com/69180601/129848759-749d66f7-1cbd-4fea-8935-179d855319be.png)

The QGC version 
![lALPBGY19k_l830xzQGe_414_49](https://user-images.githubusercontent.com/69180601/129848765-a01d52c1-d20c-40a3-8342-fbd5196d5d2d.png)

The version of Firmware of CUAVv5 flight controller:
commit :ff39e27e2d093001e777f48e2e178368c90a9ae5
![image](https://user-images.githubusercontent.com/69180601/129849048-e233721d-ab17-437a-b409-c64f338ceaa1.png)

From this commit , QGC:Parameters: abnormal display

**Comment by dagar** [comment]
Thanks for reporting, I'll try to reproduce.

**Comment by dagar** [comment]
Should be fixed in https://github.com/PX4/PX4-Autopilot/pull/18105.
