### ISSUE TITLE
Can't get Jinja2, toml, or empy to install at all

### ISSUE THREAD

**Issue by HatedFate** [PX4/PX4-Autopilot#18092]
[2/796] Generating mixer_multirotor.generated.h
FAILED: src/lib/mixer/MultirotorMixer/mixer_multirotor.generated.h 
cd /home/kannachan/px4/PX4-Autopilot/build/px4_sitl_default/src/lib/mixer/MultirotorMixer && /usr/bin/python3 /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/tools/px_generate_mixers.py -f /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/dodeca_bottom_cox.toml /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/dodeca_top_cox.toml /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/hex_cox.toml /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/hex_plus.toml /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/hex_t.toml /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/hex_x.toml /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/octa_cox.toml /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/octa_cox_wide.toml /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/octa_plus.toml /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/octa_x.toml /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/quad_deadcat.toml /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/quad_h.toml /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/quad_plus.toml /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/quad_s250aq.toml /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/quad_vtail.toml /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/quad_wide.toml /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/quad_x_cw.toml /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/quad_x.toml /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/quad_x_pusher.toml /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/quad_y.toml /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/tri_y.toml /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/twin_engine.toml -o mixer_multirotor.generated.h
Failed to import toml: No module named 'toml'

You may need to install it using:
    pip3 install --user toml

[3/796] Generating mixer_multirotor_normalized.generated.h
FAILED: src/lib/mixer/MultirotorMixer/mixer_multirotor_normalized.generated.h 
cd /home/kannachan/px4/PX4-Autopilot/build/px4_sitl_default/src/lib/mixer/MultirotorMixer && /usr/bin/python3 /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/tools/px_generate_mixers.py --normalize -f /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/dodeca_bottom_cox.toml /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/dodeca_top_cox.toml /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/hex_cox.toml /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/hex_plus.toml /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/hex_t.toml /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/hex_x.toml /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/octa_cox.toml /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/octa_cox_wide.toml /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/octa_plus.toml /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/octa_x.toml /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/quad_deadcat.toml /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/quad_h.toml /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/quad_plus.toml /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/quad_s250aq.toml /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/quad_vtail.toml /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/quad_wide.toml /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/quad_x_cw.toml /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/quad_x.toml /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/quad_x_pusher.toml /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/quad_y.toml /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/tri_y.toml /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/twin_engine.toml -o mixer_multirotor_normalized.generated.h
Failed to import toml: No module named 'toml'

You may need to install it using:
    pip3 install --user toml

[4/796] Generating mixer_multirotor_6dof.generated.h
FAILED: src/lib/mixer/MultirotorMixer/mixer_multirotor_6dof.generated.h 
cd /home/kannachan/px4/PX4-Autopilot/build/px4_sitl_default/src/lib/mixer/MultirotorMixer && /usr/bin/python3 /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/tools/px_generate_mixers.py --sixdof -f /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/dodeca_bottom_cox.toml /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/dodeca_top_cox.toml /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/hex_cox.toml /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/hex_plus.toml /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/hex_t.toml /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/hex_x.toml /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/octa_cox.toml /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/octa_cox_wide.toml /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/octa_plus.toml /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/octa_x.toml /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/quad_deadcat.toml /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/quad_h.toml /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/quad_plus.toml /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/quad_s250aq.toml /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/quad_vtail.toml /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/quad_wide.toml /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/quad_x_cw.toml /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/quad_x.toml /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/quad_x_pusher.toml /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/quad_y.toml /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/tri_y.toml /home/kannachan/px4/PX4-Autopilot/src/lib/mixer/MultirotorMixer/geometries/twin_engine.toml -o mixer_multirotor_6dof.generated.h
Failed to import toml: No module named 'toml'

You may need to install it using:
    pip3 install --user toml

[5/796] Generating uORB topic headers
FAILED: uORB/topics/uORBTopics.hpp uORB/topics/actuator_armed.h uORB/topics/actuator_controls.h uORB/topics/actuator_outputs.h uORB/topics/adc_report.h uORB/topics/airspeed.h uORB/topics/airspeed_validated.h uORB/topics/airspeed_wind.h uORB/topics/battery_status.h uORB/topics/camera_capture.h uORB/topics/camera_status.h uORB/topics/camera_trigger.h uORB/topics/cellular_status.h uORB/topics/collision_constraints.h uORB/topics/collision_report.h uORB/topics/commander_state.h uORB/topics/control_allocator_status.h uORB/topics/cpuload.h uORB/topics/debug_array.h uORB/topics/debug_key_value.h uORB/topics/debug_value.h uORB/topics/debug_vect.h uORB/topics/differential_pressure.h uORB/topics/distance_sensor.h uORB/topics/ekf2_timestamps.h uORB/topics/ekf_gps_drift.h uORB/topics/esc_report.h uORB/topics/esc_status.h uORB/topics/estimator_baro_bias.h uORB/topics/estimator_event_flags.h uORB/topics/estimator_innovations.h uORB/topics/estimator_optical_flow_vel.h uORB/topics/estimator_selector_status.h uORB/topics/estimator_sensor_bias.h uORB/topics/estimator_states.h uORB/topics/estimator_status.h uORB/topics/estimator_status_flags.h uORB/topics/event.h uORB/topics/follow_target.h uORB/topics/generator_status.h uORB/topics/geofence_result.h uORB/topics/gimbal_device_attitude_status.h uORB/topics/gimbal_device_information.h uORB/topics/gimbal_device_set_attitude.h uORB/topics/gimbal_manager_information.h uORB/topics/gimbal_manager_set_attitude.h uORB/topics/gimbal_manager_set_manual_control.h uORB/topics/gimbal_manager_status.h uORB/topics/gps_dump.h uORB/topics/gps_inject_data.h uORB/topics/heater_status.h uORB/topics/home_position.h uORB/topics/hover_thrust_estimate.h uORB/topics/input_rc.h uORB/topics/internal_combustion_engine_status.h uORB/topics/iridiumsbd_status.h uORB/topics/irlock_report.h uORB/topics/landing_gear.h uORB/topics/landing_target_innovations.h uORB/topics/landing_target_pose.h uORB/topics/led_control.h uORB/topics/log_message.h uORB/topics/logger_status.h uORB/topics/mag_worker_data.h uORB/topics/manual_control_setpoint.h uORB/topics/manual_control_switches.h uORB/topics/mavlink_log.h uORB/topics/mission.h uORB/topics/mission_result.h uORB/topics/mount_orientation.h uORB/topics/multirotor_motor_limits.h uORB/topics/navigator_mission_item.h uORB/topics/obstacle_distance.h uORB/topics/offboard_control_mode.h uORB/topics/onboard_computer_status.h uORB/topics/optical_flow.h uORB/topics/orb_test.h uORB/topics/orb_test_large.h uORB/topics/orb_test_medium.h uORB/topics/orbit_status.h uORB/topics/parameter_update.h uORB/topics/ping.h uORB/topics/position_controller_landing_status.h uORB/topics/position_controller_status.h uORB/topics/position_setpoint.h uORB/topics/position_setpoint_triplet.h uORB/topics/power_button_state.h uORB/topics/power_monitor.h uORB/topics/pwm_input.h uORB/topics/px4io_status.h uORB/topics/radio_status.h uORB/topics/rate_ctrl_status.h uORB/topics/rc_channels.h uORB/topics/rc_parameter_map.h uORB/topics/rpm.h uORB/topics/rtl_flight_time.h uORB/topics/safety.h uORB/topics/satellite_info.h uORB/topics/sensor_accel.h uORB/topics/sensor_accel_fifo.h uORB/topics/sensor_baro.h uORB/topics/sensor_combined.h uORB/topics/sensor_correction.h uORB/topics/sensor_gps.h uORB/topics/sensor_gyro.h uORB/topics/sensor_gyro_fft.h uORB/topics/sensor_gyro_fifo.h uORB/topics/sensor_mag.h uORB/topics/sensor_preflight_mag.h uORB/topics/sensor_selection.h uORB/topics/sensors_status_imu.h uORB/topics/system_power.h uORB/topics/takeoff_status.h uORB/topics/task_stack_info.h uORB/topics/tecs_status.h uORB/topics/telemetry_status.h uORB/topics/test_motor.h uORB/topics/timesync.h uORB/topics/timesync_status.h uORB/topics/trajectory_bezier.h uORB/topics/trajectory_waypoint.h uORB/topics/transponder_report.h uORB/topics/tune_control.h uORB/topics/uavcan_parameter_request.h uORB/topics/uavcan_parameter_value.h uORB/topics/ulog_stream.h uORB/topics/ulog_stream_ack.h uORB/topics/vehicle_acceleration.h uORB/topics/vehicle_actuator_setpoint.h uORB/topics/vehicle_air_data.h uORB/topics/vehicle_angular_acceleration.h uORB/topics/vehicle_angular_acceleration_setpoint.h uORB/topics/vehicle_angular_velocity.h uORB/topics/vehicle_attitude.h uORB/topics/vehicle_attitude_setpoint.h uORB/topics/vehicle_command.h uORB/topics/vehicle_command_ack.h uORB/topics/vehicle_constraints.h uORB/topics/vehicle_control_mode.h uORB/topics/vehicle_global_position.h uORB/topics/vehicle_gps_position.h uORB/topics/vehicle_imu.h uORB/topics/vehicle_imu_status.h uORB/topics/vehicle_land_detected.h uORB/topics/vehicle_local_position.h uORB/topics/vehicle_local_position_setpoint.h uORB/topics/vehicle_magnetometer.h uORB/topics/vehicle_odometry.h uORB/topics/vehicle_rates_setpoint.h uORB/topics/vehicle_roi.h uORB/topics/vehicle_status.h uORB/topics/vehicle_status_flags.h uORB/topics/vehicle_thrust_setpoint.h uORB/topics/vehicle_torque_setpoint.h uORB/topics/vehicle_trajectory_bezier.h uORB/topics/vehicle_trajectory_waypoint.h uORB/topics/vtol_vehicle_status.h uORB/topics/wheel_encoders.h uORB/topics/wind.h uORB/topics/yaw_estimator_status.h 
cd /home/kannachan/px4/PX4-Autopilot/msg && /usr/bin/python3 tools/px_generate_uorb_topic_files.py --headers -f /home/kannachan/px4/PX4-Autopilot/msg/actuator_armed.msg /home/kannachan/px4/PX4-Autopilot/msg/actuator_controls.msg /home/kannachan/px4/PX4-Autopilot/msg/actuator_outputs.msg /home/kannachan/px4/PX4-Autopilot/msg/adc_report.msg /home/kannachan/px4/PX4-Autopilot/msg/airspeed.msg /home/kannachan/px4/PX4-Autopilot/msg/airspeed_validated.msg /home/kannachan/px4/PX4-Autopilot/msg/airspeed_wind.msg /home/kannachan/px4/PX4-Autopilot/msg/battery_status.msg /home/kannachan/px4/PX4-Autopilot/msg/camera_capture.msg /home/kannachan/px4/PX4-Autopilot/msg/camera_status.msg /home/kannachan/px4/PX4-Autopilot/msg/camera_trigger.msg /home/kannachan/px4/PX4-Autopilot/msg/cellular_status.msg /home/kannachan/px4/PX4-Autopilot/msg/collision_constraints.msg /home/kannachan/px4/PX4-Autopilot/msg/collision_report.msg /home/kannachan/px4/PX4-Autopilot/msg/commander_state.msg /home/kannachan/px4/PX4-Autopilot/msg/control_allocator_status.msg /home/kannachan/px4/PX4-Autopilot/msg/cpuload.msg /home/kannachan/px4/PX4-Autopilot/msg/debug_array.msg /home/kannachan/px4/PX4-Autopilot/msg/debug_key_value.msg /home/kannachan/px4/PX4-Autopilot/msg/debug_value.msg /home/kannachan/px4/PX4-Autopilot/msg/debug_vect.msg /home/kannachan/px4/PX4-Autopilot/msg/differential_pressure.msg /home/kannachan/px4/PX4-Autopilot/msg/distance_sensor.msg /home/kannachan/px4/PX4-Autopilot/msg/ekf2_timestamps.msg /home/kannachan/px4/PX4-Autopilot/msg/ekf_gps_drift.msg /home/kannachan/px4/PX4-Autopilot/msg/esc_report.msg /home/kannachan/px4/PX4-Autopilot/msg/esc_status.msg /home/kannachan/px4/PX4-Autopilot/msg/estimator_baro_bias.msg /home/kannachan/px4/PX4-Autopilot/msg/estimator_event_flags.msg /home/kannachan/px4/PX4-Autopilot/msg/estimator_innovations.msg /home/kannachan/px4/PX4-Autopilot/msg/estimator_optical_flow_vel.msg /home/kannachan/px4/PX4-Autopilot/msg/estimator_selector_status.msg /home/kannachan/px4/PX4-Autopilot/msg/estimator_sensor_bias.msg /home/kannachan/px4/PX4-Autopilot/msg/estimator_states.msg /home/kannachan/px4/PX4-Autopilot/msg/estimator_status.msg /home/kannachan/px4/PX4-Autopilot/msg/estimator_status_flags.msg /home/kannachan/px4/PX4-Autopilot/msg/event.msg /home/kannachan/px4/PX4-Autopilot/msg/follow_target.msg /home/kannachan/px4/PX4-Autopilot/msg/generator_status.msg /home/kannachan/px4/PX4-Autopilot/msg/geofence_result.msg /home/kannachan/px4/PX4-Autopilot/msg/gimbal_device_attitude_status.msg /home/kannachan/px4/PX4-Autopilot/msg/gimbal_device_information.msg /home/kannachan/px4/PX4-Autopilot/msg/gimbal_device_set_attitude.msg /home/kannachan/px4/PX4-Autopilot/msg/gimbal_manager_information.msg /home/kannachan/px4/PX4-Autopilot/msg/gimbal_manager_set_attitude.msg /home/kannachan/px4/PX4-Autopilot/msg/gimbal_manager_set_manual_control.msg /home/kannachan/px4/PX4-Autopilot/msg/gimbal_manager_status.msg /home/kannachan/px4/PX4-Autopilot/msg/gps_dump.msg /home/kannachan/px4/PX4-Autopilot/msg/gps_inject_data.msg /home/kannachan/px4/PX4-Autopilot/msg/heater_status.msg /home/kannachan/px4/PX4-Autopilot/msg/home_position.msg /home/kannachan/px4/PX4-Autopilot/msg/hover_thrust_estimate.msg /home/kannachan/px4/PX4-Autopilot/msg/input_rc.msg /home/kannachan/px4/PX4-Autopilot/msg/internal_combustion_engine_status.msg /home/kannachan/px4/PX4-Autopilot/msg/iridiumsbd_status.msg /home/kannachan/px4/PX4-Autopilot/msg/irlock_report.msg /home/kannachan/px4/PX4-Autopilot/msg/landing_gear.msg /home/kannachan/px4/PX4-Autopilot/msg/landing_target_innovations.msg /home/kannachan/px4/PX4-Autopilot/msg/landing_target_pose.msg /home/kannachan/px4/PX4-Autopilot/msg/led_control.msg /home/kannachan/px4/PX4-Autopilot/msg/log_message.msg /home/kannachan/px4/PX4-Autopilot/msg/logger_status.msg /home/kannachan/px4/PX4-Autopilot/msg/mag_worker_data.msg /home/kannachan/px4/PX4-Autopilot/msg/manual_control_setpoint.msg /home/kannachan/px4/PX4-Autopilot/msg/manual_control_switches.msg /home/kannachan/px4/PX4-Autopilot/msg/mavlink_log.msg /home/kannachan/px4/PX4-Autopilot/msg/mission.msg /home/kannachan/px4/PX4-Autopilot/msg/mission_result.msg /home/kannachan/px4/PX4-Autopilot/msg/mount_orientation.msg /home/kannachan/px4/PX4-Autopilot/msg/multirotor_motor_limits.msg /home/kannachan/px4/PX4-Autopilot/msg/navigator_mission_item.msg /home/kannachan/px4/PX4-Autopilot/msg/obstacle_distance.msg /home/kannachan/px4/PX4-Autopilot/msg/offboard_control_mode.msg /home/kannachan/px4/PX4-Autopilot/msg/onboard_computer_status.msg /home/kannachan/px4/PX4-Autopilot/msg/optical_flow.msg /home/kannachan/px4/PX4-Autopilot/msg/orb_test.msg /home/kannachan/px4/PX4-Autopilot/msg/orb_test_large.msg /home/kannachan/px4/PX4-Autopilot/msg/orb_test_medium.msg /home/kannachan/px4/PX4-Autopilot/msg/orbit_status.msg /home/kannachan/px4/PX4-Autopilot/msg/parameter_update.msg /home/kannachan/px4/PX4-Autopilot/msg/ping.msg /home/kannachan/px4/PX4-Autopilot/msg/position_controller_landing_status.msg /home/kannachan/px4/PX4-Autopilot/msg/position_controller_status.msg /home/kannachan/px4/PX4-Autopilot/msg/position_setpoint.msg /home/kannachan/px4/PX4-Autopilot/msg/position_setpoint_triplet.msg /home/kannachan/px4/PX4-Autopilot/msg/power_button_state.msg /home/kannachan/px4/PX4-Autopilot/msg/power_monitor.msg /home/kannachan/px4/PX4-Autopilot/msg/pwm_input.msg /home/kannachan/px4/PX4-Autopilot/msg/px4io_status.msg /home/kannachan/px4/PX4-Autopilot/msg/radio_status.msg /home/kannachan/px4/PX4-Autopilot/msg/rate_ctrl_status.msg /home/kannachan/px4/PX4-Autopilot/msg/rc_channels.msg /home/kannachan/px4/PX4-Autopilot/msg/rc_parameter_map.msg /home/kannachan/px4/PX4-Autopilot/msg/rpm.msg /home/kannachan/px4/PX4-Autopilot/msg/rtl_flight_time.msg /home/kannachan/px4/PX4-Autopilot/msg/safety.msg /home/kannachan/px4/PX4-Autopilot/msg/satellite_info.msg /home/kannachan/px4/PX4-Autopilot/msg/sensor_accel.msg /home/kannachan/px4/PX4-Autopilot/msg/sensor_accel_fifo.msg /home/kannachan/px4/PX4-Autopilot/msg/sensor_baro.msg /home/kannachan/px4/PX4-Autopilot/msg/sensor_combined.msg /home/kannachan/px4/PX4-Autopilot/msg/sensor_correction.msg /home/kannachan/px4/PX4-Autopilot/msg/sensor_gps.msg /home/kannachan/px4/PX4-Autopilot/msg/sensor_gyro.msg /home/kannachan/px4/PX4-Autopilot/msg/sensor_gyro_fft.msg /home/kannachan/px4/PX4-Autopilot/msg/sensor_gyro_fifo.msg /home/kannachan/px4/PX4-Autopilot/msg/sensor_mag.msg /home/kannachan/px4/PX4-Autopilot/msg/sensor_preflight_mag.msg /home/kannachan/px4/PX4-Autopilot/msg/sensor_selection.msg /home/kannachan/px4/PX4-Autopilot/msg/sensors_status_imu.msg /home/kannachan/px4/PX4-Autopilot/msg/system_power.msg /home/kannachan/px4/PX4-Autopilot/msg/takeoff_status.msg /home/kannachan/px4/PX4-Autopilot/msg/task_stack_info.msg /home/kannachan/px4/PX4-Autopilot/msg/tecs_status.msg /home/kannachan/px4/PX4-Autopilot/msg/telemetry_status.msg /home/kannachan/px4/PX4-Autopilot/msg/test_motor.msg /home/kannachan/px4/PX4-Autopilot/msg/timesync.msg /home/kannachan/px4/PX4-Autopilot/msg/timesync_status.msg /home/kannachan/px4/PX4-Autopilot/msg/trajectory_bezier.msg /home/kannachan/px4/PX4-Autopilot/msg/trajectory_waypoint.msg /home/kannachan/px4/PX4-Autopilot/msg/transponder_report.msg /home/kannachan/px4/PX4-Autopilot/msg/tune_control.msg /home/kannachan/px4/PX4-Autopilot/msg/uavcan_parameter_request.msg /home/kannachan/px4/PX4-Autopilot/msg/uavcan_parameter_value.msg /home/kannachan/px4/PX4-Autopilot/msg/ulog_stream.msg /home/kannachan/px4/PX4-Autopilot/msg/ulog_stream_ack.msg /home/kannachan/px4/PX4-Autopilot/msg/vehicle_acceleration.msg /home/kannachan/px4/PX4-Autopilot/msg/vehicle_actuator_setpoint.msg /home/kannachan/px4/PX4-Autopilot/msg/vehicle_air_data.msg /home/kannachan/px4/PX4-Autopilot/msg/vehicle_angular_acceleration.msg /home/kannachan/px4/PX4-Autopilot/msg/vehicle_angular_acceleration_setpoint.msg /home/kannachan/px4/PX4-Autopilot/msg/vehicle_angular_velocity.msg /home/kannachan/px4/PX4-Autopilot/msg/vehicle_attitude.msg /home/kannachan/px4/PX4-Autopilot/msg/vehicle_attitude_setpoint.msg /home/kannachan/px4/PX4-Autopilot/msg/vehicle_command.msg /home/kannachan/px4/PX4-Autopilot/msg/vehicle_command_ack.msg /home/kannachan/px4/PX4-Autopilot/msg/vehicle_constraints.msg /home/kannachan/px4/PX4-Autopilot/msg/vehicle_control_mode.msg /home/kannachan/px4/PX4-Autopilot/msg/vehicle_global_position.msg /home/kannachan/px4/PX4-Autopilot/msg/vehicle_gps_position.msg /home/kannachan/px4/PX4-Autopilot/msg/vehicle_imu.msg /home/kannachan/px4/PX4-Autopilot/msg/vehicle_imu_status.msg /home/kannachan/px4/PX4-Autopilot/msg/vehicle_land_detected.msg /home/kannachan/px4/PX4-Autopilot/msg/vehicle_local_position.msg /home/kannachan/px4/PX4-Autopilot/msg/vehicle_local_position_setpoint.msg /home/kannachan/px4/PX4-Autopilot/msg/vehicle_magnetometer.msg /home/kannachan/px4/PX4-Autopilot/msg/vehicle_odometry.msg /home/kannachan/px4/PX4-Autopilot/msg/vehicle_rates_setpoint.msg /home/kannachan/px4/PX4-Autopilot/msg/vehicle_roi.msg /home/kannachan/px4/PX4-Autopilot/msg/vehicle_status.msg /home/kannachan/px4/PX4-Autopilot/msg/vehicle_status_flags.msg /home/kannachan/px4/PX4-Autopilot/msg/vehicle_thrust_setpoint.msg /home/kannachan/px4/PX4-Autopilot/msg/vehicle_torque_setpoint.msg /home/kannachan/px4/PX4-Autopilot/msg/vehicle_trajectory_bezier.msg /home/kannachan/px4/PX4-Autopilot/msg/vehicle_trajectory_waypoint.msg /home/kannachan/px4/PX4-Autopilot/msg/vtol_vehicle_status.msg /home/kannachan/px4/PX4-Autopilot/msg/wheel_encoders.msg /home/kannachan/px4/PX4-Autopilot/msg/wind.msg /home/kannachan/px4/PX4-Autopilot/msg/yaw_estimator_status.msg -i /home/kannachan/px4/PX4-Autopilot/msg -o /home/kannachan/px4/PX4-Autopilot/build/px4_sitl_default/uORB/topics -e templates/uorb -t /home/kannachan/px4/PX4-Autopilot/build/px4_sitl_default/msg/tmp/headers -q
Failed to import em: No module named 'em'

You may need to install it using:
    pip3 install --user empy

[6/796] Generating serial_params.c
FAILED: generated_params/serial_params.c 
cd /home/kannachan/px4/PX4-Autopilot/build/px4_sitl_default/src/lib/parameters && /usr/bin/cmake -E make_directory /home/kannachan/px4/PX4-Autopilot/build/px4_sitl_default/generated_params && /usr/bin/python3 /home/kannachan/px4/PX4-Autopilot/Tools/serial/generate_config.py --params-file /home/kannachan/px4/PX4-Autopilot/build/px4_sitl_default/generated_params/serial_params.c --serial-ports --ethernet --config-files /home/kannachan/px4/PX4-Autopilot/src/lib/battery/module.yaml /home/kannachan/px4/PX4-Autopilot/src/lib/pwm/pwm_main_params.yaml /home/kannachan/px4/PX4-Autopilot/src/lib/pwm/pwm_aux_params.yaml /home/kannachan/px4/PX4-Autopilot/src/lib/pwm/pwm_extra_params.yaml /home/kannachan/px4/PX4-Autopilot/src/drivers/gps/module.yaml /home/kannachan/px4/PX4-Autopilot/src/modules/mavlink/module.yaml
Failed to import jinja2: No module named 'jinja2'

You may need to install it using:
    pip3 install --user jinja2

[7/796] Generating px4 event header file
FAILED: events/events_generated.h 
cd /home/kannachan/px4/PX4-Autopilot/src/lib/events && /usr/bin/cmake -E make_directory /home/kannachan/px4/PX4-Autopilot/build/px4_sitl_default/events && /usr/bin/python3 libevents/scripts/generate.py --template libevents/libs/cpp/templates/events_generated.h.jinja --output /home/kannachan/px4/PX4-Autopilot/build/px4_sitl_default/events /home/kannachan/px4/PX4-Autopilot/build/px4_sitl_default/events/common_with_enums.json
Failed to import jinja2: No module named 'jinja2'

You may need to install it using:
    pip3 install --user jinja2

[8/796] Generating Flight Tasks
FAILED: src/modules/flight_mode_manager/FlightTasks_generated.hpp src/modules/flight_mode_manager/FlightTasks_generated.cpp 
cd /home/kannachan/px4/PX4-Autopilot/src/modules/flight_mode_manager && /usr/bin/python3 generate_flight_tasks.py -t AutoFollowMe AutoLineSmoothVel Descend Failsafe ManualAcceleration ManualAltitude ManualAltitudeSmoothVel ManualPosition ManualPositionSmoothVel Transition Orbit -i /home/kannachan/px4/PX4-Autopilot/src/modules/flight_mode_manager/Templates -o /home/kannachan/px4/PX4-Autopilot/build/px4_sitl_default/src/modules/flight_mode_manager -f FlightTasks_generated.hpp FlightTasks_generated.cpp -s Orbit
Traceback (most recent call last):
  File "generate_flight_tasks.py", line 3, in <module>
    import em
ModuleNotFoundError: No module named 'em'
ninja: build stopped: subcommand failed.
Makefile:230: recipe for target 'px4_sitl' failed
make: *** [px4_sitl] Error 1 

I'm working in an anaconda environment and I had tried to install jiinja2, toml, and empy but it said it was already installed and met all the requirements. Then, I tried to uninstall all 3 packages and reinstall by typing pip3 install --user jinga2 toml empy. I run sudo make px4_sitl jmavsim again and the same error messages appeared. I uninstall the packages again and try to install it by typing pip install jinja2 toml empy which worked on my other machine but for some reason I still get the same error messages

**Comment by dagar** [comment]
Can you try `make px4_sitl_default install_python_requirements`?

It installs the python requirements within the build with whichever python environment it found.

**Comment by HatedFate** [comment]
> Can you try `make px4_sitl_default install_python_requirements`?
> 
> It installs the python requirements within the build with whichever python environment it found.

[0/1] cd /home/kannachan/px4/PX4-Autopilot/build/px4_sitl_default...nt /home/kannachan/px4/PX4-Autopilot/Tools/setup/requirements.txt
/usr/bin/python3: No module named pip
FAILED: CMakeFiles/install_python_requirements 
cd /home/kannachan/px4/PX4-Autopilot/build/px4_sitl_default && /usr/bin/python3 -m pip install --requirement /home/kannachan/px4/PX4-Autopilot/Tools/setup/requirements.txt
ninja: build stopped: subcommand failed.
Makefile:225: recipe for target 'px4_sitl_default' failed
make: *** [px4_sitl_default] Error 1

This is the error i got from trying to run the command:
sudo make px4_sitl_default install_python_requirements

**Comment by LuoRongLuoRong** [comment]
> Can you try `make px4_sitl_default install_python_requirements`?
> 
> It installs the python requirements within the build with whichever python environment it found.

It works for me! Thanks~
