### ISSUE TITLE
SITL-2 died

### ISSUE THREAD

**Issue by HatedFate** [PX4/PX4-Autopilot#18119]
I downloaded PX4, ROS, and Gazebo 9 according to the documentation provided in:
https://docs.px4.io/master/en/simulation/ros_interface.html

After installing, exporting, and sourcing everything, I'd ran:

`roslaunch px4 posix_sitl.launch
` 

But this returns an error:

`[gazebo-3] process has died [pid 3361, exit code 127, cmd /opt/ros/melodic/lib/gazebo_ros/gzserver -e ode /home/kannachan/Developer/PX4-Autopilot/Tools/sitl_gazebo/worlds/empty.world __name:=gazebo __log:=/home/kannachan/.ros/log/b091d7c0-01fe-11ec-8747-3c58c292baa8/gazebo-3.log].
log file: /home/kannachan/.ros/log/b091d7c0-01fe-11ec-8747-3c58c292baa8/gazebo-3*.log
[gazebo_gui-4] process has died [pid 3373, exit code 127, cmd /opt/ros/melodic/lib/gazebo_ros/gzclient __name:=gazebo_gui __log:=/home/kannachan/.ros/log/b091d7c0-01fe-11ec-8747-3c58c292baa8/gazebo_gui-4.log].
log file: /home/kannachan/.ros/log/b091d7c0-01fe-11ec-8747-3c58c292baa8/gazebo_gui-4*.log
` 

I searched for some answers online ( https://answers.gazebosim.org//question/4153/gazebo-crashes-immediately-using-roslaunch-after-installing-gazebo-ros-packages/ )and was told that I should run:
 
`killall gzserver` 

But there is no processes named gzserver, so the I relaunch px4 and the sitl but still got the same error. I'd noticed that my drivers might be the issue to gazebo dying so I ran:

`sudo apt-get update -y && sudo apt-get upgrade -y && sudo apt autoremove -y`

This worked but it return a new error:

`REQUIRED process [sitl-2] has died!
process has died [pid 16927, exit code 255, cmd /home/kannachan/Developer/PX4-Autopilot/build/px4_sitl_default/bin/px4 /home/kannachan/Developer/PX4-Autopilot/build/px4_sitl_default/etc -s etc/init.d-posix/rcS __name:=sitl __log:=/home/kannachan/.ros/log/f1a14eea-0216-11ec-afec-3c58c292baa8/sitl-2.log].
log file: /home/kannachan/.ros/log/f1a14eea-0216-11ec-afec-3c58c292baa8/sitl-2*.log
`

I am not sure what I did, but now I am having a new error similar to the previous error:

`REQUIRED process [sitl-1] has died!
process has died [pid 2669, exit code 255, cmd /home/kannachan/Developer/PX4-Autopilot/build/px4_sitl_default/bin/px4 /home/kannachan/Developer/PX4-Autopilot/build/px4_sitl_default/etc -s etc/init.d-posix/rcS __name:=sitl __log:=/home/kannachan/.ros/log/f975f502-0217-11ec-afec-3c58c292baa8/sitl-1.log].
log file: /home/kannachan/.ros/log/f975f502-0217-11ec-afec-3c58c292baa8/sitl-1*.log
`

**Comment by codingCoffee** [comment]
@HatedFate were you able to resolve this issue by any chance?

**Comment by HatedFate** [comment]
> @HatedFate were you able to resolve this issue by any chance? 

Sorry for the late response. Yes, the issue did resolved on its own, but I am not entirely sure what happen so it's probably not that big of a deal.
