### ISSUE TITLE
IridiumSBD Driver and Parameters Missing

### ISSUE THREAD

**Issue by SAR-mango** [PX4/PX4-Autopilot#18121]
**Description**
The Iridium SBD section simply does not appear in Parameters in QGC. Searching for any relevant parameters (ISBD_CONFIG, for example) yields no results. Attempts to start the driver through the shell lead to `nsh: iridiumsbd: command not found`.

I have this issue with master, v1.12.1, and v1.12.0. I flashed to a Pixhawk 4 (fmu-v5) board and ensured all parameters were firmware default.

**Modifying `boards/px4/fmu-v5/default.cmake` as described below appears to fix the problem.** I was just messing around and did not expect this to work, and now that it does work, I have no idea why.

Line 52 currently contains:
`telemetry # all available telemetry drivers`
Below line 52 I just added:
`telemetry/iridiumsbd`
After making this change, building, and flashing, the Iridium SBD section appears, the parameters are present, and the driver is functional (confirmed by trying `iridiumsbd status` in the shell).

**To Reproduce**
1. Flash master, v1.12.1, or v1.12.0 to a Pixhawk 4 board. Though it doesn't matter, reset all parameters to firmware default if desired.
2. Open the list of parameters in QGC and search for the Iridium SBD section — it won't be present.
3. Search for relevant parameters such as ISBD_CONFIG — they will not be found.
4. Open the shell (MAVLink Console) in QGC and try iridiumsbd commands such as `iridiumsbd status`. The commands will not be found.

**Expected behavior**
The Iridium SBD section and its parameters should appear in QGC with fmu-v5_default firmware. The driver should also be enabled and working, and commands in the shell should be recognized.

**Log Files and Screenshots**
No flight tests were performed as they are irrelevant to this issue, so there are no logs to provide.

**Not Working (v1.12.1)**
<img width="1672" alt="search_not_present" src="https://user-images.githubusercontent.com/35402904/130336598-1145e337-3652-4e87-afef-0b485d0b40be.png">
<img width="364" alt="param_not_present_1" src="https://user-images.githubusercontent.com/35402904/130336600-99a5e953-fefd-4ae3-8433-d40552360a69.png">
<img width="335" alt="param_not_present_2" src="https://user-images.githubusercontent.com/35402904/130336601-83963e98-1511-4906-a320-99f568d2a0c2.png">
<img width="245" alt="param_not_present_3" src="https://user-images.githubusercontent.com/35402904/130336603-56199de0-423c-4b37-b1a3-3188e6e361ce.png">
<img width="274" alt="param_not_present_4" src="https://user-images.githubusercontent.com/35402904/130336604-aa107f98-a272-4a1f-9c7c-2283bed911e5.png">
<img width="1670" alt="shell_test_fail" src="https://user-images.githubusercontent.com/35402904/130336606-afece6a6-f5ee-4086-8cdb-792998734ce8.png">

**Working (after firmware modification)**
<img width="1675" alt="param_present" src="https://user-images.githubusercontent.com/35402904/130336618-ed3d8683-bd73-4ee2-97be-cca5d9d3a0a4.png">
<img width="1669" alt="shell_test_success" src="https://user-images.githubusercontent.com/35402904/130336620-56322583-cb26-4cce-b13a-b9b2ca88d2f8.png">

**Drone**
Irrelevant, but I have successfully set up PX4 with a large fixed-wing glider. Working on an ultra long range project (solar plane) where satellite might be necessary. I took all the avionics out and they are just on the bench, so a photo of the setup isn't really helpful.

**Additional Context**
Screenshots show when I was testing with Mac, but this problem is present on Windows QGC as well; it shouldn't have anything to do with QGC.

**Comment by dagar** [comment]
The `iridiumsbd` driver was disabled for now due to a number of outstanding issues. I believe in certain situations it was crashing on startup and getting users stuck in a boot loop.

https://github.com/PX4/PX4-Autopilot/pull/17837

**Comment by SAR-mango** [comment]
Right, sorry, I just realized that about an hour ago and was about to close this issue.

I have HW to test with and I have time as well, school starts in two weeks. I enabled the driver and configured it with TELEM2. It did not crash or anything, but the driver was not communicating with the modem. Switched to TELEM1 and it worked perfectly. Should I make a new issue?

**Comment by ryanjAA** [comment]
@SAR-mango do you have a slack account in the px4 workspace? DM me at @ryanjohnston

**Comment by SAR-mango** [comment]
Sorry... not in the PX4 workspace. The invite link seems not to be working.

**Comment by julianoes** [comment]
The IridiumSBD driver can be enabled using KConfig. See https://github.com/PX4/PX4-Autopilot/pull/21105#issuecomment-1429042093 for how it's done.

For instance for Pixhawk 6X the command is: `make px4_fmu-v6x_default boardconfig`, then you select *drivers* -> *Telemetry* -> *iridiumsbd*
