### ISSUE TITLE
uavcan differential pressure sensor filtrated value (LowPassFilter2p) always becomes unstable

### ISSUE THREAD

**Issue by PonomarevDA** [PX4/PX4-Autopilot#18151]
**Describe the bug**
After several minutes of UAVCAN differential pressure sensor usage, his filtrated value always becomes unstable.
Old versions of firmware (I tested `v1.11.0-rc1`) seem to ok.

**To Reproduce**
Connect uavcan differential sensor (it might be just simulated sensor) to an autopilot, wait several minutes depending on publish rate of your sensor and check in console: `listener differential_pressure` or if your vehicle has also barometric sensor, you can check airspeed estimation as a consequence.

**Log Files and Screenshots**
My data from the real sensor looks like that:

![raw_air_data_Screenshot from 2021-08-25 11-19-35](https://user-images.githubusercontent.com/36133264/130928997-c0fa47c4-3cd6-466a-a1fd-8bbc6aa9b75f.png)

First few minutes it's ok. But then it becomes crazy.

For example, at 6 minutes of sensor usage with publish rate 100 hz:
![image](https://user-images.githubusercontent.com/36133264/130930487-e0ab85df-e2f4-479e-b5dc-dedc2827c32a.png)

10 minutes of usage:
![image](https://user-images.githubusercontent.com/36133264/130930907-f8e1002e-f2bc-4956-8fd6-7922c6e74016.png)

The same behavior I get on both `cuav v5+` and `cuav x7 pro`.

Since we can't record a log without fly I tried it in uavcan hitl simulator. It has different scale and there is no offset in data, but we have the same behavior.
Here is the log with just takeoff and hold for several minutes in simulator: https://review.px4.io/plot_app?log=3252ae38-db81-4cca-91b6-c06ae59b7d95
That is what you can see from differential_pressure: 
![image](https://user-images.githubusercontent.com/36133264/130940322-d1e1b9ba-d61d-4e6d-88e0-8463608644de.png)

**Additional context**
I tried to figure out what is the problem.
I noticed that the filter has [constrain with min 5 hz here](https://github.com/PX4/PX4-Autopilot/blob/c6a6403ce2039823f80af40ac5441f51afcdefb0/src/lib/mathlib/math/filter/LowPassFilter2p.hpp#L74), but uavcan sensor has [cutoff_freq 1.1 hz and sample_freq 10 hz](https://github.com/PX4/PX4-Autopilot/blob/c6a6403ce2039823f80af40ac5441f51afcdefb0/src/drivers/uavcan/sensors/differential_pressure.hpp#L62), so in result cutoff_freq 5 hz and sample_freq 10 hz. It leads to following values of the filter params: b0 = 1, b1=2, b2=1, a1=2, a2=1 which seems to be critical (I'm not expert in such filters, it is just my suggestion).

I see following solution which I may do if it's ok:
1. Decrease min value of constrain to 1.1 hz. There is no sensor that uses frequency lower than that. By the way, [MS5525 uses cutoff_freq 1.2 Hz](https://github.com/PX4/PX4-Autopilot/blob/c6a6403ce2039823f80af40ac5441f51afcdefb0/src/drivers/differential_pressure/ms5525/MS5525.hpp#L74)
2. Increase sample rate from 10 hz to 90-100 hz as [ms5525 has](https://github.com/PX4/PX4-Autopilot/blob/c6a6403ce2039823f80af40ac5441f51afcdefb0/src/drivers/differential_pressure/ms5525/MS5525.hpp#L74).

Any of above seems to be fix the problem.

**Comment by PonomarevDA** [comment]
Close because #18145 was merged. Thanks.

**Comment by dagar** [comment]
Thanks for the followup @PonomarevDA. Please let me know if you need anything else, I still plan to make the airspeed calibration per sensor instance, but need to review the work flow (eg blow into tube to verify).

**Comment by PonomarevDA** [comment]
Hi @dagar. It would be nice to have an ability to use several differential pressure sensors simultaneously. At this moment it's better to use only a single diff pressure sensor: if you use several of them it will average them into a single airspeed, so error on a one of the sensor will be propagated into the wrong airspeed estimation.
Although for this feature it is desirable to initially have a separate calibration of each of the airspeeds, in my case the calibration process might be performed on the sensor side individually.
I explained the details here #18767. I would appreciate if you check it.
