### ISSUE TITLE
Offboard failed 

### ISSUE THREAD

**Issue by saadnec** [PX4/PX4-Autopilot#18158]
I am trying to control vehicle iris through rospy , when i run the mavlink offboard example, it runs succesfully. But now i am trying to write my own code i copied all the functions but didnt use rosrun, I keep getting this error. 
"""
AssertionError: failed to set mode | new mode: OFFBOARD, old mode: AUTO.LOITER | timeout(seconds): 5

"""

**Comment by julianoes** [comment]
It's hard to help you because we don't see the original example and neither the code you are trying. So we can only guess what is going on. My guess would be that you're trying to switch mode but have not regularly sent offboard setpoints yet which need to be sent first.

**Comment by Jaeyoung-Lim** [comment]
Closing as stale, @saadnec If you think this is still an issue, please reopen
