### ISSUE TITLE
ConnectionPtr Events (such as ConnectWorldUpdateBegin/End) not thrown

### ISSUE THREAD

**Issue by AndreaDelbene** [PX4/PX4-Autopilot#18159]
Good morning 

I have experienced an issue in the versions 1.12.1 and later, that I am currently using: I have a registered plugin in a model I created, but when I launch the simulation, the event ConnectWorldUpdateBegin, that I am listening, is not thrown.

One other thing I am noticing it's that most of times gazebo doesn't launch properly (the world is not loaded, but everything on the terminal looks fine); otherwise it's fine only when "gzserver not ready yet, trying again!" appears.

I really can't demonstrate these two could be related, but this wasn't happening with the previous version i was using (1.11.3).
Any suggestions?

**Comment by julianoes** [comment]
Have you tried `VERBOSE_SIM=1` to get more output?

https://github.com/PX4/PX4-Autopilot/blob/ca2d8f6de2e86568b4da12a46567d2221484fb9f/Tools/sitl_run.sh#L46

**Comment by Jaeyoung-Lim** [comment]
@AndreaDelbene It could be that the plugin you wrote is stuck somewhere, (e.g. finding some kind of resource) and then the simulation is not progressing.

> but this wasn't happening with the previous version i was using (1.11.3)

What do you mean? We are talking about a custom plugin that you created right?
