### ISSUE TITLE
RTL: inconsistent RTL altitudes for FW and VTOLs

### ISSUE THREAD

**Issue by ThomasRigi** [PX4/PX4-Autopilot#18169]
@RomanBapst 

**Describe the bug**
RTLs that go to a different location than home have an inconsistent way of calculating the return altitude. In https://github.com/PX4/PX4-Autopilot/blob/master/src/modules/navigator/rtl.cpp#L272-L273 you check for home altitude even though that has nothing to do if not RTLing to home. You could be 10km away from and 300m below home altitude and be forced to climb to home altitude + RTL_RETURN_ALT instead of just climbing to `_destination.alt` + RTL_RETURN_ALT. 

I think the line should be the following:
`_rtl_alt = max(global_position.alt, _destination.alt + _param_rtl_return_alt.get()); `and it should be `_destination.alt` that handles if it's home or some other type of rally point.

The current way is especially inconsistent with the following line: https://github.com/PX4/PX4-Autopilot/blob/master/src/modules/navigator/rtl.cpp#L287. We've had an occurrence where the drone was RTLing at current altitude but still had the message logged "[navigator] RTL: climb to 621 m (45 m above destination)". To note that RTL_RETURN_ALT was 60m and not 45m. IMO it's line 287 that is good and L272-L273 that have to be fixed accordingly.

**To Reproduce**
Can be done on a simulator, fly a mission on a plane or VTOL with a Land WP at e.g. 20m above home and fly the mission at 50m in FW mode. With RETURN_TYPE = 3 and RTL_RETURN_ALT = 40 I would expect the drone to return at 60m to the Land WP, but it doesn't climb and instead goes there at 50m.

**Expected behavior**
Return to the Rally point at RTL_RETURN_ALT (or higher), independently of the type of rallypoint.

**Log Files and Screenshots**
Simulated flight, master, should have been 40m above destination.
https://logs.px4.io/plot_app?log=21935019-fcd5-4506-8c5c-e8707d20922b
![image](https://user-images.githubusercontent.com/48206725/131357217-d805e833-c7a9-43dc-b5c8-70311808328c.png)

**Drone (please complete the following information):**
- Had an occurrence on a real drone (quadplane VTOL)
- easy to reproduce on sitl_gazebo standard_vtol
- most likely applies to normal FW planes too, but I didn't test explicitly.

**Additional context**

**Comment by RomanBapst** [comment]
@ThomasRigi Thanks for reporting, I'll have a look asap!
