### ISSUE TITLE
Is there a ubuntu.sh can help me install px4 on Ubuntu20.04 ROS2 foxy?

### ISSUE THREAD

**Issue by SEUZTh** [PX4/PX4-Autopilot#18179]
There is a shell script which is referred in https://docs.px4.io/master/en/dev_setup/dev_env_linux_ubuntu.html that can install px4 in ubuntu18.04 quickly.

But I haven't found a method to install px4 on  ubuntu20.4 foxy. I need some help.

I'm looking forward to receiving your reply! Thanks very much!

**Comment by hhenryy** [comment]
you should be able just to run the `PX4-Autopilot/Tools/setup/ubuntu.sh `script to setup PX4 and gazebo on Ubuntu 20.04
