### ISSUE TITLE
ERROR [param] not enough arguments in the VTOL gazebo simulation at v1.12.2

### ISSUE THREAD

**Issue by Kim-zhi-jiang** [PX4/PX4-Autopilot#18177]
From: PX4-Autopilot/src/systemcmds/param/param.cpp
line 292

![2021-09-01 19-53-51 的屏幕截图](https://user-images.githubusercontent.com/80669694/131670278-3e4357be-4452-4cbe-8d91-1545ca494dda.png)

INFO  [init] Mixer: etc/mixers-sitl/standard_vtol_sitl.main.mix on /dev/pwm_output0
ERROR [param] not enough arguments.
Try 'param set PWM_AUX_OUT 3 [fail]'

**Comment by hamishwillee** [comment]
FWIW I can reproduce this behaviour against tag v1.12.2 using `HEADLESS=1 make px4_sitl gazebo_standard_vtol`. I also see it in master.

The simulated vehicle appears to fly OK. 

@bkueng is this something to worry about? AUX3 is supposed to be an elevator :-)

**Comment by Kim-zhi-jiang** [comment]
Still have
