### ISSUE TITLE
Raspberry Pi not starting when connected with PixHawk

### ISSUE THREAD

**Issue by MuhammadBilal1** [PX4/PX4-Autopilot#18241]
Hi,

**RPi =** Raspberry Pi 4 Model B
**PixHawk =** PixHawk 4
**Firmware =** PX4 - 1.11.3
**Baudrate =** 921600
**PixHawk Port =** Telemetry 2
**RPi Port =** GPIO14, GPIO15
**RPi OS =** Ubuntu 20.04.04

**Issue:**
I am getting an issue while trying to start the RPi while connected with the PixHawk.
Some invalid characters starts coming up on the screen. Screenshot is attached.

**What I tried?**
1- If I disconnect RPi from PixHawk & start both separately, then after both things bootup everything works fine. I can use mavros/mavlink to arm/disarm the drone (Heartbeat is coming ok). 
2- I tried disconnecting all the peripherals except the telemetry/serial wire. Not worked.

**RPi connection with PixHawk**
Raspberry Pi is connected with PixHawk via serial connection (Telemetry 2 @ 921600).

**Power to RPi**
RPi is powered ON by connecting the power adapter (Micro USB) to the power port.

**The following peripheral are connected with RPi:**
* LCD at HDMI port
* Keyboard
* Mouse
* Ethernet Cable
* Micro USB Cable (Power)

![assembly](https://user-images.githubusercontent.com/7131058/133433991-70a5cdde-ad02-49cd-bc1a-417e3535b667.png)

![Error screen -1](https://user-images.githubusercontent.com/7131058/133434030-cb79b32a-d59a-46cb-bf57-0cbe5cf71fbf.JPEG)

![Error Screen -2](https://user-images.githubusercontent.com/7131058/133434069-e83cec82-10b5-4774-af12-9dbd395c2687.JPEG)

**Comment by JStoop97** [comment]
I have had a similar issue before with the pi with a faulty keyboard plugged in. The keyboard would spam information onto the pi USB/uart during start up and the pi would not boot properly. I think this therefore an issue with the pi and you would be better off directing your search there.

**Comment by MuhammadBilal1** [comment]
> think this therefore an issue with the pi and you would be better off directing your search there.

The same happened even after removing the Keyboard, Mouse & Ethernet cable.

**Comment by JStoop97** [comment]
No what I mean is that sometimes when the uart port is spammed during start up by a device such as a pixhawk or faulty keyboard (as was my case) this could happen. Perhaps try a different baudrate and see if that doesn't solve the error.

**Comment by MuhammadBilal1** [comment]
Updating the post so if anyone else is getting the same issue, they can get a fix.
I changed the wiring from GPIO ports to USB and things are now working fine.

I was getting the issue while connecting the PixHawk and Raspberry Pi via GPIO ports.
The working solution is to use the **FTDI cable** to connect the PixHawk and Raspberry Pi.

![image](https://user-images.githubusercontent.com/7131058/134487859-be2ff280-cfad-440f-b842-50d29204b8f9.png)
