### ISSUE TITLE
better height estimation for multi-vehicle parameters for better height estimation barometer,lidar, gps  

### ISSUE THREAD

**Issue by airsimdevdd** [PX4/PX4-Autopilot#18257]

**Comment by airsimdevdd** [comment]
@Paul Riseborough please help me

**Comment by garlinplus** [comment]
Default parameter is enough for your need.

**Comment by dagar** [comment]
@airsimdevdd could you please add more context? What problems are you seeing specifically? Can you share any flight logs showing the issue? https://logs.px4.io

**Comment by airsimdevdd** [comment]
> Default parameter is enough for your need.
all my 4  vehicles are not maintaining same altitude wat to do

**Comment by airsimdevdd** [comment]
> @airsimdevdd could you please add more context? What problems are you seeing specifically? Can you share any flight logs showing the issue? https://logs.px4.io

sir  when i fly my vehicles in offboard for example i gave 10m  altitude some vehicles go to correct height but some go to 15m 13m altitudes

**Comment by mrpollo** [comment]
I'm going to close this issue since we don't have any information, next time you run into an issue grab the logs so we can help you.
