### ISSUE TITLE
How to implement a Quad4V or Quad4A mixer

### ISSUE THREAD

**Issue by CkovMk** [PX4/PX4-Autopilot#18301]
**Describe problem solved by the proposed feature**

> The V-Tail and A-Tail are basically quadcopter config with the front motors on normal quadcopter arms, while the rear motors located in close proximity, tilted at an vertical angle either inward or outward. It’s a mix between a quadcopter and a tricopter and very similar to Y4 config.
>
![image](https://oscarliang.com/ctt/uploads/2013/10/vtail-copter.jpg)
> quoted from [this site](https://oscarliang.com/types-of-multicopter/)

Mixers for Quadrotor aircrafts include 4X and 4+, but it seems no support for such 4A or 4V quadrotors from PX4 as I know. I'm  
 building a tiltrotor VTOL aircraft with Quad A-Tail configuration, aiming at reducing drag caused by those two fixed rotors.

**Describe your preferred solution**
Adding 4A and 4V mixer would perfectly solve this issue. Or maybe there's some way to override the mixer system, as described [here](https://discuss.px4.io/t/mixer-customization-and-override/12098).

**Comment by bkueng** [comment]
You can now configure the motor axis (https://github.com/PX4/PX4-Autopilot/pull/19990)
