### ISSUE TITLE
Omnibus F4 SD GPS does not work

### ISSUE THREAD

**Issue by Dunnodv** [PX4/PX4-Autopilot#18319]
I have this board (**Omnibus F4 AIO OSD 5V**):
<img width="434" alt="Screenshot 2021-08-15 at 21 07 32" src="https://user-images.githubusercontent.com/8294813/135516724-f1a8d2e9-3bc0-426f-a743-993446a2cec3.png">

I installed PX4 bootloader (OmnibusF4SD)

I tried to connect **_BN-880 GPS_** by using these pairs: **TX6/RX6**, **TX3/RX3**, **TX1/RX1**, but it doesn't work. (When it was betaflight - GPS worked completely)

**GPS_1_CONFIG** param has two values: **UART 6**, **TELEM 2**, **Unknown 201** (by default).

When I selected **UART 6**, MAVLink Console returned this info:
<img width="528" alt="Screenshot 2021-09-30 at 22 27 27" src="https://user-images.githubusercontent.com/8294813/135518243-f9d1413b-ca97-4422-84ea-95e5c7f61913.png">

When I Selected **TELEM 2**, MAVLink Console returned this info:
<img width="578" alt="Screenshot 2021-09-30 at 22 33 40" src="https://user-images.githubusercontent.com/8294813/135518975-34641c3b-6c4f-44cc-92e7-c4025525267e.png">

I tried to start GPS manually 
`gps start -d /dev/ttyS2 -b 57600`
But it didn't work.

Can you help me to connect this GPS module to my board?

**Comment by taileron** [comment]
the baud (parameter) of that port should set to 9600 or 0 (automatic) then the GPS negotiate it´s bitrate mostly to 115200. Only 9600 works as fixed bitrate, all others do not recognize the GPS module.
Attention some Omnibus have an inverter on this port that Betaflight can remotely switch off.
PX4 doesn't´t remote this inverter and the GPS only works directly connected to the port without that inverter.
The compass needs pull-ups 2.2k but that works independently of the GPS. 
For proper EKF2 a barometer is recommended.
