### ISSUE TITLE
ROS2-PX4 OFFBOARD triggers Failsafe enabled: No manual control stick input

### ISSUE THREAD

**Issue by hashimK** [PX4/PX4-Autopilot#18389]
**The bug**
No manual control stick input failsafe is triggered when OFFBOARD example (`ros2 run px4_ros_com offboard_control`) is executed. Although no issues were found in the ROS2-PX4 bridge when `ros2 run px4_ros_com sensor_combined_listener`
 is executed, it works as expected.

**To Reproduce**
1. Install ROS2 Foxy on Ubuntu 20.04 LTS
2. Clone the current PX4 master branch and install the Linux toolchain
3. Install Fast-RTPS-Gen only as installation of Fast DDS is not required because ROS2 Foxy is already installed
4. Follow all the other steps that are required as mentioned here [https://docs.px4.io/master/en/ros/ros2_comm.html](https://docs.px4.io/master/en/ros/ros2_comm.html)
5. Run `make px4_sitl_rtps gazebo` and `micrortps_agent -t UDP`
6. Run `ros2 run px4_ros_com offboard_control`
7. `INFO  [commander] Armed by external command	
WARN  [commander] Failsafe enabled: No manual control stick input`

![Screenshot from 2021-10-08 17-35-42](https://user-images.githubusercontent.com/19934293/136566744-6cb90211-cdb5-4837-b142-71ad831b0adf.png)

**Expected behavior**
The drone should takeoff and be in OFFBOARD mode (as per my understanding of the `offboard_control` example)

**Comment by benjinne** [comment]
I changed the behavior recently to fix offboard failsafes, but it defaults to requiring RC which can be achieved by enabling virtual joysticks in QGC or setting COM_RCL_EXCEPT to 4 to ignore RC failsafe
