### ISSUE TITLE
Bug Found in msgID #147 mavlink protocol OOB

### ISSUE THREAD

**Issue by BOB4Drone** [PX4/PX4-Autopilot#18385]
-----------------------------------------------------------------------------------------
1. Turn the drone on
2. Prepare many MAVLINKs with msgID 147 with different "sysID" and "compID".
3. send a packet
4. Out Of Bound (OOB) vuln occur
5. Turn the drone off

**Describe the bug**
-----------------------------------------------------------------------------------------
The method we tested sets MAVLINK's msgID to 147, compID and sysID to random, and sends a packet.

The source code part where the problem occurs is 1733 code line ~ 1736 code line and 1733 code line of the site below.

The reason for the problem is that MAVLINK packets with different compID and sysID operate the target handler function and
When the "cell_count++" part is calculated at a specific timing, "cell_count" becomes greater than 10 and goes out of the range of the "battery_mavlink.voltages[cell_count]" array (the size of the array is 10).

I found it in sitl mode and also checked it on the drone board.

source code
-----------------------------------------------------------------------------------------
https://github.com/PX4/PX4-Autopilot/blob/master/src/modules/mavlink/mavlink_receiver.cpp

PX4-Autopilot/src/modules/mavlink/mavlink_receiver.cpp (line 1733 ~ line 1737, The line of code where the problem occurs is 1733. )

TEST board
-----------------------------------------------------------------------------------------
px4_fmu-v5
nxp_fmuk66-v3

log file page
-----------------------------------------------------------------------------------------
https://logs.px4.io/plot_app?log=0f0583c3-a609-4b61-a283-6e3df243141c

screen shot
-----------------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/91944211/136547203-1b51b617-1aca-4759-bff8-28ea9eeb46c5.png)

**Comment by dagar** [comment]
Your line numbers don't match current master. What's the closet upstream commit to what you're using?

Based on the current upstream code I'm not seeing how cell_count can exceed 10, could you explain? I'm not following what you're saying about specific timing, the receive for each instance is single threaded.

https://github.com/PX4/PX4-Autopilot/blob/47dc2ae5a561b2bc69ea1b1144085a0f4b398438/src/modules/mavlink/mavlink_receiver.cpp#L1733-L1737

**Comment by BOB4Drone** [comment]
The code line is based on github, and the code line in the screenshot is personally modified while adding "printf", so the code line does not match.


When we tested, we randomly set the sysid and compid and then sent a lot of MAVLINK PACKETs.

We also thought that the crash did not occur because there was "cell_count < 10" in the "while (battery_mavlink.voltages[cell_count] < UINT16_MAX && cell_count < 10)" part, but a crash occurred.


When we tested it, when we modified it to "while (cell_count < 10 && battery_mavlink.voltages[cell_count] < UINT16_MAX)", no crash occurred and the drone board did not turn off.

**Comment by dagar** [comment]
> When we tested it, when we modified it to "while (cell_count < 10 && battery_mavlink.voltages[cell_count] < UINT16_MAX)", no crash occurred and the drone board did not turn off.

Oh right, it's out of bands in the conditional, not the body. I'll get that fixed.

Thanks and please keep these coming!
