### ISSUE TITLE
RTL after Quadchute: drone flying away instead of returning home

### ISSUE THREAD

**Issue by ThomasRigi** [PX4/PX4-Autopilot#18440]
**Describe the bug**
After a Quadchute soon after transition the drone flew away from home in RTL mode for a good 100m and about 20s before our pilot took over manually. The problem is also SITL-reproducible.

@bresch @MaEtUgR I need some help from MC experts, and maybe @dagar's overall knowledge. And I reckon it's of interest to @sfuhrer too. I suspect that the fault lies with the MC trajectory initialisation when done at high speeds. 

**General Overview**
To give some context for non-VTOL people, if in Mission mode the drone quadchutes (immediate switch to MC mode) because of a problem in FW mode, [an RTL is automatically triggered](https://github.com/PX4/PX4-Autopilot/blob/master/src/modules/commander/state_machine_helper.cpp#L579). This part works fine, from the logged info messages you can see that the RTL logic works as expected. 

But the drone doesn't fully brake and return as expected. Instead, it just kind of drifts on its path until at some point it eventually remembers to fly back. Took more than 20s on the real flight, and 25s on the third log attached below. During all this time the drone basically doesn't control its position while in an automatic mode, which can easily lead to crashes or geofence breaches.

Also, the drone flies back to the place where the RTL was triggered before it starts climbing and effectively execute the RTL. Consider the case where the drone was flying towards home, stalled for some reason, was almost at home after the quadchute stabilized, then flies away again to where it quadchuted before finally coming home. Doesn't really make sense, it should go to RTL altitude directly and fly towards the destination without going back to where it was initiated.

**Log Files and Screenshots**
Real quadplane drone: https://logs.px4.io/plot_app?log=101ed7b8-2a88-4bd0-8faf-8a197772bd72 (v1.12.1 with minor unrelated modifs)
SITL, master, no airmode: https://logs.px4.io/plot_app?log=f726849a-bf6e-4871-acd6-318bc0b80236
Some oscillations due to lack of control authority on low thrust, but general problem remains the same.
SITL, master, airmode: https://logs.px4.io/plot_app?log=35c28707-3dc2-4afb-8e51-2c6c94fa046c

**Details of what I suspect goes wrong**
(log files at the end)
I think the main problem is that the MC trajectory generation algorithm gets initialized with values that are way out of its normal constraints. And things get worse if you have a significant downspeed upon initialization, but actually gain a lot of altitude just after the quadchute.

Speeds at initialisation : (screenshots from real flight log)
![image](https://user-images.githubusercontent.com/48206725/137286152-605fbecc-6c59-4124-a022-485445c02250.png)
- vz = 3.4m/s (down)
- vx = 28m/s (way out of MPC cruise speed)

Quadchute effect 2s later:
![image](https://user-images.githubusercontent.com/48206725/137286602-4c0af8e7-f005-45b3-a3ef-0fbf5b4b7884.png)
- vz = 16m/s (up!)
- vz setpoint asking for max descend speed
- vx = 12m/s (already well slowed down)

About 10s, speeds have converged, but still drifting away.
![image](https://user-images.githubusercontent.com/48206725/137287135-49e6143f-b446-451c-9295-cbb2513e8de1.png)
- vz = vz setpoint = 2.2m/s (down) *even though at RTL return altitude!*
- vx and vx setpoint are within constraints, *but still moving away from destination without trying to slow down and come back!*
- local position setpoint z is way too low for what is asked for by the RTL. It should be at 40m, not 20m.

I'm not familiar with all the details on how the MC trajectory is generated, but it's that the algorithm fails in this case. The drone knows that its final altitude goal is at 40m, yet it asks to go down to 20m even when it is at 40m... Also, it knows that it has to turn around but I guess because of the faulty altitude mismatch between `local_position_setpoint.z` and `local_position.z` it does not consider that it's going in the wrong direction? Why is horizontal position not controlled when altitude is off?

**To Reproduce**
1. Get your drone to quadchute in mission mode
2. Observe undesired behaviour

Easiest way to reproduce in SITL is to set the transition airspeed to an unattainable value (e.g. VT_ARSP_TRANS = 25) and have the transition time out.

**Expected behavior**
The drone should brake and fly back to the designated RTL spot immediately.

**First ideas for a solution**
(assuming my above analysis is mostly correct)
- reinitialise the trajectory generation when the estimated position is off by more than a threshold
- (at least partly) decouple horizontal and vertical control. It doesn't make sense to keep moving in the wrong direction just because you're above your (imaginary) target)
- take more into account where your final position setpoint is and reinitialise the trajectory generation accordingly. Don't go down from 55m to 20m when your final target altitude is 40m.

**Comment by MaEtUgR** [comment]
@ThomasRigi Sorry for not reacting instantly. I think you already narrowed it down quite well with the trajectory initialisation. The trajectory setpoint initializes with the much too high horizontal velocity that is way above the limit. Also the vehicle seems to gain a lot of altitude just after the transition happens and hence the controller brings it down again to the same altitude transition was triggered. So we can see the trajectory_setpoint horizontal velocity stays above the limit following the acceleration limits but the controller enforces the hard limit on velocity so it's not smooth even though that's the goal of the acceleration limit.

![image](https://user-images.githubusercontent.com/4668506/137900621-31ea339b-f689-4bd4-bffe-e5dc0ec492e1.png)

We had a similar case with RTL getting triggered in free fall on a normal multicopter and you seem to see the same issue in the horizontal direction. The idea for the solution is to initialize with the actual velocity estimate, only allow the setpoint to get smaller until it's below the limit, not strictly enforce the limit in that time and have a much higher acceleration limit for this "emergency slow down". Alternatively we could jump directly to the limit and leave the error above to the controller, not sure if that's acceptable.

**Comment by bresch** [comment]
> It's not smooth at all (quadchutes never are smooth almost by definition...) but at least it's no longer drifting way too far

I understand that you mostly care of not having the drone flying too far, but the reason why we created the emergency braking mode for altitude is exactly to do this while still having smooth setpoints. Simply clipping the setpoints like you did will result in huge control efforts and some larger airframes will suffer from this.

> I don't think anymore that the approach in #18277 is sufficient. Just after the transition the drone gains a lot of altitude for sure, so the "emergency braking mode" is deactivated straight away

Of course, the "horizontal emergency braking mode" needs to have its own set of condition and not just use the ones for the "vertical emergency braking mode"

**Comment by ThomasRigi** [comment]
I was thinking some more about the conditions when the emergency braking should be activated and when deactivated. Wouldn't it make sense to activate it earlier than (2.0 * max velocity), maybe around 1.2 or 1.3 * max velocity? And then deactivate the emergency mode once everything is back inside the constraints.

My main two points of reasoning are:
1) if you fly faster than the constraints something is not good and you should get back into nominal conditions as fast as possible in any case. (I see that it is debatable if you should allow to violate your acceleration constraints to get back inside the velocity constraints faster - I'm probably biased by our drone that we want to fly really smooth in normal conditions but we know it's strong enough to be able to deliver hard responses with large jerk and acceleration if needed)
2) with the current solution if we don't activate the emergency braking mode the position controller will anyway hard-cut the setpoints and we end up with a non-smooth behaviour. -> the real jerk is probably larger than what my proposition above would output.

I would argue that this reasoning also applies to the vertical component. I'd be curious to hear your thoughts on this @bresch and @MaEtUgR

**Comment by ryanjAA** [comment]
Still relevant?

From reading all this I first thought the aircraft "flew away" but really it just sort of keeps coasting or going in the wrong direction due to vastly exceeding the MC trajectory init levels but it does eventually turn around and get home, it just essentially flies down (or up), then back to where the RTL happened and then home. Is that a correct understanding?

**Comment by ThomasRigi** [comment]
Should have gotten closed with https://github.com/PX4/PX4-Autopilot/pull/18614.
