### ISSUE TITLE
tried to create board support for mro cntrl zero classic

### ISSUE THREAD

**Issue by taileron** [PX4/PX4-Autopilot#18448]
https://github.com/taileron/PX4-Autopilot/tree/New-Target-Mamba-F405-MK2/boards/mro/ctrl-zero-classic

everything seems to be correct, timer to port pin seems to be correct (stm32h7x3xx_pinmap.h) but timer 15 ch1 for pwm out no. 10 (PE5) is not taken - as if this was not implemented at all:

boards/mro/ctrl-zero-classic/src/CMakeFiles/drivers_board.dir/timer_config.cpp.obj -MF boards/mro/ctrl-zero-classic/src/CMakeFiles/drivers_board.dir/timer_config.cpp.obj.d -o boards/mro/ctrl-zero-classic/src/CMakeFiles/drivers_board.dir/timer_config.cpp.obj -c ../../boards/mro/ctrl-zero-classic/src/timer_config.cpp
../../boards/mro/ctrl-zero-classic/src/timer_config.cpp:40:24: error: 'Timer15' is not a member of 'Timer'; did you mean 'Timer14'?
   40 |     initIOTimer(Timer::Timer15, DMA{DMA::Index1}),
      |                        ^~~~~~~
      |                        Timer14
compilation terminated due to -Wfatal-errors.
[2/244] Linking CXX static library src/lib/parameters/libparameters.a
ninja: build stopped: subcommand failed.
make: *** [mro_ctrl-zero-classic] Error 1

**Comment by dagar** [comment]
Can you open a clean PR with the ctrl zero classic board support and we'll take a closer look?

It's likely the stm32h7 hardware description that needs to be extended. https://github.com/PX4/PX4-Autopilot/blob/master/platforms/nuttx/src/px4/stm/stm32h7/include/px4_arch/io_timer_hw_description.h
