### ISSUE TITLE
Global Position estimator: altitude offset

### ISSUE THREAD

**Issue by ThomasRigi** [PX4/PX4-Autopilot#18529]
**Describe the bug**
Due to a momentarily degraded GPS signal, the altitude (AMSL) as reported by the GPS was off by about 100m. The estimator was using this wrong altitude and didn't reset it when sitting on the ground and GPS altitude was good again. This offset could cause real problems when flying missions in global frame based on AMSL.

**To Reproduce**
I don't know... Momentarily degrade your GPS signal so that its reported altitude is wrong...

See below with the log files for a detailed description of what happened to us.
To note that we're using the GPS altitude as the primary source.

**Expected behavior**
When the drone is sitting on the ground (disarmed) (- and only then), it should reset the altitude estimate more often if there is a significant offset between it and the primary altitude source.

Maybe check every minute when disarmed and reset if there's a mismatch of more than 20m? (could be parametrized too for the thresholds)

**Log Files and Screenshots**
- 10h56-11h04: First flight, everything was good (real AMSL altitude according to terrain data is around 220m) : https://logs.px4.io/plot_app?log=5df10324-d0f3-4eba-adc7-2b65d097c8f5
- 11h19-11h20: Flight with (at least initially) degraded GPS: https://logs.px4.io/plot_app?log=10be42c4-428b-41c3-b5c4-e7c84f79b33d.
- - to note that the real horizontal displacement was maximum 5m, and our pilot had to fight against the drifts. -> we know GPS was degraded
- - we did not reboot the drone since the flight that stopped 15min earlier
- - The GPS altitude had drifted 100m up in the meantime and the estimator did reset the fused altitude at some point when sitting on the ground (starts around 320m, which is wrong)
![image](https://user-images.githubusercontent.com/48206725/139214399-b99ae3f3-30b2-466c-ba55-06b232620816.png)
- - it's good that the fused altitude did not reset during the flight
- 11h27: quick motor test: https://logs.px4.io/plot_app?log=0c218f38-92aa-481f-917c-e2effa763bb4
- - The fused altitude is still wrong, even though the GPS altitude (primary source) was presumably good for the last 7min when the drone was sitting on the ground. -> _This is what my bug report is about. If there is a significant offset between estimated altitude and primary altitude source and the drone is sitting on the ground for a significant amount of time, the fused altitude should reset to the primary source._
![image](https://user-images.githubusercontent.com/48206725/139215370-fff56559-8d3a-46a1-a15c-9f5e8559e4a6.png)
- 11h30: We triggered an RTL when we (finally) realised the offset: https://logs.px4.io/plot_app?log=480a7a87-cccb-4eaf-8588-25c309e61b64
![image](https://user-images.githubusercontent.com/48206725/139217375-96c8840b-a32c-412c-bec0-34cac18576b2.png)
- After this we rebooted PX4 and it initialised correctly (11h46): https://logs.px4.io/plot_app?log=ff722e9f-8d56-4ffb-ba27-17f695e079b2

**Drone:**
- Quadplane VTOL
- Pixhawk 4, running a slightly modified version of v1.12.3 (modifications not related to estimator)
- [CUAV Neo 3 pro GPS](https://store.cuav.net/shop/neo-3-pro/) (which typically gave us good performance so far)

**Comment by bresch** [comment]
This should now be fixed by https://github.com/PX4/PX4-Autopilot/pull/19944
