### ISSUE TITLE
DSHOT support on VTOL tailsitter configuration

### ISSUE THREAD

**Issue by galdalali** [PX4/PX4-Autopilot#18567]
**Describe the bug**
Using the cube orange configured as a VTOL tailsitter with DSHOT300 configuration and the ESC's are connected via AUX 1-4 output (SYS_USE_IO=0) the ESC'S are not getting signal at all (neither from the main outputs).

When working with PWM/ONESHOT configuration using the AUX 1-4 output (SYS_USE_IO=0) - behavior is OK.

Configure the frame as multi-copter with DSHOT300 configuration and the ESC's are connected via AUX 1-4 output (SYS_USE_IO=0) - behavior is OK.

**Expected behavior**
Working VTOL with DSHOT configuration on the cube orange AUX outputs

**Comment by dagar** [comment]
With the new output configuration system (and control allocation) this should all be possible (depending on the physical timers of course). https://github.com/mavlink/qgroundcontrol/pull/9952

**Comment by taileron** [comment]
looks very exciting

**Comment by galdalali** [comment]
Great! What's holding this PR from merging to master?

**Comment by Ecstasy-EC** [comment]
Any updates about this PR? Just came across the same problem. Motors on my tail-sitter did not receive any signals. Many thanks! @dagar

**Comment by dagar** [comment]
> Any updates about this PR? Just came across the same problem. Motors on my tail-sitter did not receive any signals. Many thanks! @dagar

Yes the big output configuration/mixing overhaul is coming together for VTOL. https://github.com/PX4/PX4-Autopilot/pull/18776

If you absolutely need dshot for vtol right now we could probably hack something together quickly, but otherwise it would be great to focus on getting the right solution finished.

**Comment by galdalali** [comment]
BTW, it appears there is no AUX mixer configured for VTOL tail-sitter configuration, once I configured a new frame and aux mixer by myself everything works OK.

**Comment by bkueng** [comment]
Control allocation is now the default (https://github.com/PX4/PX4-Autopilot/pull/19990)
