### ISSUE TITLE
False positive Imbalanced propeller detected, landing advised for fixedwings

### ISSUE THREAD

**Issue by Jaeyoung-Lim** [PX4/PX4-Autopilot#18574]
**Describe the bug**
The imbalanced propeller check is always triggered when doing a fixedwing runway takeoff in SITL Gazebo

**To Reproduce**
1. Start SITL with a plane model
```
make px4_sitl gazebo_plane
```
2. Start mission with a takeoff waypoint

**Log Files and Screenshots**
```
INFO  [commander] Failsafe mode deactivated
INFO  [tone_alarm] notify positive
WARN  [fw_pos_control_l1] Start loiter with fixed bank angle.
INFO  [commander] Armed by external command
INFO  [fw_pos_control_l1] Takeoff on runway
INFO  [commander] Takeoff detected
INFO  [runway_takeoff] #Takeoff airspeed reached
WARN  [commander] Imbalanced propeller detected, landing advised
INFO  [runway_takeoff] #Climbout
```

**Additional context**
- The warning has been introduced from https://github.com/PX4/PX4-Autopilot/pull/18553

**Comment by TSC21** [comment]
Seems that we need to reduce the threshold for thr fixed wing models in Gazebo. @bresch what do you say,

**Comment by dagar** [comment]
What does vehicle_imu_status.var_accel look like in that log?

**Comment by dagar** [comment]
By default `COM_IMB_PROP_ACT` is set to warning.

**Comment by bresch** [comment]
@Jaeyoung-Lim Could you provide a log please?

**Comment by Jaeyoung-Lim** [comment]
@bresch Here is one: https://logs.px4.io/plot_app?log=15f471bd-2a86-4855-9206-ce111cd0b393 :grinning:

**Comment by bresch** [comment]
@Jaeyoung-Lim It's apparently because of the high horizontal acceleration when the pusher starts

![DeepinScreenshot_select-area_20211108160248](https://user-images.githubusercontent.com/14822839/140765768-57beeb73-20d4-4386-8dcb-4a81572dcb7c.png)

We could
1) increase the threshold (quick fix)
2) make the detector less sensitive to quick changes (better)

**Comment by dagar** [comment]
Fixed in https://github.com/PX4/PX4-Autopilot/pull/18590.
