### ISSUE TITLE
Commander doesn't handle system broadcast commands

### ISSUE THREAD

**Issue by lukegluke** [PX4/PX4-Autopilot#18572]
Shouldn't commander handle broadcast system commands here?
https://github.com/PX4/PX4-Autopilot/blob/f492fa9d3ab5a1e7b105594a1f637bd6a22bfad4/src/modules/commander/Commander.cpp#L743-L747

Like this:
```
	/* only handle commands that are meant to be handled by this system and component (or broadcast) */
	if (((cmd.target_system != _status.system_id) && (cmd.target_system != 0))
			|| ((cmd.target_component != _status.component_id)
					&& (cmd.target_component != 0))) {
		return false;
	}
```

As I see there are several module that publish internal vehicle_command (from_external = false), usually they use cleared  vehicle_command with zeroed target_system. How do they work then?

**Comment by dagar** [comment]
@lukegluke yes I think you're right.

In general I think we need to more intentionally maintain a barrier between PX4 internal vehicle_commands and Mavlink commands.

FYI @julianoes

**Comment by julianoes** [comment]
I agree, we should not ignore broadcast.
