### ISSUE TITLE
False positive "Start loiter with fixed bank angle"

### ISSUE THREAD

**Issue by Jaeyoung-Lim** [PX4/PX4-Autopilot#18573]
**Describe the bug**
Whenever doing a fixedwing takeoff, a warning message "Start loiter with fixed bank angle" is wrongly being triggered

@sfuhrer FYI

**To Reproduce**
1. Start SITL with a plane model
`make px4_sitl gazebo_plane`
2. Start mission with a takeoff waypoint

**Log Files and Screenshots**
![image](https://user-images.githubusercontent.com/5248102/140536497-958697c2-b445-4bd7-9bcf-f83e0354e896.png)

**Additional context**
- This seems to be appearing after https://github.com/PX4/PX4-Autopilot/pull/17547 has been merged

**Comment by dagar** [comment]
What failsafe is actually triggering?

**Comment by dagar** [comment]
Link loss confusion?

**Comment by sfuhrer** [comment]
> What failsafe is actually triggering?

No failsafe actually triggers, it's just that `_pos_sp_triplet.current.valid ` in FW Position controller gets set to valid one iteration after `_control_mode.flag_control_auto_enabled` and `_control_mode.flag_control_position_enabled` are set to true, and caused the internal FW position mode to be set to FW_POSCTRL_MODE_AUTO_ALTITUDE for one brief moment after triggering the FW takeoff.
We could also think about removing `_pos_sp_triplet.current.valid `check from the logic here, I don't know in what case this can be invalidated.

**Comment by dagar** [comment]
> We could also think about removing _pos_sp_triplet.current.valid check from the logic here, I don't know in what case this can be invalidated.

Originally I think it was more for the ability to explicitly publish something that invalidates existing position setpoints that consumers already have.
