### ISSUE TITLE
Fixed wing aircraft takeoff logic check

### ISSUE THREAD

**Issue by xn365** [PX4/PX4-Autopilot#18635]
We don't seem to consider the initialization and management of takeoff and landing status during takeoff in manual mode?
I only see that in auto mode:
https://github.com/PX4/PX4-Autopilot/blob/29b9e4666478266b09bda766d332ca9b96d93872/src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp#L711

**Comment by Jaeyoung-Lim** [comment]
@xn365 Takeoff / landing modes are only relevant for auto modes. Is there a specific usecase that you need these states in manual modes?

**Comment by xn365** [comment]
It looks good. I misunderstood it. 
This issues can be closed.
