### ISSUE TITLE
mixer does not publish actuator_outputs in the first instance

### ISSUE THREAD

**Issue by NicolasM0** [PX4/PX4-Autopilot#18668]
**Describe the bug**
On master (4a14a8bc7fb6f47c8e7be72d3de502d35a61a40e) with default parameters, mixer publishes actuator_outputs topic on the instance 2 but all subscribers subscribe to the instance 0. The effect is that actuator's command is not in the mavlink stream and SIH does not work.

![actuator_with_uavcan](https://user-images.githubusercontent.com/59083163/142396752-2e2f9d5f-bb73-4b78-a178-03c1092e421e.png)

setting UAVCAN_ENABLE to 0 fix the issue ; SIH is working fine :

![actuator_no_UAVCAN](https://user-images.githubusercontent.com/59083163/142396875-6ab73c2e-d90b-4469-8ed7-bead121db616.png)

**To Reproduce**
1. flash master
2. reset all parameters
3. set airframe to sih
4. try to take off
--> the quad does not takeoff

Why UAVCAN create instances of actuator_outputs ? It is for simulation through CAN ?

**Comment by bkueng** [comment]
Should be fixed with https://github.com/PX4/PX4-Autopilot/pull/19990
