### ISSUE TITLE
OFFBOARD CONTROL USING MAVROS

### ISSUE THREAD

**Issue by bhaskar-glitch** [PX4/PX4-Autopilot#18679]
Hi,
I’m using **pixhawk 2.4.8**+**jetson xavier** and i’m using VINS_FUSION for locatization of my drone…now please help that how i can use **OFFBOARD** mode and what topic i've to publish to make **my drone fly** and also my drone should take inputs of local position from **VINS_FUSION** because i'm not using **GPS**...
Please help…i’m done with all the things but stuck in flying part of drone…?

**Comment by Jaeyoung-Lim** [comment]
@bhaskar-glitch Please be more specific on which aspect you need help. Otherwise offboard mode is reasonably well documented in http://docs.px4.io/master/en/flight_modes/offboard.html and http://docs.px4.io/master/en/ros/mavros_offboard.html

**Comment by bhaskar-glitch** [comment]
> @bhaskar-glitch Please be more specific on which aspect you need help. Otherwise offboard mode is reasonably well documented in http://docs.px4.io/master/en/flight_modes/offboard.html and http://docs.px4.io/master/en/ros/mavros_offboard.html

Thank you for your reply bta I've solved this issue so far..

**Comment by Jaeyoung-Lim** [comment]
@bhaskar-glitch Thanks for the update and glad to hear that it worked out. Closing the issue
