### ISSUE TITLE
ALT broken in the VTOL RTL

### ISSUE THREAD

**Issue by Kim-zhi-jiang** [PX4/PX4-Autopilot#18718]
The altitude keeps falling at RTL to home.

**Comment by RomanBapst** [comment]
@Kim-zhi-jiang Please add a log or a better explanation.

**Comment by Kim-zhi-jiang** [comment]
@RomanBapst   [log](https://logs.px4.io/plot_app?log=23730b9e-596b-4cff-980e-178ff4b928b6)

**Comment by RomanBapst** [comment]
@Kim-zhi-jiang Can you explain how you reproduced this? Any code changes? What was your command for the simulation?
Did you change params?

**Comment by Kim-zhi-jiang** [comment]
@RomanBapst 
Not Changes code,
PX4_SIM_SPEED_FACTOR=3 PX4_HOME_LAT=22.5692507 PX4_HOME_LON=113.4770233 PX4_HOME_ALT=29.5 make -j4 px4_sitl gazebo_standard_vtol
I don't know where it happened Maybe commander.cpp,
Test Master everyday.

**Comment by NicolasM0** [comment]
It seems that your RTL point altitude is set to 0m so 29m below your ground altitude.

**Comment by Kim-zhi-jiang** [comment]
@NicolasM0  Can be easily reproduced,  git clone master  make px4_sitl gazebo_standard_vtol
RTL then...

**Comment by Kim-zhi-jiang** [comment]
@NicolasM0   Maybe from here #18395
