### ISSUE TITLE
macos (M1) make sitl gazebo get error

### ISSUE THREAD

**Issue by liganggg** [PX4/PX4-Autopilot#18954]
hi everyone 

I get error when I build make px4_sit gazebo on Mac OS  

i use MacBook Air (M1, 2020) macOS Monterey 12.1
gezebo version is Gazebo multi-robot simulator, version 11.9.1
px4 version V1.12.3 i also try the master breanch 

It can be compiled normally when  make px4_fmu-v5_default or make px4_sitl jmavsim
 
but when i make px4_sitl gazebo 
i get error：

```
/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/c++/v1/cmath:329:9: error: no member named 'isless' in the global namespace using ::isless;
/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/c++/v1/cmath:333:9: error: no member named 'isunordered' in the global namespace using ::isunordered;
13 errors generated.
fatal error: too many errors emitted, stopping now [-ferror-limit=]
ninja: build stopped: subcommand failed.
[1/5] Generating ../../logs
FAILED: external/Stamp/sitl_gazebo/sitl_gazebo-build /Users/l/px4/PX4-Autopilot/build/px4_sitl_default/external/Stamp/sitl_gazebo/sitl_gazebo-build 
cd /Users/l/px4/PX4-Autopilot/build/px4_sitl_default/build_gazebo && /usr/local/Cellar/cmake/3.22.1/bin/cmake --build /Users/l/px4/PX4-Autopilot/build/px4_sitl_default/build_gazebo -- -j 0

ninja: build stopped: subcommand failed.
make: *** [px4_sitl] Error 1
````

I have tried some methods found on the Internet eg: reinstall "xcode command line tools" "python""brew"   but it don't work

I need some help Anyone get this error and recommendation? thanks!

this file is the all output msg when i make px4_sitl gazebo.
[out.txt](https://github.com/PX4/PX4-Autopilot/files/7823251/out.txt)

**Comment by Jaeyoung-Lim** [comment]
@liganggg Probably you might get some hints from https://github.com/PX4/PX4-Autopilot/pull/18617

**Comment by liganggg** [comment]
> @liganggg Probably you might get some hints from #18617

thanks for you advice ,i have tryed reinstall homebrew-core and brew tap osrf/simulation 
but still get the same error，i guess it maybe related with the macos monterey 12.1. or gazebo version?
Can someone help try the same environment,and give some suggestion thanks ~

**Comment by liganggg** [comment]
```
adsfjkaf
adsfgd
```

**Comment by liganggg** [comment]
these days i have tryed to use anaconda instead python whitch mac raw version，bug the same error still exist.

**Comment by liganggg** [comment]
thanks everyone  
 i had solve this problem by restore all content and settings,and then install step by step flow 'px4 develop guide' 
The previous error may be some step has  mistake operation
