### ISSUE TITLE
RTL instability when VEHICLE_CMD_DO_SET_HOME is used with ROS2

### ISSUE THREAD

**Issue by adk4davsys** [PX4/PX4-Autopilot#18983]
**Describe the bug**
When triggering RTL during HITL with VEHICLE_CMD_DO_SET_HOME results in instability. I included screenshots but it seems to me that the vehicle still points to the origin while flying towards the new home location.

**To Reproduce**
1. Using the offboard mode, set new home position (offset latitude by 100 meters) using VEHICLE_CMD_DO_SET_HOME (only works after ARMING)
2. Takeoff and fly to an arbitrary location
3. Trigger RTL
4. Observe vehicle flies toward the new HOME location while twitching
5. Landing is very hazardous as the vehicle keeps bouncing
6. After landing, vehicle does not DISARM automatically

**Expected behavior**
Vehicle should fly towards HOME in a stable manner.

**Log Files and Screenshots**
![RTL_BUG_REPORT_1](https://user-images.githubusercontent.com/68663395/148790328-7b1a9d22-0590-46d7-b883-265ba3bffbff.png)
![RTL_BUG_REPORT_2](https://user-images.githubusercontent.com/68663395/148790353-c2b5eb96-6e8b-404c-86cd-7fa884ccdc19.png)

**Drone (please complete the following information):**
- Using V1.12.3, not master branch
- When using RTL without setting new HOME, it flies fine.

**Comment by dagar** [comment]
Is VEHICLE_CMD_DO_SET_HOME being sent multiple times? Can you share the full log? https://logs.px4.io

**Comment by adk4davsys** [comment]
@dagar Thank you for your reply. Attached is the log from above flight, please let me know if you need anything else.

[log](https://review.px4.io/plot_app?log=a77dd16c-01bc-41be-a272-ec70dc880002)

**Comment by adk4davsys** [comment]
@dagar Seems like when using VEHICLE_CMD_DO_SET_HOME affects Position Mode as well. I tried setting home using `current location=1` once and switching to Position Mode does the same thing (setpoint is set to local origin). Below is the screenshot of my log:

![SetHome_PositionMode_SP](https://user-images.githubusercontent.com/68663395/149362324-ffb7cfbb-6632-45e8-ba56-eb507212b20f.png)

Can someone else replicate this behavior by using VEHICLE_CMD_DO_SET_HOME? I would like to use this feature but seems like it is very hazardous at the moment.

**Comment by adk4davsys** [comment]
@dagar Turns out `trajectory_setpoint` topic from companion computer still gets subscribed and applied during RTL. Not publishing to this topic when  RTL is triggered the problem does not persist. I will open a new issue and reference this issue.
