### ISSUE TITLE
(Asking for Ideas) Exception for Non-aerial vehicle's takeoff altitude check for missions

### ISSUE THREAD

**Issue by junwoo091400** [PX4/PX4-Autopilot#19045]
**Situation**
With a simulated boat (`make px4_sitl gazebo_boat`), uploading the mission with take-off altitude of less than 1.5 meters will result in a QGC message : "Mission rejected: takeoff altitude too low! Minimum: 1.5m'. Preventing it from loading the mission.

**Explanation**
Mission Feasibility Checker inside the Navigator doesn't consider rover / boat cases as an **exception** (since they don't take-off).
> https://github.com/PX4/PX4-Autopilot/blob/1f73294ad768414f39ccc2d047e321cc5d8547a4/src/modules/navigator/mission_feasibility_checker.cpp#L359

I thought having `!(_navigator->get_vstatus()->vehicle_type == vehicle_status_s::VEHICLE_TYPE_ROVER)` condition would be enough to solve the case, but turns out Boat simulation considers it's vehicle type as VEHICLE_TYPE_UNKNOWN.

**Ideas**
1. Giving an exception to all the UNKNOWN vehicle type & ROVER : This can mistakenly include aerial vehicles with UNKNOWN type into account
2. Creating the Boat vehicle type
3. Consider Boats as Rovers

I would like to hear some ideas on what's the best way to handle this!

**Comment by Jaeyoung-Lim** [comment]
@junwoo091400 I have fixed this in https://github.com/PX4/PX4-Autopilot/pull/20082
