### ISSUE TITLE
velocity setpoints for fixedwing

### ISSUE THREAD

**Issue by airsimdevdd** [PX4/PX4-Autopilot#19078]
Is there any way  to set velocity setpoints to fixedwing ,mavsdk velocity setpoints are not working i dont know why ?

**Comment by Jaeyoung-Lim** [comment]
@airsimdevdd Support for velocity setpoints for fixedwing was only added in https://github.com/PX4/PX4-Autopilot/pull/18495

This is why it is not written in the documentation (yet): https://docs.px4.io/master/en/flight_modes/offboard.html#fixed-wing

**Comment by airsimdevdd** [comment]
can use the now anyway to use it

**Comment by Jaeyoung-Lim** [comment]
@airsimdevdd yes it is merged in latest master

**Comment by airsimdevdd** [comment]
But , Iam  unable  to set velocity setpoints using the latest master

**Comment by airsimdevdd** [comment]
[](url)https://review.px4.io/plot_app?log=96f7c7b5-6856-4c84-9434-f8368fdf5773

**Comment by Jaeyoung-Lim** [comment]
@airsimdevdd The vehicle never went into offboard mode. I think the log is irrelevant to verify the functionality of offboard mode

**Comment by airsimdevdd** [comment]
why it is not going to offboard

**Comment by Jaeyoung-Lim** [comment]
@airsimdevdd It says in the log, that since you don't have a manual stick input, a failsafe is triggered. Try enabling virtual joystick in QGC and retry

**Comment by airsimdevdd** [comment]
thanks vehicle went to offboard but the velocity doesnot  chnage according my setpoints

**Comment by Jaeyoung-Lim** [comment]
@airsimdevdd Only the bearing vector and climbrates are set with velocity setpoints since you don't want to change your air relative velocity for fixedwing vehicles.

**Comment by airsimdevdd** [comment]
we want to change the airspeed can't we do that

**Comment by Jaeyoung-Lim** [comment]
@airsimdevdd Yes, you cannot change the airspeed

**Comment by airsimdevdd** [comment]
By anyway  can i control the airspeed using atittude setpoints or any 
other way to control airspeed in offboardmode

**Comment by Jaeyoung-Lim** [comment]
@airsimdevdd Currently this is not supported. If you are interested in extending the offboard interface to control airspeed, this would be very welcome
