### ISSUE TITLE
Problem with adding topics to the microRTPS bridge

### ISSUE THREAD

**Issue by gustavotbarros** [PX4/PX4-Autopilot#19104]
Hi all,

I am trying to add the topic VehicleGpsPosition to the px4_ros_com package. I’ve already modified the file urtps_bridge_topics.yaml in the PX4-Autopilot/msg/tools folder. And when I try to run the uorb_to_ros_urtps_topics.py to mirror the topics into px4_ros_com, I get this error:
![thumbnail_image](https://user-images.githubusercontent.com/49133021/151816224-0c2555f0-9bf6-4814-8710-e65a9632f3d9.png)
Do you know what might be happening?

Thanks in advance

**Comment by dsix-ls2n** [comment]
Hello, you should run your script using
`./uorb_to_ros_urtps_topics -i input_file -o output_file`
