### ISSUE TITLE
 Is it possible to get a camera image from the MavSDK using the Gazebo simulator?

### ISSUE THREAD

**Issue by takata1021** [PX4/PX4-Autopilot#19106]
I am making an application that acquires and displays images from the camera protocol of MavSDK.
I don't know how to run the app on the Gazebo simulator.

１．The user guide says only "make px4_sitl_default gazebo_plane_cam", but can I extend MakeFile to use "iris_fpv_cam"?
２．Is it possible to edit MakeFile to increase the drones available in Gazebo?

**Comment by Jaeyoung-Lim** [comment]
@takata1021 The `iris_fpv_cam` is a model for getting a camera wrapper for ROS applications and not simulating a mavlink camera manager. Therefore you cannot use this model with mavsdk to acquire images. (This is also why it has intentionally been left out of the make target)

**Comment by takata1021** [comment]
Thank you
