### ISSUE TITLE
Cannot switch to OFFBOARD mode in PX4 firmware 1.12.3

### ISSUE THREAD

**Issue by awaisk65** [PX4/PX4-Autopilot#19137]
I recently update my multirotor to FW 1.12.3 and tried to switch to 'offboard' mode through MAVROS. No error was shown in QGC and the multirotor could not switch to 'offboard' mode. The terminal gave me following warning
`
CMD: Unexpected command 176, result 0
`
However, I am able to switch to 'AUTO.TAKEOFF' mode and ARM the multirotor through ROS services. I am getting the heartbeat and Firmware version through MAVROS, verified that the system id is correct. Previously, I have been using offboard mode on FW 1.11.1 and it worked fine. I guess there is some issue in the updated firmware.

**Comment by dagar** [comment]
Can you share the full log? https://logs.px4.io

**Comment by r1b4z01d** [comment]
any update?
