### ISSUE TITLE
Problem in Px4 Offboard v1.12.3 

### ISSUE THREAD

**Issue by airsimdevdd** [PX4/PX4-Autopilot#19170]
I'm using PX4 1.12.3 firmware for Fixed-wing sitl in gazebo for multiple vehicle mode doesn't  change to off-board it needs manual 
stick inputs @Jaeyoung-Lim

**Comment by airsimdevdd** [comment]
I enabled virtual joystick but it works for only one vehicle  goes to offboard other vehicle stays in hold mode ,I Want offboard in both vehicles

**Comment by Jaeyoung-Lim** [comment]
@airsimdevdd If you don't want to use RC, you can set `COM_RCL_EXCEPT=4`

This is not a problem of offboard in PX4 v1.12.3, therefore I find the title of this issue misleading.

**Comment by airsimdevdd** [comment]
Thanks for Solutions my problem solved.
