### ISSUE TITLE
Fixedwing doesn't land properly

### ISSUE THREAD

**Issue by airsimdevdd** [PX4/PX4-Autopilot#19181]
RTL and Land doesn't work properly while landing it keeps on gliding doesn't stop and RTL also doesn't works properly its flyaway after loitering ,I'm using Px4-1.12.3

**Comment by Jaeyoung-Lim** [comment]
@airsimdevdd Please explain what was the expected behavior, what yoi tried and what is not working and provide additional materials such as flight logs.

We have issue templates that you can follow if it helps

**Comment by Jaeyoung-Lim** [comment]
Closing as there was no response. Please feel free to reopen.
