### ISSUE TITLE
Gazebo simulation don't takeoff

### ISSUE THREAD

**Issue by Zxr1230** [PX4/PX4-Autopilot#19205]
I followed instructions from this link https://docs.px4.io/master/en/simulation/gazebo.html. The gazebo and PX4 can start but I don't see "commencing GPS fusion" and the drone doesn't takeoff when I  commander takeoff. 
The terminal script is below. How should I solve it? Thanks!
![image](https://user-images.githubusercontent.com/47097582/154562708-261b5cad-d5c9-4403-bba2-dfdf2531e50f.png)

**Comment by Jaeyoung-Lim** [comment]
@Zxr1230 As you can see in the log, failsafe is being triggered as: `Failsafe enabled: no data link` 

This is due to the fact that you don't have a groundcontrol station running along side the SITL simulation.
