### ISSUE TITLE
Any parameter update leads to UDP client source reinitialization

### ISSUE THREAD

**Issue by lukegluke** [PX4/PX4-Autopilot#19215]
UDP mavlink is started on the board: `mavlink start -u 14556`
GCS connects to board, data communication is ok, but when board (by GCS or internally) changes a parameter (even not related to mavlink) there is noticeable ~1s freezes in mavlink communication (for example in GPS data received from board).

I've noticed several messages `INFO  [mavlink] partner IP: 192.168.1.221` in console and discovered that the reason of freezes is reinitialization of partner IP on any parameter updating.

Here when any parameter is updated:
https://github.com/PX4/PX4-Autopilot/blob/8489cec08fcb895a64ce9999034c88098f97f283/src/modules/mavlink/mavlink_main.cpp#L2254-L2255
source initialization state is cleared if multicast is not enabled
https://github.com/PX4/PX4-Autopilot/blob/8489cec08fcb895a64ce9999034c88098f97f283/src/modules/mavlink/mavlink_main.cpp#L2265-L2267
and after this only on first message received from GCS partner IP is initialized again with info message:
https://github.com/PX4/PX4-Autopilot/blob/dab7b007de17b3449b875735d337149716af80c4/src/modules/mavlink/mavlink_receiver.cpp#L3172-L3174
in my case this message is heartbeat from GCS every 1s. If I make it 5 s, the communication will freeze for this 5 seconds.

Enabling multicast `param set MAV_BROADCAST 2` fixes reinitializations and freezes, because it will not clear partner initialization.

I'm using custom f7 based board in custom project (it is somewhere near 1.12+ of px4), but it can be reproduced with QGC too. Start UDP mavlink on board with no broadcast. In QGC enable emitting heartbeat and disable virtual joystick if any (otherwise freezes will not be noticeable due to high rate messages sent from QGC), connect to board and change any parameter in QGC or in nsh. In board console you will notice `INFO  [mavlink] partner IP: x.x.x.x` messages with delay up to 1s after parameter change.
If you disable emitting heartbeat in QGC and change a parameter a connection to board will be lost at all.
Anyway QGC will never connect by UDP if heartbeat from QGC is not enabled in first place. Is this normal and docs warn about this somewhere?

**Comment by lukegluke** [comment]
> As a start I don't see why the `_src_addr_initialized` reset should be happening with parameter updates.

Maybe it was due to possible changes of MAV_BROADCAST parameter while mavlink is already working? Now as I see in recent master these parameters are in effect on mavlink start on boot only.

**Comment by dagar** [comment]
Fixed in https://github.com/PX4/PX4-Autopilot/pull/19216.

**Comment by lukegluke** [comment]
@dagar, what about enabling heartbeat to connect by UDP, that is supposed to be enabled?

**Comment by dagar** [comment]
> @dagar, what about enabling heartbeat to connect by UDP, that is supposed to be enabled?

@lukegluke can you elaborate? I'm not sure what you mean.

Do you mean establishing the client IP explicitly from a particular HEARTBEAT? https://github.com/PX4/PX4-Autopilot/blob/52221b0bb79b241dd4db3e2cba85d84bb521af70/src/modules/mavlink/mavlink_receiver.cpp#L3155-L3176

**Comment by lukegluke** [comment]
I meant that client source initialization is done on first data received from GCS by UDP. Of course this is the only way to work through UDP.
With broadcast heartbeats from px4 and auto UDP connection in QGC everything is cleared. But if user creates a manual UDP connection, he has to enable heartbeat from GCS to establish connection, so px4 receives it, initializes client IP and starts sending vehicle heartbeats back. Otherwise vehicle will never connects.
I suppose docs should warn about this or maybe for UDP links QGC should send heartbeats despite the setting "send heartbeats" until receiving first heartbeat from vehicle.
But when I've written this, I see all of this is related to QGC itself. Sorry for bothering here.

**Comment by dagar** [comment]
> But when I've written this, I see all of this is related to QGC itself. Sorry for bothering here.

No problem, happy to discuss in detail if there's more we should do.
