### ISSUE TITLE
[PROPOSAL] New follow-me mode (discussion)

### ISSUE THREAD

**Issue by mrpollo** [PX4/PX4-Autopilot#19251]
[Follow-Me](https://docs.px4.io/master/en/flight_modes/follow_me.html) is a fun feature of PX4 that allows a drone to follow you around (QGC with a GPS, for example). It's a great way to interact with a drone and have some fun!

The current implementation of the Follow-Me feature doesn't work so well and has many problems described in the document found below.

The goal would be to do a total refactor on the Follow-Me, based on @potaito implementation ( #18026), to improve Follow-Me and make it stable and usable

Team
* @junwoo091400
* @potaito 
* @tstastny 

https://docs.google.com/document/d/1E04Rn6sxYNqKve4-KZYdC2-9LExKmHKuYjWZlwf61rA/edit?usp=sharing

## Let's collect feedback on this thread

**Comment by junwoo091400** [comment]
Since the goal was achieved, would be good to close 🙏
