### ISSUE TITLE
PX4 should emit MAV_PROTOCOL_CAPABILITY_PARAM_ENCODE_BYTEWISE 

### ISSUE THREAD

**Issue by hamishwillee** [PX4/PX4-Autopilot#19275]
The `MAV_PROTOCOL_CAPABILITY_PARAM_ENCODE_BYTEWISE` protocol bit should be set in [`AUTOPILOT_VERSION.capabilities`](https://mavlink.io/en//en/messages/common.html#AUTOPILOT_VERSION) to indicate that parameter values are encoded bytewise in a `float` when they are sent. This is the mechanism used by PX4. Setting the bit tells a GCS that does not know it is connected to PX4 what encoding approach is being used.

The bit was recently renamed, and will become available in PX4 when MAVLink is updated: https://github.com/mavlink/mavlink/pull/1799

**Comment by lukegluke** [comment]
Was done in https://github.com/PX4/PX4-Autopilot/pull/19447, this issue could be closed.
