### ISSUE TITLE
Invalid method name

### ISSUE THREAD

**Issue by msurov** [PX4/PX4-Autopilot#19282]
I found the `Quaternion` class method `conjugate` which actually rotates a vector:
https://github.com/PX4/PX4-Autopilot/blob/80c6ab7106d120c3a815a511614409622803e9fa/src/lib/matrix/matrix/Quaternion.hpp#L488

The name is misleading, because [quaternion conjugation](https://en.wikipedia.org/wiki/Quaternion#Conjugation,_the_norm,_and_reciprocal) is a different operation.

**Comment by MaEtUgR** [comment]
I completely agree. Thanks @msurov for bringing this up and thanks to @bresch for highlighting the issue.
Here's my suggestion: https://github.com/PX4/PX4-Autopilot/pull/19290
