### ISSUE TITLE
No documentation for adding a camera to iris model

### ISSUE THREAD

**Issue by yhdurkaya** [PX4/PX4-Autopilot#19339]
I see that PX4 has changed a bit since I used last time. Now, there are no .xacro files or urdf folder. I want to add a camera to iris model to use on gazebo but I couldn't find anything on how to do. All the sources I found is about those xacro folders and stuff. Is there a documentation about this, I checked but couldn't find.

Thanks!

**Comment by Jaeyoung-Lim** [comment]
@yhdurkaya You can go through creating gazebo models with a sdf in this tutorial: https://gazebosim.org/tutorials?tut=build_model
