### ISSUE TITLE
[PreFlightCheck] Mode not suitable for takeoff

### ISSUE THREAD

**Issue by julianoes** [PX4/PX4-Autopilot#19348]
**Describe the bug**
The simple MAVSDK takeoff and land example does not work properly anymore, that is, it only works once, then it refuses to arm saying "Mode not suitable for takeoff" as it is in Land mode.
This used to work and is very confusing.

**To Reproduce**
1. Start SITL
2. Try https://github.com/mavlink/MAVSDK-Python/blob/main/examples/takeoff_and_land.py with latest mavsdk from pip installed.
3. Run it once.
4. Run it again.

**Comment by julianoes** [comment]
@dagar @MaEtUgR ?

**Comment by Czw007** [comment]
How to modify the code of "takeoff_and_land" to avoid "Mode not suitable for takeoff"?

> **Describe the bug** The simple MAVSDK takeoff and land example does not work properly anymore, that is, it only works once, then it refuses to arm saying "Mode not suitable for takeoff" as it is in Land mode. This used to work and is very confusing.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Start SITL
> 2. Try https://github.com/mavlink/MAVSDK-Python/blob/main/examples/takeoff_and_land.py with latest mavsdk from pip installed.
> 3. Run it once.
> 4. Run it again.

Hello! Can you tell me how to modify the code of "takeoff_and_land.py" to avoid this error "Mode not suitable for takeoff"

**Comment by MaEtUgR** [comment]
@julianoes @Czw007 Does https://github.com/PX4/PX4-Autopilot/pull/19449 not hotfix/unblock this issue? At least for the case you're in land mode after landing. We need an automatic switch to keep being compatible to the arm and then switch mode workflow. I still suggest changing the workflow to first switch the mode and then arm in the future or possibly making it atomic in the state machine in further future.

**Comment by julianoes** [comment]
Yes, thanks @MaEtUgR
