### ISSUE TITLE
No flight data is logged in SD card sometimes.

### ISSUE THREAD

**Issue by Abner0907** [PX4/PX4-Autopilot#19379]
Hi, My branch is based on [v1.12.3](https://github.com/PX4/PX4-Autopilot/releases/tag/v1.12.3).

I have faced a issues that sometimes it will not logged the flight data in the SD card sometimes.  
I am sure it will log the data most of the time.  I am very appreciate that someone has the similar problem and let me know how to fix it.

By the way, I have review the issue  https://github.com/PX4/PX4-Autopilot/issues/18672 but not sure is the same as me.

**Comment by Abner0907** [comment]
This is my sd_bench -r 50 test results:
![Screenshot from 2022-03-23 20-37-08](https://user-images.githubusercontent.com/64906552/159700796-e375850f-8892-4e84-8ca7-abbbb1885fdb.png)

**Comment by Abner0907** [comment]
BTW:  
My hardware is use a private board which is based on a  stm32H743VIT6 chip. 
My card is the below:
![Screenshot from 2022-03-23 21-19-02](https://user-images.githubusercontent.com/64906552/159708583-1fd20665-6f38-432b-86df-55b89a6b99d3.png)

**Comment by dagar** [comment]
How reproducible is the problem? Can you try with master (soon to be v1.13)?

**Comment by spiderkeys** [comment]
Given that you are on an H743-based board, you might want to check out this PR that was merged back in February. If you can't test on master yet, you should be able to try cherry-picking this commit or manually making the change. One of our boards uses the H743VIT6 as well (MatekH743-Wing), and this changed fixed intermittent SD card issues for us.

https://github.com/PX4/PX4-Autopilot/pull/19177

**Comment by Abner0907** [comment]
@dagar  it happens this issues many times, but I have not find the happen regularly. sorry, I can not test v1.13 as soon as possible as some changes in my code.
@spiderkeys  thank you. I will cherry pick your #19177 and test it.

**Comment by Abner0907** [comment]
@spiderkeys Hi, I have a manual making the changes.
I found that #19177 can not fix my issues.



@dagar 
I plug the sd card and found the log exist. But the file name is wrong update. This is the raw log. 
https://drive.google.com/file/d/1r5OoeqqW3wnY0qAZCkJxXaU2ZeknpFgu/view?usp=sharing

![Screenshot from 2022-03-26 14-18-00](https://user-images.githubusercontent.com/64906552/160227429-5c50e68d-8367-48c5-9d71-f4ac701256e0.png)

**Comment by Abner0907** [comment]
@dagar 
another log issues is: while download the log, it will show the error below:
![Screenshot from 2022-03-28 12-12-42](https://user-images.githubusercontent.com/64906552/160325541-164d6201-1fdd-4a1c-a0bf-a49ef06fd8b3.png)

It seems that something wrong is happened while writing the log. and the log record is stopped. but when the vehicle land , and then arm the drone again(without power off), the log will continue record in the next log file.
