### ISSUE TITLE
PX4 Aux output ports not outputting PWM signal when using RC passthrough 3/24/22

### ISSUE THREAD

**Issue by tyrian869** [PX4/PX4-Autopilot#19392]
**Describe the bug**
I've mapped under the radio tab on herelink AUX2 to channel 7 that is clearly moving under the channel monitor

**Expected behavior**
To allow me to control a single servo, that is plugged into the Aux output port of the cube standard carrier board.

**Drone (please complete the following information):**
Generic 10" Octo coaxial geometry, because there was nothing bigger then a 10"................. 

**Additional context**
I've read that the PX4 airframe reference was important when choosing because if it did not show aux ports with Aux rc channel passthrough this would not work? not sure why that would matter as we have the option of configuring these ourselves within QGC.

I've read that people who are doing PWM camera triggers say that they can get the camera to shutter when using trigger PWM signal setup on any one of the six available aux ports,  which is true for me as well, just can't assign RC passthrough for controlling a servo.

I read also that the system has to be armed for both camera shutter trigger test and RC passthrough to work, this was not true for camera shutter as preforming a test shutter on the ground worked just fine without arming, I tried it anyway for RC passthrough but that did not work.

I've tried also setting up landing gear under flight mode as well since that is what this is for, as well as  just assign the RC channel to the aux port directly, nether worked, my tests are on the ground with system suspended. 

I might connect a scope up to the AUX port to see if it's doing anything, perhaps there is a duty cycle that needs adjusting, I've connected a servo but it does nothing. 
I do have +5v supply connected to the aux side output rail.

Can't believe I'm here again.

Hope this helps you help me help others.

**Comment by spiderkeys** [comment]
I don't know if it is exactly the problem you are having, but there are some similar elements to issues I was having with trying to control servos via RC Passthrough under the new control allocator system. I'd be interested to learn what the current 'proper' way of achieving control through RC Passthrough of aux servos is currently supposed to look like... Are you using Control Allocator on your airframe?

Screenshots of my problem description from a slack thread, if it ends up being related:
![Screenshot from 2022-03-24 15-05-04](https://user-images.githubusercontent.com/859469/160018229-1162901c-f124-4af8-b519-85f5416412ee.png)

![Screenshot from 2022-03-24 15-05-55](https://user-images.githubusercontent.com/859469/160018242-44a818be-cea1-49d5-b918-bddde08cdbf7.png)

![Screenshot from 2022-03-18 11-43-43](https://user-images.githubusercontent.com/859469/160018259-653a5a40-991e-48df-bce7-9c157317fb40.png)

**Comment by tyrian869** [comment]
It's not that for this instance we couldn't use Mavlink to make this work,  I was more or less just trying to use what is already in place, this is for a landing gear controller that takes in the PWM signal, to start powering dc brushed motors that are worm driven, that uses amp out technology to stop, old school but for a test bench it's just fine. this actuator outputs menu, I have not seen this before, is that part of QGC? (Q ground control)

**Comment by spiderkeys** [comment]
Yes, the actuators tab will appear in QGC if you are running PX4 with the new control allocation system enabled (SYS_CTRL_ALLOC=1). If you don't see the tab, then the behaviors I saw are probably unrelated. 

Looking at the your airframe's startup scripts, it looks like it still defaults to the old mixer system, so this probably doesn't apply.
