### ISSUE TITLE
KakuteH7 QGC PX4 Master Installation Failed

### ISSUE THREAD

**Issue by vincentpoont2** [PX4/PX4-Autopilot#19432]
**Describe the bug**
With the bootloader `make holybro_kakuteh7_bootloader` flashed onto the board via betaflight configurator. Unable to install PX4 Master via QGC.

**To Reproduce**
1. Flash bootloader `make holybro_kakuteh7_bootloader` to board with betaflight configurator
2. Connect to QGroundcontrol -> advanced settings -> install master

**Expected behavior**
Install KakuteH7 Master Firmware

**Log Files and Screenshots**
![QGrouncontrol-Master](https://user-images.githubusercontent.com/46874772/161253294-9cc9b6a5-a45a-4d5b-890d-e843e915ef90.png)

**Comment by bkueng** [comment]
The board needs to be added to QGC, like this: https://github.com/mavlink/qgroundcontrol/pull/8058
(we really need to make this more generic)

**Comment by vincentpoont2** [comment]
@mrpollo @bkueng Would you be able to assist to on helping the board added to QGC? 

I don't understand how it works in the back end. I tried http://px4-travis.s3.amazonaws.com/Firmware/stable/holybro_kakuteh7_default.px4 and it doesn't work. Does the firmware need to be uploaded first?

**Comment by mrpollo** [comment]
Hey @vincentpoont2 CI automatically builds and uploads to S3 for us, it seems we forgot to include the new board to the list of boards, I fixed that on #19453

**Comment by vincentpoont2** [comment]
@mrpollo is this https://github.com/mavlink/qgroundcontrol/pull/8058 still the correct way to link a board ID to the firmware? 
A lot of the boards aren't on here   [  // Supported bootloader board ids](https://github.com/mavlink/qgroundcontrol/blob/c7c070cfb1fd8fdf4f855f1c5c56d731a1081222/src/VehicleSetup/Bootloader.h#L63) . Would you be able to help us link the Board ID to the firmware S3 link?

![image](https://user-images.githubusercontent.com/46874772/162367271-06b2ada7-3c76-484f-a22f-f82a6967f968.png)

**Comment by Sam2636** [comment]
![Screenshot from 2023-09-27 07-51-56](https://github.com/PX4/PX4-Autopilot/assets/52746303/29651d08-7cbc-47d0-9ec7-f4de78fe3838)
I am getting no gyro found for kakuteh7  how to solve this issue?

**Comment by vincentpoont2** [comment]
> ![Screenshot from 2023-09-27 07-51-56](https://github.com/PX4/PX4-Autopilot/assets/52746303/29651d08-7cbc-47d0-9ec7-f4de78fe3838)
> I am getting no gyro found for kakuteh7  how to solve this issue?
> 

Which version firmware did u install and which version of kakute h7 do you have?

**Comment by julianoes** [comment]
Could this be related to https://github.com/PX4/PX4-Autopilot/issues/22236?
