### ISSUE TITLE
Oscillation in altitude

### ISSUE THREAD

**Issue by cnpcshangbo** [PX4/PX4-Autopilot#19441]
Hello,
I am new to PX4. [This log](https://logs.px4.io/plot_app?log=b228a5f5-7161-422d-8769-981983fdaae1) show that the altitude has an oscillation.
<img width="891" alt="image" src="https://user-images.githubusercontent.com/4831029/161628842-72e16d39-ef79-4ef8-ba8c-809394768c26.png">
I tried to check something in the log, but felt difficult to understand the meaning of the logs. Since the flight was in Stabilize mode, the lever directly controls the throttle. The pilot didn't change the throttle much, but the oscillation happens. We were thinking we need to check those items:
- Motor speed set-points;
- Motor speed estimations;

Hope to get your suggestions.
Thanks,
Bo

**Comment by junwoo091400** [comment]
![Screenshot_20221202_014847](https://user-images.githubusercontent.com/23277211/205189682-253f86b1-4339-4367-8372-4a202c8f16e5.jpg)

The throttle input isn't constant as you said, and is also having slow motions. Could you try again with absolutely still throttle?
