### ISSUE TITLE
Pool Timeout - PX4 Simulator Gazebo

### ISSUE THREAD

**Issue by ZhaiMen-Hub** [PX4/PX4-Autopilot#19567]
**Describe the bug**
I am trying to control each rotor of a quadrotor directly, so I write a `overwrite.main.mix`, which is similar to the pass.aux.mix, and apply it to both a real quad airframe `4001_quad_x` and a simulated quad `if750a`. This mixer works well in the real quad but occurs `ERROR [simulator] poll timeout 0, 22` in the simulator. 

**To Reproduce**
I commit my code on GitHub, which was developed on branch `release/v1.12`:
https://github.com/ErcBunny/PX4-Autopilot/tree/overwrite-main-v1.12-issue
1. To reproduce the error:
    - run the simulation: `make px4_sitl gazebo_if750a`
    - pub actuator_controls_1 to overwrite mixer: `px4_simple_app 1 -1 -0.5 0.5 1 `
2. Apply it on a real quadrotor: 
    - ` make cubepilot_cubeorange `
    - `px4_simple_app 1 -1 -0.5 0.5 1 `

**Log Files and Screenshots**
- Screenshot about the error occurring in simulation.
![image-20220502112555175](https://user-images.githubusercontent.com/44313617/166195591-17f4bbf0-4571-4c89-ab29-6e81116ebd2e.png)

- Screenshot about the mixer working well in a real quad. 
![image](https://user-images.githubusercontent.com/44313617/166195839-6950883d-485a-4503-b2bd-2459b37674e9.png)

**Additional context**
I find a similar issue about 'ERROR [simulator] poll timeout 0, 22' here: 
https://github.com/PX4/PX4-Autopilot/issues/19203 
and a disscussion: 
https://discuss.px4.io/t/px4-poll-timeout/20484 

Thanks!

**Comment by zhikh1** [comment]
Did you manage to solve the problem? I am facing the same behavior with my custom model

**Comment by julianoes** [comment]
If you are publishing actuator_controls directly, you need to use SITL without lockstep:

https://docs.px4.io/main/en/simulation/#disable-lockstep-simulation

**Comment by schefferac2020** [comment]
My issue was not including the correct imu, barometer, and magnetometer models

**Comment by julianoes** [comment]
@ZhaiMen-Hub can this be closed? Did you find a fix?

**Comment by ZhaiMen-Hub** [comment]
No. Because we didn't find a solution at that time, we this attempt is terminated in June 2022

**Comment by julianoes** [comment]
Ok thanks for the note.
