### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by cjychenjiayi** [PX4/PX4-Autopilot#19572]
I've install all the document under the guideline， when I type make px4_fmu-v4_rtps, it shows  as below:
Makefile:527: *** "Make target px4_fmu-v4_rtps not found. It either does not exist or px4_fmu-v4_rtps cannot be the first argument. Use 'make help|list_config_targets' to get a list of all possible [configuration] targets.".  Stop.
make px4_fmu-v4 , make px4_sitl_rtps can both run successfully, I don't know why it happened
my system is Ubuntu 20.04
Looking forward to help, thx

**Comment by chenrc98** [comment]
Create a file in `PX4_Source/boards/px4/fmu-v4` named `rtps.px4board` and put the following line`CONFIG_MODULES_MICRORTPS_BRIDGE=y` into the file. Then try `make px4_fmu-v4_rtps`

**Comment by cjychenjiayi** [comment]
Thx for your help, it worked!
