### ISSUE TITLE
Gradle assemble went wrong when install Fast-RTPS-Gen

### ISSUE THREAD

**Issue by cjychenjiayi** [PX4/PX4-Autopilot#19617]
![image](https://user-images.githubusercontent.com/71555947/167421942-271bfb1e-99b4-41b2-a860-f5c69ed06765.png)
this is what shows in my terminal. My gradle version is 6.3
![image](https://user-images.githubusercontent.com/71555947/167421897-3ae372cd-4f42-4afc-8814-0e9c111772bc.png)
this is the corresponding build.gradle document, the blue part is where the error happened I don't know why it worked improperly, I just done the same thing correctly at another computer.  I followed the tutorial but stuck at "gradle assemble" step.
Looking forward to help, thx

**Comment by husseinalijaafar** [comment]
How did you install gradle? sdkman?

**Comment by cjychenjiayi** [comment]
> How did you install gradle? sdkman?

yeah, by sdkman
