### ISSUE TITLE
 RTT too high for timesync

### ISSUE THREAD

**Issue by Abner0907** [PX4/PX4-Autopilot#19626]
hi, I have a question, in which situation and what will cause this, it will print 
>[mavlink] [timesync] RTT too high for timesync: 165 ms (sender: 1)

My print information shows as below:

![Screenshot from 2022-05-10 19-52-19](https://user-images.githubusercontent.com/64906552/167622182-685f1187-b20b-4b1b-95bf-2e2ff6c795b9.png)
 I have seen @bkueng  had add a print information https://github.com/PX4/PX4-Autopilot/pull/15539, I am very appreciate anyone who can leave some notes here.

**Comment by Abner0907** [comment]
This is my test log, https://logs.px4.io/plot_app?log=3a7a7624-41c0-4f1d-b450-8475744ed50d

**Comment by bkueng** [comment]
compid=1 is the autopilot, do you have a routing loop?

**Comment by Abner0907** [comment]
@bkueng I think I  do not have a routing loop in autopilot.  But I have a onboard computer and send the mavlink to fc(autopilot) through serial. I have checked, it do not send the message id 'MAVLINK_MSG_ID_TIMESYNC' to the fc.

**Comment by Abner0907** [comment]
@bkueng 
Thanks,  I get the cause reason.
I have add an outside mavlink `handle_message_odometry()` which will sync time below, it cause the issues.
https://github.com/PX4/PX4-Autopilot/blob/fc7e979d84715ca71e9de025492a1c59673e415d/src/modules/mavlink/mavlink_receiver.cpp#L1397
