### ISSUE TITLE
MAV_CMD_DO_REPOSITION fails when only changing yaw

### ISSUE THREAD

**Issue by DonLakeFlyer** [PX4/PX4-Autopilot#19722]
I found this testing master sitl. Not sure when this broke but it used to work. Here are the value I'm sending starting with param 1:

```
                -1,                                                                                    // no change in ground speed
                MAV_DO_REPOSITION_FLAGS_CHANGE_MODE,    // switch to guided mode
                0,                                                                                    //reserved
                qDegreesToRadians(headingDegrees),                      // change heading
                qQNaN(), qQNaN(), qQNaN());                                   // no change lat, lon, alt
```

This results in a positive ack for the command but the vehicle does nothing. This is caused by a bug in navigator_main.cpp falling through there here: https://github.com/PX4/PX4-Autopilot/blob/master/src/modules/navigator/navigator_main.cpp#L306 in this case. The code is incorrect in that it is only looking at lat/lon/alt for nans but there could be a value in yaw. I have a fix for it which I'll post soon.

**Comment by dagar** [comment]
Fixed in https://github.com/PX4/PX4-Autopilot/pull/19725.
