### ISSUE TITLE
Divide by zero when calculating IMU integration interval

### ISSUE THREAD

**Issue by davegelwan** [PX4/PX4-Autopilot#19760]
## Describe the bug
Divide by zero in VehicleIMU::ParametersUpdate method in VehicleIMU.cpp when IMU_GYRO_RATEMAX is set to zero.  This causes the estimator to fail and complete loss of control of drone!

## To Reproduce
1. Fixed-wing drone with v1.13.0-alpha1-4403-g5717434e93 software
2. IMU_GYRO_RATEMAX set to zero (default in QGroundControl)
3. Takeoff
4. Trigger VehicleIMU::ParametersUpdate method by changing a parameter
5. Complete loss of control of drone

## Expected behavior
Divide macro which checks for zero before dividing!

## Log Files and Screenshots
VehicleIMU::ParametersUpdate method annotated:
![image](https://user-images.githubusercontent.com/95655460/171721630-bd9b2512-a530-4ec6-bcd9-5dcacb38c024.png)

QGroundControl defaults IMU_GYRO_RATEMAX to zero for fixed-wing vehicles:
![image](https://user-images.githubusercontent.com/95655460/171719124-875da07b-7881-4883-9ed0-99246b10e1df.png)

Link to problematic commit:
https://github.com/PX4/PX4-Autopilot/commit/aa64789792d551a5a4be0dda22606cac33449f98

## Drone:
- Fixed-wing drone
- QGroundControl defaults
- PX4-Autopilot v1.13.0-alpha1-4403-g5717434e93 software

**Comment by dagar** [comment]
Sorry to hear about the crash. Within VehicleIMU the actual intervals are calculated from actual data publication rates, so I think it might be easier to skip the IMU_GYRO_RATEMAX constraint in the first place. The IMU_GYRO_RATEMAX default is no longer 0.

Can you review https://github.com/PX4/PX4-Autopilot/pull/19765?
