### ISSUE TITLE
13.0rc1 airspeed calibration not possible

### ISSUE THREAD

**Issue by jstrebel** [PX4/PX4-Autopilot#19772]
Can't calibrate airspeed using sdp3x sensor. Error message: calibration failed
I tried with two SDP3x sensors and with two holybro (pixhawk4 and pixhawk4 mini)
Attached: logs and debug info.
[1.13rc1_sensor status.txt](https://github.com/PX4/PX4-Autopilot/files/8852777/1.13rc1_sensor.status.txt)
![sdp3](https://user-images.githubusercontent.com/2244311/172369335-2fb580a2-22f4-46ad-b344-febdeda977c5.JPG)
[sdp3.txt](https://github.com/PX4/PX4-Autopilot/files/8852778/sdp3.txt)

**Comment by ryanjAA** [comment]
But you’re not supposed to calibrate those. It’s still giving you an airspeed preflight error (and red icon) in QGC unless you try to calibrate? 

What about entering in value of 50 into the dpres parameter. Does they make it go away (meaning it’s expecting a successful calibration even though there should not be one?

**Comment by dagar** [comment]
It appears they aren't starting.

Can you run `i2cdetect` across the external buses and share the output?

Could you also share the output of `dmesg` so we can see if anything failed at startup?

**Comment by sfuhrer** [comment]
Did you enable the sensor via SENS_EN_SDP3X?

**Comment by sfuhrer** [comment]
>But you’re not supposed to calibrate those. It’s still giving you an airspeed preflight error (and red icon) in QGC unless you try to calibrate?

A very valid input. We could make the airspeed calibration optional, like we did for the Level Horizon some time ago,

**Comment by jstrebel** [comment]
@sfuhrer This was the cause. My apology, did read the updated documentation!

**Comment by sfuhrer** [comment]
All good, happy I could help!
