### ISSUE TITLE
Negative RC threshold not working in v1.13.0

### ISSUE THREAD

**Issue by Katawann** [PX4/PX4-Autopilot#19809]
### Describe the bug
I would like to trigger the RTL mode when the switch is at its low value instead of high. In v1.10.1 I could use the parameter [RC_RETURN_TH](https://dev.px4.io/master/en/advanced/parameter_reference.html#RC_RETURN_TH) with a negative value to obtain this behavior. The same parameter in v1.13.0-rc1 has no effect (the RTL mode is not triggered at all when you set a negative value). The workaround is to change the RCX_REV of the corresponding channel but it is not the best solution as this value is cleared when you redo a radio calibration

### To Reproduce
1. Set the Return mode to a channel
2. Change the RC_RETURN_TH to a negative value >= -1
3. The RTL is not triggered anymore

### Expected behavior
Threshold when lower than the value instead of higher 

I guess the issue is the same with all RC mode. Thank you for your help !

**Comment by brunweil** [comment]
not sure but it's looks like: I get something similar with Flap on chanel 6:
in V1.12.3 minFlap with 1000us, half flaps at 1500us, full flap at 2000us
in v1.13.0 minFlap with 1000us, always minFlap at 1500us & full flap at 2000us

**Comment by Katawann** [comment]
Hi @junwoo091400,

The problem is still existing on the v1.13.2. Do you have any update regarding this issue or a fix in main branch that I missed ?

Thank you for your help !

**Comment by Katawann** [comment]
Temporally fixed by setting RC6_REV (used in my case for the RTH) to 1 

This need to be done after calibration of the RC

**Comment by junwoo091400** [comment]
> The problem is still existing on the v1.13.2. Do you have any update regarding this issue or a fix in main branch that I missed ?

Hi @Katawann I missed this! I have added this to the v1.14 project board to keep track of it 🙌, thanks for the report and reminder!

**Comment by Katawann** [comment]
Hi @junwoo091400,

I reopen the issue as I just tried on v1.14 and the issue is still there

**Comment by junwoo091400** [comment]
I have created a Fix PR for this linked above @Katawann 🙏. Thank you again for the report!
