### ISSUE TITLE
 when make px4_sitl_default gazebo

### ISSUE THREAD

**Issue by 747640013** [PX4/PX4-Autopilot#19887]
ninja: error: '../../src/lib/events/libevents/events/common.json', needed by 'events/common_with_enums.json', missing and no known rule to make it
Makefile:230: recipe for target 'px4_sitl_default' failed
make: *** [px4_sitl_default] Error 1

**Comment by 747640013** [comment]
> ninja: error: '../../src/lib/events/libevents/events/common.json', needed by 'events/common_with_enums.json', missing and no known rule to make it Makefile:230: recipe for target 'px4_sitl_default' failed make: *** [px4_sitl_default] Error 1

**Comment by liurxing** [comment]
Hello, how did you solve this problem？

**Comment by 747640013** [comment]
Mostly due to network issues, the source code was not fully downloaded, or the script did not complete execution entirely.

**Comment by liurxing** [comment]
> 

Okay, thanks！

**Comment by ynyl123** [comment]
hello,I've downloaded src/lib/events/libevents/events/common.json, but the error still shows that the file is missing, How can I fix this?
ninja: error: 'src/lib/events/libevents/events/common.json', needed by 'events/common_with_enums.json', missing and no known rule to make it
make: *** [Makefile:227：px4_sitl] Error 1
