### ISSUE TITLE
EKF2 start fail error with EKF2 Replay 

### ISSUE THREAD

**Issue by thermofluid06** [PX4/PX4-Autopilot#19969]
## Describe the bug
EKF module is not starting in replay mode and the replay returns "Startup script returned with return value: 65280
" after following the steps described in [https://docs.px4.io/v1.12/en/debug/system_wide_replay.html](https://docs.px4.io/v1.12/en/debug/system_wide_replay.html)

## To Reproduce
1.  Checkout to main branch (at the time of writing -- `97f632a408` ) 
2.  Build for sitl target to generate a sample ulog file by `make px4_sitl_default jmavsim`
3. Follow the instructions from the EKF2 Replay in this [tutorial](https://docs.px4.io/v1.12/en/debug/system_wide_replay.html)
4. After target is built in replay mode, parameters cannot be exported, ekf2 module doesn't start. Replay stops and returns the value 65280 as in the screenshot below.
5. Problem exists also if the ulog file is generated by the FMU.

## Expected behavior
Replay should be completed and another ulog file with the replayed data should be generated.

## Log Files and Screenshots

![Screenshot](https://user-images.githubusercontent.com/37408853/181172751-46fa0d5e-e9de-410a-8cf0-d9e94d27b138.png)

## Drone (please complete the following information):
- Describe the type of drone.
- Photo of the IMU / autopilot setup if possible.

## Additional context
Ubuntu 20.04 , Holybro Pixhawk 4, Ublox F9P RTK Gnss Receiver

**Comment by bresch** [comment]
fixed by https://github.com/PX4/PX4-Autopilot/pull/20016
