### ISSUE TITLE
Can not change param of Kakute H7 using QGC.

### ISSUE THREAD

**Issue by ckl677** [PX4/PX4-Autopilot#19992]
## Describe the bug
Can not change param of Kakute H7 using QGC.When I used a USB cable to connect the flight control board and QGC, I tried to modify the parameters. After saving, I powered off the flight control board, and the parameters could not be saved when powering on again.My QGC version is v4.2.0,my firmware version is v1.13.0-beta1.

**Comment by PrcsnFlyer** [comment]
Do you have an SD-Card in use? You can define if the parameters get saved in Flash or on the SD-Card.

**Comment by ckl677** [comment]
I do not have sd card,it is the problem,i fixed it now,thanks!

**Comment by kokoory** [comment]
> I do not have sd card,it is the problem,i fixed it now,thanks!

how did you fix it?
