### ISSUE TITLE
Nuttx Target Auto-build Flash Overflowed Error

### ISSUE THREAD

**Issue by vincentpoont2** [PX4/PX4-Autopilot#20088]
On all recent PR, v5, v5x, v6x Nuttx Target Auto build encounters `FLASH' overflowed. Any recommended workaround or way to fix this?

![image](https://user-images.githubusercontent.com/46874772/185911054-f1aba782-b299-4ae4-a702-82ba0b0ec0d9.png)

**Comment by logos-electromechanical** [comment]
I have the same issue with the Pixhawk 6x. I solved it by going through and disabling modules and drivers I didn't think I'd be using until it compiled. This is... not ideal.

**Comment by julianoes** [comment]
I assume the #20108 PR will fix this.

Until then, I was suggesting to update to arm-none-eabi-gcc 10.3 which saves a bit of flash as well: #20179.
