### ISSUE TITLE
Pixhawk 6X Accelerometer Calibration Error - Release/1.13 Branch

### ISSUE THREAD

**Issue by vincentpoont2** [PX4/PX4-Autopilot#20091]
## Describe the bug
Unable to calibrate Pixhawk 6X FC when using Release/1.13 branch. Issue does not occur in Master FW. 

[1.13.1 listener sensor_accel.txt](https://github.com/PX4/PX4-Autopilot/files/9395951/1.13.1.listener.sensor_accel.txt)
[1.13.1 Test Cal Error.txt](https://github.com/PX4/PX4-Autopilot/files/9395952/1.13.1.Test.Cal.Error.txt)
[1.13.1 Test Dmesg.txt](https://github.com/PX4/PX4-Autopilot/files/9395953/1.13.1.Test.Dmesg.txt)

https://user-images.githubusercontent.com/46874772/185969731-ffdfa3c2-1709-44d2-bc73-4fe997c22be8.mp4

## To Reproduce
1. Build with release/1.13 branch.
2. Calibration Accelerometer on a Pixhawk 6X.

**Comment by julianoes** [comment]
I couldn't always reproduce the accel problem, but also the gyro calibration did not work at all.

That's because gyro instance 2 only seemed to publish once and then stopped which matches the warning that you see about accel 2.

@dagar's fixes in https://github.com/PX4/PX4-Autopilot/pull/19660 seem to fix that. Once I cherry picked these two commits onto the `release/1.13` branch, the calibration for gyro and accel looked much better for me.

Before:

```
INFO  [commander] [cal] calibration started: 2 gyro
INFO  [commander] [cal] progress <0>
INFO  [commander] [cal] progress <0>
INFO  [commander] [cal] progress <0>
INFO  [commander] [cal] progress <0>
INFO  [commander] [cal] progress <0>
INFO  [commander] [cal] progress <0>
INFO  [commander] [cal] progress <0>
...
[stuck forever]
```

```
INFO  [commander] [cal] calibration started: 2 accel
...
INFO  [commander] [cal] Hold still, measuring up side
ERROR [commander] [cal] accel 2 invalid Z-axis, check rotation
WARN  [commander] [cal] calibration failed: accel
```

After:
```
nsh> INFO  [commander] [cal] calibration started: 2 gyro
...
GYRO 2424858 EN: 1, offset: [-0.038 -0.007 -0.000], Internal
GYRO 2490386 EN: 1, offset: [-0.005 0.013 0.012], Internal
GYRO 2752522 EN: 1, offset: [0.006 -0.020 -0.003], Internal
INFO  [commander] [cal] calibration done: gyro
```

```
nsh> INFO  [commander] [cal] calibration started: 2 accel
...
ACC 2424858 EN: 1, offset: [0.141 0.022 -0.067], scale: [1.001 1.001 0.981], Internal
ACC 2490386 EN: 1, offset: [0.049 0.011 -0.172], scale: [1.000 1.000 1.000], Internal
ACC 2752522 EN: 1, offset: [-0.003 -0.057 0.008], scale: [1.000 1.000 1.000], Internal
INFO  [commander] [cal] calibration done: accel
```
