### ISSUE TITLE
PX4 is not sending RTCMStream DroneCAN msgs

### ISSUE THREAD

**Issue by vincentpoont2** [PX4/PX4-Autopilot#20134]
## Describe the bug
PX4 is not sending RTCMStream DroneCAN msgs, which it should be sending when it gets GPS_RTCM_DATA MAVLink messages. Test with DroneCAN F9P RTK, used DroneCAN GUI tool and PX4 isn't sending them.

## To Reproduce
Using a DroneCAN F9P RTK, unable to get RTK GPS Lock. 
![image](https://user-images.githubusercontent.com/46874772/187644136-08e2a7f9-234d-4246-84e1-5b68363400ac.png)

Repeat the same with a i2c F9P RTK, no issue
![image](https://user-images.githubusercontent.com/46874772/187644380-b141d985-0c68-4d2d-8a0f-1f56edb1e9ea.png)

**Comment by AlexKlimaj** [comment]
Enable UAVCAN_PUB_RTCM
https://github.com/PX4/PX4-Autopilot/blob/main/src/drivers/uavcan/uavcan_params.c#L207

**Comment by OfficerJannis** [comment]
I have the same problem. I tested the issue with an _Here3 GPS_ in CAN mode, aswell as in serial mode: 

In CAN mode the GPS lock does **not** switch to RTK (float), although i was sending RTCM-Date via MavLink. 
When i open the CLI, the `uavcan status` printout _gnss rtcm publisher counter_ increases.  

In serial mode the GPS lock switches immediately to RTK (float) if i send RTCM-Data via MavLink.

I tested this with the latest stable PX4 1.13.
The parameter UAVCAN_PUB_RTCM mentioned by @AlexKlimaj  is not in the latest stable build.

Then i also tested the latest developer build (master) which has the parameter UAVCAN_PUB_RTCM included. I also enabled it.
In CAN mode i don't get RTK and the the `uavcan status` printout _gnss rtcm publisher counter_ stops at 1 event.
I also enabled the UAVCAN_PUB_MBD parameter, still no RTK.

**Comment by AlexKlimaj** [comment]
UAVCAN_PUB_RTCM is currently broken in main. See the fix here https://github.com/PX4/PX4-Autopilot/pull/20056

**Comment by AlexKlimaj** [comment]
Fixed with https://github.com/PX4/PX4-Autopilot/pull/20056
