### ISSUE TITLE
Gazebo SITL - Boat

### ISSUE THREAD

**Issue by ArturZolich** [PX4/PX4-Autopilot#20235]
An SDF file of boat model is broken, which causes SITL to hang during loading. No clear error is indicated.
The problem is caused by line 456:
   ` </plugin>`
which doesn't have a start-tag. Removing the line solves the issue.

I discovered the issue following a tutorial on SITL and trying to make gazebo_boat:
make px4_sitl gazebo_boat
(https://docs.px4.io/main/en/simulation/gazebo.html)

**Comment by Jaeyoung-Lim** [comment]
@ArturZolich Thanks, would you be able to make a Pull Request in https://github.com/PX4/PX4-SITL_gazebo ?
