### ISSUE TITLE
Apple M1 make "px4_sitl jmavsim" problem

### ISSUE THREAD

**Issue by msasen** [PX4/PX4-Autopilot#20246]
Device: Apple M1 macbook air.

I run the command make "px4_sitl jmavsim", it failing and giving below error I tried all solution on the internet nothing worked.

<img width="1440" alt="Ekran Resmi 2022-09-19 14 49 53" src="https://user-images.githubusercontent.com/29780691/191010989-28be4d71-d888-495e-a7fb-d84b880ca910.png">

**Comment by dagar** [comment]
Thanks for reporting, @bkueng already had a little fix for this that I've cherry-picked to main. https://github.com/PX4/PX4-Autopilot/commit/c707997b9e8c8766e64d6b91806117e051647a86
