### ISSUE TITLE
Set default PWM to 50Hz

### ISSUE THREAD

**Issue by jstrebel** [PX4/PX4-Autopilot#20258]
Please set the default PWM frequency to 50Hz. 
Analog Servos get "overloaded" and burn. I refer to Issue #19866
Just tested, fired up 1.13.beta (current main)

**Comment by dagar** [comment]
@bkueng

**Comment by bkueng** [comment]
This was already done in https://github.com/PX4/PX4-Autopilot/pull/19991 (not sure if it's in 1.13). @jstrebel did you see that? Anything missing?

**Comment by jstrebel** [comment]
Just tested it again after the discussion we had yesterday in the Fixed Wing call. 
If Servo is selected in PWM then the value of 50Hz is shown in the screen. 
(without any selection of Servo we see 400hz)  We can close this!
