### ISSUE TITLE
Fixedwing RTL failsafe makes the vehicle crash right after takeoff

### ISSUE THREAD

**Issue by Jaeyoung-Lim** [PX4/PX4-Autopilot#20260]
## Describe the bug
When running takeoff in SITL without QGC running, the plane immediately goes into failsafe, goes into RTL and then crases

## To Reproduce
Steps to reproduce the behavior: (Make sure no QGC is running)
1. Start plane SITL simulation
```
make px4_sitl gazebo_plane
```
2. Command takeoff
```
commander takeoff
```

## Expected behavior
- Vehicle should either takes off or rejects the takeoff command

## Log Files and Screenshots
![plane_bug](https://user-images.githubusercontent.com/5248102/191316218-3a925953-5b73-4fca-82e9-a51dd60b0ded.gif)
- Flight log: https://review.px4.io/plot_app?log=0314e693-cb1e-4675-a7ef-bad36473a129
- Log:
```
pxh> commander takeoff
pxh> INFO  [commander] Armed by internal command	
INFO  [tone_alarm] arming warning
INFO  [navigator] Using minimum takeoff altitude: 30.00 m	
INFO  [fw_pos_control_l1] Takeoff on runway	
INFO  [commander] Takeoff detected	
WARN  [commander] Failsafe enabled: no datalink	
INFO  [commander] Failsafe mode activated	
INFO  [tone_alarm] battery warning (fast)
INFO  [navigator] RTL: landing at home position.	
INFO  [navigator] RTL: climb to 589 m (100 m above destination)	
INFO  [commander] Failsafe mode deactivated	
WARN  [health_and_arming_checks] Preflight Fail: velocity estimate error
ERROR [commander] Critical failure detected: lockdown	
WARN  [commander] Motor failure detected	
WARN  [health_and_arming_checks] Preflight Fail: velocity estimate error
```

**Comment by bkueng** [comment]
Fixed in https://github.com/PX4/PX4-Autopilot/pull/20172
