### ISSUE TITLE
Control Allocator Outputs Not Working on FMUV6X 1.13

### ISSUE THREAD

**Issue by AlexKlimaj** [PX4/PX4-Autopilot#20276]
Enable the control allocator, reboot, and PWM main and aux outputs do not show up on the actuator page for fmuv6x 1.13.

![image](https://user-images.githubusercontent.com/2019539/191569657-87965b70-ef55-4ebd-bb3a-8df747a002e5.png)

**Comment by ryanjAA** [comment]
Tried as well - same result.

**Comment by vincentpoont2** [comment]
Does this only happen on the v6X?

**Comment by ryanjAA** [comment]
I selected quad x but doesn’t happen on 6c but that is on latest main. Will check uavcan status above.

**Comment by AlexKlimaj** [comment]
Building the latest release/1.13 branch it looks like it is working on the v5x and v6x thanks to @julianoes recent work.

**Comment by julianoes** [comment]
Oh, not sure what I did but I guess that's good.
