### ISSUE TITLE
OFFBOARD not working

### ISSUE THREAD

**Issue by Cavalletta98** [PX4/PX4-Autopilot#20371]
Hi, i'm using the branch release/1.13 with the lastest commit and try to set the drone into OFFBOARD via QGroundControl but it is not working. Can someone could help me?
I'm getting this feedback from PX4:
`[ WARN] [1665065699.177400041, 472.568000000]: CMD: Unexpected command 176, result 1`
`INFO  [tone_alarm] notify negative`

**Comment by Cavalletta98** [comment]
I'm launching the simulation with the command: `roslaunch px4 posix_sitl.launch`. Then a set,from QGroundcontrol the OFFBOARD mode

**Comment by Jaeyoung-Lim** [comment]
@Cavalletta98 That is the expected behavior. There is a safety mechanism, so that the vehicle rejects offboard mode if you are not supplying the vehicle with any setpoints.

You can read about offboard mode in https://docs.px4.io/main/en/flight_modes/offboard.html#offboard-mode

**Comment by Cavalletta98** [comment]
ok thank you for your clarification
