### ISSUE TITLE
Resource not found: px4 ROS path [0] ..

### ISSUE THREAD

**Issue by JomondLim** [PX4/PX4-Autopilot#20437]
After following the offboard control example (python), when running roslaunch offboard_py start_offb.launch, i received this error despite adding the extra few lines to the bashrc as instructed in the tutorial:
Resource not found: px4
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/home/ubuntu/catkin_ws/src/mavlink
ROS path [2]=/home/ubuntu/catkin_ws/src/mavros/libmavconn
ROS path [3]=/home/ubuntu/catkin_ws/src/mavros/mavros_msgs
ROS path [4]=/home/ubuntu/catkin_ws/src/mavros/mavros
ROS path [5]=/home/ubuntu/catkin_ws/src/mavros/mavros_extras
ROS path [6]=/home/ubuntu/catkin_ws/src/offboard_py
ROS path [7]=/home/ubuntu/catkin_ws/src/mavros/test_mavros
ROS path [8]=/opt/ros/melodic/share
The traceback for the exception was written to the log file

This is what my .bashrc file is looking like:

source /opt/ros/melodic/setup.bash
source ~/PX4-Autopilot/Tools/simulation/gazebo/setup_gazebo.bash ~/PX4-Autopilot ~/PX4-Autopilot/build/px4_sitl_default
source /home/ubuntu/catkin_ws/devel/setup.bash
export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH:~/PX4-Autopilot
export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH:~/PX4-Autopilot/Tools/simulation/gazebo/sitl_gazebo
export GAZEBO_MODEL_PATH=$GAZEBO_MODEL_PATH:~/PX4-Autopilot/Tools/simulation/gazebo/sitl_gazebo
export GAZEBO_PLUGIN_PATH=$GAZEBO_PLUGIN_PATH:/usr/lib/aarch64-linux-gnu/gazebo-9/plugins

Would appreciate if someone helps with this issue.
Thanks in advance

**Comment by Jaeyoung-Lim** [comment]
@JomondLim Are you sure your PX4 autopilot source exists in the path `/PX4-Autopilot` ?

You can check with
```
ls /PX4-Autopilot
```

**Comment by JomondLim** [comment]
@Jaeyoung-Lim 

Hi thanks for the reply, 

When entering ls /PX4-Autopilot in home directory
ls: cannot access '/PX4-Autopilot': No such file or directory

**Comment by stevenchangg** [comment]
Hi @JomondLim

Currently I am facing the same issue as you :( 
Have u figured out the solution to it ? Would mean a lot as I have been struggling with this issue for a week  @Jaeyoung-Lim 
Thank you

**Comment by FrancSerra** [comment]
I'm currently facing the exact same problem. DId you guys managed to fix this? I really need help on this. Thank you very much

**Comment by beniaminopozzan** [comment]
@FrancSerra are you referring to this script?
https://docs.px4.io/main/en/ros/mavros_offboard_python.html#launching-your-script

**Comment by FrancSerra** [comment]
> @FrancSerra are you referring to this script? https://docs.px4.io/main/en/ros/mavros_offboard_python.html#launching-your-script

Yes indeed I am

**Comment by beniaminopozzan** [comment]
ok, then try to use
```sh
source ~/PX4-Autopilot/Tools/simulation/gazebo-classic/setup_gazebo.bash ~/PX4-Autopilot ~/PX4-Autopilot/build/px4_sitl_default
export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH:~/PX4-Autopilot
export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH:~/PX4-Autopilot/Tools/simulation/gazebo-classic/sitl_gazebo-classic
```
instead of
```sh
source ~/PX4-Autopilot/Tools/simulation/gazebo/setup_gazebo.bash ~/PX4-Autopilot ~/PX4-Autopilot/build/px4_sitl_default
export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH:~/PX4-Autopilot
export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH:~/PX4-Autopilot/Tools/simulation/gazebo/sitl_gazebo
export GAZEBO_PLUGIN_PATH=$GAZEBO_PLUGIN_PATH:/usr/lib/x86_64-linux-gnu/gazebo-9/plugins
```

the reason is the `sitl_gazebo` has been renamed `sitl_gazebo-classic` and it is now located in `Tools/simulation/gazebo-classic/sitl_gazebo-classic`

**Comment by pranavc2255** [comment]
> ok, then try to use
> 
> ```shell
> source ~/PX4-Autopilot/Tools/simulation/gazebo-classic/setup_gazebo.bash ~/PX4-Autopilot ~/PX4-Autopilot/build/px4_sitl_default
> export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH:~/PX4-Autopilot
> export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH:~/PX4-Autopilot/Tools/simulation/gazebo-classic/sitl_gazebo-classic
> ```
> 
> instead of
> 
> ```shell
> source ~/PX4-Autopilot/Tools/simulation/gazebo/setup_gazebo.bash ~/PX4-Autopilot ~/PX4-Autopilot/build/px4_sitl_default
> export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH:~/PX4-Autopilot
> export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH:~/PX4-Autopilot/Tools/simulation/gazebo/sitl_gazebo
> export GAZEBO_PLUGIN_PATH=$GAZEBO_PLUGIN_PATH:/usr/lib/x86_64-linux-gnu/gazebo-9/plugins
> ```
> 
> the reason is the `sitl_gazebo` has been renamed `sitl_gazebo-classic` and it is now located in `Tools/simulation/gazebo-classic/sitl_gazebo-classic`

Did anyone solve this issue?

I am still getting the same error, even changing to gazebo-classic?

**Comment by pranavc2255** [comment]
> I'm currently facing the exact same problem. DId you guys managed to fix this? @stevenchangg @JomondLim. I really need help on this. Thank you very much

Did you solve my friend?

**Comment by Jaeyoung-Lim** [comment]
@pranavc2255 High chance that your change to `gazebo-classic` was incomplete.
Please share what you actually did

**Comment by mgrallos** [comment]
I'm getting the same error and I'm new to PX4. what if I use this for simulatio "make -j8 px4_sitl_default gazebo "
 and not gazebo-classic? 
Also, I don't see a "simulation" folder inside my /PX4-Autopilot/Tools directory.

**Comment by beniaminopozzan** [comment]
@mgrallos 
please share which PX4 version / commit / tag you are currently using.

**Comment by mgrallos** [comment]
> @mgrallos please share which PX4 version / commit / tag you are currently using.
it says v1.12.3

![image](https://github.com/PX4/PX4-Autopilot/assets/64775540/e5de4caa-1dfa-436b-987d-b6c7ad31a6bb)

**Comment by mgrallos** [comment]
here's the inside my PX4-Autopilot/Tools directory 
![image](https://github.com/PX4/PX4-Autopilot/assets/64775540/c63d3fc2-2374-4ac3-9024-5bc83cf8795d)

**Comment by beniaminopozzan** [comment]
@mgrallos , you are working with version 1.12 then, please follow the gazebo simulation documentation for that version
https://docs.px4.io/v1.12/en/simulation/gazebo.html
