### ISSUE TITLE
release v1.13.1 error "vehicle_command lost, generation xxx -> xxx"

### ISSUE THREAD

**Issue by 473867143** [PX4/PX4-Autopilot#20454]
## Describe the bug
Mavros disconnects when running offboard node,Shut down the node mavros to restore the connection.System console prompt "ERROR [mavlink] COMMAND_LONG vehicle_command lost, generation 1496 -> 2259" ,
"ERROR [commander] vehicle_command lost, generation 2273 -> 2276",
"ERROR [navigator] vehicle_command lost, generation 2266 -> 2365",
"ERROR [mavlink] vehicle_command_ack lost, generation 839 -> 879"

![图片](https://user-images.githubusercontent.com/26379380/196835946-311709d6-7169-4f9e-a191-9f626148b644.png)

When I use the main branch or realease v1.12.3 branch, Don't have this problem.

**Comment by 473867143** [comment]
solved it .

**Comment by SriKrishnaTKVSS** [comment]
how @473867143 ? Can you explain?
