### ISSUE TITLE
Where can I find the files for the model if750a that are listed in the px4 user guide?

### ISSUE THREAD

**Issue by tgkang43** [PX4/PX4-Autopilot#20463]
Dear

http://docs.px4.io/main/en/simulation/gazebo.html
It's mentioned in the link above, " make px4_sitl gazebo_if750a ".
No matter how much I search, I can't find the relevant files and how to run it.
I am desperate for help from experts.

Best Regards,

**Comment by Jaeyoung-Lim** [comment]
@tgkang43 IF750a is no longer supported and has been removed in https://github.com/PX4/PX4-SITL_gazebo/pull/891

**Comment by tgkang43** [comment]
Sorry, 
I'd appreciate it if you could tell me more specifically how to find the model if750a files.

**Comment by Jaeyoung-Lim** [comment]
@tgkang43 You can open the PR link, open the "Files Changed" tab and find the removed file

**Comment by tgkang43** [comment]
Thank you I got it, but what about binary files like *.stl ?

**Comment by Jaeyoung-Lim** [comment]
@tgkang43 You can checkout to the commit before the file was removed: https://www.atlassian.com/git/tutorials/using-branches/git-checkout

**Comment by tgkang43** [comment]
Sorry I'm a beginner.
Do you mean to do it this way?
 $ git init
 $ git https://github.com/PX4/PX4-SITL_gazebo/pull/891/files
 $ git remote add origin https://github.com/PX4/PX4-SITL_gazebo/pull/891/files
 $ git ls-files --deleted | xargs git checkout --
 ... ?
It is difficult for me without prior knowledge.
Sorry, but please help me more. 
Thank you !

**Comment by tgkang43** [comment]
I looked at the history with 'github desktop', but there is nothing I can do.

![image](https://user-images.githubusercontent.com/35491162/197265502-8750222f-2d9b-4b0b-9a8d-e6ca323bdafa.png)

**Comment by tgkang43** [comment]
I can get the model files including if750a from the link below.
https://git.sjtu.edu.cn/1070037389/px4-sitl_gazebo/-/tree/c0d926f7b15126498a05c466891d08083b864afc/models
Thank you !
