### ISSUE TITLE
I2C port In/Out configuration issue

### ISSUE THREAD

**Issue by synerex2016** [PX4/PX4-Autopilot#20599]
Hi

I'm now talking about I2C port In/Out configuration.

In fact, we're faced on mass production of the LTE module integrated RTK GPS device. As you can imagine that the LTE module can be able to receive the RTCM data from the network RTK base stations automatically, so our new device deliver the RTCM data to PX4 thru I2C port.

However, we found out whenever we make a connection between PX4 and f9p, **PX4 make a configuration of I2C port In/Out is set to None(Disable) since stable version 1.13.1.** Therefore, our device cannot deliver the rtcm data coming from LTE modem to F9p.

Thus, Modification is required so that the setting for I2C does not change during F9P port setting in PX4. Or, we need an additional options.

Anyhow, we would like to know why PX4 make a configuration of I2C port in/out is set to None(Disable) since stable version 1.13.1?

Many thanks,
JD, Park

For your understanding, the following are our product features.

![슬라이드1](https://user-images.githubusercontent.com/117953166/201465997-3110a057-8891-4326-9f7a-db00777f3308.PNG)
![슬라이드2](https://user-images.githubusercontent.com/117953166/201466001-2bdf5773-e238-42d8-9368-4be7d61b294c.PNG)

**Comment by lfeng17** [comment]
Same problem.

**Comment by bkueng** [comment]
I2C was disabled in https://github.com/PX4/PX4-GPSDrivers/pull/81. It might still be fine if we allow RTCM as input. @Igor-Misic can you have a look?

**Comment by synerex2016** [comment]
Our product is working fine when tested by **changing** the F9P I2C setting in the GPS driver of PX4. F9P I2C port setting were performed by setting In : RTCM3, Out : NMEA.
**_Therefore, can you modify the PX4 GPS driver to set the F9P I2C port to In: RTCM3, Out: NMEA in default?_**

And while our testing, we found out that the GPS driver sets the measurement rate of **F9P to 10Hz**, but we think that part seems to be wrong.

According to the specification of F9P datasheet, The rate is as follows:
![image](https://user-images.githubusercontent.com/117953166/206687598-3466a3ec-6a12-4d01-a586-072d2792de69.png)
![image](https://user-images.githubusercontent.com/117953166/206687656-6a70ef5d-670c-4df3-b0f9-cf639f20cb88.png)

That is, when used as single GNSS, it is 7Hz and when used as a moving base, it is 5Hz.

**_Is this also being modified later?_**

**Comment by Igor-Misic** [comment]
We disabled all communication at I2C input since F9P has an issue with the heading when it receives too much data to process. I'll try to enable RTCM only at I2C and check if the heading is still working. If not I'll add a parameter option to select a port for RTCM data.

**Comment by synerex2016** [comment]
Many thanks for your great efforts. If possible, please enable IN:UBX+RTCM and OUT:UBX+NMEA at I2C.
We will waiting for your any feedbacks. 

> We disabled all communication at I2C input since F9P has an issue with the heading when it receives too much data to process. I'll try to enable RTCM only at I2C and check if the heading is still working. If not I'll add a parameter option to select a port for RTCM data.

**Comment by bkueng** [comment]
@synerex2016 Igor added a configuration option in https://github.com/PX4/PX4-Autopilot/pull/20788.

**Comment by synerex2016** [comment]
@bkueng @Igor-Misic Thanks for you guys great efforts! Keep in touch!
