### ISSUE TITLE
Current Main not responding on Cube Orange

### ISSUE THREAD

**Issue by danielhonies** [PX4/PX4-Autopilot#20609]
## Describe the bug
Current Main build flashing through QGC will not respond to request for parameters. 

## To Reproduce
Flash Dev Build through QGC onto Cube Orange

## Expected behavior
Should respond to request for params

**Comment by Ecuashungo** [comment]
The same is true for the pixhawk 4 mini

**Comment by AlexKlimaj** [comment]
This should be fixed now https://github.com/PX4/PX4-Autopilot/pull/20596

**Comment by danielhonies** [comment]
Thanks @AlexKlimaj
