### ISSUE TITLE
ADIS16507 IMU PX4 Driver Support

### ISSUE THREAD

**Issue by vincentpoont2** [PX4/PX4-Autopilot#20607]
ADIS16507 is newer & lower cost high grade IMU option compare to other AD IMU . Would love to see PX4 Driver support on ADIS16507. 

I see that ADIS16477 & ADIS16497 are both supported, but not ADIS16507.
We can provide hardware for driver testing if needed.

**Comment by dagar** [comment]
At a glance the datasheet looks pretty similar, it shouldn't be that hard to get a driver together.

Is this going to be available as an external IMU?

**Comment by vincentpoont2** [comment]
@dagar We are considering using it as internal IMU for Flight controllers.

**Comment by dagar** [comment]
https://github.com/PX4/PX4-Autopilot/pull/20630

**Comment by vincentpoont2** [comment]
> https://github.com/PX4/PX4-Autopilot/pull/20630

@dagar Would you like us to send you hardware to test?

**Comment by dagar** [comment]
> > #20630
> 
> @dagar Would you like us to send you hardware to test?

If someone already has this hardware and is a position to actually flight test I'd be happy to work with them interactively to finish the pull request, otherwise I can do it here.
