### ISSUE TITLE
Pitch and Roll setpoint is not zero

### ISSUE THREAD

**Issue by Jiajian-Chang** [PX4/PX4-Autopilot#20629]
Firmware: 1.13.1
Controller: Pixhawk 6c

Is there any method that I can check each channel’s PWM output? In the flight review, the actuator output is in thrust, pitch, roll and yaw.

There is an issue that the PWM is too high while arming. The thrust is almost take-off thrust. I tried to change the PWM_MAIN_MIN and do ESC calibration but it doesn’t work. The motors can spin at a low speed when I pass a low PWM in Qground Control.
It is ok to fly. But the takeoff and landing are unstable due to the high PWM.

https://review.px4.io/plot_app?log=9d8dedcc-fe39-4127-8e30-c13bbad7bde6
Here is the arm without propeller log.
https://review.px4.io/plot_app?log=28e106d4-cb11-47ee-bc7d-136c667e82ce

**Comment by Jiajian-Chang** [comment]
I found the reason is that the set point of roll and pitch angle is not zero. From the estimated angle, the IMU looks ok. I have no idea why this happens. I can exclude the vibration reason because I isolated the controller and put it on the ground. I changed a new controller and it works well. 

https://review.px4.io/plot_app?log=a78dd24b-aa3c-4cd8-9fec-590c9b88024d

**Comment by bresch** [comment]
The setpoints are not zero because of the RC sticks. You probably have some trim values set on the remote.
![DeepinScreenshot_select-area_20221128102200](https://user-images.githubusercontent.com/14822839/204240641-bfa0f8a3-ac32-4806-8a49-22f9caf31d44.png)
