### ISSUE TITLE
Build Error when running make px4_sitl gazebo

### ISSUE THREAD

**Issue by cmm6758** [PX4/PX4-Autopilot#20632]
Hello,

Whenever I attempt to build the simulator for PX4 I receive this error below. I am new to this so I am not sure what I am doing wrong. What does this error mean and what should I do to resolve it? I posted the entire terminal including the installation in case I missed something.

$make px4_sitl gazebo

[  1%] Built target events_header
[  1%] Built target ver_gen
[  1%] Built target parameters_xml
[  1%] Built target uorb_headers
[  1%] Built target actuators_json
[  1%] Built target flighttasks_generated
[  1%] Built target output_functions_header
[  2%] Built target drivers_board
[  3%] Built target git_gps_devices
[  3%] Built target topic_bridge_files
[  3%] Built target git_mavlink_v2
[  3%] Built target uorb_ucdr_headers
[  3%] Built target git_micro_xrce_dds_client
[  3%] Built target git_gazebo
[  3%] Built target events_json
[  3%] Built target perf
[  3%] Built target tinybson
[  5%] Built target work_queue
[  5%] Built target version
[  5%] Built target geo
[  5%] Built target wind_estimator
[  6%] Built target world_magnetic_model
[  6%] Built target mode_util
[  6%] Generating Mavlink development: src/modules/mavlink/mavlink/message_definitions/v1.0/development.xml
[  8%] Performing configure step for 'sitl_gazebo'
[  9%] Built target libmicroxrceddsclient_project
[ 27%] Built target uorb_msgs
-- install-prefix: /usr/local
-- cmake build type: RelWithDebInfo
-- Using C++17 standard
[ 27%] Built target component_general_json
[ 27%] Built target parameters
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found suitable version "1.71.0", minimum required is "1.58") found components: system thread filesystem
[ 28%] Built target romfs_gen_files_target
Scanning dependencies of target px4_work_queue
[ 28%] Building CXX object platforms/common/px4_work_queue/CMakeFiles/px4_work_queue.dir/ScheduledWorkItem.cpp.o
[ 28%] Building CXX object platforms/common/px4_work_queue/CMakeFiles/px4_work_queue.dir/WorkItem.cpp.o
Traceback (most recent call last):
  File "/home/mellarijocm/Firmware/src/modules/mavlink/mavlink/pymavlink/tools/mavgen.py", line 16, in <module>
    from pymavlink.generator import mavgen
  File "/home/mellarijocm/Firmware/src/modules/mavlink/mavlink/pymavlink/generator/mavgen.py", line 26, in <module>
    from future import standard_library
ModuleNotFoundError: No module named 'future'
make[4]: *** [src/modules/mavlink/CMakeFiles/mavlink_c_generate.dir/build.make:62: mavlink/development/development.h] Error 1
make[3]: *** [CMakeFiles/Makefile2:10299: src/modules/mavlink/CMakeFiles/mavlink_c_generate.dir/all] Error 2
make[3]: *** Waiting for unfinished jobs....
[ 28%] Building CXX object platforms/common/px4_work_queue/CMakeFiles/px4_work_queue.dir/WorkItemSingleShot.cpp.o
[ 28%] Building CXX object platforms/common/px4_work_queue/CMakeFiles/px4_work_queue.dir/WorkQueue.cpp.o
[ 28%] Building CXX object platforms/common/px4_work_queue/CMakeFiles/px4_work_queue.dir/WorkQueueManager.cpp.o
[ 28%] Linking CXX static library libpx4_work_queue.a
[ 28%] Built target px4_work_queue
-- Found DART: /usr/include (Required is at least version "6.6") found components: dart
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found suitable version "1.71.0", minimum required is "1.40.0") found components: thread system filesystem program_options regex iostreams date_time
-- Looking for ignition-math6 -- found version 6.13.0
-- Searching for dependencies of ignition-math6
-- Looking for OGRE...
-- Found Ogre Ghadamon (1.9.0)
-- Looking for OGRE_Paging...
-- Found OGRE_Paging: optimized;/usr/lib/x86_64-linux-gnu/libOgrePaging.so;debug;/usr/lib/x86_64-linux-gnu/libOgrePaging.so
-- Looking for OGRE_Terrain...
-- Found OGRE_Terrain: optimized;/usr/lib/x86_64-linux-gnu/libOgreTerrain.so;debug;/usr/lib/x86_64-linux-gnu/libOgreTerrain.so
-- Looking for OGRE_Property...
-- Found OGRE_Property: optimized;/usr/lib/x86_64-linux-gnu/libOgreProperty.so;debug;/usr/lib/x86_64-linux-gnu/libOgreProperty.so
-- Looking for OGRE_RTShaderSystem...
-- Found OGRE_RTShaderSystem: optimized;/usr/lib/x86_64-linux-gnu/libOgreRTShaderSystem.so;debug;/usr/lib/x86_64-linux-gnu/libOgreRTShaderSystem.so
-- Looking for OGRE_Volume...
-- Found OGRE_Volume: optimized;/usr/lib/x86_64-linux-gnu/libOgreVolume.so;debug;/usr/lib/x86_64-linux-gnu/libOgreVolume.so
-- Looking for OGRE_Overlay...
-- Found OGRE_Overlay: optimized;/usr/lib/x86_64-linux-gnu/libOgreOverlay.so;debug;/usr/lib/x86_64-linux-gnu/libOgreOverlay.so
-- Looking for ignition-math6 -- found version 6.13.0
-- Looking for ignition-transport8 -- found version 8.3.0
-- Searching for dependencies of ignition-transport8
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so;-lpthread (found suitable version "3.6.1", minimum required is "3")
-- Config-file not installed for ZeroMQ -- checking for pkg-config
-- Checking for module 'libzmq >= 4'
--   Found libzmq , version 4.3.2
-- Checking for module 'uuid'
--   Found uuid, version 2.34.0
-- Looking for ignition-msgs5 -- found version 5.10.0
-- Searching for dependencies of ignition-msgs5
-- Looking for ignition-math6 -- found version 6.13.0
-- Checking for module 'tinyxml2'
--   Found tinyxml2, version 6.2.0
-- Looking for ignition-msgs5 -- found version 5.10.0
-- Looking for ignition-common3 -- found version 3.14.2
-- Searching for dependencies of ignition-common3
-- Looking for dlfcn.h - found
-- Looking for libdl - found
-- Searching for <ignition-common3> component [graphics]
-- Looking for ignition-common3-graphics -- found version 3.14.2
-- Searching for dependencies of ignition-common3-graphics
-- Looking for ignition-math6 -- found version 6.13.0
-- Looking for ignition-fuel_tools4 -- found version 4.6.0
-- Searching for dependencies of ignition-fuel_tools4
-- Checking for module 'jsoncpp'
--   Found jsoncpp, version 1.7.4
-- Checking for module 'yaml-0.1'
--   Found yaml-0.1, version 0.2.2
-- Checking for module 'libzip'
--   Found libzip, version 1.5.1
-- Looking for ignition-common3 -- found version 3.14.2
-- Looking for ignition-math6 -- found version 6.13.0
-- Looking for ignition-msgs5 -- found version 5.10.0
-- Checking for module 'gstreamer-1.0 >= 1.0'
--   No package 'gstreamer-1.0' found
-- Checking for module 'gstreamer-base-1.0 >= 1.0'
--   No package 'gstreamer-base-1.0' found
-- Checking for module 'gstreamer-app-1.0 >= 1.0'
--   No package 'gstreamer-app-1.0' found
-- Building klt_feature_tracker without catkin
-- Building OpticalFlow with OpenCV
-- Could NOT find MAVLink (missing: MAVLINK_INCLUDE_DIRS) (found version "2.0")
-- catkin DISABLED
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so;-lpthread (found version "3.6.1")
-- Gazebo version: 11.11
-- Found GStreamer: adding gst_camera_plugin
-- Found GStreamer: adding gst_video_stream_widget
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
GSTREAMER_APP_LIBRARIES (ADVANCED)
    linked by target "AdvancedLiftDragPlugin" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "ForceVisual" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "gazebo_airship_dynamics_plugin" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "sensor_msgs" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "gazebo_airspeed_plugin" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "gazebo_groundtruth_plugin" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "physics_msgs" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "std_msgs" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "gazebo_usv_dynamics_plugin" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "gazebo_video_stream_widget" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "gazebo_gps_plugin" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "gazebo_opticalflow_mockup_plugin" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "gazebo_irlock_plugin" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "gazebo_parachute_plugin" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "gazebo_lidar_plugin" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "gazebo_multirotor_base_plugin" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "gazebo_wind_plugin" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "gazebo_opticalflow_plugin" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "gazebo_uuv_plugin" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "gazebo_drop_plugin" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "nav_msgs" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "gazebo_sonar_plugin" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "gazebo_vision_plugin" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "gazebo_user_camera_plugin" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "gazebo_gst_camera_plugin" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "mav_msgs" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "gazebo_controller_interface" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "gazebo_gimbal_controller_plugin" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "gazebo_imu_plugin" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "gazebo_mavlink_interface" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "gazebo_motor_model" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "gazebo_camera_manager_plugin" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "gazebo_magnetometer_plugin" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "gazebo_barometer_plugin" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "LiftDragPlugin" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "gazebo_catapult_plugin" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
GSTREAMER_LIBRARIES (ADVANCED)
    linked by target "AdvancedLiftDragPlugin" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "ForceVisual" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "gazebo_airship_dynamics_plugin" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "sensor_msgs" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "gazebo_airspeed_plugin" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "gazebo_groundtruth_plugin" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "physics_msgs" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "std_msgs" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "gazebo_usv_dynamics_plugin" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "gazebo_video_stream_widget" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "gazebo_gps_plugin" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "gazebo_opticalflow_mockup_plugin" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "gazebo_irlock_plugin" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "gazebo_parachute_plugin" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "gazebo_lidar_plugin" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "gazebo_multirotor_base_plugin" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "gazebo_wind_plugin" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "gazebo_opticalflow_plugin" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "gazebo_uuv_plugin" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "gazebo_drop_plugin" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "nav_msgs" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "gazebo_sonar_plugin" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "gazebo_vision_plugin" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "gazebo_user_camera_plugin" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "gazebo_gst_camera_plugin" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "mav_msgs" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "gazebo_controller_interface" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "gazebo_gimbal_controller_plugin" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "gazebo_imu_plugin" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "gazebo_mavlink_interface" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "gazebo_motor_model" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "gazebo_camera_manager_plugin" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "gazebo_magnetometer_plugin" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "gazebo_barometer_plugin" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "LiftDragPlugin" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
    linked by target "gazebo_catapult_plugin" in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
_MAVLINK_INCLUDE_DIR
   used as include directory in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
   used as include directory in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
   used as include directory in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
   used as include directory in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
   used as include directory in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
   used as include directory in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
   used as include directory in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
   used as include directory in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
   used as include directory in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
   used as include directory in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
   used as include directory in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
   used as include directory in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
   used as include directory in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
   used as include directory in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
   used as include directory in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
   used as include directory in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
   used as include directory in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
   used as include directory in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
   used as include directory in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
   used as include directory in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
   used as include directory in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
   used as include directory in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
   used as include directory in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
   used as include directory in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
   used as include directory in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
   used as include directory in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
   used as include directory in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
   used as include directory in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
   used as include directory in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
   used as include directory in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
   used as include directory in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
   used as include directory in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
   used as include directory in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
   used as include directory in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
   used as include directory in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
   used as include directory in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
   used as include directory in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
   used as include directory in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
   used as include directory in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
   used as include directory in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
   used as include directory in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
   used as include directory in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
   used as include directory in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
   used as include directory in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
   used as include directory in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo
   used as include directory in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo/unit_tests
   used as include directory in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo/unit_tests
   used as include directory in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo/unit_tests
   used as include directory in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo/unit_tests
   used as include directory in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo/unit_tests
   used as include directory in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo/unit_tests
   used as include directory in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo/unit_tests
   used as include directory in directory /home/mellarijocm/Firmware/Tools/simulation/gazebo/sitl_gazebo/unit_tests

-- Configuring incomplete, errors occurred!
See also "/home/mellarijocm/Firmware/build/px4_sitl_default/build_gazebo/CMakeFiles/CMakeOutput.log".
See also "/home/mellarijocm/Firmware/build/px4_sitl_default/build_gazebo/CMakeFiles/CMakeError.log".
make[4]: *** [src/modules/simulation/simulator_mavlink/CMakeFiles/sitl_gazebo.dir/build.make:107: external/Stamp/sitl_gazebo/sitl_gazebo-configure] Error 1
make[3]: *** [CMakeFiles/Makefile2:34202: src/modules/simulation/simulator_mavlink/CMakeFiles/sitl_gazebo.dir/all] Error 2
make[2]: *** [CMakeFiles/Makefile2:37289: src/modules/simulation/simulator_mavlink/CMakeFiles/gazebo_rover.dir/rule] Error 2
make[1]: *** [Makefile:14331: gazebo_rover] Error 2
make: *** [Makefile:232: px4_sitl] Error 2

**Comment by tayyabkhalil-313** [comment]
> from future import standard_library
ModuleNotFoundError: No module named 'future'

Seems like python library 'future' is missing. Install it by running '`pip install future`' (or  '`pip3 install future`' if you have pip3).

**Comment by junwoo091400** [comment]
I am also troubleshooting this, I think it's related to the MAVLink dependency not being found:

```
-- Could NOT find MAVLink (missing: MAVLINK_INCLUDE_DIRS) (found version "2.0")
```

**Comment by junwoo091400** [comment]
Seems to be related: https://github.com/gnuradio/gnuradio/issues/3581

**Comment by junwoo091400** [comment]
Found the solution:

I had to first build the `px4_sitl_default`, and then after that built the `px4_sitl_default sitl_gazebo-classic`. In other words:

```bash
make px4_sitl_default
make px4_sitl_default sitl_gazebo-classic
```

Note that I am doing this on current `main` branch (v1.14.0-beta), so the `-classic` part should be omitted from your side (if testing with v1.13.0 or lower versions)!
