### ISSUE TITLE
Issues when using the SITL GZ launch configuration through VSCode Launch and Debug panel on Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by lvanasse** [PX4/PX4-Autopilot#20668]
## Describe the bug
At the moment, when using the Launch and Debug window in VSCode and using the launch configuration `SITL (GZ)`, I get the error that `ign` command is not found on Ubuntu 22.04.

## To Reproduce
1. On an Ubuntu 22.04 LTS, download PX4 GitHub project with its submodules
2. Install the dependencies with the `ubuntu.sh` script and use the argument `--sim_jammy`
3. Open the PX4 folder with VSCode
4. Navigate to the Launch and Debug Panel (4th one starting from the top)
5. Select the `SITL (GZ)` launch configuration and launch it by clicking the small green play button beside the dropdown.
6. Look at the terminal tab at the bottom

## Expected behavior
When selecting the `SITL (GZ)` I'd expect that PX4 and Gazebo launch without issue and with the x500 model running in Gazebo.

## Log Files and Screenshots
Here's the terminal log:
```
______  __   __    ___ 
| ___ \ \ \ / /   /   |
| |_/ /  \ V /   / /| |
|  __/   /   \  / /_| |
| |     / /^\ \ \___  |
\_|     \/   \/     |_/

px4 starting.

INFO  [px4] startup script: /bin/sh etc/init.d-posix/rcS 0
INFO  [init] found model autostart file as SYS_AUTOSTART=4001
INFO  [param] selected parameter default file parameters.bson
INFO  [param] importing from 'parameters.bson'
INFO  [parameters] BSON document size 236 bytes, decoded 236 bytes (INT32:9, FLOAT:3)
INFO  [param] selected parameter backup file parameters_backup.bson
  SYS_AUTOCONFIG: curr: 0 -> new: 1
+ SYS_AUTOSTART: curr: 10016 -> new: 4001
* SENS_BOARD_X_OFF: curr: 0.0000 -> new: 0.0000
* SENS_DPRES_OFF: curr: 0.0000 -> new: 0.0010
INFO  [dataman] data manager file './dataman' size is 7866640 bytes
INFO  [init] PX4_GZ_VERBOSE not explicitly set, defaulting to: 1.
etc/init.d-posix/rcS: 43: /home/ludovic/Code/PX4-Autopilot/build/px4_sitl_default/rootfs/etc/init.d-posix/px4-rc.simulator: ign: not found
etc/init.d-posix/rcS: 45: /home/ludovic/Code/PX4-Autopilot/build/px4_sitl_default/rootfs/etc/init.d-posix/px4-rc.simulator: ign: not found
etc/init.d-posix/rcS: 46: /home/ludovic/Code/PX4-Autopilot/build/px4_sitl_default/rootfs/etc/init.d-posix/px4-rc.simulator: ign: not found
etc/init.d-posix/rcS: 47: /home/ludovic/Code/PX4-Autopilot/build/px4_sitl_default/rootfs/etc/init.d-posix/px4-rc.simulator: ign: not found
etc/init.d-posix/rcS: 49: [: Illegal number: 
etc/init.d-posix/rcS: 49: [: Illegal number: 
etc/init.d-posix/rcS: 49: [: Illegal number: 
WARN  [init] using older version of MultiCopterMotor plugin, please update to latest gazebo > 6.12.0.
WARN  [init] setting PX4_SIM_MODEL -> x500-Legacy from x500 till gazebo > 6.12.0
INFO  [init] starting ign gazebo
etc/init.d-posix/rcS: 64: /home/ludovic/Code/PX4-Autopilot/build/px4_sitl_default/rootfs/etc/init.d-posix/px4-rc.simulator: ign: not found
WARN  [init] PX4_GZ_MODEL_NAME or PX4_GZ_MODEL not set using PX4_SIM_MODEL.
etc/init.d-posix/rcS: 68: /home/ludovic/Code/PX4-Autopilot/build/px4_sitl_default/rootfs/etc/init.d-posix/px4-rc.simulator: ign: not found
INFO  [gz_bridge] world: default, model name: x500-Legacy_0, simulation model: x500-Legacy
ERROR [gz_bridge] Service call timed out
ERROR [gz_bridge] Task start failed (-1)
ERROR  [init] ign gazebo failed to start
ERROR [px4] Startup script returned with return value: 256
[1] + Done                       "/usr/bin/gdb" --interpreter=mi --tty=${DbgTerm} 0<"/tmp/Microsoft-MIEngine-In-waqwsqt0.rt0" 1>"/tmp/Microsoft-MIEngine-Out-0nuh3gza.cgn"
```
![image](https://user-images.githubusercontent.com/12837376/203831296-13a7e06b-0aeb-4fe5-b066-bd3370723c39.png)

## Drone (please complete the following information):
- SITL, using the x500 model

## Additional context
I also had a different issue with Ubuntu 20.04 with the same launch configuration on VSCode, but I'd like to focus on fixing the latest version of LTS Ubuntu.

**Comment by ivanpadavan** [comment]
I had this issue not related to vscode stuff so I was not able to run gazebo simulation on macos.
To overcome this i needed to change GZBridge.cpp lines 276 and 119 (as for b5a6d6db0da2964d2fe4e40fd613fc579358dc68)
```cpp
if (_node.Request(create_service, req, 10000, rep, result)) {
...
int sleep_count_limit = 10000;
```
1000 to 10000

**Comment by master0v** [comment]
Got the following error trying to run `make px4_sitl gz_x500`:

```
INFO  [gz_bridge] world: default, model name: x500_0, simulation model: x500
ERROR [gz_bridge] timed out waiting for clock message
ERROR [gz_bridge] Task start failed (-1)
ERROR [px4] Startup script returned with return value: 2
```

Tried the fixes above, that didn't help.

**Comment by vacabun** [comment]
> Got the following error trying to run `make px4_sitl gz_x500`:
> 
> ```
> INFO  [gz_bridge] world: default, model name: x500_0, simulation model: x500
> ERROR [gz_bridge] timed out waiting for clock message
> ERROR [gz_bridge] Task start failed (-1)
> ERROR [px4] Startup script returned with return value: 2
> ```
> 
> Tried the fixes above, that didn't help.

I also had the same problem.

**Comment by lvanasse** [comment]
I think my fix was that I was missing some dependencies. It was fixed in the installation script a while back.

**Comment by vacabun** [comment]
Thank you for your answer, it was fixed after i turn off the firewall.

**Comment by bastianhjaeger** [comment]
In case anyone else stumbles over it: 
In my case there was a instance of the gazebo ignition server running in the background causing the issue. Killing it resolved things.

**Comment by RodrigofrBastos** [comment]
> 

how do you kill the ig server running in the background?

**Comment by bastianhjaeger** [comment]
Sorry, oversaw this. I killed it be searching for in in htop and killing it there.

**Comment by usmanNoor5** [comment]
i have same error did anyone solves it

**Comment by meowchine1** [comment]
Faced a problem with Gazebo and px4 interaction: gz_bridge failed to start and spawn model. Can anyone help? 
```
 MicroXRCEAgent udp4 -p 8888
 gz sim -v 4 aruco_field.sdf
 export PX4_GZ_MODEL_NAME=x500_vision_0 && 
 export PX4_GZ_MODEL_POSE='3,3,0.5,0,0,0,0,0' && 
 cd ~/PX4-Autopilot && make px4_sitl gz_x500_vision 
```
Error:
```
INFO [px4] startup script: /bin/sh etc/init.d-posix/rcS 0
INFO [init] found model autostart file as SYS_AUTOSTART=4005
INFO [param] selected parameter default file parameters.bson
INFO [param] importing from 'parameters.bson'
INFO [parameters] BSON document size 316 bytes, decoded 316 bytes (INT32:13, FLOAT:3)
INFO [param] selected parameter backup file parameters_backup. bson
INFO [dataman] data manager file './dataman' size is 7872608 bytes
INFO [init] Gazebo simulator
INFO [init] gazebo already running world: aruco_world
WARN [init] PX4_GZ_MODEL_POSE not set, spawning at origin.
INFO [gz_bridge] world: aruco_world, model name: x500_vision_0, simulation model: x500_vision
INFO [gz_bridge] Requested Model Position: 0,0,0,0,0,0,0,0,0,0
INFO [gz_bridge] Model position z is less than or equal to 0. 0, moving upwards
ERROR [gz_bridge] timed out waiting for clock message
ERROR [gz_bridge] Task start failed (-1)
ERROR [init] gz_bridge failed to start and spawn model
ERROR [px4] Startup script returned with return value: 256
FAILED: src/modules/simulation/gz_bridge/CMakeFiles/gz_x500_vision /home/vor/PX4-Autopilot/build/px4_sitl_default/src/modules/simulation/gz_bridge/CMakeFiles/gz_x500_vision 
cd /home/vor/PX4- Autopilot/build/px4_sitl_default/src/modules/simulation/gz_bridge && /usr/bin/cmake -E env PX4_SIM_MODEL=gz_x500_vision /home/vor/PX4-Autopilot/build/px4_sitl_default/bin/px4
ninja: build stopped: subcommand failed.
make: *** [Makefile:232: px4_sitl] Error 1
```

Translated with [DeepL.com](https://www.deepl.com/?utm_campaign=product&utm_source=web_translator&utm_medium=web&utm_content=copy_free_translation) (free version)

**Comment by usmanNoor5** [comment]
I guess using webots simulator for this is a better choice
