### ISSUE TITLE
Yaw rotation of drone

### ISSUE THREAD

**Issue by saitella** [PX4/PX4-Autopilot#20670]
Hi Bresch

 I am flying quad coaxial with cine66 motors recently I had a race due to decent speed is too high met with a hard landing and crashed  after the next flight I calibrated the compass and changed the decent speed of landing and from here the issue started it is spinning when in take off even in manual mode it is not take even the stick yaw input when I gave counter to it .Can you please go through the log and let me know whether the issue is with compass gone because of hard landing or the firmware I used is 1.13.2 . autopilot is cuav v7+ 

kindly go through the attached log file

[log_113_2022-11-25-16-48-06.zip](https://github.com/PX4/PX4-Autopilot/files/10093020/log_113_2022-11-25-16-48-06.zip)

**Comment by afwilkin** [comment]
Hey @saitella the PX4 forum might be a better place for this
https://discuss.px4.io/
