### ISSUE TITLE
Control Allocator - Can't tie ailerons up (crow) to flap deployment

### ISSUE THREAD

**Issue by ryanjAA** [PX4/PX4-Autopilot#20694]
On main. Pixhawk 4 for testing.

With the mixer setup we have ailerons go up when flaps are deployed to slow down.

On CA, there isn't a way (that I can figure out) to get this to do the same.

When in mission mode during  flight, flaps should be up, ailerons should be ailerons. During Landing, flaps go down, ailerons go up. 

During takeoff only flaps should go down if set (need to be decoupled from the ailerons or takeoff would be hard).

Aileron deflection should be a settable amount (not hardcoded).

During non mission mode you should be able to tie flaps and the crow/speedbrake setup to a channel and use it to slow down for a manual landing.

@dagar as discussed just now re 1.14 blocker

**Comment by junwoo091400** [comment]
@ryanjAA did https://github.com/PX4/PX4-Autopilot/pull/20815 fix this issue?

**Comment by ryanjAA** [comment]
> @ryanjAA did #20815 fix this issue?

Yes. Fixed and closed.
