### ISSUE TITLE
Log Download on Cube Orange

### ISSUE THREAD

**Issue by danielhonies** [PX4/PX4-Autopilot#20731]
## Describe the bug
On current main building on Ubuntu, log download through QGC doesn't work on the Cube Orange. When trying to download, QGC shows 'error'

## To Reproduce
Build Main, Flash on Cube Orange, Fly, try to download log

**Comment by ryanjAA** [comment]
This seems to be a common issue. Can you save your Params and upload that here. 

Is anyone not having this issue and we can compare?

**Comment by TedObrien** [comment]
Also having issues with this on 13.2, did you find a solution?

**Comment by ripdk12** [comment]
I can only download the log when connected via telemetry radio, when I try to download log while plugged in USB I get the same error.

**Comment by danielhonies** [comment]
fixed by https://github.com/PX4/PX4-Autopilot/pull/20824
