### ISSUE TITLE
Switching to offboard not possible due to timecheck

### ISSUE THREAD

**Issue by ecmnet** [PX4/PX4-Autopilot#20944]
In `src/modules/commander/HealthAndArmingChecks/checks/offboardCheck.cpp` the timestamp of the offboard message is compared to `hrt_absolute_time()`:

`bool data_is_recent = hrt_absolute_time() <  offboard_control_mode.timestamp +_param_com_of_loss_t.get() * 1_s;`

This check fails - at least with JMAVSIM - due to a wrong type conversion. I solved this by changing the comparison to

`bool data_is_recent = hrt_absolute_time() < ( offboard_control_mode.timestamp + (long)(_param_com_of_loss_t.get() * 1_s ));`

**Comment by dagar** [comment]
This is actually kind of insidious, where the 64 bit microsecond monotonic time is converted to float which can't represent it exactly. Ideally we'd turn on compiler conversion warnings, but there are probably too many existing cases (that are probably fine).
