### ISSUE TITLE
BARO timeout when running SITL gazebo-classic nolockstep on Rover - main branch

### ISSUE THREAD

**Issue by russkel** [PX4/PX4-Autopilot#21043]
## Describe the bug
Barometer timeout errors appear in the shell.

```
ERROR [vehicle_air_data] BARO #0 failed:  TIMEOUT!	
INFO  [vehicle_air_data] BARO switch from #0 -> #1
```

## To Reproduce
1. Launched SITL from within Docker
2. Observe errors on shell

```
./Tools/docker_run.sh 'make px4_sitl_nolockstep gazebo-classic_rover'
```

## Expected behavior
No barometer errors.

## Log Files and Screenshots
https://logs.px4.io/plot_app?log=0352673a-690e-41a0-93cd-363471be4c7a

## Drone (please complete the following information):
- SITL Gazebo-classic rover

## Additional context
Running up to date main branch as of posting. It didn't seem to occur in `stable` branch.
It also occurs as far back as https://github.com/PX4/PX4-Autopilot/commit/5a2e41c4e44823d84d800f7178a94d8d03abd6d0

Also nuttx commands (ls, ps etc) seem to not be enabled in SITL?

**Comment by 321thijs123** [comment]
Have you been able to solve this? I'm running into the same issue while trying to do thrust and torque command with px4_sitl_nolockstep.

**Comment by russkel** [comment]
> Have you been able to solve this? I'm running into the same issue while trying to do thrust and torque command with px4_sitl_nolockstep.

Only by turning off the sensors using the `SYS_HAS_BARO` parameter.

**Comment by matiasguzmanp** [comment]
Hi! Did you manage to solve this issue? I'm having the exact same problem. The magnetometer also fails.

**Comment by russkel** [comment]
Sorry, I stopped using PX4 and started using Ardupilot as it had better support.
