### ISSUE TITLE
Encoding error in px4

### ISSUE THREAD

**Issue by arongu321** [PX4/PX4-Autopilot#21076]
When I ran catkin build that includes the PX4 package, I get this encoding error for some reason.
![IMG_3097](https://user-images.githubusercontent.com/67613556/217058069-ddc15df8-aa1e-47f5-a331-d21043aa8401.jpg)
From what I searched up it relates to an issue where the open() function is not compatible with Python 2.x but with Python 3.x though I appreciate if there's another solution to this issue.

**Comment by arongu321** [comment]
Ok I managed to get rid of the encoding error though these make errors still persist:
make[2]: *** [events/events_generated.h] Error 1
make[1]: *** [src/lib/events/CMakeFiles/events_header.dir/all] Error 2
make: *** [all] Error 2

**Comment by junwoo091400** [comment]
Did you resolve the issue at the end?

**Comment by arongu321** [comment]
Yes I did, I basically ran the ubuntu.sh script provided in the Tools/Setup directory of the PX4-Autopilot git repository using:
`bash ./PX4-Autopilot/Tools/setup/ubuntu.sh`
Where . is the catkin workspace src directory.

**Comment by junwoo091400** [comment]
Closing as solved, thanks for the answer!
