### ISSUE TITLE
random max thrust when takeoff

### ISSUE THREAD

**Issue by TompsonTan** [PX4/PX4-Autopilot#21087]
![55666](https://user-images.githubusercontent.com/3468649/217477865-59be71fc-8f08-408b-b018-fd3f5c82145b.png)

firmware is based on v1.14beta1
log file url [https://logs.px4.io/plot_app?log=ec4160cd-0b5b-4204-8c87-0ed4168c3562](https://logs.px4.io/plot_app?log=ec4160cd-0b5b-4204-8c87-0ed4168c3562)

**Comment by sfuhrer** [comment]
@MaEtUgR

**Comment by junwoo091400** [comment]
Could be related to #20275

**Comment by dynamicUAVsolutions** [comment]
This happened to me on main around the same time on the Ark Fmu-v6x. It has since been fixed at least on the Ark, I've flown it. I believe the fix was from this merge (or one right before it, can't remember): https://github.com/PX4/PX4-Autopilot/pull/21113

**Comment by dynamicUAVsolutions** [comment]
But you might want to tether that thing down just in case! :)
