### ISSUE TITLE
Nose Gear control does not move when in Manual Mode

### ISSUE THREAD

**Issue by ryanjAA** [PX4/PX4-Autopilot#21108]
On #20815 on a 6C

The nose gear is setup on a main output in Control Actuator but it doesn't respond to manual input when in Manual mode.

Switch to any other mode where you can control it, aka Stabilized and it works fine.

No log since wasn't armed but recreated a bunch. If a log is needed, will make one.

@sfuhrer

**Comment by sfuhrer** [comment]
Thanks for the report, and no, no log needed, should be straight forward to reproduce and fix.

**Comment by sfuhrer** [comment]
That's the fix https://github.com/PX4/PX4-Autopilot/pull/20815/commits/1bfd1215010e37efb14a5d6825c8e7367ced6cc2
