### ISSUE TITLE
Failsafe triggering wrong

### ISSUE THREAD

**Issue by marceloroberti** [PX4/PX4-Autopilot#21206]
Hi everyone!
I'm having problems with a wrong failsafe activation every time I try to arm my vehicle. I have checked batteries, tried with different ones, replaced the power module and none of this solved the problem. The failsafe actions are configured to start with battery level in 15%, but even with 100% the vehicle enters in failsafe mode and goes to land mode. I'm arming by RC a VTOL frame. The printscreen below shows the message of the failsafe as soon as I arm the drone.

![Screenshot from 2023-02-27 16-07-46](https://user-images.githubusercontent.com/120598280/221661234-8bfdc074-5572-42ca-94d3-250a1fac7931.png)

I don't know what's happening, may be a bug or something. I saw a similar issue posted two weeks earlier, but there was related to GPS signal, as described by the author. May be related.
If anyone could help, I'd appreciate.

**Comment by bresch** [comment]
Strange, which PX4 version are you using?
Could you make a log from boot maybe?
