### ISSUE TITLE
Permission denied error while replaying PX4 ekf2 log

### ISSUE THREAD

**Issue by wardazahra** [PX4/PX4-Autopilot#21218]
I am trying to replay a PX4 ulog file. but as I type the command 
_export replay=</home/warda/src/Firmware/build/px4_sitl_default/rootfs/log/2023-03-01>/10_49_33.ulg_
I get permission denied error.

**Comment by bresch** [comment]
You apparently don't have the permission to set an env variable on you session. That's not a PX4 issue, please google the error to find how to solve this.
