### ISSUE TITLE
Gazebo classic documentation not up to date

### ISSUE THREAD

**Issue by Spider1097** [PX4/PX4-Autopilot#21247]
I tried go with tutorial as in  ( https://docs.px4.io/main/en/simulation/ros_interface.html ) for gazebo classic. When i ran all commands  i do not take the result what i need (how in link and i change all path where is necessary). I installed it 1 year ago, when was not gazebo classic and it worked, but now it only run the world ( no_sim=1 make px4_sitl_default gazebo-classic ). Someone had the same problem or i doing something wrong?

**Comment by beniaminopozzan** [comment]
Thank for spotting this @Spider1097 !
I updated the instructions.
