### ISSUE TITLE
dataman file contains random data after creation

### ISSUE THREAD

**Issue by digitalw0lf** [PX4/PX4-Autopilot#21278]
## Describe the bug
When PX4 creates a dataman file on SD card, contents of this file is not cleared, but contains random data from deleted files on that disk.
This is because Nuttx is not fully compliant with Posix standard: using lseek() to expand file size does not erases resulting "gap" in file on FAT32 (yes, FAT32 does not support real sparse files, but according to specs, this "gap" should read as zero bytes anyway).
If it happens that this random data looks similar to real dataman records, then PX4 tries to read and process it.

## To Reproduce
1. Take new SD card or delete dataman file on existing SD card.
2. Write large file(s) with non-zero content to SD card and delete them to fill all unused space with garbage. I used a sequence of 0x04000000 that looks like a header of dataman record.
3. Run PX4 with this SD card.
4. Check error messages on connection to GCS.
4. Download dataman file and view it in hex editor. It is filled with garbage from deleted file, except the "compatibility key" at file end.

## Expected behavior
dataman file should be filled with zero bytes on creation.

## Log Files and Screenshots
![Mission read errors](https://user-images.githubusercontent.com/63538674/224072409-6e1624e0-0b4f-4221-b4d0-f40e4fb7c3e8.png)
![Mission transfer failed](https://user-images.githubusercontent.com/63538674/224072476-79f6b087-5a98-4bd7-8c1d-bb42888f00ae.png)
![Hextor](https://user-images.githubusercontent.com/63538674/224073503-83496722-9efe-4ace-a82b-54d168150cc7.png)

## Drone (please complete the following information):
- Tested on Dropix fmu-v2 flight controller, but I think it's the same for all Nuttx-based boards.

**Comment by digitalw0lf** [comment]
I've tried to fix this bug by filling entire dataman file with zero's after creation, but encountered another weird behavior: writing of compatibility key failed after that. After some trials and errors, I've settled with strange but working solution: fill entire file except last kilobyte.
[dm.patch](https://github.com/PX4/PX4-Autopilot/files/10933907/dm.patch)

**Comment by Igor-Misic** [comment]
Solved here: https://github.com/PX4/PX4-Autopilot/pull/21594
