### ISSUE TITLE
[PX4_SITL/ROS2] Matching XRCE_DDS_DOM_ID with ROS_DOMAIN_ID for SITL

### ISSUE THREAD

**Issue by zp-yang** [PX4/PX4-Autopilot#21291]
I am currently trying to run multiple px4_sitl instances in different docker containers with different ROS_DOMAIN_IDs.
The micro_dds_client on px4 supports setting [XRCE_DDS_DOM_ID](https://github.com/PX4/PX4-Autopilot/blob/9be8f81d754d71a1357e739a21cac2c3d9be1acb/src/modules/microdds_client/module.yaml#L38) parameter but right now it does not automatically update to the value set by ROS_DOMAIN_ID. You can only update it after launching px4_sitl and it needs a reboot after the update. 
A simple addition to the [px4-rc.params](https://github.com/zp-yang/PX4-Autopilot/blob/main/ROMFS/px4fmu_common/init.d-posix/px4-rc.params) could solve this problem.
```
if [ -n "$ROS_DOMAIN_ID" ]; then
	param set XRCE_DDS_DOM_ID $ROS_DOMAIN_ID
fi
```
I saw a similar situation in another issue #19599 and no one seemed to have fixed it yet.

Should I submit a PR for this? Thanks for your advice!

**Comment by beniaminopozzan** [comment]
@junwoo091400 thanks for pinging me!

That's a good feature!
