### ISSUE TITLE
ADS1115 issue with fmu_v6x

### ISSUE THREAD

**Issue by huytd-pi** [PX4/PX4-Autopilot#21318]
Hello, my hardware is Pixhawk 6X full version running firmware v1.13.3. I am trying to set up the Mauch analog BEC module through the ADS1115 module. The wiring diagram is implemented according to the documentation from Holybro.
Pixhawk 5X/6X with Analog Power Module: [https://docs.holybro.com/autopilot/pixhawk-6x/digital-power-module-pm](url) 
I2C has been initialized and my log is showing up in Mavlink CMD on QGC.
```
board_adc status 
INFO  [board_adc] not running 
nsh> board_adc test 
nsh> board_adc status 
INFO  [board_adc] not running 
nsh> ads1115 status 
INFO  [SPI_I2C] Running on I2C Bus 2, Address 0x48 
ads1115: single-sample: 7450 events, 12636449us elapsed, 1696.17us avg, min 1677us max 1815us 24.802us rms 
INFO  [SPI_I2C] Running on I2C Bus 4, Address 0x48 
ads1115: single-sample: 7047 events, 3419017us elapsed, 485.17us avg, min 450us max 691us 37.991us rms 

 

nsh> listener adc_report 
TOPIC: adc_report 
 adc_report 
    timestamp: 893594977 (0.010437 seconds ago) 
    device_id: 9455633 (Type: 0x90, I2C:2 (0x48)) 
    raw_data: [14353, 160, 16317, 16437, 0, 0, 0, 0, 0, 0, 0, 0] 
    resolution: 32768 
    v_ref: 6.1440 
    channel_id: [0, 1, 2, 3, -1, -1, -1, -1, -1, -1, -1, -1] 
```
![image](https://user-images.githubusercontent.com/53168072/225661031-9b0b3b2c-c18c-4307-8a78-b0c85eff6898.png)
![image](https://user-images.githubusercontent.com/53168072/225659463-3f5d1dce-ebc6-4e7d-bc48-e489e71c0e70.png)

It seems that my battery_status has not updated the voltage and battery percentage. I have consulted a few sources and they said to turn off board_adc before turning on ads1115 to avoid conflicts. Please help me resolve this issue. Thanks!

**Comment by rizvanovic** [comment]
Any updates to this? Experiencing similar issues.

**Comment by huytd-pi** [comment]
I have reconfigured the board, the ADS1115 is received and the battery % is also showing
[boardconfig.txt](https://github.com/PX4/PX4-Autopilot/files/11118274/boardconfig.txt)
however i have problem with sensor hub mauch.
normal operating voltage measurement when using 1 sensor. However, when using a two-sensor hub, measure the voltage as shown below and set the voltage divider
![image](https://user-images.githubusercontent.com/53168072/229027114-a153ebb5-5271-476f-a7b4-c32a89a2b80d.png)
![image](https://user-images.githubusercontent.com/53168072/229027131-4193adab-57d2-4c1e-b27a-393bced5ffe9.png)
When going through the sensor hub, V div is (V div sensor1 + V div sensor2)/2, and A/V is (A/V sensor1 + A/V sensor2). which consists of 2 16000mah 6s batteries in series. with 6s battery the PL200 sensor will be connected in parallel and [V div is 10](https://www.mauch-electronic.com/pl-xxx-sensor-boards) .
![image](https://user-images.githubusercontent.com/53168072/229027759-6acb5db3-5938-4c40-ba53-8c8ab8d21108.png)

**Comment by rizvanovic** [comment]
Interesting, I'm using a Mauch PDB (2x200A hall) (032 on their website). I was planning on using the ads1115 to convert the analog readout to i2c. However I do not see the parameters to enable this. Is it required to change the board config file to get the ADC_ADS1115_EN parameter?

**Comment by huytd-pi** [comment]
> Interesting, I'm using a Mauch PDB (2x200A hall) (032 on their website). I was planning on using the ads1115 to convert the analog readout to i2c. However I do not see the parameters to enable this. Is it required to change the board config file to get the ADC_ADS1115_EN parameter?
on fmu6x, default ADC_ADS1115_EN is not enabled, need to change in board config and disable adc board like config file I shared

**Comment by rizvanovic** [comment]
@huytd-pi Cheers, will give it a try.
