### ISSUE TITLE
GPS Drift

### ISSUE THREAD

**Issue by Cavalletta98** [PX4/PX4-Autopilot#21322]
Hi,i'm using two drones with PX4 Autopilot fw v 1.13.2. One has Pixhawk4 and the other has Pix32 v5. I noticed that,if the drone Is standing on the ground( not armed) and i wait for some minutes, i see the drift of the position of the drone on QGControl. I mean,the position shows on QGControl Is far from the real position. This happen on both Flight controllers. What i can do for avoid that?
Thanks

**Comment by bresch** [comment]
Try to also check the metrics such as eph, P/H/VDOP, satellite count, jamming. Also note that the surrounding environment impacts the accuracy (e.g.: buildings, trees, ...)
