### ISSUE TITLE
[v1.14 Release] beta regression: Failsafe Flight Task triggered after startup without Manual control

### ISSUE THREAD

**Issue by junwoo091400** [PX4/PX4-Autopilot#21370]
## Describe the bug
After this commit https://github.com/PX4/PX4-Autopilot/commit/da4644c20adce8aeedd5be432fc88b1b115d7eb9, the Jenkins Hardware rack tests were all failing on the main branch, as the "Failsafe Flighttask activated" error was popping up.

## To Reproduce
Checkout `da4644c20adce8aeedd5be432fc88b1b115d7eb9` commit, then: `make px4_sitl gazebo-classic` -> Soon after startup, "Failsafe Flighttask activated" error will appear

## Expected behavior
Failsafe flighttask error shouldn't arise.

## Diagnosis
As https://github.com/PX4/PX4-Autopilot/commit/da4644c20adce8aeedd5be432fc88b1b115d7eb9 introduced concept of invalidating Sticks object if there's no manual control coming in (makes sense), the "ManualAcceleration" task started failing (as in HITL & SITL, no manual control is provided), and it then falls back to "ManualAltitudeSmoothVel" task:

https://github.com/PX4/PX4-Autopilot/blob/da4644c20adce8aeedd5be432fc88b1b115d7eb9/src/modules/flight_mode_manager/FlightModeManager.cpp#L226-L229

That somehow triggered the Failsafe task timeout. I learned a lot during debugging but still don't understand fully to explain what's going on. But @MaEtUgR I think you will be able to identify the root cause more efficiently! :mechanical_arm: 

## Log Files and Screenshots
![image](https://user-images.githubusercontent.com/23277211/227709300-cfe0decc-3136-4ca0-8e53-825cd14d24ce.png)

## Additional context
@dagar I always ignored the Jenkins Hardware rack tests, but this one really showed me that it will actually catch the cases we shouldn't ignore. Let's make sure we catch these in the future before it getting merged as well!!

**Comment by junwoo091400** [comment]
Note: I have found that before/after that problematic [commit](https://github.com/PX4/PX4-Autopilot/commit/ea97a38b2b5edaa515d8d6feb836c45f302b3b95), the Flight Task activation pattern has differed.

After the commit: Switches between 0, 3, 5 indexes (each Auto, ManualAcceleration, ManualAltitudeSmoothVel)
![Screenshot from 2023-03-25 17-38-16](https://user-images.githubusercontent.com/23277211/227706978-c74e1b2f-ee61-478c-b18c-0cb311e2076c.png)

Before the commit: Switches between 0, 3 indexes (each Auto, ManualAcceleration)

It is very strange why after that commit the "ManualAltitudeSmoothVel" is suddenly failing to activate/initialize, but at least the problem is getting narrowed down :grimacing:

**Comment by junwoo091400** [comment]
![image](https://user-images.githubusercontent.com/23277211/227708117-c6cdcbca-ac39-49d2-b7aa-eb87c85a3520.png)

Ah no! I realized there's actually *plenty of commits between these two. Idk why Jenkins didn't run (or preserve log) for commits in between, but it now excludes possibility that Alex's commit actually introduced this bug (as it's only related to UAVCAN, it is not likely. The driver isn't even running in the STIL).

Now investigating all the commits between them :disappointed:

**Comment by junwoo091400** [comment]
The answer lies somewhere here: https://github.com/PX4/PX4-Autopilot/compare/fe3c1d0a92a202a8f1428aea1028bcc0aca2333e...ea97a38b2b5edaa515d8d6feb836c45f302b3b95

**Comment by junwoo091400** [comment]
Now doing bissect, as @MaEtUgR taught me :wink:

**Comment by junwoo091400** [comment]
Found it by bisecting 8 times! It's this commit: https://github.com/PX4/PX4-Autopilot/commit/da4644c20adce8aeedd5be432fc88b1b115d7eb9

**Comment by MaEtUgR** [comment]
@junwoo091400 Heeey, thanks for looking into this! That's already really helpful. I noticed the `Failsafe Flighttask activated` in SITL and wanted to see why it comes up in a quiet moment but wasn't aware that it trips CI (a good thing) or someone else found it too.

Let me check if it's easy to reproduce.

**Comment by MaEtUgR** [comment]
I added the validity flag to the requirements of using stick input:
https://github.com/PX4/PX4-Autopilot/commit/da4644c20adce8aeedd5be432fc88b1b115d7eb9#diff-a65eff8fc6362bb2a8c4c7495f56778e1896809f6251a9403e57ff18f754076aR66
Maybe there's a glitch.

**Comment by MaEtUgR** [comment]
It's because it goes through Altitude mode during boot even when there is no stick input and Altitude mode reports to fail :confused:

**Comment by junwoo091400** [comment]
@MaEtUgR Btw I did some analysis (in comments above), feel free to reference them in case that helps as well! :raised_hands: 

What I found weird was that FlightTask was trying to activate 3 different tasks (trying to activate Auto, failing then falling back to ManualAcceleration, failing then falling back to ManualAltitudeSmoothVel, etc"

Is this how Flighttasks are supposed to operate? I was surprised by how many `switchTask` gets called!!

**Comment by MaEtUgR** [comment]
Thank you so much @junwoo091400 ! :rocket: I'm on it :pray:

**Comment by MaEtUgR** [comment]
It's a fallback but Commander always tries to be in `NAVIGATION_STATE_AUTO_LOITER` from the beginning on but something fails there. I'm guessing because there's no position estimate available yet.

**Comment by MaEtUgR** [comment]
I'm pretty sure now the problem is that with the new failsafe state machine it is allowed to switch to a mode before arming even though it cannot run. When doing so e.g. switching to Hold mode `FlightTaskAuto` is ran and reports it cannot run because it requires local position, global reference and a position setpoint triplet. So the question is how to solve that best. :thinking: 
https://github.com/PX4/PX4-Autopilot/blob/319f3db5e1f0f799be45064330d9c9504f5b5bcc/src/modules/flight_mode_manager/tasks/Auto/FlightTaskAuto.cpp#L97-L100

**Comment by MaEtUgR** [comment]
It's there from the introduction of the flight tasks. Any task that requires a local position fails to execute if its requirements are not fulfilled: https://github.com/PX4/PX4-Autopilot/commit/afd02aca92564e9e2be05942233f5d31773c797a

I'd rather not make a hole for just `FlightTaskAuto` but change how it works in general.
