### ISSUE TITLE
Cannot change mode to offboard in px4 v.1.13.3

### ISSUE THREAD

**Issue by RonaldDutu** [PX4/PX4-Autopilot#21381]
Hello everyone, I'm trying to run the Offboard control example as explained in [Px4 Ros2 offboard tutorial](https://gist.github.com/julianoes/adbf76408663829cd9aed8d14c88fa29), using Ubuntu 22.04, ROS2 Humble and px4 version 1.13.3. 

Following the procedure everything works fine till he asks to change mode to Offboard. Even if I changed the parameter COM_RCL_EXCEPT to 4, It doesn't allow me to switch to Offboard and in the PX4 shell it gives the following message INFO  [tone_alarm] notify negative. I don't know how to understand where that message comes from or what others parameters I need to set in order to switch to Offboard mode correctly.

**Comment by mrpollo** [comment]
any ideas @julianoes ?

**Comment by julianoes** [comment]
@mrpollo no sorry. I'm not familiar with ROS 2 and offboard.

**Comment by Jaeyoung-Lim** [comment]
@RonaldDutu You need to check if your ros messages are actually reaching the vehicle.

**Comment by RonaldDutu** [comment]
@Jaeyoung-Lim I checked and they don't. I couldn't install correctly the micrortps_agent because the bulding of px4_ros_com fails to complete, so I used instead microdds_client and Micro-XRCE. The agent-client communication works but px4-ros2 communications doesn't work. Could it be that the issue is the microdds_client isn't well supported in v1.13 and the only way to make the bridge is by using micrortps? I didn't use the main version since the drone in which I want to deploy the offboard control doesn't work with that version of the firmware.

**Comment by Jaeyoung-Lim** [comment]
@RonaldDutu Ah, microdds is not supported on v1.13 and was only added after.

Could you try with main? There is the v1.14 planned to have this change included, but not released yet. This is also written in the beginning of the instructions that you used: https://gist.github.com/julianoes/adbf76408663829cd9aed8d14c88fa29#px4-ros2-offboard-tutorial

**Comment by RonaldDutu** [comment]
@Jaeyoung-Lim We have the microdds_client command inside px4 v1.13 why it shouldn't work, considering also It's a stable version of the firmware? 
With the main version I tried and everything works, the thing is that I'm using v1.13 since that's the most recent version that works also with Omnibus F4, which is the FC that I have mounted on my drone. I've tried to run the drone with 1.14 and It seems that is not supported very well.

**Comment by mrpollo** [comment]
hey @RonaldDutu the microdds feature is planned for the v1.14 release and won't be backported to v1.13, we urge you to try the v1.14 beta, if you run into any issues let us know so we can help.

**Comment by RonaldDutu** [comment]
Hi @mrpollo understood. I will try to go back to Ubuntu 20.04 and follow the installation instructions on the docs v1.13. In this way I think I will be able to use the rtps bridge and solve my issue. .

**Comment by RonaldDutu** [comment]
Hello everyone, as you where saying there is no way to work with rtps bridge on Ubuntu 22.04, the only thing to do in order to work with that bridge is go back do Ubuntu 20.04. Nonetherless, I succeded to configure the Ominbus F4 to work with the main version. In this way I can keep using microxrce and Ubuntu 22.04. Therefore, I can close the issue.
