### ISSUE TITLE
NMEA Protocol listing under GPSx_protocol   PX4 v1.13.3 

### ISSUE THREAD

**Issue by sibujacob** [PX4/PX4-Autopilot#21397]
As discussed during Q&A meeting 29/03/2023      

( PX4 v1.13.3 ) 
 The  NMEA protocol is listed as one of the options in QGC parameters ------> gps1_protocol  where as the same is not  
  listed as a option  while configuring  secondary gps devices  under QGC parameters ----> gps2_protocol .

PS:  The PX4 documentation illustrates this NMEA option for  both gps1_protocol ad gps2_protocol .

![Screenshot (953)](https://user-images.githubusercontent.com/42690572/228723164-316b8c15-4989-4981-acc2-57ac809ba98b.jpg)

![Screenshot (952)](https://user-images.githubusercontent.com/42690572/228723099-5212288d-c935-46af-84a7-c28fb584bc8b.jpg)

**Comment by julianoes** [comment]
Can you set 6 using the force option?

**Comment by sibujacob** [comment]
As far as I can remember,  it doesn't  have a 6th option  at all.on the gps2- protocol. 
I am not infront of my CUBE ORANGE drone. Hopefully by mid May I will be able to test. again.

**Comment by julianoes** [comment]
I just tested main and v1.13.3 against QGC 4.2.4 and both showed all options for GPS 2:

![Uploading 2023-04-04_10-59.png…]()

**Comment by sibujacob** [comment]
this is great info ...thank you
