### ISSUE TITLE
[EstimatorInterface::setSystemFlagData]:This function seems to have a bug

### ISSUE THREAD

**Issue by BreederBai** [PX4/PX4-Autopilot#21421]
![image](https://user-images.githubusercontent.com/27894314/229674271-414f25b6-ca48-41aa-b3d0-5870b5033784.png)

It will never be true.
`if (time_us >= static_cast<int64_t>(_system_flag_buffer->get_newest().time_us + _min_obs_interval_us)) `
Variable system_ Flags and_ system_ flag_ buffer->get_ The newest() value is the same. That is to say, A-B>=A+C. When B and C are both positive numbers, this formula cannot hold.

**Comment by bresch** [comment]
Thanks for reporting this @BreederBai , it looks like the first buffer push shouldn't be there (the correct one is protected by the `if`): https://github.com/PX4/PX4-Autopilot/pull/21422

**Comment by BreederBai** [comment]
@bresch You're welcome. I'm glad to contribute to the improvement of the PX4 code
