### ISSUE TITLE
The code comment for the state vector(quat_nominal) in the ekf2 module may be incorrect.

### ISSUE THREAD

**Issue by mooncakeG** [PX4/PX4-Autopilot#21470]
When I learn the ekf2 module, I find that the code comment of "quat_nominal" in the state vector of ekf2 is the opposite of the mathematical derivation.

When I looked at The definition of state vector in the official website "PX4 User Guide - Using The ECL EKF", I found that the definition in the website was contrary to the code comment.

According to my derivation, I think the definition in the official website is correct and the code comment is wrong.

code annotation:

struct stateSample {
	Quatf    quat_nominal{};        ///< quaternion defining the rotation from body to earth frame
        ......
};

Web site "PX4 User Guide - Using the ECL EKF":

The Estimation and Control Library (ECL) uses an Extended Kalman Filter (EKF) algorithm to process sensor measurements and provide an estimate of the following states:
       Quaternion defining the rotation from North, East, Down local earth frame to X, Y, Z body frame

Hope to get official reply. Thanks!

**Comment by bresch** [comment]
Hi @mooncakeG ,

You're right, we use a standard Hamiltonian quaternion that represents a rotation from earth to body frame. The confusion probably comes from the fact that this quaternion is often used to express a body-frame vector in the earth frame (i.e.:passive rotation). Transforming the quaternion to a rotation matrix gives a `R_body_to_earth` and can be used for `v_earth = R_body_to_earth * v_body` where `v_body` is the `v` vector measured in body frame and `v_earth` is the same vector measured in earth frame.

**Comment by mooncakeG** [comment]
Thank you for your reply, this question really confused me for a while, now all the mathematical derivation is in order.
