### ISSUE TITLE
The new control_allocator module works very bad in PWM_MAIN output

### ISSUE THREAD

**Issue by TianmingLi** [PX4/PX4-Autopilot#21481]
## Describe the bug
With last main branch or v1.14.0_beta2 tag firmware, when the `Actuator ` configured like below image(PWM_MAIN1_2 -> MOTOR1_2, PWM_MAIN3_4 -> MOTOR3_4), after armed vehicle, the motor spin very strange with noise and jerk. the quadcopter is barely can not flight. 

[![i7d5NU.png](https://i.328888.xyz/2023/04/15/i7d5NU.png)](https://imgloc.com/i/i7d5NU)
[](url)

but, when actuator outputs change to PWM_AUX, every thing works fine.

[![i7duHX.png](https://i.328888.xyz/2023/04/15/i7duHX.png)](https://imgloc.com/i/i7duHX)

we tried v1.13 release version firmware, the PWM_MAIN output works well.

flight controller we tried: cuav v5+, hex cubeorange.

so, it's maybe not hardware issue.

## To Reproduce
1. flash last main branch firmware
2. open QGC
3. open Actuator tab, set PWM_MAIN1 to motor1, set PWM_MAIN2 to motor2, set PWM_MAIN3 to motor3, set set PWM_MAIN4 to motor4
4. switch to Stabilized mode
5. arm vehicle
6. push up throttle 

## Expected behavior
the motor spin very strange with noise and jerk

## Log Files and Screenshots
*Always* provide a link to the flight log file:
- Download the flight log file from the vehicle ([tutorial](https://docs.px4.io/main/en/getting_started/flight_reporting.html)).
- Upload the log to the [PX4 Flight Review](http://logs.px4.io/)
- Share the link to the log (Copy and paste the URL of the log)

Add screenshots to help explain your problem.

## Drone (please complete the following information):
- Generic quadcopter.

## Additional context
`[PWM outputs are grouped based on the hardware timer groups. Meaning all the outputs in one group must operate under the same protocol at the same rate (e.g. PWM signal at 400Hz for all the outputs in one group). Therefore it is not possible to map Servo and a Motor in the same output group, as they usually operate at a different rate.](https://docs.px4.io/main/en/config/actuators.html#actuator-outputs)`

is this issue caused by this?

**Comment by AlexKlimaj** [comment]
Set the minimum pwm values higher.
