### ISSUE TITLE
make px4_sitl_default jmavsim error

### ISSUE THREAD

**Issue by among777** [PX4/PX4-Autopilot#21648]
ubuntu22.04 jmavsim 
<img width="740" alt="image" src="https://github.com/PX4/PX4-Autopilot/assets/60375407/dab73767-9e79-4210-9e55-57d2954b9191">

The problem appears in Ubuntu22.04, but there is no problem in Ubuntu20.04

**Comment by julianoes** [comment]
I bet you are not using the latest version of PX4 since that has been fixed in the meantime.

It is just a warning, if you want to ignore it, just remove this line:
https://github.com/PX4/PX4-Autopilot/blob/6535cc758ebe1302bbd24a7bac14969c7c5129f0/cmake/px4_add_common_flags.cmake#L71
