### ISSUE TITLE
[Bug]: Unresponsive Drone in Multi-Drone Simulation

### ISSUE THREAD

**Issue by Apurv354** [PX4/PX4-Autopilot#21730]
### Describe the bug

I am trying to create a multi-drone simulation following this document - https://docs.px4.io/main/en/ros/ros2_multi_vehicle.html.
I am trying to spawn 4 drones and send commands through ROS2. One of the drones is not responding. I have tried changing the namespace but it doesn't work. The vehicle numbers are 2,3,4,5 and the problem happens in the 5th vehicle.

### To Reproduce

Run - sitl_multiple_run.sh with 4 px4_instance. 
Run - Write a Publisher similar to this - https://github.com/PX4/px4_ros_com/tree/main/src/examples/offboard_py for 4 drones. 

### Expected behavior

Target System 5 will not respond to the commands from the publisher. 

### Screenshot / Media

![PHOTO-2023-06-16-00-31-38](https://github.com/PX4/PX4-Autopilot/assets/61135492/2833733d-21d1-4a6e-b306-b4ebb3f4798c)

### Flight Log

```txt
https://logs.px4.io/plot_app?log=c7e2d06c-7a75-4ac2-a597-6e898f36bcb6
```

### Software Version

```txt
v1.13.3
```

### Flight controller

Pixhawk

### Vehicle type

Multicopter

**Comment by beniaminopozzan** [comment]
Hi @Apurv354 


I see a huge amount of preflight fails in the log you should fix those before looking into ROS 2
I see the from the log the drone moving even if all motors are stopped, there is something wrong with the simulation here

**Comment by Apurv354** [comment]
> 

I am using this [script](https://github.com/PX4/PX4-Autopilot/blob/main/Tools/simulation/gazebo-classic/sitl_multiple_run.sh) from PX4 to launch 4 drones in the simulation. Pre-flight fails are happening only in one drone I will try to fix them but all the other drones are working fine.
