### ISSUE TITLE
[Bug] unexpected work_queue exit or hang up on customer H743VI board

### ISSUE THREAD

**Issue by askariz** [PX4/PX4-Autopilot#21893]
### Base Information:

1. customer made STM32H743VI board reference to px4_fmu_v6c 
2. loop test : power on -> wait fix -> take off -> mission -> rtl  without propeller 

total tests :  91

### Isussue Information: 

ulog link : https://review.px4.io/plot_app?log=26fddd2c-b015-4eb7-8481-aa2def25bc3c 

### self analyse : 

some work_items of work_queue not running , but do not know it is exactly exited or just enter infinite loop 
the pic of it is like 
![image](https://github.com/PX4/PX4-Autopilot/assets/39890252/89060e6b-7f67-455b-8a5b-09973a5b6cab)
![image](https://github.com/PX4/PX4-Autopilot/assets/39890252/c07a236d-4d96-4c9f-8589-ce5ac1ab2cd6)
the upper items  are  not running yet 

same ulog is here https://review.px4.io/plot_app?log=eeef97b9-64f8-4601-8786-7eeb04e5e6dd 

### To Reproduce

loop test : power on -> wait fix -> take off -> mission -> rtl  without propeller 

total tests :  91

### Expected behavior

work_queue items running well 

### Flight Log

https://review.px4.io/plot_app?log=26fddd2c-b015-4eb7-8481-aa2def25bc3c

https://review.px4.io/plot_app?log=eeef97b9-64f8-4601-8786-7eeb04e5e6dd 

### Software Version

base version is 

https://github.com/PX4/PX4-Autopilot/commits/v1.12.3 of1daf0654ff02a0e40a12149d2dc7946dd6f9a607

### Flight controller

customer made refer px4fmu_v6c

### Vehicle type

Multicopter

**Comment by dagar** [comment]
I haven't seen this issue in PX4, we'd probably need to review any changes you've made. Nearly everything that runs in the work queues should be non-blocking with each scheduled cycle running to completion in a relatively short amount of time.
