### ISSUE TITLE
[Bug] Cant connect pixhawk with orin nx 

### ISSUE THREAD

**Issue by Thanosrom** [PX4/PX4-Autopilot#21982]
### Describe the bug

Hello im having trouble connecting pixhawk to orange cube with orin nx and then to intel d455.

I dont know if i have to install all those packages from that website :

https://ardupilot.org/dev/docs/companion-computer-nvidia-tx2.html

Jetpack is already installed and also the steps are not so analytic of how and what to do.

Iv also tried this article : Connecting PixHawk to Raspberry Pi and NVIDIA Jetson - Hackster.io

I used pip3 but the mavlink send me crypto kind of staff .Also i then try to open mission planner but i cant connect my drone to my baord with this software.

Im kinda confused of what software - firmware i need there are so many.Mavlink protocol , mavros,ros .

Can anyone tell me how i can connect all of this and what steps i need to follow?

Thanks.

### To Reproduce

-

### Expected behavior

-

### Screenshot / Media

-

### Flight Log

-

### Software Version

-

### Flight controller

-

### Vehicle type

Multicopter

### How are the different components wired up (including port information)

-

### Additional context

-

**Comment by TianmingLi** [comment]
Use  USB to UART Bridge for communication

Jetson baseboard UART not works

![]( https://user-images.githubusercontent.com/5005440/262902519-6d262265-988f-4394-ab43-b5eeccded96f.png)

and take a look this Mavros Offboard control setting up reference  https://github.com/TianmingLi/offboard-control/tree/main

ROS2 offboard control  is same schedule.
