### ISSUE TITLE
Use cmake as a unified build rule

### ISSUE THREAD

**Issue by zyy37** [PX4/PX4-Autopilot#22035]
### Describe problem solved by the proposed feature

Use cmake as a common build rule in your projects.

1. When building the entire project (`cd PX4-Autopilot && make px4_sitl_default`), you are directly using the `Makefile` file from the home directory, not the one generated by `cmake`. Now `Makefile` have many disadvantages, it is outdated, writing and reading are more troublesome, and not conducive to the development of large-scale projects.
2. The home directory has both `CMakeLists.txt` and `Makefile` file, which are two different source files. Not only increases the maintenance workload, but also confuses others.
3. Your `make` command is used not only for build, but also for executing binaries, like `cd /path/to/PX4-Autopilot && make px4_sitl gz_x500`. It's best to decouple.

### Describe your preferred solution

The best solution is to use `cmake` as a unified and unique build rule. Removing the method of directly writing `Makefile` file.

### Describe possible alternatives

N/A

**Comment by dagar** [comment]
There's nothing stopping you from using cmake directly, the Makefile is just for convenience.

For example running `make px4_sitl_default` is equivalent to running cmake and building manually.

``` Console

# using Makefile for convenience
$ make px4_sitl_default

# using cmake directly/manually
$ mkdir -p build/px4_sitl_default
$ cmake --build-dir=build/px4_sitl_default/ -DCONFIG=px4_sitl_default .
$ cmake --build build/px4_sitl_default/

```
