### ISSUE TITLE
[Bug] unable to start mission vehicle rejected arming

### ISSUE THREAD

**Issue by zyy37** [PX4/PX4-Autopilot#22042]
### Describe the bug

Hello, when I simulated the `px4_sitl`, `gz-garden` and QGroundControl, the QGC was in green but the aircraft did not move and displayed that "unable to start mission vehicle rejected arming". How to solve it, thanks.

![360截图20230905070731797](https://github.com/PX4/PX4-Autopilot/assets/143855581/fa9ddac6-7b93-413f-821c-89b5f413cdea)

### To Reproduce

1. Execute `make px4_sitl gz_x500` on Ubuntu 22.04 arm64.
2. Execute QGC on Windows10 x64. Use QGC's UDP mode to connect the platform of `px4_sitl`.

### Expected behavior

QGC should be in green and the aircraft should be moving along the route.

### Flight Log

n/a

### Software Version

ver all
HW arch: PX4_SITL
PX4 git-hash: d2819ca7542c7fc1c3b122371d9dd35cb7005270
PX4 version: 1.14.0 80 (17694848)
PX4 git-branch: main
OS: Linux
OS version: Release 5.15.0 (84869375)
Build datetime: Sep  4 2023 00:36:45
Build uri: localhost
Build variant: default
Toolchain: GNU GCC, 11.4.0
PX4GUID: 1006554d49534954414c44494e4f30303030
UNKNOWN MCU

### Flight controller

gz_x500

### Vehicle type

None

**Comment by bkueng** [comment]
Fix: https://github.com/mavlink/qgroundcontrol/pull/10810
