### ISSUE TITLE
[Bug] When rate & angle param value is changed to a specific value, a multicopter falls down or flies erratically

### ISSUE THREAD

**Issue by patric6123** [PX4/PX4-Autopilot#22052]
### Describe the bug

When rate & angle param value is changed to a specific value, a multicopter falls down or flies erratically.

The cases that a multicopter falls down,
1. MC_PITCHRATE_FF : 1.0 ( or higher )
2. MC_PITCHRATE_P : 0.01
3. MC_ROLL_P : -0.9
4. MC_ROLLRATE_D : 0.01
5. MC_ROLLRATE_D : 4.2
6. MC_ROLLRATE_FF : 4.0 ( or higher )
7. MC_ROLLRATE_P : 0.01
8. MPC_THR_MAX 0.0

The cases that a multicopter files abnormally,
1. MC_PITCH_P : 0.0
2. MC_PITCH_P : 345.0
3. MC_PITCHRATE_K : 4.0 ( or higher )
4. MC_PITCHRATE_P : 0.3
5. MC_ROLL_P : 0.0
6. MC_ROLLRATE_P : 0.03 and MC_ROLL_P : 0.1 ( change at once )
7. 

### To Reproduce

1. Run px4 gazebo_typhoon_h480
2. Take off
3. set the one of the cases

### Expected behavior

normal flight

### Screenshot / Media

[fall_down_hexa.webm](https://github.com/PX4/PX4-Autopilot/assets/143891125/9cec5c3e-599b-4ebc-8978-7726429ea1e6)

### Flight Log

.

### Software Version

1.13.3

### Flight controller

Hexarotor

### Vehicle type

Multicopter

**Comment by dagar** [comment]
This isn't a bug, these are parameters for the controller that need to be tuned for a specific vehicle. On products these generally aren't exposed for user editing because as you've seen setting them incorrectly can cause the vehicle to crash.
