### ISSUE TITLE
[Bug] PX4 sends wrong mission_type mavlink message for geofence

### ISSUE THREAD

**Issue by av-jeroen** [PX4/PX4-Autopilot#22069]
### Describe the bug

When sending the Geofence PX4 does not send the proper `mission_type` for the mavlink message `MISSION_ITEM_INT`. 

Looking at *mavlink_mission.cpp* it seems like the param `mission_type` is not set in `format_mavlink_mission_item()`, and it defaults to `MAV_MISSION_TYPE_MISSION`. For a geofence this should be `MAV_MISSION_TYPE_FENCE`. (eventhough the geofence was originally sent as `MAV_MISSION_TYPE_FENCE`)

This is especially troublesome because since v4.2.5 QGC does check the type of mission messages, and QGC will therefore after a restart be unable to load the geofence and report "*GeoFence transfer failed. Error: Mission read failed, maximum retries exceeded*". Link to PR: https://github.com/mavlink/qgroundcontrol/pull/10509/files
(Note that QGC is correct in checking this, it is PX4 which sends the wrong data)

### To Reproduce

1. Connect to drone / Run PX4 gazebo
2. Open QGC and connect to drone, draw a Geofence. Stop QGC.
3. Start wireshark, start recording
4. Open QGC, see Geofence is received.
5. Stop wireshark recording. 
6. Analyse mavlink mission messages in Wireshark

QGC receives from PX4 `MAV_MISSION_TYPE=MAV_MISSION_TYPE_MISSION`. 

By running Wireshark before step 2 you can also verify that QGC sents MISSION_ITEM_INT with `mission_type=MAV_MISSION_TYPE_FENCE`. 

### Expected behavior

When sending the geofence the mavlink message MISSION_ITEM_INT, entry MAV_MISSION_TYPE should equal "MAV_MISSION_TYPE_MISSION". 

### Flight Log

https://logs.px4.io/plot_app?log=2e053ada-7454-4bca-aadf-615c88717477

### Software Version

PX4 1.13.*

### Flight controller

Gazebo + Custom build

### Vehicle type

Multicopter

**Comment by julianoes** [comment]
I can reproduce this! Thanks for the issue!
