### ISSUE TITLE
[Bug] A multicopter flies abnormally when changing parameters.

### ISSUE THREAD

**Issue by patric6123** [PX4/PX4-Autopilot#22067]
### Describe the bug

A multicopter flies abnormally when chaning parameters.

In Quadrotor,
1. MC_PITCH_P : 21.5
2. MC_ROLL_P : 17.9, MPC_XY_VEL_P_ACC : 4.78
3. MC_ROLLRATE_K : 5.0
4. MC_YAW_P : 0.01( or lower )
5. MPC_XY_VEL_D_ACC : 1.8 ( or higher )
6. MPC_Z_VEL_MAX_DN : 2.0

In Hexarotor,
1. MPC_XY_P : 17.0 ( or higher )
7. MPC_Z_P : 0.0 ( or lower )
8. MPC_Z_VEL_P_ACC : 0.0

In VTOL Standard
1. MPC_Z_VEL_MAX_DN : -1.0
9. MC_ROLL_P : 0.5 ( or lower )
10. MPC_XY_P : 57.5 ( or higher )
11. MC_PITCH_P : 0.01
12. MPC_XY_VEL_I_ACC : 60.0
13. MPC_XY_VEL_D_ACC : 1.98
14. MPC_XY_VEL_P_ACC : 50.0
15. MPC_Z_VEL_MAX_UP : 0.0
16. MC_PITCHRATE_FF : 3.12
17. MC_ROLLRATE_P : 0.01
18. MC_ROLLRATE_FF 1.0
19. MC_PITCHRATE_P : 0.02
20. MC_ROLLRATE_K : 0.01
21. MC_ROLLRATE_FF : 10.0

### To Reproduce

1. Run px4
2. Take off
3. change params

### Expected behavior

.

### Flight Log

.

### Software Version

1.14.0-rc1

### Flight controller

Quadrotor, Hexarotor, VTOL Standard

### Vehicle type

Multicopter

**Comment by bresch** [comment]
same as : https://github.com/PX4/PX4-Autopilot/issues/22052

What are you actually trying to do?
