### ISSUE TITLE
[Bug] Mission start command sets idle after reboot instead of takeoff

### ISSUE THREAD

**Issue by tstastny** [PX4/PX4-Autopilot#22072]
### Describe the bug

Ok - so this is a real one. I thought I just messed up some branches / versions etc last time I caught this, but it happened again.
https://github.com/PX4/PX4-Autopilot/issues/21358#issuecomment-1696323289

Title describes it. Leads to runaway.

Sets IDLE position setpoint type instead of takeoff.
![image](https://github.com/PX4/PX4-Autopilot/assets/8026163/1ef57860-12c4-43c0-836e-d2e6be581c6d)

My guess is some bug in navigator on that command, not setting the right item for some reason .. and then secondary issue on fixedwing position controller that holds the last throttle command (which was initialized to cruise throttle in position mode) -- but need to investigate further.

### To Reproduce

I haven't been able to reliably reproduce yet. This is only second time I've seen it. But order of operations:
1. `make px4_sitl gazebo-classic_plane`
2. make a mission with a takeoff
3. slide for takeoff in QGC
4. let it finish the mission
5. dont delete the mission if it asks you to
6. kill the sim
7. `make px4_sitl gazebo-classic_plane`
8. dont delete the mission if it asks you to
9. slide for takeoff in QGC
10. plane will keep cruise throttle but set IDLE mode position setpoint type

### Expected behavior

Should set takeoff item, and takeoff properly.

### Flight Log

https://review.px4.io/plot_app?log=9bfc46e9-82f4-450f-af9c-c0dcceb82615

### Software Version

`main` - was testing fix branch.

### Flight controller

sim

### Vehicle type

Fixed Wing

**Comment by sfuhrer** [comment]
I was able to reproduce following your guide above. Got an additional warning message: No valid mission available, refusing takeoff (which it then obviously didn't refuse). 
![image](https://github.com/PX4/PX4-Autopilot/assets/26798987/7ed44196-5970-4be7-83f4-7baeeb72e965)
