### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by reo7749** [PX4/PX4-Autopilot#22104]
### Describe the bug

ubuntu20.04, PX4 1.14, "make px4_fmu-v3_default", error

### To Reproduce

reo@reo-T58-D:~/PX4-Autopilot$ make px4_fmu-v3 
-- PX4 version: v1.14.0-beta2-573-g6bd13c5514 (1.14.0)
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.8.10", minimum required is "3") 
-- PX4 config file: /home/reo/PX4-Autopilot/boards/px4/fmu-v3/default.px4board
-- PLATFORM nuttx
-- TOOLCHAIN arm-none-eabi
-- ARCHITECTURE cortex-m4
-- ROMFSROOT px4fmu_common
-- IO px4_io-v2_default
-- CONSTRAINED_MEMORY y
-- SERIAL_GPS1 /dev/ttyS3
-- SERIAL_TEL1 /dev/ttyS1
-- SERIAL_TEL2 /dev/ttyS2
-- SERIAL_TEL4 /dev/ttyS6
-- UAVCAN_INTERFACES 2
-- PX4 config: px4_fmu-v3_default
-- PX4 platform: nuttx
/usr/bin/env: “bash\r”: 没有那个文件或目录
/usr/bin/env: “bash\r”: 没有那个文件或目录
/usr/bin/env: “bash\r”: 没有那个文件或目录
mv: 无法获取'.version.tmp' 的文件状态(stat): 没有那个文件或目录
/usr/bin/env: “bash\r”: 没有那个文件或目录
/usr/bin/env: “bash\r”: 没有那个文件或目录
/usr/bin/env: “bash\r”: 没有那个文件或目录
mv: 无法获取'.version.tmp' 的文件状态(stat): 没有那个文件或目录
/usr/bin/env: “bash\r”: 没有那个文件或目录
make[2]: *** [tools/Unix.mk:390：clean_dirlinks] 错误 127
make[1]: *** [tools/Unix.mk:605：olddefconfig] 错误 2
-- The CXX compiler identification is GNU 9.3.1
-- The C compiler identification is GNU 9.3.1
-- The ASM compiler identification is GNU
-- Found assembler: /opt/gcc-arm-none-eabi-9-2020-q2-update/bin/arm-none-eabi-gcc
-- Check for working CXX compiler: /opt/gcc-arm-none-eabi-9-2020-q2-update/bin/arm-none-eabi-g++
-- Check for working CXX compiler: /opt/gcc-arm-none-eabi-9-2020-q2-update/bin/arm-none-eabi-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /opt/gcc-arm-none-eabi-9-2020-q2-update/bin/arm-none-eabi-gcc
-- Check for working C compiler: /opt/gcc-arm-none-eabi-9-2020-q2-update/bin/arm-none-eabi-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- cmake build type: MinSizeRel
CMake Error at platforms/nuttx/cmake/px4_impl_os.cmake:152 (message):
  Could not determine chip architecture from NuttX config.  You may have to
  add it.
Call Stack (most recent call first):
  CMakeLists.txt:318 (px4_os_determine_build_chip)

-- Configuring incomplete, errors occurred!
See also "/home/reo/PX4-Autopilot/build/px4_fmu-v3_default/CMakeFiles/CMakeOutput.log".
See also "/home/reo/PX4-Autopilot/build/px4_fmu-v3_default/CMakeFiles/CMakeError.log".
Error: /home/reo/PX4-Autopilot/build/px4_fmu-v3_default is not a directory
make: *** [Makefile:232：px4_fmu-v3] 错误 1

### Expected behavior

i help "Creating /home/reo/PX4-Aut..._fmu-v3_default/px4_fmu-v3_default.px4"

### Flight Log

no

### Software Version

1.14

### Flight controller

px4  2.4.8

### Vehicle type

None

**Comment by dagar** [comment]
Something is broken in your dev environment, but I'm not sure what.

As a workaround until that's resolved you could do the build in docker.

`./Tools/docker_run.sh 'make px4_fmu-v3_default'`
