### ISSUE TITLE
[Bug] Vehicles glitching into the ground in Gazebo 

### ISSUE THREAD

**Issue by frede791** [PX4/PX4-Autopilot#22214]
### Describe the bug

When launching Gazebo using one of the configuration options, such as: 
`PX4_SYS_AUTOSTART=4001 PX4_GZ_MODEL=x500 ./build/px4_sitl_default/bin/px4`
the vehicle glitches half into the ground rather than sitting on top of it. If you then try to take off, the vehicle will take off and immediately land again. I found this to happen with other vehicles too. 

### To Reproduce

In the PX4-Autopilot repo run:

`PX4_SYS_AUTOSTART=4001 PX4_GZ_MODEL=x500 ./build/px4_sitl_default/bin/px4`

You can also replicate the takeoff issue by typing:

`commander takeoff`

### Expected behavior

Vehicle should not clip into the ground but instead sit on top of it. The command should work as it is described in: http://docs.px4.io/main/en/sim_gazebo_gz/

### Screenshot / Media

![Screenshot from 2023-10-12 15-12-47](https://github.com/PX4/PX4-Autopilot/assets/80588263/67a1d2aa-dd69-4075-afe7-692be9918571)

### Flight Log

https://review.px4.io/plot_app?log=15b27264-2cad-4aaf-be7a-13764ceaa1cb

### Software Version

This is main from today. The exact commit is: 476b5d5594f6de867fcf2d59f5d56ffb1a2dc4d0

### Flight controller

It's in simulation.

### Vehicle type

Multicopter

**Comment by frede791** [comment]
Turns out it is not a glitch but rather the default position that is set to 0,0,0,0,0,0. Since the center of the vehicle is taken as the reference point, the result is that the lower half of the vehicle ends up below the ground.

**Comment by Jaeyoung-Lim** [comment]
@frede791 Yeap, that is why gazebo it is spawned a little higher, but is hacky either way

**Comment by frede791** [comment]
![Screenshot from 2023-10-12 18-27-39](https://github.com/PX4/PX4-Autopilot/assets/80588263/98b9aecb-e6f9-47e1-ab29-4d13411fd5be)

Running: `make px4_sitl gz_omnicopter`. Here the default pose is provided as 0 0 0 0 0 0. This should probably be slightly higher.

**Comment by frede791** [comment]
@Jaeyoung-Lim so it should probably never default to 0,0,0,0,0,0 but instead always take the pose from the sdf file?
