### ISSUE TITLE
[Bug] Broken px4vision model in Gazebo.

### ISSUE THREAD

**Issue by frede791** [PX4/PX4-Autopilot#22219]
### Describe the bug

The px4vision model does not work on Gazebo. It opens gazebo, but no model is loaded. Instead the error as shown below in the screenshot pops up. It appears to be segmentation fault. This does not happen with any other tested vehicles (standard_vtol, rc_cessna, x500 variants).

### To Reproduce

Running inside the PX4-Autopilot:
`make px4_sitl gz_px4vision`

### Expected behavior

Model should load into gazebo.  

### Screenshot / Media

![image](https://github.com/PX4/PX4-Autopilot/assets/80588263/a884b881-ff48-402c-953d-ec993ff71d31)

### Flight Log

-

### Software Version

Using newest commit: 476b5d5594f6de867fcf2d59f5d56ffb1a2dc4d0

### Flight controller

It's in simulation.

### Vehicle type

None

**Comment by Jaeyoung-Lim** [comment]
@frede791 Thanks for raising this, I can confirm that this is a problem

**Comment by frede791** [comment]
@Jaeyoung-Lim The xx-inertia values on the rotors seem way too large to me? If you place a minus (so 10^-7 rather than 10^7), I can load the model, but takeoff still does not work.

**Comment by Claudio-Chies** [comment]
`make px4_sitl gz_px4vision` seems to work now, so i'll close this for now.
