### ISSUE TITLE
[Bug] Wrong rotor and faulty mesh

### ISSUE THREAD

**Issue by frede791** [PX4/PX4-Autopilot#22275]
### Describe the bug

In the rc_cessna model, the turning direction of the rotor is set to be clockwise (`cw`), however the .dae mesh model that is used is `iris_prop_ccw.dae` which is incorrect. 

While using the `iris_prop_cw.dae` would solve the issue, this mesh in itself has some flaws at there are pieces of the rotor missing when viewed from the back (but not the front). 

While this does not impact flight performance, it is an ugly visual bug. 

### To Reproduce

Change the 'rotor_puller_visual' mesh uri from `iris_prop_ccw.dae` to `iris_prop_cw.dae` and launch gazebo as normal with: `make px4_sitl gz_rc_cessna`.

### Expected behavior

Full rotor should be visible from front and back.

### Screenshot / Media

![Screenshot from 2023-10-30 14-29-29](https://github.com/PX4/PX4-Autopilot/assets/80588263/ea0f60e8-e29f-4bff-826b-b04dfc1e1fde)

### Flight Log

N/A

### Software Version

Current main branch, commit: 794d0d177bf526a83b94c23f36b674f961955200

### Flight controller

It's in simulation.

### Vehicle type

None

**Comment by Jaeyoung-Lim** [comment]
@frede791 We could also just reverse the turning direction of the rotor since it only has one rotor right?

**Comment by frede791** [comment]
@Jaeyoung-Lim  Yes this would be a better solution, as the rotors on a Cessna are supposed to spin in a clockwise direction when viewed from the rear. Gazebo defines the rotation when viewed from the front.
