### ISSUE TITLE
Set system time from DDS timestamps

### ISSUE THREAD

**Issue by dakejahl** [PX4/PX4-Autopilot#22289]
### Describe problem solved by the proposed feature

In systems with a companion computer without a GPS, it would be nice to use the timestamps from the DDS bridge to set the PX4 system time.

### Describe your preferred solution

Set PX4 system time using DDS timestamps.

### Describe possible alternatives

Mavlink TIMESYNC service

### Additional context

Initial implementation here, looking for feedback
https://github.com/PX4/PX4-Autopilot/pull/22290

**Comment by PetervdPerk-NXP** [comment]
People considered using ntp as well? it's supported in NuttX and it works besides mavlink or dds.
Not sure about the code size and the timing precision, but could be worthwhile to test out.
https://github.com/apache/nuttx-apps/blob/647db6393d59dbeab3c12ab5d692585fa608148e/netutils/ntpclient/ntpclient.c#L85
