### ISSUE TITLE
[Bug] Land mode bug

### ISSUE THREAD

**Issue by lgh5054** [PX4/PX4-Autopilot#22422]
### Describe the bug

When switching to land mode, it does not land at the current location but RTL to Home.

### To Reproduce

1.arming and flight Position mode
2. Qground or RC Land mode change

### Expected behavior

return to home

### Flight Log

no

### Software Version

1.14.0 releases

### Flight controller

kakute h7 mini

### Vehicle type

None

**Comment by dakejahl** [comment]
Land mode does indeed work on 1.14. Please provide a log and more specific information about your issue.
