### ISSUE TITLE
[Bug] The Breach Return Point set in QGC is invalid.

### ISSUE THREAD

**Issue by Drone-Lab** [PX4/PX4-Autopilot#22428]
### Describe the bug

When we set up a geofence and a Breach Return Point in QGC, and manually fly the drone into the geofenced area, even with RTL TYPE set to 3 (Closest Safe Destination Return Type, RTL_TYPE=3), the drone ignores the Breach Return Point and returns to the home point instead. It appears that the Breach Return Point is a non-functional feature. I couldn't find any documentation for this feature in the official PX4 documentation

### To Reproduce

1. Take off the drone and upload the geofence. Add a Breach Return Point near the geofence in QGC.
![图片](https://github.com/PX4/PX4-Autopilot/assets/151698793/ea51df0a-ec5e-45d4-a1bc-7f933647a50d)

2. Manually control the aircraft to fly towards the restricted area, making contact with the geofence (It's not possible to set a direct course into the restricted area, but you can set a route outside the restricted zone).
![图片](https://github.com/PX4/PX4-Autopilot/assets/151698793/1a1de060-0265-4b27-99a1-c0aa24481370)

### Expected behavior

Even when the Breach Return Point is closer than the home point, the drone does not navigate towards the Breach Return Point after breaching the geofence.
![图片](https://github.com/PX4/PX4-Autopilot/assets/151698793/c0f71a17-27a5-4d8c-afd2-c6860d9e2f79)

### Flight Log

none

### Software Version

HW arch: PX4_SITL
PX4 git-hash: 83841d1ad183e1b874fad1d07e5cd6a448d0c90e
PX4 version: 1.14.0 0 (17694720)
PX4 git-branch: main
OS: Linux
OS version: Release 5.15.0 (84869375)
Build datetime: Nov 14 2023 17:45:03
Build uri: localhost
Build variant: default
Toolchain: GNU GCC, 9.4.0
PX4GUID: 1006554d49534954414c44494e4f30303030
UNKNOWN MCU

### Flight controller

none

### Vehicle type

None

**Comment by sfuhrer** [comment]
With current main it works as expected. I here set RTL_TYPe to 3.
https://github.com/PX4/PX4-Autopilot/assets/26798987/61167af5-4649-45a8-b367-b2561b22ca85

**Comment by Drone-Lab** [comment]
> With current main it works as expected. I here set RTL_TYPe to 3. https://github.com/PX4/PX4-Autopilot/assets/26798987/61167af5-4649-45a8-b367-b2561b22ca85

Nice work,thanks for your contribution!
