### ISSUE TITLE
[Bug] Drone does not stop when clicking Pause in QGC during mission mode

### ISSUE THREAD

**Issue by Drone-Lab** [PX4/PX4-Autopilot#22492]
### Describe the bug

We have identified a bug where, during the execution of a mission, clicking 'Pause' in QGroundControl (QGC) does not cause the drone to stop as per the QGC manual. Instead, the drone completes the current task and flies to the next waypoint before stopping. Additionally, attempting to 'Hold' manually  again during this process does not halt the drone.It's not a ui bug, the drone is indeed in loiter/hold mode.But it seems to only execute part of the code in hold mode.

**We are trying to fix this issue.**

### To Reproduce

1. Plot the mission.
2. Drone executes the mission.
3. While executing the mission (not in takeoff or ascent/descent states), click 'Pause' in QGroundControl (QGC).

### Expected behavior

The drone does not stop immediately as per the manual; instead, it continues until reaching the mission waypoint before coming to a halt.

### Screenshot / Media

![image](https://github.com/PX4/PX4-Autopilot/assets/151698793/9a67fa4d-af02-4282-a3f4-7155a0bf8b08)

![image](https://github.com/PX4/PX4-Autopilot/assets/151698793/63cd28e5-3271-41c3-a0a6-7485c8edfaf7)

### Flight Log

[issue_mission_pause_fail.zip](https://github.com/PX4/PX4-Autopilot/files/13579083/issue_mission_pause_fail.zip)

### Software Version

HW arch: PX4_SITL
PX4 git-hash: 9d465615d11ab4b570a66da22a3681f56679a317
PX4 version: 1.15.0 40 (17760320)
PX4 git-branch: main
OS: Linux
OS version: Release 5.15.0 (84869375)
Build datetime: Nov 30 2023 15:12:54
Build uri: localhost
Build variant: default
Toolchain: GNU GCC, 9.4.0
PX4GUID: 1006554d49534954414c44494e4f30303030
UNKNOWN MCU

### Flight controller

SITL

### Vehicle type

None

**Comment by ryanjAA** [comment]
Same. Confirmed. If you hit hold it will stop but pause is broken and does continue.

**Comment by Drone-Lab** [comment]
> Same. Confirmed. If you hit hold it will stop but pause is broken and does continue.

Yes.It's not a ui bug, the drone is indeed in loiter/hold mode.But it seems to only execute part of the code in hold mode.

**Comment by sfuhrer** [comment]
I'm not able to reproduce, for me it always stops when I pause. This is with current main and QGC 4.2.8
https://github.com/PX4/PX4-Autopilot/assets/26798987/e2d51215-3a1a-482a-82a0-c080e248201b

**Comment by Drone-Lab** [comment]
Thanks ,I reproduce it on  QGC 4.2.8 and current main agaian. 

When you try to reproduce this bug, let the drone fly for a while (for example, between waypoint 2 and 3) and wait until it is highly stabilized before hitting pause.

We've pinpointed the cause of the problem, which is due to a multi-threaded race condition, so this doesn't always trigger (but most do). Additionally this issue doesn't trigger when the drone takes off, as pause while taking off, will use the current position as the mission target.

**Comment by ryanjAA** [comment]
I’ll make a video. Does it every-time in sitl for me.

**Comment by Drone-Lab** [comment]
https://github.com/PX4/PX4-Autopilot/assets/151698793/93dfb37a-6255-4b8d-86b4-cafedab6c7a8

This is with current main.

**Comment by sfuhrer** [comment]
> can.t.pause.mp4
> 
> This is with current main.

Thanks for reproducing again and sharing the video. Do you per chance still have the log file? You can find it for SITL flights under `/build/px4_sitl_default/rootfs/log`
