### ISSUE TITLE
[Bug] Somes px4 ros topic don't open

### ISSUE THREAD

**Issue by ozitoune** [PX4/PX4-Autopilot#22523]
### Describe the bug

I just make a fresh install off ubuntu serveur 22.04 on a raspbery pi 4. 
I have installed and sourced px4 msg by dowloading it then colcon, no problem...
I have installed uxrece by snap, and its ok , i see the px4 topics, but i have a problem with  /fmu/out/vehicle_local_position and  /fmu/out/vehicle_air_data...  I can open /fmu/out/vehicle_odometry,  /fmu/out/vehicle_attitude, and others... buen impossible to echo vehicle_local_position... 
I have used the official documenttaion ...
I can see and echo this topics on another computer , or on my old ubuntu desktop install on my raspery

Here is a terminal output from a note that read different px4 topics : 

`>>> [rcutils|error_handling.c:108] rcutils_set_error_state()
This error state is being overwritten:

  'Fast CDR exception deserializing message of type px4_msgs::msg::dds_::VehicleLocalPosition_., at ./src/type_support_common.cpp:118'

with this new error message:

  'Fast CDR exception deserializing message of type px4_msgs::msg::dds_::SensorGps_., at ./src/type_support_common.cpp:118'

rcutils_reset_error() should be called after error handling to avoid this.
<<<

>>> [rcutils|error_handling.c:108] rcutils_set_error_state()
This error state is being overwritten:

  'Fast CDR exception deserializing message of type px4_msgs::msg::dds_::SensorGps_., at ./src/type_support_common.cpp:118'

with this new error message:

  'Fast CDR exception deserializing message of type px4_msgs::msg::dds_::VehicleLocalPosition_., at ./src/type_support_common.cpp:118'

rcutils_reset_error() should be called after error handling to avoid this.
<<<

>>> [rcutils|error_handling.c:108] rcutils_set_error_state()
This error state is being overwritten:

  'Fast CDR exception deserializing message of type px4_msgs::msg::dds_::VehicleLocalPosition_., at ./src/type_support_common.cpp:118'

with this new error message:

  'Fast CDR exception deserializing message of type px4_msgs::msg::dds_::VehicleAirData_., at ./src/type_support_common.cpp:118'

rcutils_reset_error() should be called after error handling to avoid this.
<<<

>>> [rcutils|error_handling.c:108] rcutils_set_error_state()
This error state is being overwritten:

  'Fast CDR exception deserializing message of type px4_msgs::msg::dds_::VehicleAirData_., at ./src/type_support_common.cpp:118'

with this new error message:

  'Fast CDR exception deserializing message of type px4_msgs::msg::dds_::VehicleLocalPosition_., at ./src/type_support_common.cpp:118'

rcutils_reset_error() should be called after error handling to avoid this.
<<<
^CTraceback (most recent call last):
`
We can see pb with air data, sensor gps and vehicle local position

### To Reproduce

Install ubuntu server 22.04 
Install uxrce agent by snap
downloads px4_msgs from git and build it with colcon.
start  the agent 
List ros topics , ty to echo /fmu/out/vehicle_local_position...
Impossible to echo thios topic and others.

### Expected behavior

normally i can echo all topics,  but now some are present and other no...

This happen only on a fresh install on my raspbery pi 4 with ubuntu 22.04 server, i can echoo all topics with another computer

### Flight Log

no log

### Software Version

the last stable version

### Flight controller

pixhawk 6x

### Vehicle type

None

**Comment by CannonFodder511** [comment]
Did you solve this? I have the same issue.

**Comment by ozitoune** [comment]
Yes , it was a mistake from me, you need to compile the correct px4_msgs for your version , if you are on the stable firmware you have to change the branch of px4_msgs and use the 1.14 for the compilation
