### ISSUE TITLE
TECS integrator tuning changes over time

### ISSUE THREAD

**Issue by sfuhrer** [PX4/PX4-Autopilot#22540]
Due to a bug present in some PX4 versions, the interpretation of the TECS tuning parameters for throttle integral (FW_T_I_GAIN_THR) and throttle damping (FW_T_THR_DAMP) changed over time.

This issue report is meant to explain the root cause, show the effect on different PX4 versions and propose a way forward.

### Introduced bug
With https://github.com/PX4/PX4-Autopilot/pull/16362, the input into the tecs throttle integral calculation was started to be filtered: 
It was overlooked that the TECS::_initialize_states() method is run at every iteration of TECS, and thus the filter was constantly reset to 0: https://github.com/PX4/PX4-Autopilot/blob/55374fe589f43dc8a14d9c0c2e0b98e60e91df66/src/lib/tecs/TECS.cpp#L499. 

### Functional changes due to the bug
The filter equation is: output=state*(1-alpha) + sample * alpha. As in our case we constantly reset the state to 0, the filter does nothing else than adding a factor of alpha to the input. 
alpha is defined as dt/(dt+T). T (time constant) is the param FW_T_STE_R_TC, which by default is 0.4 → the factor is 0.048 (~0.05) by default, which means that, if the integrator gain is unchanged, the bug results in a 20 times slower convergence of the throttle integrator. 

### TECS throttle integrator behavior of different PX4 versions (left at default)
The bug was introduced in v1.12, and was persistent also in v1.13. v1.14 has it fixed with https://github.com/PX4/PX4-Autopilot/commit/b1cbe04694bcb85161126df641dc7ebb66e8697a (part of a big TECS refactor).

In the following plots the result of the throttle integrator on a step input is shown. The step input is simulated by increasing the trim throttle (THR_TRIM) by 10%. All params are left as default (resp. as they are set in the SITL plane config).

v1.11:
This is the last version before the bug. Additionally there was a factor of 8 applied to the integral increase (through the throttle TC).
![image](https://github.com/PX4/PX4-Autopilot/assets/26798987/693136b6-56d3-4d1b-8b43-5f72e8c23b60)

v1.12:
This is the first version with the bug.
![image](https://github.com/PX4/PX4-Autopilot/assets/26798987/c1fb1fd2-fed1-47c9-9963-80a9355a638f)

v1.13:
Second version with bug. 
![image](https://github.com/PX4/PX4-Autopilot/assets/26798987/a6cba09c-f646-4c46-8647-a322bc87f672)

v1.14:
First version with the fix.
![image](https://github.com/PX4/PX4-Autopilot/assets/26798987/8dd6b761-2089-4412-ac68-ad3d2b7691a3)

current main:
![image](https://github.com/PX4/PX4-Autopilot/assets/26798987/aa6a61de-b7ed-4c2b-8b04-f25bf28a1b86)

From v1.11 to v1.12 the throttle integrator convergence is massively slowed down. This is likely mostly due to the introduced bug (~20x slower), plus the deliberate removal of the throttle time constant (~8x). 
From v1.12 to v1.13 the integrator became again much faster, and back to reasonable regions. Part of that increase came from the bumping of the integrator gain (FW_T_I_GAIN_THR) from 0.1 to 0.3. 
The change to v1.14 resulted in a small reduction in convergence time (faster integrator). It includes the fix for the filter reset (~20x faster) as well as a reduction of the gain by 6x. 

### Conclusion
The default behavior of v1.13 and v1.14 is similar. Users who just fly with the default TECS gains thus won't notice a lot. If they instead changed the TECS tuning previously to updating to v1.14, then the update brings along a drastic change of flight dynamics. Example: They set FW_T_I_GAIN_THR to 0.4, which is only 30% higher than the default at the time, but then after updating, it is 8x the default, and will lead to a bad flight performance. 

Here the plot of a SITL test of current main with FW_T_I_GAIN_THR set to 0., so the previous default. There are some clear oscillations visible in the response, and would that have been a real plane it would have likely got unstable. 
![image](https://github.com/PX4/PX4-Autopilot/assets/26798987/825ea9c8-1222-4458-a570-2d3b09e5df7a)

The same btw applies to the throttle damping, FW_T_THR_DAMP. It is a bit less of an issue because the default on v1.13 was very small (0.1), and it can still be flown on an average plane with v1.14 with that value without experiencing instability. 

### Proposed next steps
- for the defaults: lower FW_FW_T_I_GAIN_THR and T_THR_DAMP both a bit more to get closer to the pr-v1.14 defaults
- for catching non-default settings:
  - Option A) Deprecate the old params FW_FW_T_I_GAIN_THR and T_THR_DAMP and in their place make new ones (on v1.14 and main). Then, on updating, previous tuning gets reset to default, which is much better than keeping it. Alternatively we could do some sort of param translation (eg with a factor of 20). 
  - Option B) limit the params to sane values (hard coded, not just in param meta data)
  - Option C) Give warning when the settings are above a certain threshold
  - Option D) Introduce an "acknowledge parameter": give a warning if either the integ or the damping params are above the new default, unless the "acknowledge parameter" is disabled. 

### Learnings
- if you find a bug that results in a strong change in param interpretation, deprecate old param and make new one

**Comment by ryanjAA** [comment]
Thanks for highlighting this.
