### ISSUE TITLE
Vector asigment with vec.xy() = vec.xy() does not work [Bug] 

### ISSUE THREAD

**Issue by sverrevr** [PX4/PX4-Autopilot#22565]
### Describe the bug

The following assignment fails:
```c++
Vector3f lhs(1,2,3);
Vector3f rhs(4,5,6);
lhs.xy() = rhs.xy();
EXPECT_EQ(lhs, Vector3f(4,5,3));
```

```bash
[ RUN      ] MatrixVector3Test.Vector3
../../src/lib/matrix/test/MatrixVector3Test.cpp:70: Failure
Expected equality of these values:
  lhs
    Which is: 
               1               2               3

  Vector3f(4,5,3)
    Which is: 
               4               5               3

[  FAILED  ] MatrixVector3Test.Vector3 (0 ms)
```

So `lhs` is not getting assigned.

This form of assignment is used multiple places in the code for example here: https://github.com/PX4/PX4-Autopilot/blob/c63214bcaecdb84bdf07d7eb76cdef7a93498148/src/modules/flight_mode_manager/tasks/ManualPosition/FlightTaskManualPosition.cpp#L112-L121

I noticed this change when the position lock no longer activated when testing 1.14

Note that the following test which is originally a part of `MatrixVector3Test.cpp` passes:
```c++
Vector2f g2(1, 3);
Vector3f g3(7, 11, 17);
g3.xy() = g2;
EXPECT_EQ(g3, Vector3f(1, 3, 17));
```

### To Reproduce

Add the following lines of code to `PX4-Autopilot/src/lib/matrix/test/MatrixVector3Test.cpp`
```c++
Vector3f lhs(1,2,3);
Vector3f rhs(4,5,6);
lhs.xy() = rhs.xy();
EXPECT_EQ(lhs, Vector3f(4,5,3));
```
Run:
`make tests`

### Expected behavior

`lhs` should be assigned, the tests should pass.

### Flight Log

Not relevant as it can be tested with unit tests

### Software Version

Newest main when writing this issue: https://github.com/PX4/PX4-Autopilot/commit/c63214bcaecdb84bdf07d7eb76cdef7a93498148
And on 1.14 release

### Flight controller

N/A

### Vehicle type

None

**Comment by sverrevr** [comment]
In 1.13 the position lock worked. This was broken by this commit which changed to using .xy instead of assigning each element separately. https://github.com/PX4/PX4-Autopilot/pull/20440/files#diff-6a93912921c62df6bced857c3dea68c3c275d25faa3f6c78866eafedc4e5612fR113

**Comment by bresch** [comment]
Thanks for reporting, I'm looking into this issue.

**Comment by MaEtUgR** [comment]
@sverrevr Thanks for spotting and reporting this in detail! We'll have a look.

**Comment by sverrevr** [comment]
Good job! And thanks for solving this so rapidly  :) This solves the observed problem of the position lock not engaging. Position set points are now set when the joystick is released.
