### ISSUE TITLE
The error occurs when using FlightGear for software-in-the-loop simulation in v1.14 and later.

### ISSUE THREAD

**Issue by 747640013** [PX4/PX4-Autopilot#22633]
### Describe the bug

I use FlightGear for fixed-wing software-in-the-loop simulation. However, after running the command "make px4_sitl_nolockstep flightgear_rascal-electric," I encountered the following error:

ERROR [simulator_mavlink] Number of simulated accelerometers 80 out of range. Max: 3.

This issue arises in PX4 Firmware version 1.14, while it doesn't occur in version 1.13.3.  I am looking to resolve this problem, but I am having difficulty identifying the issue. Does anyone have any suggestions?

### To Reproduce

1.
```bash
cd /the path/PX4-Autopilot
```
2.
```bash
make px4_sitl_nolockstep flightgear_rascal-electric
```
3.waiting for FG load
4. The error is as follows:
```bash
ERROR [simulator_mavlink] Number of simulated accelerometers 80 out of range. Max: 3.
or ERROR [simulator_mavlink] Number of simulated accelerometer 96 out of range. Max: 3
```

### Expected behavior

provide some suggestions

### Flight Log

https://review.px4.io/plot_app?log=089bc4a9-4f92-40e9-9775-5051d74f5f44

### Software Version

v1.14

### Flight controller

no

### Vehicle type

rascal-electric

**Comment by 747640013** [comment]
I seem to have found the cause of the issue. In PX4-Autopilot/Tools/simulation/flightgear/flightgear_bridge/vehicle_state.cpp, the rcehicleState::getSensorMsg function lacks initialization for sensor_msg.id.

**Comment by bmklein5** [comment]
@747640013 how did you initialize it?
