### ISSUE TITLE
PX4 postion control about  velocity PID of D control [Question] 

### ISSUE THREAD

**Issue by lixiaowei123** [PX4/PX4-Autopilot#22807]
### Describe the bug

Why does speed PID control not use error differentiation, but rather the differentiation of the current speed.

![3d650de3e507162665cdd0d57c40a05](https://github.com/PX4/PX4-Autopilot/assets/16605202/7c2bd906-0e23-439e-bf7f-9600ed7e9eba)

![1c5c27134142fe3519d08538ef82696](https://github.com/PX4/PX4-Autopilot/assets/16605202/a1f58656-cd1f-4a71-a982-07d9240ce54a)

### To Reproduce

..

### Expected behavior

..

### Screenshot / Media

..

### Flight Log

...

### Software Version

all 

### Flight controller

PX4    velocity PID

### Vehicle type

None

### How are the different components wired up (including port information)

...

### Additional context

...

**Comment by bresch** [comment]
Hi @lixiaowei123 , 

Here you can find the reason why we don't differentiate the error: http://brettbeauregard.com/blog/2011/04/improving-the-beginner%E2%80%99s-pid-derivative-kick/

Please use the forum (https://discuss.px4.io/) and the Dronecode Discord server to ask questions. The github issues is reserved for issues.
