### ISSUE TITLE
[Bug] CDC/ACM reconnecting when powered from USB power supply

### ISSUE THREAD

**Issue by PetervdPerk-NXP** [PX4/PX4-Autopilot#23179]
### Describe the bug

Since the change from #22234 when powering an FMU from a USB power supply you get constant serdis/sercon events.
```
serdis: Disconnected
sercon: Registering CDC/ACM serial driver
sercon: Successfully registered the CDC/ACM serial driver
serdis: Disconnected
sercon: Registering CDC/ACM serial driver
sercon: Successfully registered the CDC/ACM serial driver
serdis: Disconnected
sercon: Registering CDC/ACM serial driver
sercon: Successfully registered the CDC/ACM serial driver
serdis: Disconnected
sercon: Registering CDC/ACM serial driver
sercon: Successfully registered the CDC/ACM serial driver
serdis: Disconnected
sercon: Registering CDC/ACM serial driver
sercon: Successfully registered the CDC/ACM serial driver
```
Before #22234 this wasn't the case.

### To Reproduce

USB power supply (not a PC) connect to FMU.
Then on debug port connect a serial adapter then you observe constant sercon/serdis events.

### Software Version

Main

### Flight controller

FMU-V6XRT

**Comment by AlexKlimaj** [comment]
@dakejahl and I just talked about it. Looks like we just need to differentiate the failed state. One where vbus is present but no computer exists on the other end and one where vbus isn't present. In your case it shouldn't change to the disconnected state but should just stay in the connecting state.

https://github.com/PX4/PX4-Autopilot/pull/22234/files#diff-62140730d7cb3793dfa65e620894497238d929ef6f9450a0bbe0660a08c1a9e5R328-R338
