### ISSUE TITLE
[Bug] The mavlink module has heap-overflow

### ISSUE THREAD

**Issue by zhangteng0526** [PX4/PX4-Autopilot#23251]
### Describe the bug

When sending a mavlink message to the drone, ASAN detected a heap-overflow and caused the software to exit.

### To Reproduce

1. Start the drone software simulation
2. Send a mavlink message to the drone,and the valid_pointsfield is greater than 5
3. The software-in-the-loop simulation crashes

### Expected behavior

The software-in-the-loop simulation crashes

### Screenshot / Media

![image](https://github.com/PX4/PX4-Autopilot/assets/49060609/637ba649-57ad-4f63-9491-c99a709ff292)

### Flight Log

。

### Software Version

v1.12.3

### Flight controller

,

### Vehicle type

None

### How are the different components wired up (including port information)

,

### Additional context

,

**Comment by federicociresola** [comment]
@zhangteng0526 can you reload the image? because it has loaded wrong

**Comment by dagar** [comment]
If you could run latest PX4 on address sanitizer on current PX4 (latest stable or main branch) that would be helpful. Unfortunately we're not able to maintain old releases (v1.12 was release July 2021).
