### ISSUE TITLE
[Bug] Again Stale message error when the gz is running

### ISSUE THREAD

**Issue by federicociresola** [PX4/PX4-Autopilot#23259]
### Describe the bug

When I run the gazebo I obtain from px4 the following error:
```
...
ERROR [sensors] Accel #0 fail:  STALE!
ERROR [sensors] Gyro #0 fail:  STALE!
...
```
I thought that has been resolved with the #22767 

### To Reproduce

1. clone the PX4 repository
2. `make px4_sitl gz_x500`

### Expected behavior

px4 without error during the simulation

### Screenshot / Media

![Screenshot from 2024-06-11 10-12-10](https://github.com/PX4/PX4-Autopilot/assets/22128232/ea87e79d-35b3-4ffb-a007-b84399f33b98)

### Flight Log

- 

### Software Version

- ROS2 version: **Humble**
- Gazebo version: **Garden**
- OS version: **Ubuntu 22.04**
- PX4 version: **last main**

### Flight controller

x500

### Vehicle type

Multicopter

**Comment by PerFrivik** [comment]
Is this a freshly cloned vanilla PX4, also did you try a `git submodule update --recursive --init` ?

**Comment by federicociresola** [comment]
I have tried, but I still have the problem

**Comment by StefanoColli** [comment]
How did you install Gazebo? From source or by using the ubuntu.sh script in the px4 repo?

**Comment by federicociresola** [comment]
I installed it from ROS2 package with the following command
```
sudo apt install ros-humble-ros-gzgarden
```
Is it possible that this is the problem?

**Comment by federicociresola** [comment]
I tried to remove the Gazebo garden installed through ROS2 and I installed gz-garden but there is still the problem
```
# Remove ros2 gz garden
sudo apt remove ros-humble-ros-gzgarden ros-humble-ros-gzgarden-sim

# Install gz garden from PX4 shell script
./Tools/setup/ubuntu.sh
```

**Comment by PerFrivik** [comment]
Can you install gazebo through the PX4 installation guide please? There may be conflicting versions issues, as PX4 does not use the newest GZ version. 

https://docs.px4.io/main/en/dev_setup/dev_env_linux_ubuntu.html#simulation-and-nuttx-pixhawk-targets 

Please try setting up the dev environment and see if that helps.

**Comment by federicociresola** [comment]
you were right there was a conflict in somewhere with Gazebo version of the package manager of Ubuntu and ROS2 Humble.

Thank you all for your help!

I leave here the brute force procedure that I have used (be careful when using it):
```
# ROS2
sudo apt remove --purge ros-humble-ros-gzgarden*

# Ubuntu apt gazebo
sudo dpkg --list | grep gazebo
sudo apt remove --purge  *gazebo*

# Ubuntu apt ignition
sudo dpkg --list | grep  ignition
sudo apt remove --purge *ignition*

sudo apt autoremove
```
