### ISSUE TITLE
[CI] VTOL SITL tests are failing on every PR

### ISSUE THREAD

**Issue by dakejahl** [PX4/PX4-Autopilot#23275]
### Describe the bug

> 'RTL direct rally without approaches forced': failed

### To Reproduce

Open a PR

### Expected behavior

CI doesn't fail

### Flight Log

n/a

### Software Version

main

### Flight controller

n/a

### Vehicle type

None

### Additional context

@sfuhrer can you take a look?

**Comment by sfuhrer** [comment]
Can you link a failed CI run please? I was not aware of that one failing, though I'm currently working on making the Fly VTOL mission with wind change (ramped_up_wind.world) more stable.
