### ISSUE TITLE
Missing Parameters for XRCE Communication on CubePilot [Bug] 

### ISSUE THREAD

**Issue by ecschuetz** [PX4/PX4-Autopilot#23439]
### Describe the bug

i installed the CubePilot Firmware for the **cubeorangeplus** Controller.
Inside [boards/cubepilot/cubeorangeplus/default.px4board](https://github.com/PX4/PX4-Autopilot/blob/81575049dfb52392673154e52c4499f360284b1b/boards/cubepilot/cubeorangeplus/default.px4board) i can find:
`CONFIG_MODULES_UXRCE_DDS_CLIENT=y
`
and with
`MicroXRCEAgent udp4 -p 8888`
i can fetch the published topics so everything seems to work.

But i am Missing most of the XRCE parameters. The only Parameter i can find is
`UXRCE_DDS_CFG`

I cannot find the following Parameters:
```
UXRCE_DDS_AG_IP 
UXRCE_DDS_DOM_ID 
UXRCE_DDS_KEY 
UXRCE_DDS_PRT 
UXRCE_DDS_PTCFG 
UXRCE_DDS_SYNCC 
UXRCE_DDS_SYNCT 
```

How can i enable those Parameters on my cubeorangeplus?

Best

### To Reproduce

Install Firmware for CubePilot as suggested. See [here](https://docs.px4.io/main/en/config/firmware.html)
Go to parameters in QGroundControl
Look for Parameters "XRCE"
Only find the UXRCE_DDS_CFG parameter

### Expected behavior

Find all suggested UXRCE-DDS Client Parameters as described [here](https://docs.px4.io/main/en/advanced_config/parameter_reference.html)

### Screenshot / Media

![image](https://github.com/user-attachments/assets/ed35bb1e-38c8-44ca-98e1-6e8553b83f12)

### Flight Log

no log

### Software Version

cubepilot

### Flight controller

CubePilot Cube Orange+ Flight Controller

### Vehicle type

None

**Comment by jynxmagic** [comment]
If you enable the UXRCE_DDS_CFG parameter and reboot the cubepilot, the other parameters will appear.

You can reproduce this bug by flashing the cubepilot orange with fresh firmware, then searching for the parameters. Only UXRCE_DDS_CFG parameter will show until it is enabled and rebooted.
