### ISSUE TITLE
[Bug] GZ Simulation bricked with worlds different from 'default', waiting endlessly

### ISSUE THREAD

**Issue by your-sudden-death** [PX4/PX4-Autopilot#23612]
### Describe the bug

When spawning any other world in Gazebo Ignition with `make px4_sitl gz_standard_vtol_default2`
with world 'default2' being an exact copy of 'default', with only the name change in the SDF File, the GZ Bridge does not exit its loop for waiting on Gazebo, endlessly cycling with:

```
ERROR [gz_bridge] Service call timed out. Check GZ_SIM_RESOURCE_PATH is set correctly.
WARN  [gz_bridge] Service call timed out as Gazebo has not been detected.
```

This is due to an oversight in commit ae165561076541efd2db00b28a05ad42c190b9ff, where the world name was not correctly substituted into the string for the message call

Diff to fix the issue:
```
diff --git a/src/modules/simulation/gz_bridge/GZBridge.cpp b/src/modules/simulation/gz_bridg
e/GZBridge.cpp
index 7b45600e57..29d19fe111 100644
--- a/src/modules/simulation/gz_bridge/GZBridge.cpp
+++ b/src/modules/simulation/gz_bridge/GZBridge.cpp
@@ -154,7 +154,7 @@ int GZBridge::init()
 				return PX4_ERROR;
 			}

-			std::string scene_info_service = "/world/default/scene/info";
+			std::string scene_info_service = "/world/" + _world_name + "/scene/
info";
 			bool scene_created = false;

 			while (scene_created == false) {
```

Thank you in advance

### Software Version

56560726d37489b9670631a844f52ddca7b99495

### Vehicle type

None

**Comment by Jaeyoung-Lim** [comment]
@your-sudden-death Thanks for the bug report. Could you make a PR for the fix?
