### ISSUE TITLE
[Bug] Syntax Issue in VehicleCommand.msg

### ISSUE THREAD

**Issue by henrihein** [PX4/PX4-Autopilot#23736]
### Describe the bug

On line 85 in msg/VehicleCommand.msg, there is an errant '\*/' sequence at the end of the line. I discovered this because the px4_msgs project does not build with the ros2 tools. I manually removed the '\*/' from the end of the line and that made the px4_msgs package build. 

### To Reproduce

One way is to try to build a ROS2 workspace. From the [guidelines](https://docs.px4.io/main/en/ros2/user_guide.html), under the "Build ROS 2 Workspace" section, step 4 fails when colcon tries to build the px4_msgs package.

Below is the specific error. Note that the error occurs in source files generated from the VehicleCommand.msg file. 

`In file included from /[workspacedir]/build/px4_msgs/rosidl_generator_c/px4_msgs/msg/detail/vehicle_command__functions.h:19,
                 from /[workspacedir]/build/px4_msgs/rosidl_generator_c/px4_msgs/msg/detail/vehicle_command__functions.c:4:
/[workspacedir]/build/px4_msgs/rosidl_generator_c/px4_msgs/msg/detail/vehicle_command__struct.h:719:3: error: expected identifier or ‘(’ before ‘/’ token
  719 |  */
      |   ^
gmake[2]: *** [CMakeFiles/px4_msgs__rosidl_generator_c.dir/build.make:6553: CMakeFiles/px4_msgs__rosidl_generator_c.dir/rosidl_generator_c/px4_msgs/msg/detail/vehicle_command__functions.c.o] Error 1

`

### Expected behavior

The px4_msgs package should build with the ROS build tools.

### Software Version

I'm using top-of-branch on px4_msgs's master.

### Vehicle type

None

### Additional context

All the involved tools and repos were updated or cloned same day, 9/27/2024.

**Comment by havel999** [comment]
Same issue. 
Raspberry PI4
Ubuntu 22.04
