### ISSUE TITLE
use

### ISSUE THREAD

**Issue by 20246688** [PX4/PX4-Autopilot#23786]
### Describe the bug

Could you please guide me on how to use PX4? Is there any detailed documentation available?

### To Reproduce

Could you please guide me on how to use PX4? Is there any detailed documentation available?

### Expected behavior

Could you please guide me on how to use PX4? Is there any detailed documentation available?

### Screenshot / Media

Could you please guide me on how to use PX4? Is there any detailed documentation available?

### Vehicle type

None

**Comment by julianoes** [comment]
https://docs.px4.io/
