### ISSUE TITLE
Yaw control is buggy.

### ISSUE THREAD

**Issue by straycat11** [PX4/PX4-Autopilot#23810]
Continuously giving yaw commands with sticks cause the controller to diverge. This is most likely because of angle wrapping and quaternion maths.

**Comment by bresch** [comment]
Angle wrapping is handled correctly. It's most likely a setup issue, do you have a log so we can verify this?

**Comment by straycat11** [comment]
Oh, I am sorry. I thought I was creating an issue on my fork,  we may close this issue.
