### ISSUE TITLE
[Bug]  In ekf.h, the uORB was used like" #include <uORB/topics/estimator_aid_source1d.h>", but i can't find the file "estimator_aid_source1d.h" in the project.

### ISSUE THREAD

**Issue by gitshitou** [PX4/PX4-Autopilot#24023]
### Describe the bug

[Bug]  In ekf.h, the uORB was used like" #include <uORB/topics/estimator_aid_source1d.h>", but i can't find the file "estimator_aid_source1d.h" in the project.

### Vehicle type

None

**Comment by bresch** [comment]
@gitshitou The uORB topics header files are generated at build time from the `msg` files: https://github.com/PX4/PX4-Autopilot/blob/main/msg/EstimatorAidSource1d.msg
