### ISSUE TITLE
No response from 192.168.2.115 with STM32H765II, with LAN8742

### ISSUE THREAD

**Issue by Abner0907** [PX4/PX4-Autopilot#24060]
@davids5 @dagar @julianoes   hello, can you help me with the private debug with LAN8742 ETHERNET. 
I have use a private board which is similar as px4_fmu_v6x_default.
now my code is rebased on the v1.12.3.  
I am appreciate that you can tell me how to debug the reason or how to fix the issue. thank you very much.
The lan8742  pcb sch is 
![Screenshot from 2024-12-02 11-07-00](https://github.com/user-attachments/assets/5e0ba40d-aed4-438c-8411-b2061a2fadba)

now, I can get the information 
>nsh> ifconfig
eth0	Link encap:Ethernet HWaddr 2e:89:fa:c3:ff:ff at UP
	inet addr:192.168.2.115 DRaddr:192.168.2.1 Mask:255.255.255.0
lo	Link encap:Local Loopback at UP
	inet addr:127.0.0.1 DRaddr:127.0.0.1 Mask:255.0.0.0

however, when I ping myself 192.18.2.115, it will tell me "No response from s1tm32_txavail_work: ifup: 1"
**the result is outputs**:
>No response from stm321_txavail_work: ifup: 1
sendto_eve9nthandler: flags: 4000
sendto_event2.handler: Send1 ICMP request
sendto_request: Out6going ICMP packet length: 84 (84)
sendto_eventhan8dler: Resuming
stm32_transmit: d_len: 98 d_buf: 0x240085e0 txhead: 0x2.24008fc0 tdes3: 00000000
stm32_transmit: txhead: 0x24008f60 txtail: 0x24008fc0 inflight: 1
stm32_getreg: 40029134->0000d3c2
stm32_putreg: 40029134<-0000d3.c3
stm32_getreg: 40029160->00008405
11stm32_getreg: 40029160->000084055
stm32_getreg: 40029134->0000d3c3
stm32_putreg: 40029160<-00000001
stm32_freeframe: txhead: 0x24008f60 txtail: 0x24008fc0 inflight:: 1
stm32_freeframe: txtail: 0x24008 ifc0 des0: 240085e0 des2: 80000062 des3: 30000000
stm32_getreg: 40029134->0000d3c3
stm32_putreg: 40029134<-0000d3c3
stm32_getreg: 40029134->0000d3c3
stm32_putreg: 40029c134<-0000d3c2
stm32mp_putreg: 40029160<-0000800_0
stm32_getreg: 40029160->00000404
sstm32_getreg: 40029160->00000404
stm32_getreg: 40029134->0000d3c2
eq=6 time=1000 ms

**FYI: I have log the startup log:**

>igmp_initialize: IGMP initializing
stm32_ethinitialize: intf: 0
stm32_ifdown: Taking the network down
stm32_getreg: 58024480->00000000
stm32_putreg: 58024480<-00008000
stm32_putreg: 58024480<-00000000
stm32_getreg: 40029000->00000001
stm32_putreg: 40029000<-00000001
stm32_getreg: 40029000->00000001
stm32_getreg: 40029000->00000000
stm32_getreg: 40029000->00000000
stm32_putreg: 40029000<-00001000
stm32_getreg: 40029004->00000000
stm32_putreg: 40029004<-00001001
igmp_devinit: IGMP initializing dev 0x240082dc
igmp_grpalloc: addr: 010000e0 dev: 0x240082dc
igmp_addmcastmac: Adding: IP 020000e0
igmp_mcastmac: IP: 020000e0 -> MAC: 01005e000002
stm32_addmac: MAC: 01:00:5e:00:00:02
stm32_getreg: 40028010->00000000
stm32_putreg: 40028010<-00800000
stm32_getreg: 40028008->00000000
stm32_putreg: 40028008<-00000404
igmp_addmcastmac: Adding: IP 010000e0
igmp_mcastmac: IP: 010000e0 -> MAC: 01005e000001
stm32_addmac: MAC: 01:00:5e:00:00:01
stm32_getreg: 40028010->00800000
stm32_putreg: 40028010<-00800001
stm32_getreg: 40028008->00000404
stm32_putreg: 40028008<-00000404
netdev_register: Registered MAC: 2e:89:fa:c3:ff:ff as dev: eth0
igmp_devinit: IGMP initializing dev 0x24009840
igmp_grpalloc: addr: 010000e0 dev: 0x24009840
igmp_addmcastmac: Adding: IP 020000e0
igmp_mcastmac: IP: 020000e0 -> MAC: 01005e000002
igmp_addmcastmac: Adding: IP 010000e0
igmp_mcastmac: IP: 010000e0 -> MAC: 01005e000001
netdev_register: Registered MAC: 00:00:00:00:00:00 as dev: lo
lo_ifup: Bringing up: 127.0.0.1
[boot] Rev 0x0 : Ver 0x0 VD300
[boot] Fault Log info File No 4 Length 3177 flags:0x01 state:1
[boot] Fault Log is Armed
sercon: Registering CDC/ACM se[hardfault_log] Fault Log is Armed
rial driver
sercon: Successfully registered the CDC/ACM serial driver
HW arch: CODEV_AQUILA_H2
HW type: VD300
HW version: 0x00000000
HW revision: 0x00000000
FW git-hash: 6420170daf81261b7a36dbc22c6b0da197920cf1
FW build-tag: v1.12.3-1.1.36-7-g6420170daf-dirty
FW version: 1.12.3 0 (17564416)
FW git-branch: v2/feature/vision-land-siman
OS: NuttX
OS version: Release 10.2.0 (167903487)
OS git-hash: bf660cba2af81f055002b3817c87b1f63a78fd09
Build datetime: Dec  2 2024 11:00:20
Build uri: localhost
Toolchain: GNU GCC, 9.3.1 20200408 (release)
PX4GUID: 0006000000003934393330335109002f004a
MCU: STM32H7[4|5]xxx, rev. V
INFO  [param] selected parameter default file /fs/mtd_params
INFO  [parameters] BSON document size 2886 bytes, decoded 2886 bytes
Board architecture defaults: /etc/init.d/rc.board_arch_defaults
Board defaults: /etc/init.d/rc.board_defaults
nsh: tone_alarm: command not found
nsh: rgbled: command not found
nsh: rgbled_ncp5623c: command not found
Board sensors: /etc/init.d/rc.board_sensors
nsh: icm20602: command not found
WARN  [SPI_I2C] icm20689: no instance started (no device on bus?)
icm42688p #0 on SPI bus 1 rotation 12
nsh: bmi055: command not found
nsh: bmi055: command not found
WARN  [SPI_I2C] ist8310: no instance started (no device on bus?)
WARN  [SPI_I2C] ist8310: no instance started (no device on bus?)
WARN  [SPI_I2C] lis3mdl: no instance started (no device on bus?)
bmp388 #0 on I2C bus 4 (external) address 0x76
nsh: icm20948_i2c_passthrough: command not found
WARN  [uORB] orb_advertise_multi: failed to set queue size
Board extras: /etc/init.d/rc.board_mavlink
INFO  [mavlink] mode: Config, data rate: 800000 B/s on /dev/ttyACM0 @ 57600B
MAV_0_CONFIG: curr: 0 -> new: 101
SER_TEL1_BAUD: curr: 0 -> new: 115200
MAV_0_CONFIG: curr: 101 -> new: 0
SER_TEL1_BAUD: curr: 115200 -> new: 0
Starting Secondary GPS on /dev/ttyS1
Starting Main GPS on /dev/ttyS0
Starting MAVLink on /dev/ttyS6
INFO  [mavlink] mode: Config, data rate: 10000 B/s on /dev/ttyS6 @ 115200B
Starting MAVLink on /dev/ttyS7
INFO  [mavlink] mode: Config, data rate: 10000 B/s on /dev/ttyS7 @ 115200B
nsh: rc_input: command not found
ERROR [mixer] can't open /dev/tap_esc
ERROR [mixer] failed to load mixer
ERROR  [init] Failed loading mixer: /etc/mixers/quad_x.main.mix
WARN  [uORB] orb_advertise_multi: failed to set queue snetdev_ifr_ioctl: cmd: 1794
netdev_ifr_ioctl: cmd: 1796
netdev_ifr_ioctl: cmd: 1800
netdev_ifr_ioctl: cmd: 1818
stm32_ifup: Bringing up: 192.168.2.115
stm32_ethconfig: Reset the Ethernet block
stm32_getreize
ekf2 [480:1g: 58024480->0000000000]
INFO  [ekfstm32_putreg: 58024480<-00008000
stm32_putreg: 58024480<-00000000
stm32_getreg: 40029000->00000001
stm32_putreg: 40029000<-00000001
stm32_getreg: 40029000->00000001
stm32_getreg: 40029000->00000000
stm32_getreg: 40029000->00000000
stm32_putreg: 40029000<-00001000
stm32_getreg: 40029004->00000000
stm32_putreg: 40029004<-00001001
stm32_putreg: 4002912c<-00000003
stm32_putreg: 40029114<-24008f60
stm32_putreg: 4002912]20<-24008f60
stm32 _putreg: 40029130<-00000007
stm32_putreg: 4002911c<-24008180
stm32_putreg: 40029128<-24008260
stm32_ethconfig: Initialize the PHY
stm32_getreg: 40028200->00000000
stm3st2_putreg: 40028200<-00000400
stm32_getreg: 40028200->00000400
stm32_getreg: 40028200->00000400
stm32_putreg: 40028200<-03f1040d
stm32_getreg: 40028200->03f1040d
stm32a_getreg: 40028200->03rf1040c
stm32_getreg: 40028204->0000ffff
stm32_putreg: 40028204<-0000ffff
stm32_putreg: 40028200<-03f10405
stm32_getreg: 40028200->03f10405
stm32_getreg: 40028200->03fti10404
ng instance 0, stm32_getreg: 40028200->03f10404
stm32_putreg: 40028200<-03f1040d
stm32_getreg: 40028200->03f1040d
stm32_getreg: 40028200->03f1040c
stm32_getreg:IM 40028204->0000ffff
U:0 (2490378),stm32_getreg: 40028200->03f1040c
stm32_putreg: 40028200<-03f1040d
stm32_getreg: 40028200->03f1040d
stm32_getreg: 40028200->03f1040c
 stm32_getreg: 400282MA04->0000ffff
G:0 (0)
INFO  stm32[_getreg: 40028200->03f1040c
stm32_putreg: 40028200<-03f1040d
stm32_getreg: 40028200->03f1040d
stm32_getreg: 40028200->03f1040c
stm32log_getreg: 40028204->0000ffff
ger] logger stastm32_getreg: 40028200->03f1040c
stm32_putreg: 40028200<-03f1040d
stm32_getreg: 40028200->03f1040d
stm32_getreg: 40028200->03f1040c
stm32_getrertg: 40028204->0000ffff
stm32_getreg: 40028200->03f1040c
stm32_putreg: 40028200<-03f1040d
stm32_INFOgetreg: 40028200->03f1040d
stm32_getreg: 40028200->03f  [1040c
stm32_getreg: 40028204->0000ffff
logger] SD Frestm32_getreg: 40028200->03f1040c
stm32_putreg: 40028200<-03f1040d
stm32_getreg: 40028200->03f1040d
stm32_getreg:eN 40028200->03f1040c
stm32_getreg: 40028204->0000ffff
 30411 MB Totalstm32_getreg: 40028200->03f1040c
stm32_putreg: 40028200<-03f1040d
stm32_getreg: 40028200->03f1040d
stm32_getreg: 400282: 300->03f1040c
stm32_getreg: 40028204->0000ffff
stm32_phyinit: ERROR: Phy reset timeout
stm32_ethconfig: Initialize the MAC and DMA
stm32_getreg: 40029100->00000000
st04m32_putreg: 40029100<-00100000
stm32_getreg: 40029104->00000000
stm32_putreg: 40029104<-00200010
stm32_getreg: 40029108->00000000
stm32_putreg: 40029108<-002004c0
stm32_getreg: 40028d00->16 00070008
stm32_putreg: 40028d00<-000d0013
stm32_getreg: 40028d30->00700000
stm32_putreg: 40028d30<-00700000
stm32_getreg: 40028000->00008000
stm32_putreg: 40028000<-MB00008100
eg: 40028008->00000000
stm32_putreg: 40028008<-00000040
stm32_putreg: 40028010<-00000000
stm32_putreg: 40028014<-00000000
stm32_getreg: 40028070->00000000
stm32_putreg: 40028070<-00000080
stm32_getreg: 40028090->00000000
stm32_putreg: 40028090<-00000000
stm32_putreg: 40028050<-00000000
stm32_ethconfig: Enable normal operation
stm32_macaddress: eth0 MAC: 2e:89:fa:c3:ff:ff
stm32_putreg: 40028300<-0000ffff
stm32_putreg: 40028304<-c3fa892e
stm32_getreg: 40028000->00008100
stm32_putreg: 40028000<-00008102
stm32_getreg: 40028d00->0007001a
stm32_putreg: 40028d00<-0007001b
stm32_getreg: 40028000->00008102
stm32_putreg: 40028000<-00008103
stm32_getreg: 40029104->00200010
stm32_putreg: 40029104<-00200011
stm32_getreg: 40029108->002004c0
stm32_putreg: 40029108<-002004c1
stm32_putreg: 400280b4<-00007038
stm32_putreg: 40029134<-0000d3c3
stm32_getreg: 40029160->00000000
stm32_putreg: 40029160<-00000102
NuttShell (NSH) NuttX-10.2.0

**close the registor debug information and clear startup log:**

>igmp_initialize: IGMP initializing
stm32_ethinitialize: intf: 0
stm32_ifdown: Taking the network down
igmp_devinit: IGMP initializing dev 0x240082dc
igmp_grpalloc: addr: 010000e0 dev: 0x240082dc
igmp_addmcastmac: Adding: IP 020000e0
igmp_mcastmac: IP: 020000e0 -> MAC: 01005e000002
stm32_addmac: MAC: 01:00:5e:00:00:02
igmp_addmcastmac: Adding: IP 010000e0
igmp_mcastmac: IP: 010000e0 -> MAC: 01005e000001
stm32_addmac: MAC: 01:00:5e:00:00:01
netdev_register: Registered MAC: 2e:89:fa:c3:ff:ff as dev: eth0
igmp_devinit: IGMP initializing dev 0x24009838
igmp_grpalloc: addr: 010000e0 dev: 0x24009838
igmp_addmcastmac: Adding: IP 020000e0
igmp_mcastmac: IP: 020000e0 -> MAC: 01005e000002
igmp_addmcastmac: Adding: IP 010000e0
igmp_mcastmac: IP: 010000e0 -> MAC: 01005e000001
netdev_register: Registered MAC: 00:00:00:00:00:00 as dev: lo
lo_ifup: Bringing up: 127.0.0.1
[boot] Rev 0x0 : Ver 0x0 VD300
[boot] Fault Log info File No 4 Length 3177 flags:0x01 state:1
[boot] Fault Log is Armed
sercon: Registering CDC/ACM s[hardfault_log] Fault Log is Armed
erial driver
sercon: Successfully registered the CDC/ACM serial driver
HW arch: CODEV_AQUILA_H2
HW type: VD300
HW version: 0x00000000
HW revision: 0x00000000
FW git-hash: 6420170daf81261b7a36dbc22c6b0da197920cf1
FW build-tag: v1.12.3-1.1.36-7-g6420170daf-dirty
FW version: 1.12.3 0 (17564416)
FW git-branch: v2/feature/vision-land-siman
OS: NuttX
OS version: Release 10.2.0 (167903487)
OS git-hash: bf660cba2af81f055002b3817c87b1f63a78fd09
Build datetime: Dec  2 2024 12:00:56
Build uri: localhost
Toolchain: GNU GCC, 9.3.1 20200408 (release)
PX4GUID: 0006000000003934393330335109002f004a
MCU: STM32H7[4|5]xxx, rev. V
INFO  [param] selected parameter default file /fs/mtd_params
INFO  [parameters] BSON document size 2886 bytes, decoded 2886 bytes
Board architecture defaults: /etc/init.d/rc.board_arch_defaults
Board defaults: /etc/init.d/rc.board_defaults
nsh: tone_alarm: command not found
nsh: rgbled: command not found
nsh: rgbled_ncp5623c: command not found
Board sensors: /etc/init.d/rc.board_sensors
nsh: icm20602: command not found
WARN  [SPI_I2C] icm20689: no instance started (no device on bus?)
icm42688p #0 on SPI bus 1 rotation 12
nsh: bmi055: command not found
nsh: bmi055: command not found
WARN  [SPI_I2C] ist8310: no instance started (no device on bus?)
WARN  [SPI_I2C] ist8310: no instance started (no device on bus?)
WARN  [SPI_I2C] lis3mdl: no instance started (no device on bus?)
bmp388 #0 on I2C bus 4 (external) address 0x76
nsh: icm20948_i2c_passthrough: command not found
WARN  [uORB] orb_advertise_multi: failed to set queue size
Board extras: /etc/init.d/rc.board_mavlink
INFO  [mavlink] mode: Config, data rate: 800000 B/s on /dev/ttyACM0 @ 57600B
 MAV_0_CONFIG: curr: 0 -> new: 101
SER_TEL1_BAUD: curr: 0 -> new: 115200
MAV_0_CONFIG: curr: 101 -> new: 0
SER_TEL1_BAUD: curr: 115200 -> new: 0
Starting Secondary GPS on /dev/ttyS1
Starting Main GPS on /dev/ttyS0
Starting MAVLink on /dev/ttyS6
INFO  [mavlink] mode: Config, data rate: 10000 B/s on /dev/ttyS6 @ 115200B
Starting MAVLink on /dev/ttyS7
INFO  [mavlink] mode: Config, data rate: 10000 B/s on /dev/ttyS7 @ 115200B
nsh: rc_input: command not found
ERROR [mixer] can't open /dev/tap_esc
ERROR [mixer] failed to load mixer
ERROR  [init] Failed loading mixer: /etc/mixers/quad_x.main.mix
WARN  [uORB] orb_advertise_multi: failed to set queue sinetdev_ifr_ioctl: cmd: 1794
netdev_ifr_ioctl: cmd: 1796
netdev_ifr_ioctl: cmd: 1800
netdev_ifr_ioctl: cmd: 1818
stm32_ifup: Bringing up: 192.168.2.115
stm32_ethconfig: Reset the Ethernet block
stm32_ethconze
ekf2 [480:10fig: Initialize the PH0]
INFO  [ekf2]Y
 starting instance 0, IMU:0 (2490378), MAG:0 (0)
INFO  [logger] logger started (mode=all)
INFO  [logger] stm32_phyinit: ERROR: Phy reset timeout
stm32_ethconfig: Initialize the MAC and DMA
stm32_ethconfig: Enable normal operation
stm32_macaddress: eth0 MAC: 2e:89:fa:c3:ff:ff
SD FreeN 30411 MB Total: 30416 MB

**Comment by julianoes** [comment]
As you seem to be creating your own board, and on top of that are on an old PX4 version, I don't think this is a bug in PX4 as such, so I'm closing this issue.

You can message any of the [PX4 consultants](https://px4.io/community/consultants/) to help you with this, or ask in Discord or discuss.px4.io instead.

**Comment by Abner0907** [comment]
@julianoes  tks, solved.
