### ISSUE TITLE
[Bug] alt_ref is NAN without GPS

### ISSUE THREAD

**Issue by dakejahl** [PX4/PX4-Autopilot#24078]
### Describe the bug

If you takeoff with QGC (MAV_CMD_NAV_TAKEOFF) without a GPS and using an ARK Flow for position mode, the vehicle will ascend to an extreme altitude. This is because local_position.ref_alt is NAN and will not be initialized without GPS.
https://github.com/PX4/PX4-Autopilot/blob/main/src/modules/ekf2/EKF2.cpp#L1575

### To Reproduce

Issue a takeoff command from QGC to a vehicle with Flow only

### Flight Log

https://review.px4.io/plot_app?log=055705b6-ba7b-43eb-95a0-62576b195f7e

### Software Version

ARK Flow, no GPS, flying indoors, takeoff with QGC

### Flight controller

arkpi6x flow

### Vehicle type

None

### Additional context

This also explains a fly away we had a few months ago when we took off using QGC without realizing GPS wasn't ready. The Flow allowed the takeoff and the vehicle climbed very high, flow then failed, and the vehicle then lost connection and flew away never to be seen again.

**Comment by bresch** [comment]
The reference of the local plane frame were always reported as `nan` without GNSS fix. Did something change in Navigator/Commander?

**Comment by AlexKlimaj** [comment]
Takeoff without a global position should be referenced in local coordinates instead. So takeoff to X meters above the current local Z.

**Comment by dakejahl** [comment]
the issue is actually the inconsistent altitude estimation when using a range finder, seems that it can be somewhat random what altitude it ends up when taking off. Sometimes stays on the ground.
