### ISSUE TITLE
[Bug] Gazebo Classic geotagged_cam does not output images on survey mission

### ISSUE THREAD

**Issue by tnedev** [PX4/PX4-Autopilot#24073]
### Describe the bug

As confirmed in the [PX4-SITL_gazebo-classic issue](https://github.com/PX4/PX4-SITL_gazebo-classic/issues/1059#issuecomment-2516063926)

Using the **Gazebo Classic** with **PX4 1.15.2** and **plane_cam** does not save survey images while doing **survey mission**. 

Manual trigger with camera capture button in QGC saves images to _build/px4_sitl_default/src/modules/simulation/simulator_mavlink/frames/_ .

The bug is confirmed by @hamishwillee and reviewed by @Jaeyoung-Lim who concluded that is not  **PX4-SITL_gazebo-classic** bug but **PX4-Autopilot** issue. 

### To Reproduce

1. Launch PX4 1.15.2 with Gazebo Classic plane_cam:
`make px4_sitl gazebo-classic_plane_cam`
2. Make sure camera trigger is set to MAVLink
3. Create a survey mission with camera triggering in QGC and execute it. 
4. During execution click on the manual image capture button.
5. Observe the captured images in _build/px4_sitl_default/src/modules/simulation/simulator_mavlink/frames/_ .

### Flight Log

https://we.tl/t-R9dX20wM9N

### Software Version

I'm using PX4 1.15.2 and Gazebo Classic under Ubuntu 20 & Ubuntu 22.

### Vehicle type

None

**Comment by Jaeyoung-Lim** [comment]
@tnedev Please post a flight log and instructions to reproduce

**Comment by tnedev** [comment]
> @tnedev Please post a flight log and instructions to reproduce

Added them. It's a 400MB log, so I uploaded it to Wetransfer.

**Comment by Jaeyoung-Lim** [comment]
I was able to reproduce the problem, and while the camera does trigger, the gazebo plugin fails to grab the mavlink stream coming out of the vehicle during the survey.
