### ISSUE TITLE
[Bug] THR_MDL_FAC causes VTOL motors not stop spinning during Fixed-wing cruising phase Firmware V 1.15

### ISSUE THREAD

**Issue by saengphet** [PX4/PX4-Autopilot#24083]
### Describe the bug

During the flight test, if THR_MDL_FAC was set to a value > 0, such as 0.2-0.5, the VTOL motor would continue to spin (observed and confirmed by eyes). I also checked the flight log and saw that the VTOL was spinning at minimum PWM, e.g., 1080. 

In the next flight. I set THR_MDL_FAC = 0, and the VTOL motors stopped spinning.were

### To Reproduce

THR_MDL_FAC > 0 and transition to fixed-wing mode (in-air or on ground have the same behavior).

### Expected behavior

THR_MDL_FAC > 0 and all VTOL motor stop spinning during fixed-wing cruising phase.the 

### Flight controller

CubeOrange

### Vehicle type

Hybrid VTOL

**Comment by sfuhrer** [comment]
Good find. I could reproduce in SITL. See the two screenshots below: if THR_MDL_FAC is non-zero, the output of the hovering motors in fixed-wing flight (vtol_state 4) is 1000, while it should be 900 (disarmed). 

![image](https://github.com/user-attachments/assets/8682b935-3884-4823-bc0f-ad468a68fa56)
![image](https://github.com/user-attachments/assets/cc18ff77-ecfe-4285-a7c3-8952a6b3e92d)

**Comment by sfuhrer** [comment]
BTW @saengphet be careful, afaik what you set in THR_MDL_FAC will also be applied to the pusher motor of a VTOL. There is no distinction.

**Comment by MaEtUgR** [comment]
Thanks for the report and quick fix 👍

**Comment by sfuhrer** [comment]
> Hi @sfuhrer Did the merged PR not fix the applying of THR_MDL_FAC on the pusher motor?

No it doesn't, it only made sure that motors that are disabled stay disabled even with THR_MDL_FAC set.
