### ISSUE TITLE
Inspect LSM303D driver

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/PX4-Autopilot#465]
We have several fuzzy reports circling around a LSM303D no-measurements state which is non-recoverable in the driver and needs a power cycle. This is extremely hard to reproduce, so causes can range from software to individual boards. Needs proper and detailed inspection.

**Comment by LorenzMeier** [comment]
Note: This has been fixed with a bypass 220 Ohm resistor on the 3.3V rail a *very long* time ago.

**Comment by drones-squad** [comment]
Hy, 

Is this fix currently to be found / implemented in the 2.4.5 schematic ?
