### ISSUE TITLE
Refactor calibration to be uORB based for all systems

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/PX4-Autopilot#5000]
@julianoes Some architectural cleanup so we don't need these ifdefs:
https://github.com/PX4/Firmware/pull/4999

**Comment by dagar** [comment]
This is a part of https://github.com/PX4/Firmware/pull/12783 (DriverFramework deprecation).

**Comment by junwoo091400** [comment]
Now there's no such #if dependencies on architecture of the build target (it does still use flags like `DEBUG_BUILD`, but the original issue seems to have been resolved.
