### ISSUE TITLE
Toolchain for Windows produces semi-working code

### ISSUE THREAD

**Issue by iljanev** [PX4/PX4-Autopilot#833]
Toolchain for Windows produces code that works only partially and crashes in some modes.
System: Windows 7 64 bit, tested on 2 instances
Toolchain installed: 03.03.2014
Code cloned from: https://github.com/DrTon/Firmware/tree/follower
FMU: Pixhawk 2.4 from 3DR
Binary file size: 869KB

Quad copter tuned and set-up to fly well in Manual, Seatbelt and Easy modes.
When I switch to Follow mode - the fmu freezes, motors are shut down and copter falls down. I receive the same behaviour in jMavSim HIL as well as in real life.

If the same code is compiled on Mac OS it results in a binary of 910KB and Follow mode works well in real life and HIL. So I suspect some differencies in toolchain or compiler settings.

**Comment by ashishmach** [comment]
Is eclipse really working for someone ? I mean when I am opening /src/examples and if I open any 'main' file, it starts showing errors.
