### ISSUE TITLE
commander error messages

### ISSUE THREAD

**Issue by dagar** [PX4/PX4-Autopilot#8369]
A common pain point (especially for new users) is the lack of useful error messages from commander when state transitions fail (arming or modes).

Maybe it's time for the event interface? http://discuss.px4.io/t/event-interface/2318

This has been mentioned in quite a few other places, but it's sufficiently annoying that I'm creating a new issue.

**Comment by hamishwillee** [comment]
@dagar This still looks relevant right?

**Comment by Antiheavy** [comment]
let's keep this issue alive.

**Comment by julianoes** [comment]
@Antiheavy it will now stay openG actually, just marked stale.
