### ISSUE TITLE
Gazebo Camera: Double triggers on distance trigger at random points

### ISSUE THREAD

**Issue by DonLakeFlyer** [PX4/PX4-Autopilot#9134]
I noticed this while doing camera trigger testing on surveys. Here is a simpler example plan which just turns on distance triggering right away:
![screen shot 2018-03-21 at 1 42 29 pm](https://user-images.githubusercontent.com/5876851/37736336-e5f93620-2d0d-11e8-9efc-9ed4411dbe19.png)

Here you can see the double triggers:
![screen shot 2018-03-21 at 1 42 17 pm](https://user-images.githubusercontent.com/5876851/37736425-1dac0f84-2d0e-11e8-8a67-be86fbc737d3.png)

[DoubleTrigger.plan.zip](https://github.com/PX4/Firmware/files/1835180/DoubleTrigger.plan.zip)

**Comment by Jaeyoung-Lim** [comment]
This should be fixed upstream. closing
