### ISSUE TITLE
Event interface design and discussion

### ISSUE THREAD

**Issue by dagar** [PX4/PX4-Autopilot#9993]
**Work in progress rough notes for the event interface. Please edit in place.**

Goals
  - replace all error message handling with structured data

Why?

  - limited length (50 characters)
  - english only
  - messages can easily be lost
  - horrible user experience!

http://discuss.px4.io/t/event-interface/2318

TODO:
 - often need data with error
 - PX4 side usage, logging, review
 - mavlink interface
 - new metadata package?

**Comment by junwoo091400** [comment]
AFAIK the Event Interface is implemented in PX4 here: https://github.com/PX4/PX4-Autopilot/pull/17479

If not, please correct me!
